force-app/main/default/objects/FileControllerEvent__e/FileControllerEvent__e.object-meta.xml
<CustomObject>
    <description>An event to trigger DML Actions for managing files and upsert content from Callouts</description>
    <label>File Controller Event</label>
    <pluralLabel>FileControllerEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/FileControllerEvent__e/fields/FileAction__c.field-meta.xml
<CustomField>
    <fullName>FileAction__c</fullName>
    <label>File Action</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FileControllerEvent__e/fields/FileContent__c.field-meta.xml
<CustomField>
    <fullName>FileContent__c</fullName>
    <label>File Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FileControllerEvent__e/fields/FileDocumentId__c.field-meta.xml
<CustomField>
    <fullName>FileDocumentId__c</fullName>
    <label>File Document Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FileControllerEventTriggerHandler.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-20-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class FileControllerEventTriggerHandler {
    public static void executeAction(List<FileControllerEvent__e> fileActionEvents) {
        for (FileControllerEvent__e stepfileActionEvent : fileActionEvents) { 
            String fileAction = stepfileActionEvent.FileAction__c;
            String documentId = stepfileActionEvent.FileDocumentId__c;
            String content = stepfileActionEvent.FileContent__c;
            System.debug('--- FileControllerEventTriggerHandler - executeAction: ' + fileAction);
            switch on fileAction {
                when 'upload' {
                    System.debug('--- FileControllerEventTriggerHandler - upload new Vresion for Document: ' + documentId);
                    FileController.uploadNewFileVersion(content,documentId);
                }
            }
        }
    }
}