force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>Business Attribute to identify the applicable Revenue and Cost Parameters</description>
    <label>Business Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>T2-{000000}</displayFormat>
        <label>Cost Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cost__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/Sales_Price__c.object-meta.xml
<CustomObject>
    <label>Sales Price</label>
    <nameField>
        <displayFormat>T3-{000000}</displayFormat>
        <label>Sales Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Sales_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Sales_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FI</fullName>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <label>Sweden</label>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
        <label>Norway</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Denmark</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Netherlands</label>
    </customValue>
    <masterLabel>Lumon Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <customValue>
        <fullName>4043 LSU Oulu</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LumonTestPriceMultipliers.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-11-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class LumonTestPriceMultipliers {
    public static void setupFactoryMultipliers() {    
        List<String> organizations = LumonTestVariables.organizations;
        List<String> countryCodes = LumonTestVariables.countries;
        List<String> businessTypes = LumonTestVariables.businessTypes;
        List<String> districts = LumonTestVariables.districts;
        List<String> productGroups= LumonTestVariables.productGroups;
        List<String> costTypes = LumonTestVariables.costTypes;
        List<Factory_Price__c> fps = new List<Factory_Price__c>();  
        for (String org : organizations) {
            for (String businessType : businessTypes) {
                for (String country : countryCodes) {  
                    List<Factory_Price__c> countryFactoryMultipliers= new List<Factory_Price__c>();                  
                    for (String pg : productGroups) {
                        List<Factory_Price__c> groupFactoryMultipliers= new List<Factory_Price__c>();
                        for (String  ct: costTypes) {
                            Factory_Price__c fp = new Factory_Price__c();
                            fp.Organization__c = org;
                            fp.Country__c = country;
                            fp.Business_Type__c = businessType;
                            fp.Product_Group__c = pg;
                            fp.Cost_Type__c = ct;
                            fp.Factory_Multiplier__c = 10.0;
                            fp.IsActive__c  = true;
                            //fps.add(fp);
                            groupFactoryMultipliers.add(fp);
                            countryFactoryMultipliers.add(fp);
                        }  
                    }    
                    insert countryFactoryMultipliers;            
                }
            }
        }
        List<Factory_Price__c> factoryPrices = LumonTestVariables.factoryPrices;
        System.debug('--- LumonTestPriceMultipliers - Factory Multipliers: '+factoryPrices);
    }
    public static void setupCostMultipliers() {
        List<Product_Cost__c> pcs = new List<Product_Cost__c>();
        List<String> organizations = LumonTestVariables.organizations;
        List<String> countryCodes = LumonTestVariables.countries;
        List<String> businessTypes = LumonTestVariables.businessTypes;
        List<String> districts = LumonTestVariables.districts;
        List<String> productGroups= LumonTestVariables.productGroups;
        List<String> costTypes = LumonTestVariables.costTypes;
        for (String org : organizations) {
            for (String businessType : businessTypes) {
                for (String country : countryCodes) {
                    for( String district : districts) { 
                        List<Product_Cost__c> districtCostMultipliers= new List<Product_Cost__c>();                      
                        for (String pg : productGroups) {
                            List<Product_Cost__c> groupCostMultipliers= new List<Product_Cost__c>();
                            for (String  ct: costTypes) {
                                Product_Cost__c pc = new Product_Cost__c();
                                pc.Organization__c = org;
                                pc.Country__c = country;
                                pc.Business_Type__c = businessType;
                                pc.District__c = district;
                                pc.Product_Group__c = pg;
                                pc.Cost_Type__c = ct;
                                pc.Cost_Multiplier__c = 20.0;
                                pc.IsActive__c  = true;
                                groupCostMultipliers.add(pc);
                                districtCostMultipliers.add(pc);
                                //pcs.add(pc);
                            }                          
                        }   
                        insert districtCostMultipliers;                     
                    }
                }
            }
        }
        List<Product_Cost__c> productCosts = LumonTestVariables.productCosts;
        System.debug('--- LumonTestPriceMultipliers - Cost Multipliers: '+productCosts);
    }
    public static void setupPriceMultipliers() {       
        //String profit = '4043 LSU Oulu';
        List<String> organizations = LumonTestVariables.organizations;
        List<String> countryCodes = LumonTestVariables.countries;
        List<String> businessTypes = LumonTestVariables.businessTypes;

        List<String> districts = LumonTestVariables.districts;
        List<String> profitCenters = LumonTestVariables.profitCenters;
        List<String> productGroups = LumonTestVariables.productGroups;
        List<String> costTypes = LumonTestVariables.costTypes;
        List<Sales_Price__c> sps = new List<Sales_Price__c>();
        for (String org : organizations) {
            for (String businessType : businessTypes) {
                for (String country : countryCodes) {
                    for( String district : districts) {
                        setupPriceMultipliers(org,country,businessType,district);
                    }
                }
            }
        }
        List<Sales_Price__c> salesPrices = LumonTestVariables.salesPrices;
        System.debug('--- LumonTestPriceMultipliers -  Price Multipliers: '+salesPrices);
    }
    public static void setupPriceMultipliers(String org, String country, String businessType, String district) {       
        //String profit = '4043 LSU Oulu';
        List<String> organizations = LumonTestVariables.organizations;
        List<String> countryCodes = LumonTestVariables.countries;
        List<String> businessTypes = LumonTestVariables.businessTypes;

        List<String> districts = LumonTestVariables.districts;
        List<String> profitCenters = LumonTestVariables.profitCenters;
        List<String> productGroups = LumonTestVariables.productGroups;
        List<String> costTypes = LumonTestVariables.costTypes;
        List<Sales_Price__c> priceMultipliers = new List<Sales_Price__c>();
        for (String profitCenter : profitCenters) {                         
            for (String pg : productGroups) {
                for (String  ct: costTypes) {
                    Sales_Price__c sp = new Sales_Price__c();
                    sp.Organization__c = org;
                    sp.Country__c = country;
                    sp.Business_Type__c = businessType;
                    sp.District__c = district;
                    //sp.Profit_Center__c = profit;
                    sp.Product_Group__c = pg;
                    sp.Cost_Type__c = ct;
                    sp.Sales_Multiplier__c = 30.0;
                    sp.IsActive__c  = true;
                    //sps.add(sp);
                    priceMultipliers.add(sp);   
                }
            } 
        }
        if (priceMultipliers.size()>0){
        	insert priceMultipliers;
        }
        List<Sales_Price__c> salesPrices = LumonTestVariables.salesPrices;
        System.debug('--- LumonTestPriceMultipliers -  Price Multipliers: '+salesPrices);
    }
    public static void setupPriceMultiplierData(){
        setupFactoryMultipliers();
        setupCostMultipliers();
        setupPriceMultipliers();
        List<Factory_Price__c> factoryPrices = LumonTestVariables.factoryPrices;
        List<Product_Cost__c> productCosts = LumonTestVariables.productCosts;
        List<Sales_Price__c> salesPrices = LumonTestVariables.salesPrices;
        System.debug('--- LumonTestPriceMultipliers - Inserted '+factoryPrices.size()+' Factory Multipliers'); 
        System.debug('--- LumonTestPriceMultipliers - Inserted '+productCosts.size()+' Cost Multipliers'); 
        System.debug('--- LumonTestPriceMultipliers - Inserted '+salesPrices.size()+' Price Multipliers'); 
    }  
    @TestSetup
    static void prepareData() {
        List<Product2> products = LumonTestVariables.products;
        Test.startTest();
        if(products?.size()>0){
            System.debug('--- LumonTestPriceMultipliers - Using Existing Products');
        } else {
            LumonTestProducts.setupProductData();
        }
        Test.stopTest();
    }
    @IsTest
    static void setupPriceMultipliersDataTest(){
        String testResult;
        Test.startTest();
        Try {
            setupPriceMultiplierData();
            testResult = 'successfully inserted Price Multipliers';
        } catch (exception e){
            testResult = 'error when inserting Price Multipliers: '+e.getMessage();
        }
        Test.stopTest();
        List<Factory_Price__c> factoryPrices = LumonTestVariables.factoryPrices;
        List<Product_Cost__c> productCosts = LumonTestVariables.productCosts;
        List<Sales_Price__c> salesPrices = LumonTestVariables.salesPrices;
        System.debug('--- LumonTestPriceMultipliers - result: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
        System.AssertNotEquals(0, factoryPrices.size(),'Expected Factory Prices to be Inserted');
        System.AssertNotEquals(0, productCosts.size(),'Expected Prodyct Costs to be Inserted');
        System.AssertNotEquals(0, salesPrices.size(),'Expected Sales Prices to be Inserted');
    }
    @IsTest
    static void setupFactoryPricesTest(){
        String testResult;
        Test.startTest();
        Try {
            setupFactoryMultipliers();
            testResult = 'successfully inserted Price Multipliers';
        } catch (exception e){
            testResult = 'error when inserting Price Multipliers: '+e.getMessage();
        }
        Test.stopTest();
        List<Factory_Price__c> factoryPrices = LumonTestVariables.factoryPrices;
        System.debug('--- LumonTestPriceMultipliers - result: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
        System.AssertNotEquals(0, factoryPrices.size(),'Expected Factory Prices to be Inserted');
    }
    @IsTest
    static void setupProductCostsTest(){
        String testResult;
        Test.startTest();
        Try {
            setupCostMultipliers();
            testResult = 'successfully inserted Price Multipliers';
        } catch (exception e){
            testResult = 'error when inserting Price Multipliers: '+e.getMessage();
        }
        Test.stopTest();
        List<Product_Cost__c> productCosts = LumonTestVariables.productCosts;
        System.debug('--- LumonTestPriceMultipliers - result: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
        System.AssertNotEquals(0, productCosts.size(),'Expected Prodyct Costs to be Inserted');
    }
    @IsTest
    static void setupSalesPricesTest(){
        String testResult;
        Test.startTest();
        Try {
            setupPriceMultipliers();
            testResult = 'successfully inserted Price Multipliers';
        } catch (exception e){
            testResult = 'error when inserting Price Multipliers: '+e.getMessage();
        }
        Test.stopTest();
        List<Sales_Price__c> salesPrices = LumonTestVariables.salesPrices;
        System.debug('--- LumonTestPriceMultipliers - result: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
        System.AssertNotEquals(0, salesPrices.size(),'Expected Sales Prices to be Inserted');
    }

}