force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>Business Attribute to identify the applicable Revenue and Cost Parameters</description>
    <label>Business Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>T2-{000000}</displayFormat>
        <label>Cost Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cost__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/BusinessId__c.field-meta.xml
<CustomField>
    <fullName>BusinessId__c</fullName>
    <description>SalesTori businessId</description>
    <label>BusinessId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/Sales_Price__c.object-meta.xml
<CustomObject>
    <label>Sales Price</label>
    <nameField>
        <displayFormat>T3-{000000}</displayFormat>
        <label>Sales Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/BusinessId__c.field-meta.xml
<CustomField>
    <fullName>BusinessId__c</fullName>
    <label>Business Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Sales_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Sales_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FI</fullName>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <label>Sweden</label>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
        <label>Norway</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Denmark</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Netherlands</label>
    </customValue>
    <masterLabel>Lumon Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <customValue>
        <fullName>4043 LSU Oulu</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LumonTestPriceParameters.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-12-2023
 * @last modified by  : Henk Reynders
**/
@isTest
public with sharing class LumonTestPriceParameters {
	@TestVisible private static List<Factory_Price__c> factoryPrices{
        get{
            return [SELECT Id, Name,  
                    		Organization__c, Country__c, 
                    		Business_Type__c,
                    		Factory_Multiplier__c, 
                    		IsActive__c, 
                    		Product_Group__c,
                            //Product_Model__c, 
                            Cost_Type__c  
                    FROM Factory_Price__c ];
        }
    }
    @TestVisible private static List<Product_Cost__c> productCosts{
        get{
            return [SELECT Id, Name,  
                    		Organization__c, Country__c, 
                    		Business_Type__c,District__c,
                    		Cost_Multiplier__c, 
                    		IsActive__c, 
                    		Product_Group__c,
                            //Product_Model__c, 
                            Cost_Type__c                    		
                    FROM Product_Cost__c ];
        }
    }
    @TestVisible private static List<Sales_Price__c> salesPrices{
        get{
            return [SELECT Id, Name,   
                    		Organization__c, Country__c, 
                    		Business_Type__c,District__c,
                    		Profit_Center__c,BusinessId__c,
                    		Sales_Multiplier__c, 
                    		IsActive__c, 
                    		Product_Group__c,
                            //Product_Model__c, 
                            Cost_Type__c  
                    FROM Sales_Price__c ];
        }
    }
    public static void setupPriceParameters(){
        List<Product2> products = [SELECT Id, ProductCode,Product_Group__c,Cost_Type__c,IsActive FROM Product2];
        List<Id> productIds = new List<Id>(new Map<Id, Product2>(products).keySet()); 
        setupPriceParameters(productIds);
    }
    public static void setupPriceParameters(list<Id> productIds) {
        List<Product2> products = [SELECT Id, ProductCode,Product_Group__c,Cost_Type__c,IsActive FROM Product2 WHERE Id IN:productIds];
        Map<String,List<String>> productGroupMap = new Map<String,List<String>>();
        List<String> productGroups = new List<String>();
        List<String> costTypes = new List<String>();
        List<AggregateResult> aggrGroupCosttype = [SELECT Count(Id) productCount, Product_Group__c productGroup,Cost_Type__c costType FROM Product2
                                                   group by Product_Group__c, Cost_Type__c];
        if(aggrGroupCosttype != null && aggrGroupCosttype.size() > 0){ 
            for(AggregateResult agr : aggrGroupCosttype){
                String productGroup = (STRING) agr.get('productGroup');
                String costType = (STRING) agr.get('costType');
                //System.debug('--- productGroup: '+productGroup);
                //System.debug('--- costType: '+costType);
                if (!productGroups.contains(productGroup)) {
                	productGroups.add(productGroup);
                }
                if (!costTypes.contains(costType)) {
                	costTypes.add(costType);  
                }
                if (!productGroupMap.containsKey(productGroup)){
                    productGroupMap.put(productGroup,new List<String>());
                } else {
                    List<String> groupCostTypes = productGroupMap.get(productGroup);
                    groupCostTypes.add(costType);
                    productGroupMap.put(productGroup,groupCostTypes);
                }                
                //System.debug('--- productGroupMap ---'+productGroupMap);
            }
            System.debug('--- productGroups ---'+productGroups);
        }
        String org = 'LSU';
        String country = 'FI';
        String businessType = 'Consumer';
        List<String> districts = New List<String>{'FI_North','FI_South','FI_West','FI_East'};
        String profit = '4043 LSU Oulu';
        List<Factory_Price__c> fps = new List<Factory_Price__c>();
        List<Product_Cost__c> pcs = new List<Product_Cost__c>();
        List<Sales_Price__c> sps = new List<Sales_Price__c>();
        
        for (String pg : productGroupMap.keySet()) {
            for (String  ct: productGroupMap.get(pg)) {
                Factory_Price__c fp = new Factory_Price__c();
                fp.Organization__c = org;
                fp.Country__c = country;
                fp.Business_Type__c = businessType;
                fp.Product_Group__c = pg;
                fp.Cost_Type__c = ct;
                fp.Factory_Multiplier__c = 10.0;
                fp.IsActive__c  = true;
                fps.add(fp);
                for (String district : districts) {
                    Product_Cost__c pc = new Product_Cost__c();
                    pc.Organization__c = org;
                    pc.Country__c = country;
                    pc.Business_Type__c = businessType;
                    pc.District__c = district;
                    pc.Product_Group__c = pg;
                    pc.Cost_Type__c = ct;
                    pc.Cost_Multiplier__c = 20.0;
                    pc.IsActive__c  = true;
                    pcs.add(pc);
                    Sales_Price__c sp = new Sales_Price__c();
                    sp.Organization__c = org;
                    sp.Country__c = country;
                    sp.Business_Type__c = businessType;
                    sp.District__c = district;
                    sp.Profit_Center__c = profit;
                    sp.Product_Group__c = pg;
                    sp.Cost_Type__c = ct;
                    sp.Sales_Multiplier__c = 30.0;
                    sp.IsActive__c  = true;
                    sps.add(sp);
                }
            }
        }
        insert fps;
        insert pcs;
        insert sps;
        System.debug('--- setupPriceParameters - Factory: '+fps);
        System.debug('--- setupPriceParameters - Cost: '+pcs);
        System.debug('--- setupPriceParameters - Sales: '+sps);
    }
    @IsTest
    static void setupPriceParametersTest(){
        String testResult;
        List<Product2> products = LumonTestProducts.setupProducts();
        List<Id> productIds = new List<Id>(new Map<Id, Product2>(products).keySet()); 
        Test.startTest();
        Try {
            setupPriceParameters(productIds);
            testResult = 'successfully inserted Price Parameters';
            System.debug('--- setupPriceParametersTest - Factory: '+factoryPrices);
            System.debug('--- setupPriceParametersTest - Cost: '+productCosts);
            System.debug('--- setupPriceParametersTest - Sales: '+salesPrices);
        } catch (exception e){
            testResult = 'error when inserting Price Parameters: '+e.getMessage();
        }
        Test.stopTest();
        System.debug('--- setupPriceParametersTest: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
    }
}