force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>Business Attribute to identify the applicable Revenue and Cost Parameters</description>
    <label>Business Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>T2-{000000}</displayFormat>
        <label>Cost Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cost__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/BusinessId__c.field-meta.xml
<CustomField>
    <fullName>BusinessId__c</fullName>
    <description>SalesTori businessId</description>
    <label>BusinessId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max. Value OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min. Value OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/Sales_Price__c.object-meta.xml
<CustomObject>
    <label>Sales Price</label>
    <nameField>
        <displayFormat>T3-{000000}</displayFormat>
        <label>Sales Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/BusinessId__c.field-meta.xml
<CustomField>
    <fullName>BusinessId__c</fullName>
    <label>Business Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/IsSellable__c.field-meta.xml
<CustomField>
    <fullName>IsSellable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sellable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max. Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min. Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Sales_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Sales_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FI</fullName>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <label>Sweden</label>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
        <label>Norway</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Denmark</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Netherlands</label>
    </customValue>
    <masterLabel>Lumon Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PriceMultiplierController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-10-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class PriceMultiplierController{
    @AuraEnabled(cacheable=true)
    public static Map<String,Map<String,Factory_Price__c>> getFactoryPrices(List<String> productGroups, String recordOrg,String recordCountry, String recordBusiness){
        //Input: Organization and Business Type
        //Output: Factory Multiplier per ProductGroup and Cost Type
        List<Factory_Price__c> factoryPrices = new List<Factory_Price__c>();
        Map<String,Map<String,Factory_Price__c>> factoryPriceMap = new  Map<String,Map<String,Factory_Price__c>>();
        if (String.isNotBlank(recordOrg) || String.isNotBlank(recordCountry) ||String.isNotBlank(recordBusiness)) {            
            factoryPrices = [SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    Business_Type__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Factory_Multiplier__c,
                                    IsActive__c
                            FROM Factory_Price__c
                            WHERE Organization__c =: recordOrg
                            AND Country__c =: recordCountry
                            AND Business_Type__c =: recordBusiness
                            AND IsActive__c = true
                            AND Product_Group__c IN: productGroups];
        }
        System.debug('--- PriceMultiplierController - '+factoryPrices.size() +' Factory Prices retrieved');
        if (!factoryPrices.isEmpty()) {
            for (Factory_Price__c factoryPrice : factoryPrices) {
                String productGroup = factoryPrice.Product_Group__c;
                String costType = factoryPrice.Cost_Type__c;

                if(!factoryPriceMap.containsKey(productGroup)) {
                    factoryPriceMap.put(productGroup, new Map<String,Factory_Price__c>());
                }
                factoryPriceMap.get(productGroup).put(costType, factoryPrice);
            }
        }
        return factoryPriceMap;
    }
    @AuraEnabled(cacheable=true)
    public static Map<String,Map<String,Product_Cost__c>> getProductCosts(List<String> productGroups, String recordOrg,String recordCountry,
                                                                             String recordBusiness,String recordDistrict){
        //Input: Organization and Business Type
        //Output: Factory Multiplier per ProductGroup and Cost Type
        List<Product_Cost__c> productCosts = new List<Product_Cost__c>();
        Map<String,Map<String,Product_Cost__c>> productCostMap = new  Map<String,Map<String,Product_Cost__c>>();
        if (String.isNotBlank(recordOrg) && String.isNotBlank(recordCountry) 
            && String.isNotBlank(recordBusiness) && String.isNotBlank(recordDistrict)) {
            productCosts = [SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    Business_Type__c,
                                    District__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Cost_Multiplier__c,
                                    Max_Value__c,
                                    Min_Value__c,
                                    IsActive__c
                            FROM Product_Cost__c
                            WHERE Organization__c =: recordOrg
                            AND Country__c =: recordCountry
                            AND Business_Type__c =: recordBusiness
                            AND District__c =: recordDistrict
                            AND IsActive__c = true
                            AND Product_Group__c IN: productGroups];
        }
        System.debug('--- PriceMultiplierController - '+productCosts.size() +' Product Costs retrieved');
        if (!productCosts.isEmpty()) {
            for (Product_Cost__c productCost: productCosts) {
                String productGroup = productCost.Product_Group__c;
                String costType = productCost.Cost_Type__c;
                if(!productCostMap.containsKey(productGroup)) {
                    productCostMap.put(productGroup, new Map<String, Product_Cost__c>());
                }
                productCostMap.get(productGroup).put(costType, productCost);
            }
        }
        return productCostMap;
    }
    @AuraEnabled(cacheable=true)
    public static Map<String,Map<String,Sales_Price__c>> getSalesPrices(List<String> productGroups,String recordOrg,String recordCountry,
                                                                             String recordBusiness,String recordDistrict,
                                                                             String recordProfitCenter, String recordBusinessId){
        //Input: Organization and Business Type
        //Output: Factory Multiplier per ProductGroup and Cost Type
        List<Sales_Price__c> salesPrices = new List<Sales_Price__c>();
        Map<String,Map<String,Sales_Price__c>> salesPriceMap = new  Map<String,Map<String,Sales_Price__c>>();
        if (String.isNotBlank(recordOrg) && String.isNotBlank(recordCountry) 
            && String.isNotBlank(recordBusiness) && String.isNotBlank(recordDistrict)
            && String.isNotBlank(recordProfitCenter)) {
            salesPrices = [SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    BusinessId__c,
                                    Business_Type__c,
                                    District__c,
                                    Profit_Center__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Sales_Multiplier__c,
                                    Max_Value__c,
                                    Min_Value__c,
                                    IsSellable__c,
                                    IsActive__c
                            FROM Sales_Price__c
                            WHERE Organization__c =: recordOrg
                            AND Country__c =: recordCountry
                            AND Business_Type__c =: recordBusiness
                            AND (
                                (District__c =: recordDistrict AND Profit_Center__c = null)
                                OR (Profit_Center__c =: recordProfitCenter)
                                OR (BusinessId__c =: recordBusinessId)
                                )
                            AND IsActive__c = true
                            AND Product_Group__c IN: productGroups];
        }
        System.debug('--- PriceMultiplierController -'+salesPrices.size() +' Sales Prices retrieved');
        if (!salesPrices.isEmpty()) {
            for (Sales_Price__c salesPrice : salesPrices) {
                String productGroup = salesPrice.Product_Group__c;
                String costType = salesPrice.Cost_Type__c;

                if(!salesPriceMap.containsKey(productGroup)) {
                    salesPriceMap.put(productGroup, new Map<String, Sales_Price__c>());
                }
                salesPriceMap.get(productGroup).put(costType, salesPrice);
            }
        }
        return salesPriceMap;
    }
    @AuraEnabled(cacheable=true)
    public static Factory_Price__c getFactoryPrice(String productGroup, String costType,
                                                    String recordOrg,String recordCountry, String recordBusiness){
        //Input: Organization and Business Type
        //Output: Factory Multiplier per ProductGroup and Cost Type
        Factory_Price__c factoryPrice = new Factory_Price__c();
        if (String.isNotBlank(recordOrg) || String.isNotBlank(recordCountry) ||String.isNotBlank(recordBusiness)) {
            System.debug('---  Retrieving Factory Prices');
            
            factoryPrice = [SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    Business_Type__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Factory_Multiplier__c,
                                    IsActive__c
                            FROM Factory_Price__c
                            WHERE Organization__c =: recordOrg
                            AND Country__c =: recordCountry
                            AND Business_Type__c =: recordBusiness
                            AND IsActive__c = true
                            AND Product_Group__c =: productGroup
                            AND Cost_Type__c =: costType
                            LIMIT 1];
        }
        System.debug('--- PriceMultiplierController - Factory Price: '+factoryPrice);
        return factoryPrice;
    }
    @AuraEnabled(cacheable=true)
    public static Product_Cost__c getProductCost(String productGroup,String costType, 
                                                    String recordOrg,String recordCountry,
                                                    String recordBusiness,String recordDistrict){
        //Input: Organization and Business Type
        //Output: Factory Multiplier per ProductGroup and Cost Type
        Product_Cost__c productCost = new Product_Cost__c();
        if (String.isNotBlank(recordOrg) && String.isNotBlank(recordCountry) 
            && String.isNotBlank(recordBusiness) && String.isNotBlank(recordDistrict)) {
            productCost = [SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    Business_Type__c,
                                    District__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Cost_Multiplier__c,
                                    Max_Value__c,
                                    Min_Value__c,
                                    IsActive__c
                            FROM Product_Cost__c
                            WHERE Organization__c =: recordOrg
                            AND Country__c =: recordCountry
                            AND Business_Type__c =: recordBusiness
                            AND District__c =: recordDistrict
                            AND Product_Group__c =: productGroup
                            AND Cost_Type__c =: costType
                            LIMIT 1];
        }
        System.debug('--- PriceMultiplierController - Product Cost: '+productCost);
        return productCost;
    }
    @AuraEnabled(cacheable=true)
    public static Sales_Price__c getSalesPrice(String productGroup, String costType, 
                                                String recordOrg,String recordCountry,
                                                String recordBusiness,String recordDistrict,
                                                String recordProfitCenter, String recordBusinessId){
        //Input: Organization and Business Type
        //Output: Factory Multiplier per ProductGroup and Cost Type
        Sales_Price__c salesPrice = new Sales_Price__c();
        if (String.isNotBlank(recordOrg) && String.isNotBlank(recordCountry) 
            && String.isNotBlank(recordBusiness) && String.isNotBlank(recordDistrict)
            && String.isNotBlank(recordProfitCenter)) {
            salesPrice = [SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    BusinessId__c,
                                    Business_Type__c,
                                    District__c,
                                    Profit_Center__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Sales_Multiplier__c,
                                    Max_Value__c,
                                    Min_Value__c,
                                    IsSellable__c,
                                    IsActive__c
                            FROM Sales_Price__c
                            WHERE Organization__c =: recordOrg
                            AND Country__c =: recordCountry
                            AND Business_Type__c =: recordBusiness
                            AND (
                                (District__c =: recordDistrict AND Profit_Center__c = null)
                                OR (Profit_Center__c =: recordProfitCenter)
                                OR (BusinessId__c =: recordBusinessId)
                                )
                            AND Product_Group__c =: productGroup
                            AND Cost_Type__c =: costType
                            LIMIT 1];
        }
        System.debug('--- PriceMultiplierController - Sales Price: '+SalesPrice);
        return salesPrice;
    }
}