force-app/main/default/objects/ResourceAbsence/fields/Approval_handled_by__c.field-meta.xml
<CustomField>
    <fullName>Approval_handled_by__c</fullName>
    <description>Filled in by the approval process. Indicates the person&apos;s name who approved the request.</description>
    <label>Approval handled by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResourceAbsence/fields/HolidayId__c.field-meta.xml
<CustomField>
    <fullName>HolidayId__c</fullName>
    <description>The Id of the Holiday Record which was user for this absence.</description>
    <inlineHelpText>The Id of the Holiday Record which was user for this absence.</inlineHelpText>
    <label>HolidayId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResourceAbsence/fields/Operating_Hours_Holiday__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours_Holiday__c</fullName>
    <description>Reference to Operating Hours Holiday record.</description>
    <label>Operating Hours Holiday</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResourceAbsence/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This absence is related to this Service Territory</description>
    <inlineHelpText>This absence is related to this Service Territory</inlineHelpText>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Resource Absences</relationshipLabel>
    <relationshipName>Resource_Absences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <label>Service Territory</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ServiceTerritoryMemberTriggerTest.cls
/**
 * @author Reijo Mattila, reijo.mattila@fluidogroup.com
 * 01.12.2023
 *
 * Trigger Test Class
 */

 @isTest
 public class ServiceTerritoryMemberTriggerTest {
     
 
    @IsTest
    public static void testInsertSTMs() {
        
        OperatingHoursHolidayTriggerHandler.dontRunInsertTriggerForTest = true;
        OperatingHours oh = new OperatingHours(Name='TestOH');
        insert oh;
        Holiday h = [SELECT Id FROM Holiday Limit 1];
        ServiceResource sr = new ServiceResource(Name='TestRes', isActive = true, RelatedRecordId = UserInfo.getUserId());
        insert sr;
        ServiceTerritory st = new ServiceTerritory(Name='TestTer', OperatingHoursId = oh.Id, isActive = true);
        insert st;
        OperatingHoursHoliday ohh = new OperatingHoursHoliday(OperatingHoursId = oh.Id, HolidayId = h.Id);
        insert ohh;

        Test.startTest();
        ServiceTerritoryMember stm = new ServiceTerritoryMember(ServiceResourceId = sr.Id, ServiceTerritoryId = st.Id, EffectiveStartDate=system.today());
        insert stm;
        Test.stopTest();

        System.assertEquals(1,[SELECT Id FROM ResourceAbsence].size());
    }

    @IsTest
    public static void testDeleteSTMs() {

        ServiceTerritoryMemberTriggerHandler.dontRunInsertTriggerForTest = true;
        OperatingHoursHolidayTriggerHandler.dontRunInsertTriggerForTest = true;
        OperatingHours oh = new OperatingHours(Name='TestOH');
        insert oh;
        Holiday h = [SELECT Id, ActivityDate FROM Holiday Limit 1];
        ServiceResource sr = new ServiceResource(Name='TestRes', isActive = true, RelatedRecordId = UserInfo.getUserId());
        insert sr;
        ServiceTerritory st = new ServiceTerritory(Name='TestTer', OperatingHoursId = oh.Id, isActive = true);
        insert st;
        ServiceTerritoryMember stm = new ServiceTerritoryMember(ServiceResourceId = sr.Id, ServiceTerritoryId = st.Id, EffectiveStartDate=system.today());
        insert stm;
        OperatingHoursHoliday ohh = new OperatingHoursHoliday(OperatingHoursId = oh.Id, HolidayId = h.Id);
        insert ohh;
        DateTime start = DateTime.newInstance(h.ActivityDate.year(), h.ActivityDate.month(), h.ActivityDate.day(), 00, 00, 01);
        DateTime end2 = DateTime.newInstance(h.ActivityDate.year(), h.ActivityDate.month(), h.ActivityDate.day(), 23, 59, 59);
        ResourceAbsence ra = new ResourceAbsence(ResourceId = sr.Id, Start = start, End = end2, HolidayId__c = ohh.Id, Operating_Hours_Holiday__c = ohh.Id, Service_Territory__c = st.Id, FSL__Approved__c = true, Approval_handled_by__c = 'System');
        insert ra;

        Test.startTest();
        delete [SELECT Id FROM ServiceTerritoryMember WHERE Id =: stm.Id];
        Test.stopTest();

        System.assertEquals(0,[SELECT Id FROM ResourceAbsence].size());
    }
 }