force-app/main/default/objects/Case/fields/CaseCategory__c.field-meta.xml
<CustomField>
    <fullName>CaseCategory__c</fullName>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Case_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CaseDetailedDescription__c.field-meta.xml
<CustomField>
    <fullName>CaseDetailedDescription__c</fullName>
    <label>Detailed Description</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseGroup__c.field-meta.xml
<CustomField>
    <fullName>CaseGroup__c</fullName>
    <description>The Group that is handling the Case</description>
    <inlineHelpText>The Group that is handling the Case</inlineHelpText>
    <label>Case Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Support_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CaseInQueue__c.field-meta.xml
<CustomField>
    <fullName>CaseInQueue__c</fullName>
    <description>Indicates is Case is Owned by a Queue</description>
    <formula>IF(ISBLANK(Owner:Queue.Id),FALSE,TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if the Case is Assigned to a Queue</inlineHelpText>
    <label>Case In Queue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseProcessStage__c.field-meta.xml
<CustomField>
    <fullName>CaseProcessStage__c</fullName>
    <description>Reclamation order stages are depended on status values.</description>
    <label>Process Stage DELETE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Stage</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Resolution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CaseResolution__c.field-meta.xml
<CustomField>
    <fullName>CaseResolution__c</fullName>
    <description>Description of the the Case Resolution</description>
    <inlineHelpText>Description of the the Case Resolution</inlineHelpText>
    <label>Case Resolution</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseResolvedOnTime__c.field-meta.xml
<CustomField>
    <fullName>CaseResolvedOnTime__c</fullName>
    <formula>IF(
    AND(
        NOT(ISBLANK( CaseResolvedDate__c )),
        CaseResolvedDate__c &lt;= SlaDeadline__c
    ),
    TRUE,
    FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Resolved in SLA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseSubType__c.field-meta.xml
<CustomField>
    <fullName>CaseSubType__c</fullName>
    <label>Case SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Case_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <description>Case Classification to indicate the Type of Issue</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Case_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/hasPictures__c.field-meta.xml
<CustomField>
    <fullName>hasPictures__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Filled in by IM / Support when creating the case. Needs to be checked for the work scheduling to be possible.</description>
    <inlineHelpText>Filled in by IM / Support when creating the case. Needs to be checked for the work scheduling to be possible.</inlineHelpText>
    <label>has Pictures</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows related opportunity</description>
    <inlineHelpText>Please associate case to an opportunity if known</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup-field for order related to the case.</description>
    <label>Order DELETE</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PermitApplicationDetails__c.field-meta.xml
<CustomField>
    <fullName>PermitApplicationDetails__c</fullName>
    <description>Details about the Building Permit Application</description>
    <inlineHelpText>Details about the Building Permit Application</inlineHelpText>
    <label>Permit Application Details</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/PermitAuthority__c.field-meta.xml
<CustomField>
    <fullName>PermitAuthority__c</fullName>
    <description>This field logs information from the city authority where the Building permit was applied.</description>
    <inlineHelpText>Please provide the name of the city authority where the Building permit was applied.</inlineHelpText>
    <label>Name City Authority</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/PermitDetails__c.field-meta.xml
<CustomField>
    <fullName>PermitDetails__c</fullName>
    <description>This Field is for additional inforrmation related to the Building Permit Case Handling</description>
    <inlineHelpText>Please provide additional information related to the Building Permit Process</inlineHelpText>
    <label>Permit Result Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/PermitPrincipalDesigner__c.field-meta.xml
<CustomField>
    <fullName>PermitPrincipalDesigner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pääsuunnittelija</description>
    <inlineHelpText>Please fill in Principal Designer for the Case</inlineHelpText>
    <label>Principal Designer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PermitApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PermitSiteManager__c.field-meta.xml
<CustomField>
    <fullName>PermitSiteManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vastaava Työnjohtaja</description>
    <inlineHelpText>Fill in Responsible Site Manager for the Case</inlineHelpText>
    <label>Responsible Site Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PermitApplications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PermitStatus__c.field-meta.xml
<CustomField>
    <fullName>PermitStatus__c</fullName>
    <description>The Status of the Permit Application</description>
    <inlineHelpText>The Status of the Permit Application</inlineHelpText>
    <label>Building Permit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PermitStructuralEngineer__c.field-meta.xml
<CustomField>
    <fullName>PermitStructuralEngineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Rakennesuunnittelija</description>
    <inlineHelpText>Fill in Structural Engineer for the Case</inlineHelpText>
    <label>Structural Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PermitApplications2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/QualityCauseCode__c.field-meta.xml
<CustomField>
    <fullName>QualityCauseCode__c</fullName>
    <description>Picklist value for reclamation classifications</description>
    <label>Cause Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Quality_Cause_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/QualityProcessClass__c.field-meta.xml
<CustomField>
    <fullName>QualityProcessClass__c</fullName>
    <description>Picklist for reclamation classification</description>
    <label>Process Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Quality_Process_Classes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reclamation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Opportunity.Order_type__c</field>
            <operation>equals</operation>
            <value>Reclamation</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Territory2Id</field>
            <operation>equals</operation>
            <value>Reclamation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (Reclamation)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReclamationCause__c.field-meta.xml
<CustomField>
    <fullName>ReclamationCause__c</fullName>
    <description>free text field (up to 255 characters) for reclamation classifications</description>
    <label>Reclamation Cause DELETE</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReclamationCauseDescription__c.field-meta.xml
<CustomField>
    <fullName>ReclamationCauseDescription__c</fullName>
    <description>Quality event reclamation cause description</description>
    <label>Reclamation Cause Description DELETE</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lumon Internal User requesting Internal IT Support</description>
    <inlineHelpText>Lumon Internal User requesting Internal IT Support</inlineHelpText>
    <label>Requester DEL</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Organization_Attribute__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Internal_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SlaCount__c.field-meta.xml
<CustomField>
    <fullName>SlaCount__c</fullName>
    <description>Count how many tickets were solved before the deadline</description>
    <formula>IF(
AND(
NOT(ISBLANK( CaseResolvedDate__c )),
CaseResolvedDate__c &lt;= SlaDeadline__c
),
1,
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SLA Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SlaDeadline__c.field-meta.xml
<CustomField>
    <fullName>SlaDeadline__c</fullName>
    <formula>CASE(
     Priority ,
    &quot;Low&quot;,  CreatedDate  + 15,
    &quot;Medium&quot;, CreatedDate  + 7,
    &quot;High&quot;, CreatedDate + 3,
    NULL
)</formula>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SourceEmail__c.field-meta.xml
<CustomField>
    <fullName>SourceEmail__c</fullName>
    <description>The Email Address from where the Case is Reported</description>
    <inlineHelpText>The Email Address from where the Case is Reported</inlineHelpText>
    <label>Source Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/SourcePhone__c.field-meta.xml
<CustomField>
    <fullName>SourcePhone__c</fullName>
    <description>The Phone Number from where the Case is Reported</description>
    <inlineHelpText>The Phone Number from where the Case is Reported</inlineHelpText>
    <label>Source Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/UnderWarranty__c.field-meta.xml
<CustomField>
    <fullName>UnderWarranty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set by the flow &quot;Account - Create Case&quot; or &quot;Mobile - Change WOLI status&quot;, then warranty is considered to be applicable and there should be no cost to the customer.</description>
    <inlineHelpText>Warranty is considered to be applicable for the case handling.</inlineHelpText>
    <label>Warranty applies DELETE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field identifies the related Work Order for which the Reclamation Case was created. Filled in by automation.</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Reclamations</relationshipLabel>
    <relationshipName>Reclamations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/WorkOrderLineItem__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field identifies the related Work Order line Item for which the Reclamation Case was created so that taken images can be re-linked to Case from WOLI.</description>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>Reclamations</relationshipLabel>
    <relationshipName>Reclamations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Case_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CS</fullName>
        <label>Customer Service</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>ICT Support</label>
    </customValue>
    <customValue>
        <fullName>LOG</fullName>
        <label>Logistics Support</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PERM</fullName>
        <label>Permit Applications</label>
    </customValue>
    <customValue>
        <fullName>FAC</fullName>
        <label>Production Support</label>
    </customValue>
    <customValue>
        <fullName>RECL</fullName>
        <label>Reclamation Support</label>
    </customValue>
    <customValue>
        <fullName>SF</fullName>
        <label>Salesforce Support</label>
    </customValue>
    <customValue>
        <fullName>SPEC</fullName>
        <label>Special Order Support</label>
    </customValue>
    <customValue>
        <fullName>TS</fullName>
        <label>Technical Support</label>
    </customValue>
    <customValue>
        <fullName>WEB</fullName>
        <label>Webshop Support</label>
    </customValue>
    <customValue>
        <fullName>QUAL</fullName>
        <label>Process Quality</label>
    </customValue>
    <customValue>
        <fullName>INST</fullName>
        <label>Installation Support</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Lumon Case Categories</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Quality_Process_Classes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>01 Guarantee</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>02 Sales (Organisation)</label>
    </customValue>
    <customValue>
        <fullName>03</fullName>
        <label>03 Installation</label>
    </customValue>
    <customValue>
        <fullName>04</fullName>
        <label>04 System</label>
    </customValue>
    <customValue>
        <fullName>05</fullName>
        <label>05 Transportation</label>
    </customValue>
    <customValue>
        <fullName>06</fullName>
        <label>06 Balustrade Factory</label>
    </customValue>
    <customValue>
        <fullName>07</fullName>
        <label>07 Prefabricated Terrace, Roof, Patio</label>
    </customValue>
    <customValue>
        <fullName>08</fullName>
        <label>08 Glazing Factory (L5, L6, L7)</label>
    </customValue>
    <customValue>
        <fullName>09</fullName>
        <label>09 Blinds</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11 Additional order</label>
    </customValue>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation_05</fullName>
        <isActive>false</isActive>
        <label>Transportation_05</label>
    </customValue>
    <customValue>
        <fullName>System_04</fullName>
        <isActive>false</isActive>
        <label>System_04</label>
    </customValue>
    <customValue>
        <fullName>Sales_Organisation_02</fullName>
        <isActive>false</isActive>
        <label>Sales_Organisation_02</label>
    </customValue>
    <customValue>
        <fullName>Prefabricated_Terrace_Roof_Patio_07</fullName>
        <isActive>false</isActive>
        <label>Prefabricated_Terrace_Roof_Patio_07</label>
    </customValue>
    <customValue>
        <fullName>Installation_03</fullName>
        <isActive>false</isActive>
        <label>Installation_03</label>
    </customValue>
    <customValue>
        <fullName>Guarantee_01</fullName>
        <isActive>false</isActive>
        <label>Guarantee_01</label>
    </customValue>
    <customValue>
        <fullName>Glazing_Factory_L5L6L7_08</fullName>
        <isActive>false</isActive>
        <label>Glazing_Factory_L5L6L7_08</label>
    </customValue>
    <customValue>
        <fullName>Blinds_09</fullName>
        <isActive>false</isActive>
        <label>Blinds_09</label>
    </customValue>
    <customValue>
        <fullName>Balustrade_Factory_06</fullName>
        <isActive>false</isActive>
        <label>Balustrade_Factory_06</label>
    </customValue>
    <masterLabel>Lumon Quality Process Classes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-18-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class CaseController {
    @AuraEnabled(cacheable=true)
    public static Case getCaseRecord(Id recordId) {
        // Populate map from SOQL query on Case
        List<Id> recordIds = new List<Id>{recordId};
        List<Case> caseRecords = getCases(recordIds);        
        Case caseRecord = caseRecords[0];
        System.debug('--- CaseController - Case Record: '+caseRecord);
        return caseRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static Case getCaseByNumber(String caseNumber) {
        Case caseRecord;
        if (String.IsNotBlank(caseNumber)){
            Id caseId = ([SELECT Id,CaseNumber FROM Case WHERE CaseNumber = :caseNumber LIMIT 1]?.Id);
            caseRecord = getCaseRecord(caseId);
        }
        return caseRecord;
    }
    @AuraEnabled(cacheable=true)
    public static List<Case> getCasesByGroup(String caseGroup) {
        List<Case> casesByGroup = ([SELECT Id,CaseGroup__c FROM Case WHERE CaseGroup__c = :caseGroup]);
        List<Id> caseIds = new List<Id>(new Map<Id, Case>(casesByGroup).keySet()); 
        List<Case> cases = getCases(caseIds);
        return cases;
    }

    @AuraEnabled(cacheable=true)
    public static List<Case> getCases(List<Id> recordIds) {
        List<Case> cases = ([SELECT Id,
                                    MasterRecordId, 
                                    CaseNumber, 
                                    ContactId, 
                                    AccountId, 
                                    AssetId, 
                                    ProductId, 
                                    EntitlementId, 
                                    FeedItemId,
                                    SourceId, 
                                    BusinessHoursId, 
                                    ParentId, 
                                    AssetWarrantyId, 
                                    ServiceContractId,
                                    SuppliedName, SuppliedEmail, SuppliedPhone, SuppliedCompany, 
                                    Type, RecordTypeId, 
                                    Status, Reason, 
                                    Origin, Language, 
                                    Subject, Priority, Description, 
                                    IsClosed, ClosedDate, 
                                    IsEscalated, CurrencyIsoCode, 
                                    OwnerId, IsClosedOnCreate, 
                                    SlaStartDate, SlaExitDate, IsStopped, StopStartDate, 
                                    CreatedDate, CreatedById, 
                                    LastModifiedDate, LastModifiedById, 
                                    SystemModstamp, 
                                    ContactPhone, ContactMobile, ContactEmail, ContactFax, 
                                    Comments, 
                                    LastViewedDate, LastReferencedDate, 
                                    MilestoneStatus, 
                                    // Case Information
                                    CaseResolution__c, 
                                    CaseDetailedDescription__c, 
                                    CaseProcessStage__c, 
                                    hasPictures__c,
                                    // Additional Relations
                                    Opportunity__c, 
                                    Order__c, 
                                    Reclamation__c,
                                    WorkOrderLineItem__c, 
                                    WorkOrder__c, 
                                    // Categorization
                                    CaseCategory__c, 
                                    CaseType__c, 
                                    CaseSubType__c,
                                    // Assignment
                                    CaseInQueue__c,
                                    CaseGroup__c, 
                                    //Milestones
                                    SlaDeadline__c, 
                                    CaseResolvedOnTime__c, 
                                    SlaCount__c, 
                                    SourceEmail__c, 
                                    SourcePhone__c, 
                                    Requester__c,                                    
                                    //Permit Applications
                                    PermitApplicationDetails__c, 
                                    PermitAuthority__c, 
                                    PermitDetails__c, 
                                    PermitPrincipalDesigner__c, 
                                    PermitSiteManager__c, 
                                    PermitStatus__c, 
                                    PermitStructuralEngineer__c,
                                    // Reclamations
                                    ReclamationCauseDescription__c, 
                                    ReclamationCause__c, 
                                    UnderWarranty__c,
                                    //Quality
                                    QualityProcessClass__c, 
                                    QualityCauseCode__c, 
                                    QualityTargetCode__c                           
                                    FROM Case 
                                    WHERE Id IN :recordIds
                                    //OR OwnedBy__c IN: recordIds
                                    //OR StructuralAnalysis__c IN: recordIds
                                    ]);
        System.debug('--- CaseController - Case Record Count : '+cases.size());
        return cases;
    } 
}