force-app/main/default/objects/Case/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the Product within a Configuration Plan.</description>
    <label>Configuration Product DELETE</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows related opportunity</description>
    <inlineHelpText>Please associate case to an opportunity if known</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Confirmed_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Delivery_Date__c</fullName>
    <description>Confirmed delivery date value from Production</description>
    <label>Confirmed Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Features_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Features_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce representation of hasFeaturesBeenConfirmed</description>
    <label>Features Confirmed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Line__c.field-meta.xml
<CustomField>
    <fullName>Plan_Line__c</fullName>
    <description>Plan Line used in the configuration</description>
    <label>Plan Line OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>IF(Inspection_Code__c = 2, IMAGE(&apos;/img/msg_icons/error32.png&apos;,&apos;ERROR&apos;,20,20),  
 IF(!Measurements_Verified__c &amp;&amp; !Features_Confirmed__c, IMAGE(&apos;/img/msg_icons/warning32.png&apos;,&apos;WARN&apos;,20,20), 
  IF(!Measurements_Verified__c || !Features_Confirmed__c, IMAGE(&apos;/img/msg_icons/info32.png&apos;,&apos;WARN&apos;,20,20), 
   IMAGE(&apos;/img/msg_icons/confirm32.png&apos;,&apos;WARN&apos;,20,20)
  )
 )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case OLD</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Delivery_Date__c</fullName>
    <inlineHelpText>This date is received from ERP.</inlineHelpText>
    <label>Confirmed Delivery Date DEL</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <description>To plan for installation, a Confirmed installation date &amp; time will show in this field. 
This data is captured from the Installation Capacity component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Confirmed installation date and time.</inlineHelpText>
    <label>Confirmed installation time DEL</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preliminary_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_installation_time__c</fullName>
    <description>To plan for installation, a preliminary installation date &amp; time will show in this field. 
This data is captured from the Installation Scheduling component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Preliminary installation date and time.</inlineHelpText>
    <label>Preliminary installation time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <label>Confirmed installation time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery Date</description>
    <inlineHelpText>Delivery Date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from related Configuration Option</description>
    <formula>Configuration_Option__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfigurationProductsController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 06-19-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ConfigurationProductsController {
    public class ComponentData {
        @AuraEnabled
        public List<Configuration_Product__c> configurationProducts { get; set; }
        @AuraEnabled
        public String opportunityId { get; set; }
        @AuraEnabled
        public String orderType { get; set; }
        public ComponentData(Id recordId) {
            Opportunity opportunity = new Opportunity();
            if (recordId.getSobjectType() == Case.getSObjectType()) {
                opportunity = caseOpportunityId(recordId);
            } else if (recordId.getSobjectType() == Opportunity.getSObjectType()) {
                opportunity = queryOpportunity(recordId);
            }
            opportunityId = opportunity.Id;
            orderType = opportunity.Order_type__c;
            configurationProducts = queryConfigurationProducts(opportunityId);
        }
    }

    @AuraEnabled
    public static Opportunity caseOpportunityId(Id recordId) {
        return [
            SELECT Id, Order_type__c
            FROM Opportunity
            WHERE Case__c = :recordId AND Order_type__c = 'Reclamation'
            LIMIT 1
        ];
    }

    // Method to fetch Order type value if the source object is Opportunity
    @AuraEnabled
    public static Opportunity queryOpportunity(Id recordId) {
        return [SELECT Id, Order_type__c FROM Opportunity WHERE Id = :recordId LIMIT 1];
    }

    private static List<Configuration_Product__c> queryConfigurationProducts(String opportunityId) {
        return [
            SELECT
                Product__r.Name,
                Product__r.Id,
                Configuration__r.Plan_Type__c,
                Configuration__r.Plan_Name__c,
                Configuration__r.Plan_Line__c,
                Configuration__r.Plan_Apartment__c,
                Configuration__r.Plan_Floor__c,
                Verification__c,
                Configuration__c,
                //Configuration__r.Opportunity__r.Delivery_Date__c,
                //Configuration__r.Opportunity__r.Confirmed_Delivery_Date__c,
                //Configuration__r.Opportunity__r.Preliminary_installation_time__c,
                //Configuration__r.Opportunity__r.Confirmed_installation_time__c,
                Configuration__r.Opportunity__r.StageName,
                Configuration__r.Quote__r.Status,
                Configuration__r.Visual_Id__c,
                RVN_Number__c,
                RVN__c,
                LastModifiedDate,
                Quantity__c,
                Features_Confirmed__c,
                Measurements_Verified__c,
                Inspection_Code__c
            FROM Configuration_Product__c
            WHERE Configuration__r.Opportunity__c = :opportunityId
            LIMIT 1000
        ];
    }

    @AuraEnabled
    public static ComponentData getComponentData(String recordId) {
        return new ComponentData(recordId);
    }

    @AuraEnabled
    public static void deleteConfigurationProducts(List<Id> configurationProductIds) {
        if (configurationProductIds.isEmpty()) {
            return;
        }

        List<Configuration_Product__c> configurationProducts = [
            SELECT Id, Configuration__c, Configuration__r.Opportunity__r.OwnerId
            FROM Configuration_Product__c
            WHERE Id IN :configurationProductIds AND Configuration__r.Opportunity__r.StageName = 'Quoting'
            LIMIT 2000
        ];

        Role_Settings__c roleSettings = RoleSettingsController.getRoleSettingsMap().get(UserInfo.getProfileId());
        Boolean manager = roleSettings.isManager__c;
        Boolean salesUser = roleSettings.isSales__c;
        Boolean serviceUser = roleSettings.isService__c;

        if (!roleSettings.isAdmin__c && !roleSettings.isSupport__c) {
            // TODO
            // if(!salesUser && !serviceUser) {
            //     throw new DeleteNotAllowedException('User does not have rights to delete');
            // }

            // User with roles above current user's role have also rights to delete
            Map<Id, UserRole> userRoles = new Map<Id, UserRole>([SELECT Id, ParentRoleId, Name FROM UserRole]);
            Map<Id, Set<Id>> roleParentRoles = new Map<Id, Set<Id>>();
            for (UserRole userRole : userRoles.values()) {
                if (!roleParentRoles.containsKey(userRole.Id)) {
                    roleParentRoles.put(userRole.Id, new Set<Id>());
                }
            }
            for (UserRole userRole : userRoles.values()) {
                UserRole parent = userRoles.get(userRole.ParentRoleId);
                while (parent != null) {
                    roleParentRoles.get(userRole.Id).add(parent.Id);
                    parent = userRoles.get(parent.ParentRoleId);
                }
            }

            Id currentUserId = UserInfo.getUserId();
            Set<Id> managersUsers = new Set<Id>();
            for (Configuration_Product__c configurationProduct : configurationProducts) {
                Id opportunityOwnerId = configurationProduct.Configuration__r.Opportunity__r.OwnerId;
                // Not the owner and the current user is below the owner in the role hierarchy
                if (
                    opportunityOwnerId != currentUserId &&
                    !roleParentRoles.get(currentUserId).contains(opportunityOwnerId)
                ) {
                    throw new DeleteNotAllowedException('Delete not allowed');
                }
            }
        }

        List<Configuration__c> configurationPlans = new List<Configuration__c>();
        Set<Id> configurationPlanIds = new Set<Id>();
        for (Configuration_Product__c configurationProduct : configurationProducts) {
            Id configurationPlanId = configurationProduct.Configuration__c;
            if (configurationPlanId != null && !configurationPlanIds.contains(configurationPlanId)) {
                configurationPlanIds.add(configurationPlanId);
                configurationPlans.add(new Configuration__c(Id = configurationPlanId));
            }
        }
        if (!configurationPlanIds.isEmpty()) {
            delete [
                SELECT Id
                FROM QuoteLineItem
                WHERE Configuration_Plan__c IN :configurationPlanIds
                LIMIT 1000
            ];
            delete configurationPlans;
        }
    }

    public class DeleteNotAllowedException extends Exception {
    }
}