force-app/main/default/objects/Case/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the Product within a Configuration Plan.</description>
    <label>Configuration Product DELETE</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reclamation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Opportunity.Order_type__c</field>
            <operation>equals</operation>
            <value>Reclamation</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Territory2Id</field>
            <operation>equals</operation>
            <value>Reclamation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (Reclamation)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Plan__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Plan__c</fullName>
    <description>Parent&apos;s Product related Plan</description>
    <formula>Configuration_Product__r.Configuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Configuration Plan OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit Of Measure OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Transmission</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <formula>TEXT(QuantityUnitOfMeasure)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Plan__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Factory_Price__c.field-meta.xml
<CustomField>
    <fullName>Factory_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Price OLD</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxCost__c.field-meta.xml
<CustomField>
    <fullName>fxCost__c</fullName>
    <description>Calculated Result of Base Price * Cost Multiplier * Quantity</description>
    <formula>IF(Cost_Multiplier__c &gt; 0,  fxUnitCost__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Line Item Cost</inlineHelpText>
    <label>fxCost</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxDiscount__c.field-meta.xml
<CustomField>
    <fullName>fxDiscount__c</fullName>
    <formula>IF(AND(UnitPrice&gt;0,fxUnitSalesPrice__c&gt;0),(1 - ( UnitPrice/fxUnitSalesPrice__c)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxDiscount</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxFactory__c.field-meta.xml
<CustomField>
    <fullName>fxFactory__c</fullName>
    <formula>IF(Factory_Multiplier__c &gt; 0, fxUnitFactoryPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxFactory</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxSales__c.field-meta.xml
<CustomField>
    <fullName>fxSales__c</fullName>
    <description>The ListPrice calculated from Base Price with a Sales Multiplier</description>
    <formula>IF( Sales_Multiplier__c &gt; 0,   fxUnitSalesPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Price on the PriceList aka List Price</inlineHelpText>
    <label>fxSales</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <inlineHelpText>List Price</inlineHelpText>
    <label>List Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Price__c</fullName>
    <inlineHelpText>Min Price</inlineHelpText>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Sales_Price__c</fullName>
    <inlineHelpText>Min Sales Price OLD</inlineHelpText>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Cost__c.field-meta.xml
<CustomField>
    <fullName>Product_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Cost</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Margin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin__c</fullName>
    <formula>IF(Revenue__c&gt;0,(Gross_Profit__c / Revenue__c),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Margin OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Sales_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Sales Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingServicesController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 11-21-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class PricingServicesController {
    @TestVisible
    public static final List<String> SERVICES_PRODUCT_GROUPS = new List<String>{'HUOLTO','PERUSHUOLTO', 'MÄÄRÄAIKAISHUOLTO','TUNTITYÖ'};

    public with sharing class ComponentData {
        @AuraEnabled
        public Quote quote { get; private set; }
        @AuraEnabled
        public Opportunity opportunity { get; private set; }
        @AuraEnabled
        public Boolean disabled { get; private set; }
        @AuraEnabled
        public Map<String, List<PricingSummaryService.PicklistOption>> picklistValues { get; private set; }
        @AuraEnabled
        public Map<String, Map<String, List<PricingSummaryService.PicklistOption>>> picklistDependencies {
            get;
            private set;
        }
        @TestVisible
        @AuraEnabled
        public List<QuoteLineItem> quoteLineItems { get; private set; }
        public ComponentData(Id recordId) {
            if (recordId.getSobjectType() == Case.getSObjectType()) {
                recordId = [SELECT Reclamation__c FROM Case WHERE Id = :recordId LIMIT 1].Reclamation__c;
            }
            opportunity = PricingSummaryService.queryOpportunity(recordId);
            try {
                quote = PricingSummaryService.queryQuote(opportunity.SyncedQuoteId);
            } catch (Exception e) {
                throw new PricingSummaryService.PricingDataException('The synced quote can\'t be found');
            }
            // Existing additional items
            quoteLineItems = [
                SELECT
                    Id,
                    Description,
                    QuoteId,
                    Product2Id,
                    Product2.Name,
                    Product2.ProductCode,
                    Product2.Cost_Type__c,
                    Product2.Product_Group__c,
                    Product2.Cost_Category__c,
                    Product2.Unit_Of_Measure__c,
                    Product2.QuantityUnitOfMeasure,
                    Quantity,
                    List_Price__c,
                    UnitPrice,
                    ListPrice,
                    Min_Sales_Price__c,
                    Min_Price__c,
                    Transmission__c,
                    Discount,
                    Discount__c,
                    fxDiscount__c,
                    CurrencyIsoCode,
                    fxFactory__c,
                    Factory_Price__c,
                    fxCost__c,
                    Product_Cost__c,
                    fxSales__c,
                    Sales_Margin__c,
                    SubTotal,
                    TotalPrice,
                    Product_Code__c,
                    Sales_Multiplier__c,
                    Configuration_Plan__c,
                    Configuration_Product__c,
                    Configuration_Option__c
                FROM QuoteLineItem
                WHERE QuoteId = :quote.Id AND Product2.Product_Group__c IN :SERVICES_PRODUCT_GROUPS
                ORDER BY Product2.Product_Group__c, Product2.Cost_Type__c
            ];

            List<AggregateResult> results = [
                SELECT Product2.Product_Group__c
                FROM QuoteLineItem
                WHERE QuoteId = :quote.Id AND Product2.Product_Group__c != NULL
                GROUP BY Product2.Product_Group__c
            ];
            List<String> productGroups =  SERVICES_PRODUCT_GROUPS;

            List<PricingSummaryService.PicklistOption> costTypeValues = new List<PricingSummaryService.PicklistOption>();
            for (AggregateResult result : [
                SELECT toLabel(Cost_Type__c) costTypeLabel, Cost_Type__c
                FROM Product2
                WHERE
                    IsActive = TRUE
                    AND Cost_Type__c != NULL
                    AND Id IN (
                        SELECT Product2Id
                        FROM PricebookEntry
                        WHERE IsActive = TRUE AND Pricebook2Id = :opportunity.Pricebook2Id
                    )
                    AND Product2.Product_Group__c IN :SERVICES_PRODUCT_GROUPS
                    AND Product2.Product_Category__c NOT IN ('Product Models','Product Groups')
                GROUP BY Cost_Type__c
            ]) {
                costTypeValues.add(
                    new PricingSummaryService.PicklistOption(
                        (String) result.get('Cost_Type__c'),
                        (String) result.get('costTypeLabel')
                    )
                );
            }
            picklistValues = new Map<String, List<PricingSummaryService.PicklistOption>>{
                'Cost_Type__c' => costTypeValues
            };
            List<String> costTypes = new List<String>();
            for (PricingSummaryService.PicklistOption costType : picklistValues.get('Cost_Type__c')) {
                costTypes.add(costType.value);
            }
            picklistDependencies = new Map<String, Map<String, List<PricingSummaryService.PicklistOption>>>{
                'Cost_Type__c' => getRelatedProducts(opportunity.Id, costTypes, productGroups)
            };
            disabled = !PricingSummaryService.ALLOWED_OPPORTUNITY_STAGES.contains(opportunity.StageName);
        }
    }

    @AuraEnabled
    public static Map<String, List<PricingSummaryService.PicklistOption>> getRelatedProducts(
        String opportunityId,
        List<String> costTypes,
        List<String> productGroups
    ) {
        Map<String, List<PricingSummaryService.PicklistOption>> options = new Map<String, List<PricingSummaryService.PicklistOption>>();
        if (costTypes.isEmpty()) {
            return options;
        }
        Opportunity opportunity = PricingSummaryService.queryOpportunity(opportunityId);
        for (PriceBookEntry pbEntry : [
            SELECT Product2Id, Product2.Id, Product2.Name, Product2.Cost_Type__c, Product2.Product_Group__c
            FROM PricebookEntry
            WHERE
                Pricebook2Id = :opportunity.Pricebook2Id
                AND IsActive = TRUE
                AND Product2.Cost_Type__c IN :costTypes
                AND Product2.Product_Group__c = :SERVICES_PRODUCT_GROUPS
                AND Product2.Product_Category__c NOT IN ('Product Models','Product Groups')
            ORDER BY Product2.Cost_Type__c, Product2.Name
        ]) {
            if (!options.containsKey(pbEntry.Product2.Cost_Type__c)) {
                options.put(pbEntry.Product2.Cost_Type__c, new List<PricingSummaryService.PicklistOption>());
            }
            options.get(pbEntry.Product2.Cost_Type__c)
                .add(new PricingSummaryService.PicklistOption(pbEntry.Product2Id, pbEntry.Product2.Name));
        }
        return options;
    }

    @AuraEnabled
    public static Product2 findProduct(String productId) {
        return PricingSummaryService.findProduct(productId);
    }

    @AuraEnabled
    public static QuoteLineItem findPrices(String opportunityId, String productId, Decimal quantity) {
        Product2 product = findProduct(productId);
        return PricingSummaryService.findPrices(
            opportunityId,
            product.ProductCode,
            quantity,
            product.Product_Group__c,
            product.Cost_Type__c
        );
    }

    @AuraEnabled(cacheable=false)
    public static ComponentData getComponentData(Id recordId) {
        return new ComponentData(recordId);
    }

    @AuraEnabled
    public static void deleteItem(Id opportunityId, Id quoteLineItemId) {
        if (
            !PricingSummaryService.ALLOWED_OPPORTUNITY_STAGES.contains(
                PricingSummaryService.queryOpportunity(opportunityId).StageName
            )
        ) {
            return;
        }
        delete new QuoteLineItem(Id = quoteLineItemId);
        PricingController.upsertQuoteLines(opportunityId);
    }

    @AuraEnabled
    public static QuoteLineItem updateItem(Id opportunityId, QuoteLineItem quoteLineItem) {
        QuoteLineItem item = findPrices(opportunityId, quoteLineItem.Product2Id, quoteLineItem.Quantity);
        item.Id = quoteLineItem.Id;
        update item;
        PricingController.upsertQuoteLines(opportunityId);
        return item;
    }

    @AuraEnabled
    public static QuoteLineItem saveItem(Id opportunityId, QuoteLineItem quoteLineItem) {
        if (
            !PricingSummaryService.ALLOWED_OPPORTUNITY_STAGES.contains(
                PricingSummaryService.queryOpportunity(opportunityId).StageName
            )
        ) {
            return null;
        }
        String productGroupCode = quoteLineItem.product2.Product_Group__c;
        Product2 servicesProduct = [
            SELECT Id
            FROM Product2
            WHERE ProductCode =  :productGroupCode 
            LIMIT 1
        ];
        List<Configuration__c> configurations = [
            SELECT Id
            FROM Configuration__c
            WHERE Opportunity__c = :opportunityId AND Plan_Type__c = 'Services'
        ];
        List<Configuration_Product__c> configurationProducts = [
            SELECT Id, RVN__c
            FROM Configuration_Product__c
            WHERE Product__c = :servicesProduct.Id AND Configuration__r.Opportunity__c = :opportunityId
        ];
        if (configurations.isEmpty()) {
            configurations.add(new Configuration__c(Opportunity__c = opportunityId, Plan_Type__c = 'Services'));
            insert configurations;
        }
        if (configurationProducts.isEmpty()) {
            configurationProducts.add(
                new Configuration_Product__c(
                    Configuration__c = configurations.get(0).Id,
                    Product__c = servicesProduct.Id,
                    Quantity__c = 1
                )
            );
            insert configurationProducts;
            configurationProducts = [
                SELECT Id, RVN__c
                FROM Configuration_Product__c
                WHERE Id IN :configurationProducts
            ];
        }

        List<Configuration_Option__c> configurationOptions = new List<Configuration_Option__c>();
        if (quoteLineItem.Configuration_Option__c != null) {
            configurationOptions = [
                SELECT Id
                FROM Configuration_Option__c
                WHERE Id = :quoteLineItem.Configuration_Option__c
            ];
        }
        if (configurationOptions.isEmpty()) {
            configurationOptions.add(
                new Configuration_Option__c(Configuration_Product__c = configurationProducts.get(0).Id)
            );
            insert configurationOptions;
        }
        QuoteLineItem oldItem = quoteLineItem.Id != null
            ? [SELECT Id, Product2Id FROM QuoteLineItem WHERE Id = :quoteLineItem.Id LIMIT 1]
            : null;
        if (oldItem != null && oldItem.Product2Id != quoteLineItem.Product2Id) {
            delete new QuoteLineItem(Id = quoteLineItem.Id);
            quoteLineItem.Id = null;
        }
        quoteLineItem.RVN_Number__c = configurationProducts.get(0).RVN__c;
        quoteLineItem.Configuration_Plan__c = configurations.get(0).Id;
        quoteLineItem.Configuration_Product__c = configurationProducts.get(0).Id;
        quoteLineItem.Configuration_Option__c = configurationOptions.get(0).Id;
        upsert quoteLineItem;
        PricingController.upsertQuoteLines(opportunityId);
        return quoteLineItem;
    }
}