force-app/main/default/objects/Case/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the Product within a Configuration Plan.</description>
    <label>Configuration Product DELETE</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows related opportunity</description>
    <inlineHelpText>Please associate case to an opportunity if known</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reclamation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Opportunity.Order_type__c</field>
            <operation>equals</operation>
            <value>Reclamation</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Territory2Id</field>
            <operation>equals</operation>
            <value>Reclamation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases (Reclamation)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product Entry in product2 Table</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Special Product</description>
    <inlineHelpText>indicates if the Product needs Special Handling</inlineHelpText>
    <label>Special OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Confirmed_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Delivery_Date__c</fullName>
    <description>Confirmed delivery date value from Production</description>
    <label>Confirmed Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Line__c.field-meta.xml
<CustomField>
    <fullName>Plan_Line__c</fullName>
    <description>Plan Line used in the configuration</description>
    <label>Plan Line OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RVN is marked as special which means that additional configuration items will be added to configuration</description>
    <label>Special</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>IF(Inspection_Code__c = 2, IMAGE(&apos;/img/msg_icons/error32.png&apos;,&apos;ERROR&apos;,20,20),  
 IF(!Measurements_Verified__c &amp;&amp; !Features_Confirmed__c, IMAGE(&apos;/img/msg_icons/warning32.png&apos;,&apos;WARN&apos;,20,20), 
  IF(!Measurements_Verified__c || !Features_Confirmed__c, IMAGE(&apos;/img/msg_icons/info32.png&apos;,&apos;WARN&apos;,20,20), 
   IMAGE(&apos;/img/msg_icons/confirm32.png&apos;,&apos;WARN&apos;,20,20)
  )
 )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Delivery_Date__c</fullName>
    <inlineHelpText>This date is received from ERP.</inlineHelpText>
    <label>Confirmed Delivery Date DEL</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <description>To plan for installation, a Confirmed installation date &amp; time will show in this field. 
This data is captured from the Installation Capacity component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Confirmed installation date and time.</inlineHelpText>
    <label>Confirmed installation time DEL</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preliminary_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_installation_time__c</fullName>
    <description>To plan for installation, a preliminary installation date &amp; time will show in this field. 
This data is captured from the Installation Scheduling component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Preliminary installation date and time.</inlineHelpText>
    <label>Preliminary installation time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <label>Confirmed installation time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Special Product</description>
    <inlineHelpText>indicates if the Product needs Special Handling</inlineHelpText>
    <label>Special OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery Date</description>
    <inlineHelpText>Delivery Date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OfferContentController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 06-19-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class OfferContentController {
    public class ComponentData {
        @AuraEnabled
        public List<Configuration_Product__c> configurationProducts { get; set; }
        @AuraEnabled
        public String opportunityId { get; set; }
        @AuraEnabled
        public String orderType { get; set; }
        
        public ComponentData(Id recordId) {
            Opportunity opportunity = new Opportunity();
            if (recordId.getSobjectType() == Case.getSObjectType()) {
                opportunity = caseOpportunityId(recordId);
            } else if (recordId.getSobjectType() == Opportunity.getSObjectType()) {
                opportunity = queryOpportunity(recordId);
            }
            opportunityId = opportunity.Id;
            orderType = opportunity.Order_type__c;
            configurationProducts = queryConfigurationProducts(opportunityId);

            // Filter out duplicate extra sales conf. products
            List<Configuration_Product__c> filteredConfigurationProducts = new List<Configuration_Product__c>();
            Boolean extraSalesAdded = false;
            for (Configuration_Product__c configurationProduct : configurationProducts) {
                Boolean isExtraSales = configurationProduct.Configuration__r.Plan_Type__c == 'Extra Sales';
                if (!isExtraSales || isExtraSales && !extraSalesAdded) {
                    filteredConfigurationProducts.add(configurationProduct);
                }
                if (isExtraSales) {
                    extraSalesAdded = true;
                }
            }
            configurationProducts = filteredConfigurationProducts;
        }
    }

    @AuraEnabled
    public static Opportunity caseOpportunityId(Id recordId) {
        Case caseRecord = [
            SELECT Type, Reclamation__c, Reclamation__r.Order_Type__c, Opportunity__c, Opportunity__r.Order_Type__c
            FROM Case
            WHERE Id = :recordId
            LIMIT 1
        ];
        if (new Set<String> { 'Warranty work request', 'Reclamation order','Customer Reclamation' }.contains(caseRecord.Type)) {
            return caseRecord.Reclamation__r;
        }
        return caseRecord.Opportunity__r;
        //  AND Order_type__c = 'Reclamation'
    }

    // Method to fetch Order type value if the source object is Opportunity
    @AuraEnabled
    public static Opportunity queryOpportunity(Id recordId) {
        return [SELECT Id, Order_type__c FROM Opportunity WHERE Id = :recordId LIMIT 1];
    }

    private static List<Configuration_Product__c> queryConfigurationProducts(String opportunityId) {
        return [
            SELECT
                Product__r.Name,
                Product__r.Id,
                Configuration__r.Plan_Type__c,
                Configuration__r.Plan_Name__c,
                Configuration__r.Plan_Line__c,
                Configuration__r.Plan_Apartment__c,
                Configuration__r.Plan_Floor__c,
                Verification__c,
                Configuration__c,
                Special__c,
                //Configuration__r.Opportunity__r.Delivery_Date__c,
                //Configuration__r.Opportunity__r.Confirmed_Delivery_Date__c,
                //Configuration__r.Opportunity__r.Preliminary_installation_time__c,
                //Configuration__r.Opportunity__r.Confirmed_installation_time__c,
                Configuration__r.Opportunity__r.StageName,
                Configuration__r.Quote__r.Status,
                Configuration__r.Visual_Id__c,
                RVN_Number__c,
                RVN__c,
                LastModifiedDate,
                Quantity__c,
                Features_Confirmed__c,
                Measurements_Verified__c,
                Inspection_Code__c
            FROM Configuration_Product__c
            WHERE Configuration__r.Opportunity__c = :opportunityId
            LIMIT 1000
        ];
    }

    @AuraEnabled(cacheable=true) //<-- DML operations not allowed!
    public static ComponentData getComponentData(String recordId) {
        return new ComponentData(recordId);
    }
    @AuraEnabled
    public static void removeManuallyAddedSpecialItems(List<Id> configurationProductIds, String opportunityId) {
        // if (configurationProductIds.isEmpty()) {
        //     return;
        // }
        // List<Configuration_Product__c> configurationProductsToUpdate = new List<Configuration_Product__c>();
        // Set<Id> visualAddedSpecialProducts = SpecialProductsService.isVisualAddedSpecialProduct(configurationProductIds);
        // for (Id configurationProductId : configurationProductIds) {
        //     if (visualAddedSpecialProducts.contains(configurationProductId)) {
        //         throw new AuraHandledException('Unable to remove special special products that are added from Visual');
        //     }
        // }

        // delete [
        //         SELECT Id
        //         FROM Configuration_Option__c
        //         WHERE Configuration_Product__c IN :configurationProductIds AND
        //         Product__r.Additional_special_product__c = true
        //         LIMIT 2000
        // ];
        // Map<String, Id> productGroupToConfigurationProductId = populateProductGroupToConfigurationProductIdMap(configurationProductIds);
        // for (String productGroup : productGroupToConfigurationProductId.keySet()) {
        //     configurationProductsToUpdate.add(
        //             new Configuration_Product__c(Id = productGroupToConfigurationProductId.get(productGroup),
        //                     Special__c = false));
        // }
        // update configurationProductsToUpdate;
        // PricingController.upsertQuoteLines(opportunityId);

    }

    // private static Map<String, Id> populateProductGroupToConfigurationProductIdMap(List<Id> configurationProductIds){
    //     Map<String, Id> productGroupToConfigurationProductId = new Map<String, Id>();
    //     for (Configuration_Product__c configurationProduct : [
    //             SELECT Id, Product_Group__c
    //             FROM Configuration_Product__c
    //             WHERE Id IN :configurationProductIds
    //             LIMIT 2000
    //     ]) {
    //         productGroupToConfigurationProductId.put(configurationProduct.Product_Group__c, configurationProduct.Id);
    //     }
    //     return productGroupToConfigurationProductId;
    // }

    @AuraEnabled
    public static void addManuallySpecialItems(List<Id> configurationProductIds, String opportunityId) {
        // if (configurationProductIds.isEmpty()) {
        //     return;
        // }
        // List<Configuration_Option__c> configurationOptionsToInsert = new List<Configuration_Option__c>();
        // List<Configuration_Product__c> configurationProductsToUpdate = new List<Configuration_Product__c>();
        // Map<String, Integer> configurationProductToMaxLineNumber = getMaxLineNumberConfigurationOptions(new Set<Id>(configurationProductIds));
        // Map<String, Id> productGroupToConfigurationProductId = populateProductGroupToConfigurationProductIdMap(configurationProductIds);
        // if (!productGroupToConfigurationProductId.isEmpty()) {
        //     for (Product2 product : SpecialProductsService.getAdditionalSpecialProducts(productGroupToConfigurationProductId.keySet())) {
        //         configurationOptionsToInsert.add(SpecialProductsService.createConfigurationOption(product,
        //                 productGroupToConfigurationProductId, configurationProductToMaxLineNumber.get(product.Product_Group__c)));
        //     }
        //     for (String productGroup : productGroupToConfigurationProductId.keySet()) {
        //         configurationProductsToUpdate.add(
        //                 new Configuration_Product__c(Id = productGroupToConfigurationProductId.get(productGroup),
        //                         Special__c = true));
        //     }
        // }

        // insert configurationOptionsToInsert;
        // update configurationProductsToUpdate;
        // PricingController.upsertQuoteLines(opportunityId);
    }

    // private static Map<String, Integer> getMaxLineNumberConfigurationOptions(Set<Id> configurationProductIds) {
    //     Map<String, Integer> productGroupToMaxLineNumber = new Map<String, Integer>();
    //     List<AggregateResult> aggregateResults = [
    //             SELECT Product_Group__c, MAX(Line_Number__c)
    //             FROM Configuration_Option__c
    //             WHERE Configuration_Product__c IN :configurationProductIds
    //             GROUP BY Product_Group__c
    //     ];
    //     for (AggregateResult aggregateResult : aggregateResults) {
    //         productGroupToMaxLineNumber.put((String)aggregateResult.get('Product_Group__c'),
    //                 Integer.valueOf((Decimal) aggregateResult.get('expr0')));
    //     }
    //     return productGroupToMaxLineNumber;
    // }

    @AuraEnabled
    public static void deleteConfigurationProducts(List<Id> configurationProductIds) {
        if (configurationProductIds.isEmpty()) {
            return;
        }

        List<Configuration_Product__c> configurationProducts = [
            SELECT
                Id,
                Configuration__c,
                Configuration__r.Opportunity__r.Owner.UserRole.Id,
                Configuration__r.Opportunity__r.StageName
            FROM Configuration_Product__c
            WHERE Id IN :configurationProductIds
            LIMIT 2000
        ];

        Role_Settings__c roleSettings = RoleSettingsController.getRoleSettingsMap().get(UserInfo.getProfileId());
        Boolean manager = roleSettings.isManager__c;
        Boolean salesUser = roleSettings.isSales__c;
        Boolean serviceUser = roleSettings.isService__c;

        // Admin/Support is always allowed to delete (no matter what stage)
        if (!roleSettings.isAdmin__c && !roleSettings.isSupport__c) {
            for (Configuration_Product__c configurationProduct : configurationProducts) {
                if (configurationProduct.Configuration__r.Opportunity__r.StageName != 'Quoting') {
                    throw new DeleteNotAllowedException('Delete is not allowed');
                }
            }
            // TODO
            // if(!salesUser && !serviceUser) {
            //     throw new DeleteNotAllowedException('User does not have rights to delete');
            // }

            // User with roles above current user's role have also rights to delete
            Map<Id, UserRole> userRoles = new Map<Id, UserRole>([SELECT Id, ParentRoleId, Name FROM UserRole]);
            Map<Id, Set<Id>> roleParentRoles = new Map<Id, Set<Id>>();
            for (UserRole userRole : userRoles.values()) {
                if (!roleParentRoles.containsKey(userRole.Id)) {
                    roleParentRoles.put(userRole.Id, new Set<Id>());
                }
            }
            for (UserRole userRole : userRoles.values()) {
                UserRole parent = userRoles.get(userRole.ParentRoleId);
                while (parent != null) {
                    roleParentRoles.get(userRole.Id).add(parent.Id);
                    parent = userRoles.get(parent.ParentRoleId);
                }
            }

            Id currentUserRoleId = UserInfo.getUserRoleId();
            Set<Id> managersUsers = new Set<Id>();
            for (Configuration_Product__c configurationProduct : configurationProducts) {
                Id opportunityOwnerRoleId = configurationProduct.Configuration__r.Opportunity__r.Owner.UserRole.Id;
                // Not the owner and the current user is below the owner in the role hierarchy
                System.debug(JSON.serializePretty(roleParentRoles));
                if (
                    opportunityOwnerRoleId != currentUserRoleId &&
                    !roleParentRoles.get(opportunityOwnerRoleId).contains(currentUserRoleId)
                ) {
                    throw new DeleteNotAllowedException('Delete is not allowed');
                }
            }
        }

        List<Configuration__c> configurationPlans = new List<Configuration__c>();
        Set<Id> configurationPlanIds = new Set<Id>();
        for (Configuration_Product__c configurationProduct : configurationProducts) {
            Id configurationPlanId = configurationProduct.Configuration__c;
            if (configurationPlanId != null && !configurationPlanIds.contains(configurationPlanId)) {
                configurationPlanIds.add(configurationPlanId);
                configurationPlans.add(new Configuration__c(Id = configurationPlanId));
            }
        }
        if (!configurationPlanIds.isEmpty()) {
            List<QuoteLineItem> quoteLineItems = [
                SELECT Id
                FROM QuoteLineItem
                WHERE Configuration_Plan__c IN :configurationPlanIds
                LIMIT 1000
            ];
            if (roleSettings.isAdmin__c || roleSettings.isSupport__c) {
                new WithoutSharing().deleteRecords(quoteLineItems, configurationPlans);
            } else {
                delete quoteLineItems;
                delete configurationPlans;
            }
        }
    }

    private without sharing class WithoutSharing {
        private void deleteRecords(List<QuoteLineItem> quoteLineItems, List<Configuration__c> configurationPlans) {
            delete quoteLineItems;
            delete configurationPlans;
        }
    }

    public class DeleteNotAllowedException extends Exception {
    }
}