force-app/main/default/objects/Case/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the Product within a Configuration Plan.</description>
    <label>Configuration Product DELETE</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows related opportunity</description>
    <inlineHelpText>Please associate case to an opportunity if known</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Confirmed_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Delivery_Date__c</fullName>
    <description>Confirmed delivery date value from Production</description>
    <label>Confirmed Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Features_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Features_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce representation of hasFeaturesBeenConfirmed</description>
    <label>Features Confirmed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Inspection_Code__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Code__c</fullName>
    <description>Salesforce equivalent of productInspectCode</description>
    <label>Inspection Code OLD</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Measurements_Verified__c.field-meta.xml
<CustomField>
    <fullName>Measurements_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce equivalent of hasMeasurementsBeenVerified</description>
    <label>Measurements Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Line__c.field-meta.xml
<CustomField>
    <fullName>Plan_Line__c</fullName>
    <description>Plan Line used in the configuration</description>
    <label>Plan Line OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>IF(Inspection_Code__c = 2, IMAGE(&apos;/img/msg_icons/error32.png&apos;,&apos;ERROR&apos;,20,20),  
 IF(!Measurements_Verified__c &amp;&amp; !Features_Confirmed__c, IMAGE(&apos;/img/msg_icons/warning32.png&apos;,&apos;WARN&apos;,20,20), 
  IF(!Measurements_Verified__c || !Features_Confirmed__c, IMAGE(&apos;/img/msg_icons/info32.png&apos;,&apos;WARN&apos;,20,20), 
   IMAGE(&apos;/img/msg_icons/confirm32.png&apos;,&apos;WARN&apos;,20,20)
  )
 )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case OLD</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Delivery_Date__c</fullName>
    <inlineHelpText>This date is received from ERP.</inlineHelpText>
    <label>Confirmed Delivery Date DEL</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <description>To plan for installation, a Confirmed installation date &amp; time will show in this field. 
This data is captured from the Installation Capacity component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Confirmed installation date and time.</inlineHelpText>
    <label>Confirmed installation time DEL</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preliminary_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_installation_time__c</fullName>
    <description>To plan for installation, a preliminary installation date &amp; time will show in this field. 
This data is captured from the Installation Scheduling component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Preliminary installation date and time.</inlineHelpText>
    <label>Preliminary installation time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Delivery Date</description>
    <inlineHelpText>Delivery Date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OppOverviewProductsCtrl.cls
/**
 * Created by Filip on 17. 2. 2023.
 * Updated by Sai on 07.06.2023
 */

public with sharing class OppOverviewProductsCtrl {
	public class OverviewProductsData{
		@AuraEnabled public List<ProductDataColumn> productColumns;
		@AuraEnabled public List<ProductDataRow> productRows;
		@AuraEnabled public String orderType;
	}
	public class ProductDataColumn{
		public String label;
		public String apiName;
		public String sortDirection;
		public String cssClass;
		public ProductDataColumn(String label, String apiName, String sortDirection, String cssClass){
			this.label = label;
			this.apiName = apiName;
			this.sortDirection = sortDirection;
			this.cssClass = cssClass;
		}
	}
	public class ProductDataRow{
		public String rowId;
		public String productId;
		public String configurationId;
		public List<ProductField> fields;
		/*public ProductDataRow(String rowId, String productId, List<ProductField> fields){
			this.rowId = rowId;
			this.productId = productId;
			this.fields = fields;
		}*/
	}
	public class ProductField{
		public String label;
		public String apiName;
		public String type;
		public Boolean isEditable;
		public Boolean isVisible;
		public Object value;
		public String id;
		public List<PickList> pickListOptions = new List<PickList>();
	}
	public class PickList{
		public String label;
		public String value;
		public PickList(String label, String value){
			this.label = label;
			this.value = value;
		}
	}
	public static Map<String, String> apiNamesLabelsProduct = createFieldApiLabelTypeMap('Product2', true);
	public static Map<String, String> apiNamesTypesProduct = createFieldApiLabelTypeMap('Product2', false);

	public static Map<String, String> apiNamesLabelsQuote = createFieldApiLabelTypeMap('Quote', true);
	public static Map<String, String> apiNamesTypesQuote = createFieldApiLabelTypeMap('Quote', false);

	public static Map<String, String> apiNamesLabelsConProduct = createFieldApiLabelTypeMap('Configuration_Product__c', true);
	public static Map<String, String> apiNamesTypesConProduct = createFieldApiLabelTypeMap('Configuration_Product__c', false);

	public static Map<String, String> apiNamesLabelsOppo = createFieldApiLabelTypeMap('Opportunity', true);
	public static Map<String, String> apiNamesTypesOppo = createFieldApiLabelTypeMap('Opportunity', false);

	public static Map<String, String> apiNamesLabelsConfiguration = createFieldApiLabelTypeMap('Configuration__c', true);
	public static Map<String, String> apiNamesTypesConfiguration = createFieldApiLabelTypeMap('Configuration__c', false);

	public static final List<String> VISIBLE_FIELDS = new List<String>{
		'RVN_Number__c',
		'Product__r.Name',
		'Configuration__r.Plan_Name__c',
		'Configuration__r.Plan_Line__c',
		'Configuration__r.Plan_Floor__c',
		'Configuration__r.Plan_Apartment__c',
		'Verification__c'
		//'Configuration__r.Quote__r.Status'


		//'Configuration__r.Opportunity__r.Delivery_Date__c',
		//'Configuration__r.Opportunity__r.Confirmed_Delivery_Date__c',
		//'Configuration__r.Opportunity__r.Preliminary_installation_time__c',
		//'Configuration__r.Opportunity__r.Confirmed_installation_time__c',
		/*'Configuration__r.Opportunity__r.StageName',
		'Configuration__r.Visual_Id__c',

		'LastModifiedDate',
		'Quantity__c',
		'Features_Confirmed__c',
		'Measurements_Verified__c',
		'Inspection_Code__c'*/
	};
	public static final List<String> EDITABLE_FIELDS = new List<String>{
		'Configuration__r.Plan_Name__c',
		'Configuration__r.Plan_Line__c',
		'Configuration__r.Plan_Apartment__c',
		'Configuration__r.Plan_Floor__c'
		//'Configuration__r.Opportunity__r.Delivery_Date__c',
		//'Configuration__r.Opportunity__r.Confirmed_Delivery_Date__c',
		//'Configuration__r.Opportunity__r.Preliminary_installation_time__c',
		//'Configuration__r.Opportunity__r.Confirmed_installation_time__c',
		/*'RVN_Number__c',
		'Quantity__c',
		'Features_Confirmed__c',
		'Measurements_Verified__c',
		'Inspection_Code__c'*/
	};
	public static final List<String> CONFIG_PRODUCT_API_NAMES = new List<String>{
			'RVN_Number__c',
			'Product__r.Name',
			'Configuration__r.Plan_Name__c',
			'Configuration__r.Plan_Line__c',
			'Configuration__r.Plan_Floor__c',
			'Configuration__r.Plan_Apartment__c',
			'Verification__c'
			//'Configuration__r.Quote__r.Status'
	};

	@AuraEnabled
	public static Opportunity caseOpportunityId(Id recordId) {
		//return [SELECT Opportunity__c,Opportunity__r.Order_Type__c FROM Case WHERE Id = :recordId LIMIT 1];
		return [SELECT Id,Order_type__c FROM Opportunity WHERE Case__c = :recordId and Order_type__c = 'Reclamation' LIMIT 1];
	}

	@AuraEnabled
	public static Opportunity queryOpportunity(Id recordId) {
		//return [SELECT Opportunity__c,Opportunity__r.Order_Type__c FROM Case WHERE Id = :recordId LIMIT 1];
		return [SELECT Id,Order_type__c FROM Opportunity WHERE Id = :recordId  LIMIT 1];
	}

	@AuraEnabled
	public static String fetchOverviewProducts(Id recordId) {
        System.debug('*** recordId ***'+recordId);
		Opportunity opp = new Opportunity();
		Id opportunityId;
		String orderType = '';
		if(recordId.getSobjectType() == Case.getSObjectType()) {
			/*Case cas = caseOpportunityId(recordId);
			opportunityId = cas.Opportunity__c;
			orderType = cas.Opportunity__r.Order_Type__c;*/

			opp = caseOpportunityId(recordId);
			System.debug('*** opp value ***'+opp.Id);
			opportunityId = opp.Id;
			orderType = opp.Order_type__c;
		}else if(recordId.getSobjectType() == Opportunity.getSObjectType()){
			opp = queryOpportunity(recordId);
			opportunityId = opp.Id;
			orderType = opp.Order_type__c;
		}
		OverviewProductsData opData = new OverviewProductsData();
		List<ProductDataRow> pDataRows = new List<ProductDataRow>();
		List<ProductDataColumn> pDataColumns = new List<ProductDataColumn>();
		Set<String> columnsAddedSet = new Set<String>();
		List<Configuration_Product__c> configurationProducts = queryConfigurationProducts(opportunityId);
		Map<String, String> apiNameValueMap = new Map<String, String>();
		if(!configurationProducts.isEmpty()){
			/*// TODO check other posibilities on how to get id as url for clickable fields
			for(Configuration_Product__c cProduct : configurationProducts){
				for(String apiName : CONFIG_PRODUCT_API_NAMES) {
					String cpValue = extractObjectValue(cProduct, apiName);
					apiNameValueMap.put(apiName, cpValue);
				}
			}*/
			for(Configuration_Product__c cProduct : configurationProducts){
				List<ProductField> productFields = new List<ProductField>();
				//productFields.add(createCheckBoxField());
				System.debug('*** cProduct.Configuration__c ***'+cProduct.Configuration__c);
				productFields.add(createQuickActionField(cProduct.Configuration__c));
				pDataColumns.add(new ProductDataColumn('', 'EditPlanAction', 'DESC', 'table-header'));
				System.debug('*** Added Quick Action Field ***');
				for(String apiName : CONFIG_PRODUCT_API_NAMES){
					String whatObject = checkWhichObject(apiName);
					String apiFlattened = flattenApiName(apiName);
					ProductField pField = new ProductField();
					pField.apiName = apiName;
					pField.id = apiName == 'Product__r.Name' ? String.valueof(cProduct.Product__r.Id) : generateId(cProduct.Product__r.Id);
					pField.type = getLabelOrType(whatObject, apiFlattened, true);
					pField.label = getLabelOrType(whatObject, apiFlattened, false);
					pField.value = extractObjectValue(cProduct, apiName);
					System.debug('*** pField.value ***'+pField.value);
					/*if(pField.type == 'DATE'){
						Date d = date.parse(pField.value);
						pField.value = String.valueOf(d);
					}
					if(pField.type == 'DATETIME'){
						Datetime d = datetime.parse(pField.value);
						pField.value = String.valueOf(d);
					}*/
					pField.isEditable = false;// EDITABLE_FIELDS.contains(pField.apiName);
					pField.isVisible = VISIBLE_FIELDS.contains(pField.apiName);
					if(pField.label != '' && !columnsAddedSet.contains(pField.apiName)  && VISIBLE_FIELDS.contains(pField.apiName)){
						columnsAddedSet.add(pField.apiName);
						pDataColumns.add(new ProductDataColumn(pField.label, pField.apiName, 'DESC', 'table-header'));
					}
					productFields.add(pField);
				}
				//TODO Check if Schema ok in for loops
				for(ProductField pF : productFields){
					if(pF.type.toUpperCase() == 'PICKLIST'){
						String fieldApi = flattenApiName(pF.apiName);
						String objectApiName = checkWhichObject(pF.apiName);
						SObjectType objType = Schema.getGlobalDescribe().get(objectApiName);
						Map<String, Schema.SObjectField> objectFieldsMap = objType.getDescribe().fields.getMap();
						Schema.SObjectField sObjField = objectFieldsMap.get(fieldApi);
						pF.pickListOptions = getPickListValuesIntoList(sObjField);
					}
				}
				ProductDataRow pDataRow = new ProductDataRow();
				pDataRow.rowId = generateId(cProduct.Product__r.Id);
				pDataRow.productId = cProduct.Product__r.Id;
				pDataRow.configurationId = cProduct.Configuration__c;
				pDataRow.fields = productFields;
				pDataRows.add(pDataRow);
			}
			opData.productColumns = pDataColumns;
			opData.productRows = pDataRows;
			opData.orderType = orderType;
		}
		return JSON.serialize(opData);
	}
	/*private static Set<String> extractAllPicklistFields(String objectApiName, List<String> fieldsApiNames){
		Set<String> picklists = new Set<String>();
		SObjectType accountType = Schema.getGlobalDescribe().get(objectApiName);
		Map<String,Schema.SObjectField> objectFieldsMap = accountType.getDescribe().fields.getMap();
		for(String fieldApiName : fieldsApiNames){
			fieldApiName = fieldApiName.replace('*','');
			if(objectFieldsMap.containsKey(fieldApiName)){
				if(String.valueOf(objectFieldsMap.get(fieldApiName).getDescribe().getType()).toUpperCase()=='PICKLIST'){
					picklists.add(fieldApiName);
				}
			}
		}
		return picklists;
	}*/
	private static List<PickList> getPickListValuesIntoList(Schema.SObjectField sObjField){
		List<PickList> picklistValues = new List<PickList>();
		List<Schema.PicklistEntry> values = sObjField.getDescribe().getPickListValues();
		for (Schema.PicklistEntry pe : values){
			PickList pl = new PickList(pe.getLabel(), pe.getValue());
			picklistValues.add(pl);
		}
		return picklistValues;
	}
	private static ProductField createCheckBoxField(){
		ProductField productF = new ProductField();
		productF.label = '';
		productF.apiName = 'RowCheckBox';
		productF.type = 'Boolean';
		productF.isVisible = true;
		return productF;
	}
	// Setup Edit Plan Quick Action Field
	private static ProductField createQuickActionField(String configPlanId){
		System.debug('*** Creating Quick Action Field for Plan '+configPlanId+' ***');
		ProductField productF = new ProductField();
		productF.label = '';
		productF.apiName = 'EditPlanAction';
		System.debug('*** Creating Quick Action Field Name '+productF.apiName+' ***');
		productF.value = configPlanId;
		System.debug('*** Creating Quick Action Field Value '+productF.value+' ***');
		productF.type = 'QuickAction';
		System.debug('*** Creating Quick Action Field Type '+productF.type+' ***');
		productF.isVisible = true;
		System.debug('*** Creating Quick Action Field isVisible '+productF.isVisible+' ***');
		System.debug('*** Created Quick Action Field ***');
		return productF;
	}
	private static String checkWhichObject(String productFieldsApi){
		if(productFieldsApi.contains('Product__r')){
			return 'Product2';
		}
		if(productFieldsApi.contains('Configuration__r.Opportunity__r')){
			return 'Opportunity';
		}
		if(productFieldsApi.contains('Configuration__r.Quote__r')){
			return 'Quote';
		}
		if(productFieldsApi.contains('Configuration__r')){
			return 'Configuration__c';
		}
		return 'Configuration_Product__c';
	}

	private static Map<String, String> createFieldApiLabelTypeMap(String obj, Boolean isLabelMap){
		Map<String, String> fieldsApiLabelTypeMap = new Map<String, String>();
		Map<String, Schema.SObjectType> describeResult = Schema.getGlobalDescribe();
		for(Schema.SObjectField f : describeResult.get(obj).getDescribe().fields.getMap().values()){
			String labelOrType = isLabelMap ? f.getDescribe().getLabel() : String.valueOf(f.getDescribe().getType());
			fieldsApiLabelTypeMap.put(f.getDescribe().getName(), labelOrType);
		}
		return fieldsApiLabelTypeMap;
	}
	private static String getLabelOrType(String obj, String apiName, Boolean mustCheckType){
		if(apiName == 'Verification__c' && mustCheckType){
			return 'ICON';
		}
		// TODO redo to custom metadata
		if(apiName == 'Name' && mustCheckType){
			return 'URL';
		}
		switch on obj {
			when 'Product2' {
				return mustCheckType ? apiNamesTypesProduct.get(apiName) : apiNamesLabelsProduct.get(apiName);
			}
			when 'Quote' {
				return mustCheckType ? apiNamesTypesQuote.get(apiName) : apiNamesLabelsQuote.get(apiName);
			}
			when 'Opportunity' {
				return mustCheckType ? apiNamesTypesOppo.get(apiName) : apiNamesLabelsOppo.get(apiName);
			}
			when 'Configuration__c' {
				return mustCheckType ? apiNamesTypesConfiguration.get(apiName) : apiNamesLabelsConfiguration.get(apiName);
			}
			when else {
				return mustCheckType ? apiNamesTypesConProduct.get(apiName) : apiNamesLabelsConProduct.get(apiName);
			}
		}
	}
	private static String flattenApiName(String productFieldsApi){
		if(productFieldsApi.contains('Product__r') ||
			productFieldsApi.contains('Configuration__r.Opportunity__r') ||
			productFieldsApi.contains('Configuration__r') ||
			productFieldsApi.contains('Configuration__r.Quote__r')) {
			return productFieldsApi.substringAfterLast('.');
		}
		return productFieldsApi;
	}

	private static Object extractObjectValue(SObject o, String fieldApiName){
		if(fieldApiName == 'Verification__c'){
			return getVerificationIcon(String.valueOf(o.get(fieldApiName)));
		}

		SObject sObj = o;
		if(fieldApiName.contains('.')){ // reference field
			List<String> reference = fieldApiName.split('\\.');
			for (Integer i = 0; i < reference.size() - 1; i++) {
				if( sObj != null ) {
					sObj = sObj?.getSObject(reference[i]);
				}
			}
			return sObj?.get(reference[reference.size()-1]);//String.valueOf(sObj?.get(reference[reference.size()-1]));
		}else{
			return o.get(fieldApiName); // String.valueOf(o.get(fieldApiName));
		}
	}
	private static List<Configuration_Product__c> queryConfigurationProducts(String oppId){
		return [
				SELECT
					Product__r.Name,
					Product__r.Id,
					Configuration__r.Plan_Name__c,
					Configuration__r.Plan_Line__c,
					Configuration__r.Plan_Apartment__c,
					Configuration__r.Plan_Floor__c,
					Verification__c,
					Configuration__c,
					//Configuration__r.Opportunity__r.Delivery_Date__c,
					//Configuration__r.Opportunity__r.Confirmed_Delivery_Date__c,
					//Configuration__r.Opportunity__r.Preliminary_installation_time__c,
					//Configuration__r.Opportunity__r.Confirmed_installation_time__c,
					Configuration__r.Opportunity__r.StageName,
					Configuration__r.Quote__r.Status,
					Configuration__r.Visual_Id__c,
					RVN_Number__c,
					LastModifiedDate,

					Quantity__c,
					Features_Confirmed__c,
					Measurements_Verified__c,
					Inspection_Code__c
				FROM Configuration_Product__c
				WHERE  Configuration__r.Opportunity__c = :oppId
				LIMIT 1000
		];
	}
	public static String generateId(String productId) {
		String random1 = productId + String.valueOf(Math.random());
		String random2 = String.valueOf(Math.random()) + productId;
		return (random1.substring(2, 20) + random2.substring(7, 20)).replaceAll(' ', '');
	}
	private static String getLabelFromFieldsApi(String fieldsApi){
		Map<String,Schema.SObjectField> cProductFields = Schema.Configuration_Product__c.SObjectType.getDescribe().fields.getMap();
		Schema.DescribeFieldResult fieldResult = cProductFields.get(fieldsApi).getDescribe();
		return String.valueOf(fieldResult.getLabel());
	}
	private static Object getVerificationIcon(String verification){
		if(verification.contains('error')){
			return 'utility:close';
		}
		if(verification.contains('confirm')){
			return 'utility:check';
		}
		if(verification.contains('info')){
			return 'utilty:warning';
		}
		return null;
	}

	public static String STATUS_SUCCESS = 'success';
	public static String STATUS_ERROR = 'error';
	public class ApexResult {
		@AuraEnabled
		public Object result;
		@AuraEnabled
		public String status;
		@AuraEnabled
		public String errorMessage;

		public ApexResult() {
			this(null, STATUS_SUCCESS, null);
		}
		public ApexResult(Exception e) {
			this(null, STATUS_ERROR, e.getTypeName() == 'System.DmlException' ? e.getDmlMessage(0) : e.getMessage());
		}

		public ApexResult(Object result, String status, String errorMessage) {
			this.result = result;
			this.status = status;
			this.errorMessage = errorMessage;
		}
	}


	@AuraEnabled public static ApexResult updateConfigurations(List<Configuration__c> configurations){
		ApexResult response = new ApexResult();
		try {
			update configurations;
		}catch (Exception e){
			return new ApexResult(e);
		}
		return response;
	}
	/*private static String modifyApiName(String apiName){
	String modifiedApi = '';
	if(apiName.contains('Product__r') || apiName.contains('Configuration__r')){
		modifiedApi = apiName.replace('Product__r', '__c');
	}
	if(apiName.contains('Configuration__r.Opportunity__r')){

	}
	return modifiedApi;
}*/
/*	private static ProductField createProductField(String apiName, Configuration_Product__c cProduct){
		ProductField pField = new ProductField();
		//String apiModified = modifyApiName(apiName);
		pField.value = extractObjectValue(cProduct, apiName);
	}*/
}