force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows related opportunity</description>
    <inlineHelpText>Please associate case to an opportunity if known</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup-field for order related to the case.</description>
    <label>Order DELETE</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_type__c.field-meta.xml
<CustomField>
    <fullName>Contract_type__c</fullName>
    <description>this defines contract type</description>
    <inlineHelpText>please mark contract type</inlineHelpText>
    <label>Contract type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preliminary Contract</fullName>
            </value>
            <value>
                <fullName>Final Contract</fullName>
                <default>true</default>
                <label>Final Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <formula>TEXT(Opportunity__r.Order_type__c)</formula>
    <label>Order type OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to bring quote data to contract - Integration purpose</description>
    <label>Quote OLD</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Signing_status__c.field-meta.xml
<CustomField>
    <fullName>Signing_status__c</fullName>
    <label>Signing status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case OLD</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preliminary_Contract_Needed__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_Contract_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is checked if preliminary contract is needed</description>
    <inlineHelpText>Please indicate if for any reason preliminary contract is needed</inlineHelpText>
    <label>Preliminary Contract Needed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Signing_Status__c.field-meta.xml
<CustomField>
    <fullName>Signing_Status__c</fullName>
    <formula>TEXT(Contract.Signing_status__c)</formula>
    <label>Signing Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReclamationController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-11-2023
 * @last modified by  : Henk Reynders
**/
public class ReclamationController {	
    public static String prepareOrder(Id recordId){
        String errorMessage;
        String objectName = DynamicObjectUtils.getObjectType(recordId);
        String queryCondition;
        Opportunity reclamation = new Opportunity();
        if(objectName == 'Opportunity' || objectName == 'Case'){
            reclamation = [SELECT Id,Case__c,AccountId,Account.BillingCity,Account.BillingCountry,
                                 Account.BillingCountryCode,Account.BillingPostalCode, Account.BillingState,
                                 Account.BillingStateCode,Account.BillingStreet,SyncedQuoteId,Order__c,
                                 ContractId,Preliminary_Contract_Needed__c,Order_type__c,Pricebook2Id,Name
                                 FROM Opportunity 
                                 WHERE Id = :recordId 
                                 OR Case__c =: recordId
                                 LIMIT 1];
        }
        if(String.IsNotBlank(reclamation.Id)){
            Id reclamationId = reclamation.Id;
            Id accountId = reclamation.AccountId;
            Id quoteId = reclamation.SyncedQuoteId;
            Id contractId = reclamation.ContractId;
            Id pricebookId = reclamation.Pricebook2Id;
            Id caseId = reclamation.Case__c;
            String reclamationName = reclamation.Name;
            String billingCity = reclamation.Account.BillingCity;
            String billingCountry = reclamation.Account.BillingCountry;
            String billingCountryCode = reclamation.Account.BillingCountryCode;
            String billingPostalCode = reclamation.Account.BillingPostalCode;
            String billingState = reclamation.Account.BillingState;
            String billingStateCode = reclamation.Account.BillingStateCode;
            String billingStreet = reclamation.Account.BillingStreet;
            String orderType = reclamation.Order_type__c;
            Opportunity reclamationToUpdate = new Opportunity();
            if (orderType == 'Reclamation'){
                reclamationToUpdate.Id = reclamationId;
                if (String.IsBlank(contractId)){
                    //Create Contract for Reclamation  
                    Try {                           
                        Contract c = new Contract(
                            AccountId = accountId,
                            BillingCity = billingCity,
                            BillingCountry = billingCountry,
                            BillingCountryCode = billingCountryCode,
                            BillingPostalCode = billingPostalCode,
                            BillingState = billingState,
                            BillingStateCode = billingStateCode,
                            BillingStreet = billingStreet,
                            Contract_type__c = 'Final Contract',
                            Opportunity__c = reclamationId,
                            Quote__c = quoteId,                           
                            Signing_status__c = 'Sent', //Simulate Signing
                            StartDate = system.today(),
                            Status = 'Draft' //Do not Activate Yet
                        ); 
                        insert c;
                        contractId = c.Id;
                        reclamationToUpdate.contractId =contractId;
                    } catch (Exception e) {
                        errorMessage = ('Error in Contract Creation: '+e.getMessage());
                    }
                }
                Id orderId = [SELECT Id,OpportunityId FROM Order WHERE OpportunityId = : reclamationId LIMIT 1]?.Id;
            	if (String.IsBlank(orderId)){
                    //Create Contract for Reclamation  
                    Try {
                    	Order o = new Order(
                            AccountId = accountId,
                            Pricebook2Id = pricebookId,
                            Name = reclamationName,
                            OpportunityId = reclamationId,
                            QuoteId = quoteId,
                            EffectiveDate = system.today(),
                            Status = 'Draft', // Just create a draft Order
                            BillingCity = billingCity,
                            BillingCountry = billingCountry,
                            BillingCountryCode = billingCountryCode,
                            BillingPostalCode = billingPostalCode,
                            BillingState = billingState,
                            BillingStateCode = billingStateCode,
                            BillingStreet = billingStreet,
                            ContractId = contractId
                    	);
            		insert o;
                    orderId = o.Id;
                    reclamationToUpdate.Order__c =orderId;
                    } catch (Exception e) {
                        errorMessage = ('Error in Order Creation: '+e.getMessage());
                    }
                }
                // Update Reclamation Opportunity
                try{
                    if (contractId != reclamationToUpdate.Id || orderId != reclamationToUpdate.Order__c){
                        update reclamationToUpdate;
                    } 
                } catch (Exception e) {
                    errorMessage = 'Error in opportunity update' + e.getMessage();
                }
            /*
            // Update Case 
            try{
                Case cUpdate = new Case();
                cUpdate.Order__c = o.Id;
                cUpdate.Id = oppRecord.Case__c;
                update cUpdate;
            }catch (Exception e) {
                errorMessage = 'Error in case update' + e.getMessage();
            }
            // Update Configuration Plan 
            try{
               Configuration__c configuration = [SELECT Id from Configuration__c where Case__c = :caseId limit 1];
                Configuration__c configUpdate = new Configuration__c();
                configUpdate.Order__c = o.Id;
                configUpdate.Id = configuration.Id;
                update configUpdate;
            }catch (Exception e) {
                errorMessage = 'Error in configuration update' + e.getMessage();
            }  */  
            }
        }
        if (String.isNotBlank(errorMessage)) {
            return errorMessage;
        } else {
            return 'Success';
        }
   }
                
}