force-app/main/default/objects/Integration_Credentials__mdt/Integration_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Integration Credentials</label>
    <pluralLabel>Integration Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Credentials__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <description>The API Key for the Integration</description>
    <inlineHelpText>The API Key for the Integration</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>The Org Domain of the Environment</description>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>The Environment this applies to</description>
    <inlineHelpText>The Environment this applies to</inlineHelpText>
    <label>Environment</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <label>Environment Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Integration__c.field-meta.xml
<CustomField>
    <fullName>Integration__c</fullName>
    <description>The Name of the Integration</description>
    <inlineHelpText>The Name of the Integration</inlineHelpText>
    <label>Integration</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>test</fullName>
                <default>true</default>
                <label>test</label>
            </value>
            <value>
                <fullName>development</fullName>
            </value>
            <value>
                <fullName>production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicated if this is preduction, test or development</description>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-17-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class IntegrationController {
	public static String getOrgDomain () {
		String orgDomain = String.valueOf(URL.getOrgDomainUrl());
		System.debug('--- IntegrationController - getOrgDomain: '+orgDomain);
		return orgDomain;
	}
	public static String getEnvironment() {
		String orgDomain;
		Boolean isSandbox;
		String envName;		
		orgDomain = getOrgDomain();
    	isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
		if (isSandbox) {
			//https://lumonoy--lumontest.sandbox.my.salesforce.com
			envName = orgDomain.substringBetween('--', '.sandbox');
			envName = envName.remove('--c');			
		} else {
			// https://lumonoy.my.salesforce.com
			envName = orgDomain.substringBetween('https://', '.my');
		}
		System.debug('--- IntegrationController - getEnvironment envName: '+envName);
		return envName;
	}
	public static String getEnvironmentType() {
		Boolean isSandbox;
		String envName;
		String envType;		
    	envName = getEnvironment();
		isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
		if (isSandbox) {
			if (envName != 'lumontest') {
					envType = 'test';
			} else {
					envType = 'development';
			}
		} else {
			envType = 'production';
		}
		System.debug('--- IntegrationController - getEnvironmentType: '+envType);
		return envType;
	}
    public static Integration_Credentials__mdt getIntegrationCredentials (String integration, String type) {
		List<Integration_Credentials__mdt>  credentials = new List<Integration_Credentials__mdt> ();
		String environment = getEnvironment();
		String domain = getOrgDomain();
		String stage = getEnvironmentType();
		//credentials = [SELECT API_Key__c, Endpoint__c FROM Integration_Credentials__mdt WHERE Integration_Name__c = 'FrendsInstallation' AND Environment_Name__c =: envName];
      
		Integration_Credentials__mdt  credential;
		credentials = [SELECT Id,
							  Domain__c,
							  Stage__c,
                              Integration__c,
                              Environment__c,
                              ApiKey__c, 
                              Endpoint__c 
						FROM Integration_Credentials__mdt 
						WHERE Integration__c =: integration 
						AND Type__c =: type
						AND Domain__c =: domain
						LIMIT 1];
		if ( credentials.size()>0){
			credential = credentials[0];
		}
		System.debug('--- IntegrationController - getIntegrationCredentials: '+credential);
        return credential;
    }
}