force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types</description>
    <formula>Configuration_Product__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <label>Sales Code OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>First Level Grouping of Products and Services</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Reference to the Product Group for this Item</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Item__c.field-meta.xml
<CustomField>
    <fullName>Product_Item__c</fullName>
    <description>Third Level Grouping of Products and Services</description>
    <label>Product Item</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from QuoteLineItem</description>
    <formula>QuoteLineItem.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <label>Sales Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Option__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Item OLD</label>
    <referenceTo>Configuration_Option__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Item__c.field-meta.xml
<CustomField>
    <fullName>Product_Item__c</fullName>
    <inlineHelpText>Third Level Grouping of Products and Services</inlineHelpText>
    <label>Product Item OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from related Configuration Option</description>
    <formula>Configuration_Option__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>F-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing Beads</fullName>
    </customValue>
    <customValue>
        <fullName>h-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>L-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Rectangular Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Telescopic Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>U-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Upper Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Wall Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Screws</fullName>
    </customValue>
    <customValue>
        <fullName>Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 1</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 2</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 3</fullName>
    </customValue>
    <customValue>
        <fullName>Special Colors</fullName>
    </customValue>
    <customValue>
        <fullName>Sand Blasting</fullName>
    </customValue>
    <customValue>
        <fullName>Special Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Edge Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Items</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderLineItemController.cls
public with sharing class OrderLineItemController {
    @AuraEnabled(cacheable=true)
    public static List<OrderItem> getOrderLineItems(Id orderId) {
        // Populate map from SOQL query on QuotelineItem
        List<OrderItem> orderlineItems = ([ SELECT  Id,
                                                    //AvailableQuantity, Only for reduction Orders
                                                    OrderItemNumber,
                                                    Description,
                                                    OrderId, 
                                                    PricebookEntryId,
                                                    OriginalOrderItemId, 
                                                    QuoteLineItemId, 
                                                    QuoteLineItem.Quantity,
                                                    QuoteLineItem.Configuration_Option__c,
                                                    RVN__c,
                                                    Quantity,
                                                    CurrencyIsoCode,
                                                    UnitPrice, 
                                                    ListPrice, 
                                                    TotalPrice,
                                                    ServiceDate, 
                                                    EndDate,
                                                    Product2Id,
                                                    Product2.Name,
                                                    Product2.Product_Group__c,
                                                    Product2.Cost_Category__c,
                                                    Product2.Cost_Type__c,
                                                    Product2.Product_Category__c, 
                                                    Product2.Product_Type__c, 
                                                    Product2.Product_Item__c, 
                                                    Product2.ProductCode, 
                                                    Product2.Sales_Code__c,
                                                    Product2.QuantityUnitOfMeasure,
                                                    Product2.Reclamation__c,
                                                    Product2.Installation__c,
                                                    Product2.IsActive
                                            FROM OrderItem
                                            WHERE OrderId = :orderId
                                            ORDER BY Product2.Product_Group__c, Product2.Cost_Type__c]);
        System.debug('--- Order Line Items: '+orderlineItems);                                         
        return orderlineItems;
    }
    @AuraEnabled(cacheable=true)
    public static Map<String,OrderItem> getProductCodeToOrderLineItemMap(Id orderId,String currencyCode) {
        // Populate List from SOQL query on OrderLineItem
        Boolean isActive = True;
        System.debug('--- Get Order Line Items for Order '+orderId); 
        List<OrderItem> orderLineItems = getOrderLineItems(orderId);
        System.debug('--- Order Line Items: '+orderLineItems.size()); 
        Map<String,OrderItem> oiMap = New Map<String,OrderItem>();     
        if (orderLineItems.size()>0) {                               
            for (OrderItem orderLineItem :orderLineItems) {
                String productCode = orderLineItem.Product2.ProductCode;
                String product2Id = orderLineItem.Product2Id;
                Decimal quantity = orderLineItem.Quantity;
                oiMap.put(productCode,orderLineItem);
            }
        }  
        return oiMap;  
    } 
}