force-app/main/default/objects/Country_Mapping__mdt/Country_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Country Mapping</label>
    <pluralLabel>Country Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_Mapping__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCodeNumeric</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/fields/CountryCodeAlpha2__c.field-meta.xml
<CustomField>
    <fullName>CountryCodeAlpha2__c</fullName>
    <label>Country Alpha2</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/fields/CountryCodeAlpha3__c.field-meta.xml
<CustomField>
    <fullName>CountryCodeAlpha3__c</fullName>
    <label>CountryCodeAlpha3</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/fields/OfficialName__c.field-meta.xml
<CustomField>
    <fullName>OfficialName__c</fullName>
    <label>OfficialName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryMappingController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 04-16-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class CountryMappingController {
    @AuraEnabled(cacheable=false)
    public static Country_Mapping__mdt getCountryMappingByAlpha2(String searchString ) {
        // Populate List from SOQL query on Country_Mapping_mdt
        System.debug('--- Get Country_Mapping_mdts'); 
        Country_Mapping__mdt countryMapping = ([  SELECT Id, 
                                                        DeveloperName, 
                                                        MasterLabel, 
                                                        Language, 
                                                        NamespacePrefix, 
                                                        Label, 
                                                        QualifiedApiName, 
                                                        CountryCodeAlpha2__c, 
                                                        CountryCodeAlpha3__c,
                                                        Country_Name__c, 
                                                        CountryCode__c, 
                                                        OfficialName__c  
                                    FROM Country_Mapping__mdt 
                                    WHERE CountryCodeAlpha2__c =: searchString
                                    LIMIT 1
                                    ]);  
        System.debug('--- Country Mapping: '+countryMapping); 
        return countryMapping;  
    }
    @AuraEnabled(cacheable=false)
    public static Country_Mapping__mdt getCountryMappingByAlpha3(String searchString ) {
        // Populate List from SOQL query on Country_Mapping_mdt
        System.debug('--- Get Country_Mapping_mdts'); 
        Country_Mapping__mdt countryMapping = ([  SELECT Id, 
                                                        DeveloperName, 
                                                        MasterLabel, 
                                                        Language, 
                                                        NamespacePrefix, 
                                                        Label, 
                                                        QualifiedApiName, 
                                                        CountryCodeAlpha2__c, 
                                                        CountryCodeAlpha3__c,
                                                        Country_Name__c, 
                                                        CountryCode__c, 
                                                        OfficialName__c  
                                    FROM Country_Mapping__mdt 
                                    WHERE CountryCodeAlpha3__c =: searchString
                                    LIMIT 1
                                    ]);  
        System.debug('--- Country Mapping: '+countryMapping); 
        return countryMapping;  
    }
    @AuraEnabled(cacheable=false)
    public static Country_Mapping__mdt getCountryMappingByName(String searchString ) {
        // Populate List from SOQL query on Country_Mapping_mdt
        System.debug('--- Get Country_Mapping_mdts'); 
        Country_Mapping__mdt countryMapping = ([  SELECT Id, 
                                                        DeveloperName, 
                                                        MasterLabel, 
                                                        Language, 
                                                        NamespacePrefix, 
                                                        Label, 
                                                        QualifiedApiName, 
                                                        CountryCodeAlpha2__c, 
                                                        CountryCodeAlpha3__c,
                                                        Country_Name__c, 
                                                        CountryCode__c, 
                                                        OfficialName__c  
                                    FROM Country_Mapping__mdt 
                                    WHERE Country_Name__c =: searchString
                                    LIMIT 1
                                    ]);  
        System.debug('--- Country Mapping: '+countryMapping); 
        return countryMapping;  
    }
    @AuraEnabled(cacheable=false)
    public static Country_Mapping__mdt getCountryMappingByCode(String searchString ) {
        // Populate List from SOQL query on Country_Mapping_mdt
        System.debug('--- Get Country_Mapping_mdts'); 
        Country_Mapping__mdt countryMapping = ([  SELECT Id, 
                                                        DeveloperName, 
                                                        MasterLabel, 
                                                        Language, 
                                                        NamespacePrefix, 
                                                        Label, 
                                                        QualifiedApiName, 
                                                        CountryCodeAlpha2__c, 
                                                        CountryCodeAlpha3__c,
                                                        Country_Name__c, 
                                                        CountryCode__c, 
                                                        OfficialName__c  
                                    FROM Country_Mapping__mdt 
                                    WHERE CountryCode__c =: searchString
                                    LIMIT 1
                                    ]);  
        System.debug('--- Country Mapping: '+countryMapping); 
        return countryMapping;  
    }
}