force-app/main/default/objects/CPQ_Settings__c/CPQ_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enable/disable CPQ functionality</description>
    <label>CPQ Settings</label>
</CustomObject>

force-app/main/default/objects/CPQ_Settings__c/fields/Enhanced_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Enhanced_Pricing__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When Enabled uses Pricing Objects and Price Parameters</description>
    <inlineHelpText>When Enabled uses Pricing Objects and Price Parameters</inlineHelpText>
    <label>Enhanced Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Group_Items__c.field-meta.xml
<CustomField>
    <fullName>Group_Items__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When Enabled Groups Configuration Items per ProductCode</description>
    <inlineHelpText>When Enabled Groups Configuration Items per ProductCode</inlineHelpText>
    <label>Group Items</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/maxDiscount__c.field-meta.xml
<CustomField>
    <fullName>maxDiscount__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The maximum Discount a User can apply</description>
    <inlineHelpText>The maximum Discount a User can apply</inlineHelpText>
    <label>maxDiscount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Use_Pricelist__c.field-meta.xml
<CustomField>
    <fullName>Use_Pricelist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When enabled use the Pricelist Object instead of Price list Pricebook for retrieving Base Prices</description>
    <inlineHelpText>When enabled use the Pricelist Object instead of Price list Pricebook for retrieving Base Prices</inlineHelpText>
    <label>Use Pricelist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CPQSettingsController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 11-22-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class CPQSettingsController {
    public static Map<String,CPQ_Settings__c> getCPQSettingsMap(){
        Id userOrgId = userInfo.getOrganizationId();
        Id userProfileId = userinfo.getProfileId();
        Id userId = UserInfo.getUserId();
        Map<String,CPQ_Settings__c> cpqSettingsMap = new Map<String,CPQ_Settings__c>(); 
        CPQ_Settings__c cpqSettingsOrg = CPQ_Settings__c.getInstance(userOrgId);
        if (cpqSettingsOrg != null) {
            cpqSettingsMap.put(userOrgId,cpqSettingsOrg);
        }       
        CPQ_Settings__c cpqSettingsProfile = CPQ_Settings__c.getInstance(userProfileId);
        if (cpqSettingsProfile != null) {
            cpqSettingsMap.put(userProfileId,cpqSettingsProfile);
        }  
        CPQ_Settings__c cpqSettingsUser = CPQ_Settings__c.getInstance(userId);
        if (cpqSettingsUser != null) {
            cpqSettingsMap.put(userId,cpqSettingsUser);
        }
        System.debug('--- CPQ Settings Map: '+cpqSettingsMap);
        List<CPQ_Settings__c> cpqSettingsList = [SELECT Id, Name, SetupOwnerId, Use_Pricelist__c, Group_Items__c, Enhanced_Pricing__c, maxDiscount__c FROM CPQ_Settings__c ];
        return cpqSettingsMap;
    }
    public static CPQ_Settings__c getCPQSettings(){
        Id userOrgId = userInfo.getOrganizationId();
        Id userProfileId = userinfo.getProfileId();
        Id userId = userInfo.getUserId();
        CPQ_Settings__c cpqSettings;
        Map<String,CPQ_Settings__c> cpqSettingsMap = getCPQSettingsMap();
        if (cpqSettingsMap.containsKey(userId)){
            cpqSettings = cpqSettingsMap.get(userId);
        } else if (cpqSettingsMap.containsKey(userProfileId)){
            cpqSettings = cpqSettingsMap.get(userProfileId);
        } else if (cpqSettingsMap.containsKey(userOrgId)){
            cpqSettings = cpqSettingsMap.get(userOrgId);
        }
        System.debug('--- CPQ Settings: '+cpqSettings);
        return cpqSettings;
    }
}