force-app/main/default/objects/CPQ_Settings__c/CPQ_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enable/disable CPQ functionality</description>
    <label>CPQ Settings</label>
</CustomObject>

force-app/main/default/objects/CPQ_Settings__c/fields/Buffer_Override__c.field-meta.xml
<CustomField>
    <fullName>Buffer_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Gives permissions to ignore buffers in the Lead Time Calculation</description>
    <inlineHelpText>Gives permissions to ignore buffers in the Lead Time Calculation</inlineHelpText>
    <label>Buffer Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Closed_Stages__c.field-meta.xml
<CustomField>
    <fullName>Closed_Stages__c</fullName>
    <label>Closed Stages</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Configure_Stages__c.field-meta.xml
<CustomField>
    <fullName>Configure_Stages__c</fullName>
    <label>Configure Stages</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Debug mode. When enabled the pricing component shows the quote line items for admin users.</description>
    <inlineHelpText>Debug mode. When enabled the pricing component shows the quote line items for admin users.</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Detailed_View__c.field-meta.xml
<CustomField>
    <fullName>Detailed_View__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Detailed View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Discount_Override__c.field-meta.xml
<CustomField>
    <fullName>Discount_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to give special permissions for the User
- Give discount &gt;10%</description>
    <inlineHelpText>Checkbox to give special permissions for the User
- Give discount &gt;10%</inlineHelpText>
    <label>Discount_Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Enhanced_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Enhanced_Pricing__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When Enabled uses Pricing Objects and Price Parameters</description>
    <inlineHelpText>When Enabled uses Pricing Objects and Price Parameters</inlineHelpText>
    <label>Enhanced Pricing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Group_Items__c.field-meta.xml
<CustomField>
    <fullName>Group_Items__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When Enabled Groups Configuration Items per ProductCode</description>
    <inlineHelpText>When Enabled Groups Configuration Items per ProductCode</inlineHelpText>
    <label>Group Items</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/IsAdmin__c.field-meta.xml
<CustomField>
    <fullName>IsAdmin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to give special permissions for the User
- See Margins and Costs
- See item level details
- Give discount &gt;10%</description>
    <inlineHelpText>Checkbox to give special permissions for the User
- See Margins and Costs
- See item level details
- Give discount &gt;10%</inlineHelpText>
    <label>IsAdmin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/IsManager__c.field-meta.xml
<CustomField>
    <fullName>IsManager__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if User is a Sales Manager or Installation Manager and needs to see hidden columns</description>
    <inlineHelpText>Flag to indicate if User is a Sales Manager or Installation Manager and needs to see hidden columns</inlineHelpText>
    <label>IsManager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/IsSupport__c.field-meta.xml
<CustomField>
    <fullName>IsSupport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if User is Technical Support and needs to see hidden columns</description>
    <inlineHelpText>Flag to indicate if User is Technical Support and needs to see hidden columns</inlineHelpText>
    <label>IsSupport</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/maxDiscount__c.field-meta.xml
<CustomField>
    <fullName>maxDiscount__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The maximum Discount a User can apply</description>
    <inlineHelpText>The maximum Discount a User can apply</inlineHelpText>
    <label>maxDiscount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CPQ_Settings__c/fields/Use_Pricelist__c.field-meta.xml
<CustomField>
    <fullName>Use_Pricelist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When enabled use the Pricelist Object instead of Price list Pricebook for retrieving Base Prices</description>
    <inlineHelpText>When enabled use the Pricelist Object instead of Price list Pricebook for retrieving Base Prices</inlineHelpText>
    <label>Use Pricelist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LumonTestCPQSettings.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-10-2024
 * @last modified by  : Henk Reynders
**/
@istest
public with sharing class LumonTestCPQSettings {
	public static void setupCPQSettings(){  
        Id cpqSettingsOwner = CPQ_Settings__c.getOrgDefaults().SetupOwnerId;  
        Id orgId = [SELECT Id FROM Organization].Id;
        CPQ_Settings__c cpqSettings = new CPQ_Settings__c();
        cpqSettings.Name = 'Default CPQ Setting';
        cpqSettings.SetupOwnerId = orgId;
        cpqSettings.Debug__c = False;
        cpqSettings.Enhanced_Pricing__c	= False;
        cpqSettings.Group_Items__c	= False;
        cpqSettings.Use_Pricelist__c = False;
        cpqSettings.Discount_Override__c = False;
        cpqSettings.Buffer_Override__c = False;
        cpqSettings.Detailed_View__c = False;
        cpqSettings.maxDiscount__c = 0;
        cpqSettings.Closed_Stages__c = ('Closed Won;Cancelled;Closed Lost');
        cpqSettings.Configure_Stages__c = ('Configure;Price;Quoting');
        // To be Deleted Fields
        // cpqSettings.IsAdmin__c	FALSE
        //cpqSettings.IsManager__c	FALSE
        //cpqSettings.IsSales__c	FALSE
        //cpqSettings.IsSupport__c	FALSE
        insert cpqSettings;
        System.debug('--- LumonTestCPQSettings - inserted cpqSettings: '+cpqSettings );
    }
    @Istest
    public static void setupCPQSettingsTest(){
        String testresult;
        try {
            setupCPQSettings();            
        	testresult = ('Inserted CPQ Settings'); 
		} catch (Exception e) {
            //Any other exceptions that occur will go here
            String errorMessage = e.getMessage(); 
            testresult = ('Error - An Exception Occured:'+errorMessage);
        }
        System.debug('--- LumonTestCPQSettings - Test Result: '+testresult );
        System.assertNotEquals('Error',testresult,' Expected CPQ Settings to be Inserted without Error');
    }
}