force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <label>Configuration Name OLD</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Configuration_Status__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Status__c</fullName>
    <formula>IMAGE(&apos;/img/msg_icons/error32.png&apos;,&apos;ERROR&apos;,20,20)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Configuration Status OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the Contract to which this Configuration belongs.
Set when Quote is Accepted and Contract Signed</description>
    <inlineHelpText>Reference to the Contract to which this Configuration belongs</inlineHelpText>
    <label>Plan Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Delivery_Batch__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Batch</label>
    <referenceTo>Delivery_Batch__c</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Delivery_Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Batch_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indicates the Number of the Delivery Batch</description>
    <inlineHelpText>Indicates the Number of the Delivery Batch</inlineHelpText>
    <label>Delivery Batch Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Lock_RVN__c.field-meta.xml
<CustomField>
    <fullName>Lock_RVN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Lock RVN value TRUE or FALSE decides whether Visual can override or create structure number for the Plan</description>
    <label>Lock RVN OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Shows the Oportunity Number related to the Configuration Plan</description>
    <formula>Opportunity__r.Opportunity_Number__c</formula>
    <inlineHelpText>The Oportunity Number related to the Configuration Plan</inlineHelpText>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity_Project__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Project__c</fullName>
    <formula>Opportunity__r.Project_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Configured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order OLD</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>Configuration_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/Delivery_Batch__c.object-meta.xml
<CustomObject>
    <description>Contains details about project work part (delivery batch).</description>
    <label>Delivery Batch</label>
    <nameField>
        <displayFormat>DB-{00000000}</displayFormat>
        <label>Delivery Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Batch__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Batches</relationshipLabel>
    <relationshipName>DeliveryBatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Batches</relationshipLabel>
    <relationshipName>LumonDeliveryBatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Quote (Offer) this Delivery Batch belongs to</description>
    <inlineHelpText>The Quote (Offer) this Delivery Batch belongs to</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Delivery Batches</relationshipLabel>
    <relationshipName>Delivery_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case OLD</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Auto number to have a unique 8 digit number that links Sales Objects. Used as sales reference</description>
    <displayFormat>{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number OLD</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Planning Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Configured</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfigurationPlanController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 04-29-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ConfigurationPlanController {
	private static String sObjectName = 'Configuration__c';
	private static String allowedFieldSet = 'Table_Fields';
	private static String visibleFieldSet = 'Table_View';
	private static String editableFieldSet = 'Table_Edit';
	@AuraEnabled(cacheable=true)
    public static List<Configuration__c> getConfigurationPlans(Id configId, Id relatedRecordId, String visualPlanId){
        System.debug('--- Get Configuration Plan for Processing');
        Configuration__c configPlan = New Configuration__c(); // Existing Configuration Plan
        List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
        // Find Configuration based on configId, recordId or VisualPlanId
        if(String.isNotBlank(configId)){
            System.debug('--- Getting Configuration Plan Id for Config Id '+configId); 
            configPlans = getConfigurationPlansById(configId);
            System.debug('--- Found '+configPlans.size()+' Configuration Plan(s) with Id: '+ configId);
        } else if (String.isNotBlank(relatedRecordId)) {
            System.debug('--- Getting Configuration Plans from Record');       
            configPlans = getConfigurationsByRelatedId(relatedRecordId);
            System.debug('--- Found '+configPlans.size()+' related Configuration Plan(s) for Id: '+ relatedRecordId);
        }  else if (String.isNotBlank(visualPlanId)){ 
            System.debug('--- Getting Configuration Plan Id for Visual Plan Id '+visualPlanId);  
            configPlans = getConfigurationsByVisualId(visualPlanId);
            System.debug('--- Found '+configPlans.size()+' Configuration Plan(s) for Visual Id: '+ visualPlanId);
        }
        return configPlans;
    }
	@AuraEnabled(cacheable=true)
	public static List<Configuration__c> getConfigurationPlansByBatchId(Id batchId){
		List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
		// Find Configuration based on Delivery BatchId
        if (String.isNotEmpty(batchId)){
            configPlans =  [ SELECT Id,
                        Name,
                        Account__c,
                        Opportunity__c,
                        Quote__c,
                        Delivery_Batch__c,
						Delivery_Batch_Number__c,
						Plan_Type__c,
						Plan_Name__c,
						Plan_Floor__c,
						Plan_Line__c,
						Plan_Apartment__c
                FROM Configuration__c 
                WHERE Delivery_Batch__c =: batchId];
		}
		return configPlans;
	}
    @AuraEnabled(cacheable=true)
	public static List<Configuration__c> getConfigurationPlansById(Id configurationId){
		List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
		// Find Configuration based on ConfigurationId
        if (String.isNotEmpty(configurationId)){
            configPlans =  [ SELECT Id,
                        Name,
                        Account__c,
                        Opportunity__c,
                        Quote__c,
                        Contract__c,
                        Order__c,
                        Work_Order__c,
                        Case__c,
                        Plan_Type__c,
						Plan_Name__c,
						Plan_Floor__c,
						Plan_Line__c,
						Plan_Apartment__c
                FROM Configuration__c 
                WHERE Id =: configurationId];
		}
		return configPlans;
	}
	@AuraEnabled(cacheable=true)
	public static List<Configuration__c> getConfigurationPlansByIds(List<Id> configurationIds){
		List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
		// Find Configuration based on ConfigurationIs
		if (configurationIds.size()>0 && configurationIds != null) {
			configPlans =  [ SELECT Id,
									Name,
									Account__c,
									Opportunity__c,
									Quote__c,
									Contract__c,
									Order__c,
									Work_Order__c,
									Case__c,
									Plan_Type__c,
									Visual_Id__c
							FROM Configuration__c 
							WHERE Id IN: configurationIds];
		}
		return configPlans;
	}
	@AuraEnabled(cacheable=true)
	public static List<Configuration__c> getConfigurationsByRelatedId(Id relatedRecordId){
		List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
		// Find Configuration based on Opportunity or Quote recordId
		if (String.isNotBlank(relatedRecordId)) {
			configPlans = getConfigurationsByRelatedIds(new List<Id>{relatedRecordId});
		}
		return configPlans;
	}
	@AuraEnabled(cacheable=true)
	public static List<Configuration__c> getConfigurationsByRelatedIds(List<Id> relatedRecordIds){
		List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
		// Find Configuration based on Opportunity or Quote recordId
		if (relatedRecordIds.size()>0) {
			configPlans = [ SELECT Id,
									Name,
									//OwnerId, Not available for Child Records
									IsDeleted, 
									Account__c,
									Building__c,
									//Apartment__c,
									Opportunity__c,
									Quote__c,
									Contract__c,
									Order__c,
									Work_Order__c,
									Case__c,									
									Status__c,
									Configuration_Name__c,
									Configuration_Status__c, 
									Opportunity_Number__c, 
									Opportunity_Project__c,  
									Lock_RVN__c,
									LockPlan__c,
									Plan_Type__c, 
									Plan_Apartment__c, 
									Plan_Floor__c, 
									Plan_Line__c, 
									Plan_Name__c,
									Visual_Id__c, 
									Config_JSON__c, 
									Pricing_JSON__c,
									Visual_Pricing_JSON__c, 
									Visual_Products_JSON__c,
									Visual_Version__c, 
									Count_Products__c,
									Sovelia_Id__c, 
									Sovelia_Pricing_JSON__c, 
									Sovelia_Products_JSON__c, 
									//Sovelia_Statistics__c, 
									Sovelia_Version__c, 
									hasInstallationTime__c,
									Installation_Duration__c,
									Installation_Time__c, 
									Installation_Hours__c, 
									fxInstallationMins__c,  
									hasProductionTime__c, 
									Production_Time__c, 
									Production_Time_Max__c
							FROM Configuration__c 
							WHERE Account__c IN : relatedRecordIds
							OR Building__c IN: relatedRecordIds
							OR Opportunity__c IN: relatedRecordIds
							OR Quote__c IN: relatedRecordIds
							OR Contract__c IN: relatedRecordIds
							OR Order__c IN: relatedRecordIds
							OR Work_Order__c IN: relatedRecordIds
							OR Case__c IN: relatedRecordIds];
		}
		return configPlans;
	}
	@AuraEnabled(cacheable=true)
	public static List<Configuration__c> getConfigurationsByVisualId(String visualPlanId){
		List<Configuration__c> configPlans = New List<Configuration__c>(); // Existing Configuration Plans  
		// Find Configuration based on Visual Confguration Id
		if (String.isNotBlank(visualPlanId)) {
			configPlans = [ SELECT Id,
									Name,
									Account__c,
									Opportunity__c,
									Quote__c,
									Contract__c,
									Order__c,
									Work_Order__c,
									Case__c,
									Plan_Type__c,
									Visual_Id__c
							FROM Configuration__c 
							WHERE Visual_Id__c =: visualPlanId];
		}
		return configPlans;
	}
	@AuraEnabled(cacheable=true)
	// Create a Map of Configuration Products and Visual Structure Number
	public static Map<String,Configuration__c> getVisualIdsToPlanMap(List<Configuration__c> configurations){
		Map<String,Configuration__c> visualToPlanMap = new Map<String,Configuration__c>();
		if (configurations.size()>0 && configurations != null) {
			for (Configuration__c configPlan : configurations){
				String visualId = configPlan.Visual_Id__c;
				if(!visualToPlanMap.containsKey(visualId)){
					visualToPlanMap.put(visualId,configPlan);
				}
			}
		}
		return visualToPlanMap;
	}
    @AuraEnabled(cacheable=true)
	// Create a Map of Configuration Products and Visual Structure Number
	public static Map<Id,Configuration__c> getOpportunitiesToPlanMap(List<Configuration__c> configurations){
		Map<Id,Configuration__c> opportunitiesToPlanMap = new Map<Id,Configuration__c>();
		if (configurations.size()>0 && configurations != null) {
			for (Configuration__c configPlan : configurations){
				Id opportunityId = configPlan.Opportunity__c;
				if(!opportunitiesToPlanMap.containsKey(opportunityId)){
					opportunitiesToPlanMap.put(opportunityId,configPlan);
				}
			}
		}
		return opportunitiesToPlanMap;
	}
}