force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit_Of_Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Code of the Product as using in External Systems</description>
    <formula>Product__r.Sales_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Code of the Product as using in External Systems</inlineHelpText>
    <label>Sales Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>The Price on the Base PriceList</description>
    <inlineHelpText>The Price of Products and Services as Listed on the Product Catalog</inlineHelpText>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Transmission</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <formula>TEXT(QuantityUnitOfMeasure)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>Base Price * Sales Multiplier</description>
    <inlineHelpText>Base Price</inlineHelpText>
    <label>Base Price OLD</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Factory_Price__c.field-meta.xml
<CustomField>
    <fullName>Factory_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Price OLD</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxCost__c.field-meta.xml
<CustomField>
    <fullName>fxCost__c</fullName>
    <description>Calculated Result of Base Price * Cost Multiplier * Quantity</description>
    <formula>IF(Cost_Multiplier__c &gt; 0,  fxUnitCost__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Line Item Cost</inlineHelpText>
    <label>fxCost</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxDiscount__c.field-meta.xml
<CustomField>
    <fullName>fxDiscount__c</fullName>
    <formula>IF(AND(UnitPrice&gt;0,fxUnitSalesPrice__c&gt;0),(1 - ( UnitPrice/fxUnitSalesPrice__c)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxDiscount</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxFactory__c.field-meta.xml
<CustomField>
    <fullName>fxFactory__c</fullName>
    <formula>IF(Factory_Multiplier__c &gt; 0, fxUnitFactoryPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxFactory</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxSales__c.field-meta.xml
<CustomField>
    <fullName>fxSales__c</fullName>
    <description>The ListPrice calculated from Base Price with a Sales Multiplier</description>
    <formula>IF( Sales_Multiplier__c &gt; 0,   fxUnitSalesPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Price on the PriceList aka List Price</inlineHelpText>
    <label>fxSales</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <inlineHelpText>List Price</inlineHelpText>
    <label>List Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Max_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Maximum Quantity of an Item per Product Group on a single Offer</inlineHelpText>
    <label>Max Quantity OLD</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Price__c</fullName>
    <inlineHelpText>Min Price</inlineHelpText>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Sales_Price__c</fullName>
    <inlineHelpText>Min Sales Price OLD</inlineHelpText>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Cost__c.field-meta.xml
<CustomField>
    <fullName>Product_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Cost</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from related Configuration Option</description>
    <formula>Configuration_Option__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Margin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin__c</fullName>
    <formula>IF(Revenue__c&gt;0,(Gross_Profit__c / Revenue__c),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Margin OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingAdditionalCostsController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class PricingAdditionalCostsController {
    @TestVisible
    public static final String ADDITIONAL_COST_PRODUCT_GROUP = 'LISAKUSTAN'; // Not used at the moment as Additional Costs relate to a Main Product
    @TestVisible
    public static final String ADDITIONAL_COST_PRODUCT_CATEGORY = 'Additional Costs';

    public with sharing class ComponentData {
        @AuraEnabled
        public Quote quote { get; private set; }
        @AuraEnabled
        public Boolean disabled { get; private set; }
        @AuraEnabled
        public Opportunity opportunity { get; private set; }
        @AuraEnabled
        public Boolean showAddCosts { get; private set; }
        @AuraEnabled
        public Map<String, List<PricingSummaryService.PicklistOption>> picklistValues { get; private set; }
        @AuraEnabled
        public Map<String, List<String>> picklistDependencies { get; private set; }
        @TestVisible
        @AuraEnabled
        public List<QuoteLineItem> quoteLineItems { get; private set; }
        public ComponentData(Id recordId) {
            opportunity = PricingSummaryService.queryOpportunity(recordId);
            try {
                quote = PricingSummaryService.queryQuote(opportunity.SyncedQuoteId);
            } catch (Exception e) {
                throw new PricingSummaryService.PricingDataException('The synced quote can\'t be found');
            }
            showAddCosts = PricingSummaryService.queryPricingSummary(opportunity.Id, quote.Id) != null
                && PricingSummaryService.opportunityHasProductItems(quote.Id)
                && !PricingSummaryService.componentDisabled(opportunity);
            quoteLineItems = [
                SELECT
                    Id,
                    Description,
                    QuoteId,
                    Product2Id,
                    Product2.Name,
                    Product2.ProductCode,
                    Product2.Product_Group__c,
                    Product2.Cost_Category__c,
                    Product2.Cost_Type__c,
                    Product2.Unit_Of_Measure__c,
                    Product2.Sales_Code__c,
                    Cost_Category__c,
                    Cost_Type__c,
                    toLabel(Cost_Type__c) costTypeLabel,
                    Product_Group__c,
                    toLabel(Product_Group__c) productGroupLabel,
                    Quantity,
                    List_Price__c,
                    UnitPrice,
                    ListPrice,
                    Min_Sales_Price__c,
                    Min_Price__c,
                    Transmission__c,
                    Discount,
                    Discount__c,
                    fxDiscount__c,
                    CurrencyIsoCode,
                    fxFactory__c,
                    Factory_Price__c,
                    fxCost__c,
                    Product_Cost__c,
                    fxSales__c,
                    Sales_Margin__c,
                    SubTotal,
                    TotalPrice,
                    Product_Code__c,
                    Base_Price__c,
                    Max_Quantity__c,
                    Configuration_Product__c,
                    Sales_Code__c
                FROM QuoteLineItem
                WHERE QuoteId = :quote.Id AND Product2.Product_Category__c = :ADDITIONAL_COST_PRODUCT_CATEGORY
                ORDER BY List_Price__c DESC, Product2.Product_Group__c, Product2.Cost_Type__c
            ];
            // Filter out the duplicate, 0 price items
            List<QuoteLineItem> filtered = new List<QuoteLineItem>();
            Set<String> filteredIds = new Set<String>();
            for(QuoteLineItem qli : quoteLineItems) {
                String filteredId = qli.Product2.Product_Group__c + '-' + qli.Product2.Cost_Type__c;
                if(!filteredIds.contains(filteredId)) {
                    filtered.add(qli);
                    filteredIds.add(filteredId);
                }
            }
            quoteLineItems = filtered;
            picklistValues = new Map<String, List<PricingSummaryService.PicklistOption>>{
                'Product_Group__c' => findAdditionalCostProductGroups(
                    PricingSummaryService.getQuoteLineItems(quote.Id)
                ),
                'Cost_Type__c' => findAdditionalCostCostTypes(opportunity.Pricebook2Id)
            };
        }
    }

    @AuraEnabled(cacheable=false)
    public static ComponentData getComponentData(Id recordId) {
        return new ComponentData(recordId);
    }

    @AuraEnabled
    public static void deleteAdditionalCost(Id opportunityId, Id quoteLineItemId) {
        QuoteLineItem quoteLineItem = [
            SELECT Id, Product2.Product_Group__c, Product2.Cost_Type__c
            FROM QuoteLineItem WHERE Id = :quoteLineItemId LIMIT 1
        ];
        List<QuoteLineItem> quoteLineItems = [
            SELECT Id
            FROM QuoteLineItem
            WHERE Quote.OpportunityId = :opportunityId
            AND Product2.Product_Group__c = :quoteLineItem.Product2.Product_Group__c
            AND Product2.Cost_Type__c = :quoteLineItem.Product2.Cost_Type__c
        ];
        if(!quoteLineItems.isEmpty()) {
            delete quoteLineItems;
        }
        PricingController.upsertQuoteLines(opportunityId);
    }

    @AuraEnabled
    public static String saveAdditionalCost(
        Id opportunityId,
        QuoteLineItem quoteLineItem,
        QuoteLineItem quoteLineItemWithPrices
    ) {
        Opportunity opportunity = PricingSummaryService.queryOpportunity(opportunityId);
        Quote quote = PricingSummaryService.queryQuote(opportunity.SyncedQuoteId);
        quoteLineItemWithPrices.Description = quoteLineItem.Description;

        Product2 product = [
            SELECT Product_Group__c, Cost_Type__c, Sales_Code__c
            FROM Product2 WHERE Id = :quoteLineItem.Product2Id
            LIMIT 1
        ];
        String productGroup = product.Product_Group__c;
        String costType = product.Cost_Type__c;
        String salesCode = product.Sales_Code__c;
        
        List<QuoteLineItem> oldQuoteLineItems = opportunity.SyncedQuoteId != null ? [
            SELECT Id FROM QuoteLineItem
            WHERE QuoteId = :opportunity.SyncedQuoteId
                AND Product_Group__c = :productGroup
                AND Cost_Type__c = :costType
        ] : new List<QuoteLineItem>();
        System.debug(oldQuoteLineItems);
        if(!oldQuoteLineItems.isEmpty()) {
            delete oldQuoteLineItems;
        }

        Integer maxQuoteLineItemNumber = 0;
        try {
            maxQuoteLineItemNumber = Integer.valueOf([
                SELECT MAX(Line_Number__c) FROM QuoteLineItem WHERE Quote.OpportunityId = :opportunityId][0].get('expr0')
            );
            if(maxQuoteLineItemNumber == null) {
                maxQuoteLineItemNumber = 1000;
            }
        } catch(Exception e) {
            maxQuoteLineItemNumber = 1000;
        }

        Id pricebook2Id = quote.Pricebook2Id;
        if(Test.isRunningTest()){
            //Invoke mock web service response
            pricebook2Id = Test.getStandardPricebookId();
        }
        PriceBookEntry entry = [
            SELECT Id, Product2Id
            FROM PriceBookEntry
            WHERE
                PriceBook2Id = :pricebook2Id
                AND Product2.Product_Group__c = :productGroup
                AND Product2.Cost_Type__c = :costType
                AND Product2.Product_Category__c = :ADDITIONAL_COST_PRODUCT_CATEGORY
                AND IsActive = TRUE
            LIMIT 1
        ];

        List<Configuration_Product__c> configurationProducts = [
            SELECT Id, RVN__c
            FROM Configuration_Product__c
            WHERE Product_Group__c = :productGroup
                AND Configuration__r.Opportunity__c = :opportunityId
        ];
        List<QuoteLineItem> newQuoteLineItems = new List<QuoteLineItem>();
        for(Integer i = 0; i < configurationProducts.size(); i++) {
            quoteLineItemWithPrices.Id = null;
            quoteLineItemWithPrices.Line_Number__c = maxQuoteLineItemNumber + 1 + i;
            quoteLineItemWithPrices.QuoteId = opportunity.SyncedQuoteId;
            quoteLineItemWithPrices.PriceBookEntryId = entry.Id;
            quoteLineItemWithPrices.Product2Id = entry.Product2Id;
            quoteLineItemWithPrices.Max_Quantity__c = 1;
            quoteLineItemWithPrices.Configuration_Product__c = configurationProducts.get(i).Id;
            quoteLineItemWithPrices.Sales_Code__c = productGroup + salesCode;
            quoteLineItemWithPrices.RVN_Number__c = configurationProducts.get(i).RVN__c;
            newQuoteLineItems.add(quoteLineItemWithPrices.clone());
        }
        upsert newQuoteLineItems;
        PricingController.upsertQuoteLines(opportunityId);
        return null;
    }

    public static List<PricingSummaryService.PicklistOption> findAdditionalCostProductGroups(
        List<QuoteLineItem> items
    ) {
        Map<String, PricingSummaryService.PicklistOption> productGroupPicklistOptions = new Map<String, PricingSummaryService.PicklistOption>();
        for (
            PricingSummaryService.PicklistOption option : PricingSummaryService.getPicklistOptions(
                Product2.Product_Group__c
            )
        ) {
            productGroupPicklistOptions.put(option.value, option);
        }
        List<String> orderedGroupNames = new List<String>();
        Map<String, String> groupNamesByName = new Map<String, String>();
        for (QuoteLineItem item : items) {
            String groupName = item.Product2.Product_Group__c;
            if (item.Product2.Product_Category__c == 'Product Options' && !groupNamesByName.containsKey(groupName)) {
                orderedGroupNames.add(groupName);
                groupNamesByName.put(groupName, productGroupPicklistOptions.get(item.Product2.Product_Group__c).label);
            }
        }
        orderedGroupNames.sort();
        List<PricingSummaryService.PicklistOption> options = new List<PricingSummaryService.PicklistOption>();
        for (String groupName : orderedGroupNames) {
            options.add(new PricingSummaryService.PicklistOption(groupName, groupNamesByName.get(groupName)));
        }
        return options;
    }

    public static List<PricingSummaryService.PicklistOption> findAdditionalCostCostTypes(Id pricebookId) {
        // TODO the LISÄKUSTAN entries are not active
        List<PriceBookEntry> entries = [
            SELECT Id, Product2Id, Product2.Cost_Type__c
            FROM PriceBookEntry
            WHERE
                PriceBook2Id = :pricebookId
                //AND Product2.Product_Group__c = :ADDITIONAL_COST_PRODUCT_GROUP
            	AND Product2.Product_Category__c = :ADDITIONAL_COST_PRODUCT_CATEGORY
                AND IsActive = TRUE
        ];
        List<Id> productIds = new List<Id>();
        for (PricebookEntry entry : entries) {
            productIds.add(entry.Product2Id);
        }
        List<Product2> products = [
            SELECT Cost_Type__c, Product_Group__c, toLabel(Cost_Type__c) costTypeLabel
            FROM Product2
            WHERE Id IN :productIds
        ];
        List<PricingSummaryService.PicklistOption> options = new List<PricingSummaryService.PicklistOption>();
        Set<String> uniqueCostTypes = new Set<String>();
        for (Product2 prod : products) {
            if (!uniqueCostTypes.contains(prod.Cost_Type__c)) {
                options.add(
                    new PricingSummaryService.PicklistOption(prod.Cost_Type__c, (String) prod.get('costTypeLabel'))
                );
                uniqueCostTypes.add(prod.Cost_Type__c);
            }
        }
        return options;
    }

    @AuraEnabled
    public static Product2 findProduct(String opportunityId, String productGroup, String costType) {
        Opportunity opportunity = PricingSummaryService.queryOpportunity(opportunityId);
        Quote quote = PricingSummaryService.queryQuote(opportunity.SyncedQuoteId);
        return PricingSummaryService.findProduct([
                SELECT Product2Id
                FROM PricebookEntry
                WHERE
                    PriceBook2Id = :quote.Pricebook2Id
                    AND Product2.Product_Group__c = :productGroup
                    AND Product2.Cost_Type__c = :costType
                    AND Product2.Product_Category__c = :ADDITIONAL_COST_PRODUCT_CATEGORY
                    AND IsActive = TRUE
                LIMIT 1
        ].Product2Id);
    }

    @AuraEnabled
    public static QuoteLineItem findPrices(String opportunityId, String productId, Decimal basePrice) {
        Product2 product = PricingSummaryService.findProduct(productId);
        return PricingSummaryService.findPrices(
            opportunityId,
            product.ProductCode,
            1,
            product.Product_Group__c,
            product.Cost_Type__c,
            basePrice
        );
    }
}