force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>Business Attribute to identify the applicable Revenue and Cost Parameters</description>
    <label>Business Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Account Billing Country)</description>
    <formula>TEXT( Account.BillingCountryCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Level 3 Classification based on District</description>
    <inlineHelpText>Level 3 Classification based on District</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Office__c.field-meta.xml
<CustomField>
    <fullName>Owner_Office__c</fullName>
    <formula>Owner.Office_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Office OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Owner_Profit_Center__c</fullName>
    <description>Level 4 Classification based on Profit Center of the Owner</description>
    <formula>Owner.Profit_Center_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 4 Classification based on Profit Center of the Owner</inlineHelpText>
    <label>Owner Profit Center OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/Pricing_Summary__c.object-meta.xml
<CustomObject>
    <label>Pricing Summary</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Pricing Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Summary__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>L2 Business Type - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>L1 Country - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>L3 District - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>L0 Organization - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>T2-{000000}</displayFormat>
        <label>Cost Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cost__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>Organization chosen in Opportunity</description>
    <formula>TEXT(Opportunity.Organization__c)</formula>
    <label>Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Option__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Item OLD</label>
    <referenceTo>Configuration_Option__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/Sales_Price__c.object-meta.xml
<CustomObject>
    <label>Sales Price</label>
    <nameField>
        <displayFormat>T3-{000000}</displayFormat>
        <label>Sales Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FI</fullName>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <label>Sweden</label>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
        <label>Norway</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Denmark</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Netherlands</label>
    </customValue>
    <masterLabel>Lumon Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-12-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
public with sharing class PricingControllerTest {
        @TestSetup
    static void prepareData(){
        Test.startTest();
        //LumonTestDataFactory.setupProducts();
        LumonTestProducts.setupProducts('LG');
        //LumonTestProducts.setupProducts('LGS');
        //LumonTestProducts.setupProducts('LFIXEDWALL');
        //LumonTestProducts.setupProducts('VT3');
        //LumonTestProducts.setupProducts('VT4');    
        //LumonTestProducts.setupProducts('VISORBLINDSALES');
        //LumonTestProducts.setupSoveliaProducts();
        //LumonTestProducts.setupRetractableProducts();
        LumonTestPricebooks.setupPricebookEntries();
        LumonTestPriceParameters.setupPriceParameters();
        LumonTestInstallationTimes.setupInstallationTimes();
        LumonTestProductionTimes.setupProductionTimes();
        LumonTestConfigurations.setupConfigurationData();
        
        // B2C Setup
        /*LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();*/
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
    private static String visualPricingJSON = LumonTestConfigurations.visualPricingJSON;
    private static String soveliaPricingJSON = LumonTestConfigurations.soveliaPricingJSON;
    //private static String testPricingJSON = LumonTestConfigurations.testPricingJSON;
    @IsTest
    static void getPricingJSONTest(){
        String recordId = b2cOpportunityId;      
        Test.startTest();
        String pricingJSON = PricingController.getPricingJSON(recordId); 
        System.assertNotEquals(null, pricingJSON, 'A pricing JSON to be returned');
        System.debug('--- getPricingJSONTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getPricingJSONTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getPricingSummaryTest(){
        String opportunityId = b2cOpportunityId;
     	Id summaryId = LumonTestPricingSummaries.setupPricingSummaryB2C(opportunityId);
        System.debug('--- getPricingSummaryTest - Summary: '+summaryId); 
        Test.startTest();
        Pricing_Summary__c summary = PricingController.getPricingSummary(opportunityId); 
        System.assertNotEquals(null, summary, 'A pricing Summary to be returned');
        System.debug('--- getPricingSummaryTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getPricingSummaryTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void upsertPricingSummaryTest(){
        String opportunityId = b2cOpportunityId;
        Id summaryId = LumonTestPricingSummaries.setupPricingSummaryB2C(opportunityId);
        System.debug('--- getPricingSummaryTest - Summary: '+summaryId); 
        Test.startTest();
        Pricing_Summary__c summary = PricingController.upsertPricingSummary(opportunityId); 
        System.assertNotEquals(null, summary, 'A pricing Summary to be updated');
        System.debug('--- upsertPricingSummaryTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- upsertPricingSummaryTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    } 
    @IsTest
    static void getConfigurationsByIdTest(){
        List<Configuration__c> configurations =  b2cConfigurations;
        List<Id> configurationIds = new List<Id>(new Map<Id, Configuration__c>(b2cConfigurations).keySet()); 
        System.debug('--- getConfigurationsByIdTest - configurationIds: '+configurationIds); 
        Test.startTest();
        List<Configuration__c> configPlans = ConfigurationController.getConfigurationsById(configurationIds);
        System.assertNotEquals(0, configPlans.size(), 'Expecting atleast 1 Configuration to be returned');
        System.debug('--- getConfigurationsByIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getConfigurationsByIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getFactoryPricesConsumerTest(){
        Opportunity opp = [SELECT Id,AccountId, SyncedQuoteId,
                                  Organization__c,Business_Type__c ,
                           			Country_Attribute__c,District__c,
                           			OwnerId, Owner_Profit_Center__c, Owner_Office__c
                          FROM Opportunity WHERE Id =:b2cOpportunityId LIMIT 1];
        Id accountId = opp.AccountId;
        Id quoteId = opp.SyncedQuoteId;
        Id owner = opp.OwnerId;
        String org = opp.Organization__c;
        String business = opp.Business_Type__c;
        String district = opp.District__c;
        String country = district.left(2);
        String profit = opp.Owner_Profit_Center__c;
        String office = opp.Owner_Office__c;
        List<String> products = new List<string>();
        products.add('LG');
        products.add('LGS');
        
        Test.startTest();
        System.Debug('--- getFactoryPricesConsumerTest - Opportunity '+opp);
        System.Debug('--- getFactoryPricesConsumerTest - factory '+[SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    Business_Type__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Factory_Multiplier__c,
                                    IsActive__c
                            FROM Factory_Price__c]);
        Map<String,Map<String,Factory_Price__c>> factoryPriceMap = PricingParameterController.getFactoryPrices(products,org,country,business); 
        System.assertNotEquals(0, factoryPriceMap.size(), 'Expecting One or More Items to be returned');
        System.debug('--- getFactoryPricesConsumerTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getFactoryPricesConsumerTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getProductCostsConsumerTest(){
        Opportunity opp = [SELECT Id,AccountId, SyncedQuoteId,
                                  Organization__c,Business_Type__c ,
                           			Country_Attribute__c,District__c,
                           			OwnerId, Owner_Profit_Center__c, Owner_Office__c
                          FROM Opportunity WHERE Id =:b2cOpportunityId LIMIT 1];
        Id accountId = opp.AccountId;
        Id quoteId = opp.SyncedQuoteId;
        Id owner = opp.OwnerId;
        String org = opp.Organization__c;
        String business = opp.Business_Type__c;
        String district = opp.District__c;
        String country = district.left(2);
        String profit = opp.Owner_Profit_Center__c;
        String office = opp.Owner_Office__c;
        List<String> products = new List<string>();
        products.add('LG');
        products.add('LGS');
        System.Debug('--- getProductCostsConsumerTest - Opportunity '+opp);
        System.Debug('--- getProductCostsConsumerTest - Cost '+[SELECT Id,
                                    Organization__c,
                                    Country__c,
                                    Business_Type__c,
                                    Product_Group__c,
                                    Cost_Type__c,
                                    Cost_Multiplier__c,
                                    IsActive__c
                            FROM Product_Cost__c]);
        Test.startTest();
        Map<String,Map<String,Product_Cost__c>> productCostMap = PricingParameterController.getProductCosts(products,org,country,business,district); 
        System.assertNotEquals(0, productCostMap.size(), 'Expecting One or More Items to be returned');
        System.debug('--- getProductCostsConsumerTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getProductCostsConsumerTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    //Tested in PricingParameterControllerTest
    /*@IsTest
    static void getSalesPriceConsumerTest(){
        Opportunity opp = [SELECT Id,AccountId, SyncedQuoteId,
                                  Organization__c,Business_Type__c ,
                           			Country_Attribute__c,District__c,
                           			OwnerId, Owner_Profit_Center__c, Owner_Office__c
                          FROM Opportunity WHERE Id =:b2cOpportunityId LIMIT 1];
        Id accountId = opp.AccountId;
        Id quoteId = opp.SyncedQuoteId;
        Id owner = opp.OwnerId;
        String org = opp.Organization__c;
        String business = opp.Business_Type__c;
        String district = opp.District__c;
        String country = opp.Country_Attribute__c;
        String profit = '';
        String office ='';
        String customer = '';
        List<String> products = new List<string>();
        products.add('LG');
        products.add('LGS');
        Test.startTest();
        Map<String,Map<String,Sales_Price__c>> salesPriceMap = PricingParameterController.getSalesPrices(products,org,country,business,district,profit,customer); 
        System.assertNotEquals(0, salesPriceMap.size(), 'Expecting One or More Items to be returned');
        System.debug('--- getSalesPriceConsumerTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getSalesPriceConsumerTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void insertQuoteLinesOpptyTest(){
        String recordId = b2cOpportunityId;
        List<Configuration__c> configurations =  b2cConfigurations;
        List<Id> configurationIds = new List<Id>(new Map<Id, Configuration__c>(b2cConfigurations).keySet()); 
        Test.startTest();
    		String upsertResult = PricingController.upsertQuoteLines(recordId); 
    		System.assertNotEquals(FALSE, String.isNotBlank(upsertResult), 'Expecting a result');
    		System.debug('--- insertQuoteLinesOpptyTest - CPU TIME: '+LIMITS.getCpuTime()); 
    		System.debug('--- insertQuoteLinesOpptyTest - SOQL USED: ' + LIMITS.getQueries());
    	Test.stopTest();
    }*/
    @IsTest
    static void updateQuoteLinesOpptyTest(){
        List<Configuration__c> configurations =  b2cConfigurations;
        List<Id> configurationIds = new List<Id>(new Map<Id, Configuration__c>(configurations).keySet()); 
        String recordId = b2cOpportunityId;
        String configPlanId = configurationIds[0];
        String pricingJSON = LumonTestConfigurations.retractablePricing;
        String visualConfigResult = ConfigurationController.processVisualConfiguration(configPlanId,recordId,pricingJSON);
    	/*List<QuoteLineItem> quoteLineItems = new List<QuoteLineItem>();
        List<PriceBookEntry> pricebookEntries = [SELECT Id,Product2Id FROM PricebookEntry];
        for (Integer i = 0; i<pricebookEntries.size();i++) {
            QuoteLineItem qli = new QuoteLineItem(QuoteId=b2cSyncedQuoteId,
                                                    Product2Id=pricebookEntries[i].Product2Id,
                                                    PricebookEntryId=pricebookEntries[i].Id,
                                                    Quantity=1,
                                                    UnitPrice=1);
            quoteLineItems.add(qli);
        }
        insert quoteLineItems;*/   
        List<PriceBookEntry> pricebookEntries = [SELECT Id,Product2Id FROM PricebookEntry];
        List<QuoteLineItem> quoteLineItems = [SELECT Id,Product2Id FROM QuoteLineItem];
        System.debug('--- updateQuoteLinesOpptyTest - PBE Count: '+pricebookEntries.size()); 
    	System.debug('--- updateQuoteLinesOpptyTest - QLI Count: ' + quoteLineItems.size());
        Test.startTest();
    		String upsertResult = PricingController.upsertQuoteLines(recordId); 
    		System.assertNotEquals(FALSE, String.isNotBlank(upsertResult), 'Expecting a result');
    		System.debug('--- updateQuoteLinesOpptyTest - CPU TIME: '+LIMITS.getCpuTime()); 
    		System.debug('--- updateQuoteLinesOpptyTest - SOQL USED: ' + LIMITS.getQueries());
    	Test.stopTest();
     }
    @IsTest
    static void upsertQuoteLinesQuoteTest(){
        String recordId = b2cOpportunityId;
        List<Configuration__c> configurations =  b2cConfigurations;
        List<Id> configurationIds = new List<Id>(new Map<Id, Configuration__c>(b2cConfigurations).keySet()); 
		String quoteId = [SELECT Id FROM Quote WHERE IsSyncing = True AND OpportunityId =:b2cOpportunityId]?.Id;        
        Test.startTest();
            String configId = String.valueOf(configurationIds[0]);
			System.debug('----upsertQuoteLinesQuoteTest - configId: '+configId);
            String upsertResult = PricingController.upsertQuoteLines(quoteId); 
            System.assertNotEquals(FALSE, String.isNotBlank(upsertResult), 'Expecting a result');
            System.debug('----upsertQuoteLinesQuoteTest - CPU TIME: '+LIMITS.getCpuTime()); 
            System.debug('----upsertQuoteLinesQuoteTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
     }
    
    @IsTest
    static void setOrderSpecificPricesTest() {
        List<QuoteLineItem> items = new List<QuoteLineItem> {
            new QuoteLineItem(Max_Quantity__c = 1, Sales_Code__c = 'a', Base_Price__c = 1),
            new QuoteLineItem(Max_Quantity__c = 1, Sales_Code__c = 'a', Base_Price__c = 1),
            new QuoteLineItem(Max_Quantity__c = 1, Sales_Code__c = 'b', Base_Price__c = 1),
            new QuoteLineItem(Max_Quantity__c = 1, Sales_Code__c = 'b', Base_Price__c = 1),
            new QuoteLineItem(Max_Quantity__c = 2, Sales_Code__c = 'c', Base_Price__c = 1),
            new QuoteLineItem(Max_Quantity__c = 2, Sales_Code__c = 'c', Base_Price__c = 1),
            new QuoteLineItem(Max_Quantity__c = 2, Sales_Code__c = 'c', Base_Price__c = 1),
            new QuoteLineItem(Sales_Code__c = 'd', Base_Price__c = 1)
        };

        Test.startTest();
        PricingController.setOrderSpecificPrices(items);
        Assert.areEqual(1, items.get(0).Base_Price__c, 'First a price should remain');
        Assert.areEqual(0, items.get(1).Base_Price__c, 'Second a price should be 0');
        Assert.areEqual(1, items.get(2).Base_Price__c, 'First b price should remain');
        Assert.areEqual(0, items.get(3).Base_Price__c, 'Second b price should be 0');
        Assert.areEqual(1, items.get(4).Base_Price__c, 'First c price should remain');
        Assert.areEqual(1, items.get(5).Base_Price__c, 'Second c price should remain');
        Assert.areEqual(0, items.get(6).Base_Price__c, 'Third c price should be 0');
        Assert.areEqual(1, items.get(7).Base_Price__c, 'First d price should remain');
        Test.stopTest();
    } 

    @IsTest
    static void pricingAfterContractSentTest() {
        List<QuoteLineItem> items = new List<QuoteLineItem>{
            new QuoteLineItem(
                Quantity = 1.0,
                UnitPrice = 150.0,
                List_Price__c = 200.0,
                Discount__c = 0.0,
                Sales_Multiplier__c = 1.0
            ),
            new QuoteLineItem(
                Quantity = 1.0,
                UnitPrice = 150.0,
                List_Price__c = 200.0,
                Discount__c = 0.0,
                Sales_Multiplier__c = 1.0
            )
        };
        Test.startTest();
        Pricing_Summary__c summary = new Pricing_Summary__c(Sales_Price__c = 280);
        PricingController.recalculateDiscountOrSalesprice(true, summary, items);
        Assert.areEqual(30.0, items.get(0).Discount__c);
        Assert.areEqual(30.0, items.get(1).Discount__c);
        PricingController.recalculateDiscountOrSalesprice(false, summary, items);
        Assert.areEqual(140.0, items.get(0).UnitPrice);
        Assert.areEqual(140.0, items.get(1).UnitPrice);
        Test.stopTest();
    }
    @IsTest
    public static void QuotingManagerTriggeredTest() {
        String errorMessage;
        String configId;
        String recordId = b2cOpportunityId;
        String objectType = 'Opportunity';
        String configAction = 'Configure';
        String configType = 'Configurator';        
        String visualPlanId;
        String documentId;
        String visualPricingJSON;
        String configJSON = LumonTestConfigurations.visualPricingJSON;
        Test.startTest();
        try {
            QuotingManager.executeQuotingProcess( configType, configAction, configId, recordId,
                                                                objectType, visualPlanId,documentId, configJSON);
        } catch (Exception e) {
            //Any other exceptions that occur will go here
            errorMessage = e.getMessage(); 
            System.Debug ('*** QuotingManagerTriggeredTest - An Exception Occured:'+errorMessage);
        }
        System.assertEquals(null,errorMessage, 'Expected to process Visual Plan');
        System.debug('*** QuotingManagerTriggeredTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('*** QuotingManagerTriggeredTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest(); 
    }
}