force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <label>Cost Multiplier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Code of the Product as using in External Systems</description>
    <formula>Product__r.Sales_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Code of the Product as using in External Systems</inlineHelpText>
    <label>Sales Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>Base Price * Sales Multiplier</description>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Cost Multiplier</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Factory Multiplier</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/fxCost__c.field-meta.xml
<CustomField>
    <fullName>fxCost__c</fullName>
    <description>Calculated Result of Base Price * Cost Multiplier * Quantity</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/fxFactory__c.field-meta.xml
<CustomField>
    <fullName>fxFactory__c</fullName>
    <label>Factory</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/fxSales__c.field-meta.xml
<CustomField>
    <fullName>fxSales__c</fullName>
    <label>Sales</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>First Level Grouping of Products and Services</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Reference to the Product Group for this Item</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from QuoteLineItem</description>
    <formula>QuoteLineItem.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <label>Sales Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>Base Price * Sales Multiplier</description>
    <inlineHelpText>Base Price</inlineHelpText>
    <label>Base Price OLD</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Factory Multiplier OLD</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxCost__c.field-meta.xml
<CustomField>
    <fullName>fxCost__c</fullName>
    <description>Calculated Result of Base Price * Cost Multiplier * Quantity</description>
    <formula>IF(Cost_Multiplier__c &gt; 0,  fxUnitCost__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Line Item Cost</inlineHelpText>
    <label>fxCost</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxFactory__c.field-meta.xml
<CustomField>
    <fullName>fxFactory__c</fullName>
    <formula>IF(Factory_Multiplier__c &gt; 0, fxUnitFactoryPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxFactory</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxSales__c.field-meta.xml
<CustomField>
    <fullName>fxSales__c</fullName>
    <description>The ListPrice calculated from Base Price with a Sales Multiplier</description>
    <formula>IF( Sales_Multiplier__c &gt; 0,   fxUnitSalesPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Price on the PriceList aka List Price</inlineHelpText>
    <label>fxSales</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from related Configuration Option</description>
    <formula>Configuration_Option__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Sales_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Sales Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <formula>Quote.Opportunity.Account.VAT__c/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderTriggerHandler.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
public class OrderTriggerHandler {
	public static Boolean checkRecursion = FALSE;
    public static String response;
    public static String upsertOrderLineItems(String recordId){
        System.debug('*** order id ***'+recordId);
        Set<Id> syncedQuoteIds = new Set <Id> ();
        Set<Id> orderIds = new Set<Id>();
        Map<Id,Id> mapOfOppIdToOdrId = new Map<Id,Id>();
        List<OrderItem> orderItemsForUpsert = new List<OrderItem>();
        List<Order> triggeredOrders = new List<Order>();
        
        
        Order triggeredOrder = [SELECT Id,OpportunityId,Status,QuoteId from Order where OpportunityId =:recordId];
        if(triggeredOrder != null){
            System.debug('*** triggeredOrder.Status ***'+triggeredOrder.Status);
            if(triggeredOrder.OpportunityId  != null && 
               triggeredOrder.Status != 'Activated')
            {   
                triggeredOrders.add(triggeredOrder);
                upsertOrderLineItems(triggeredOrders,null, null);
            }
        }
        
        return null;
        
    }
    
    public static void upsertOrderLineItems(List<Order> triggeredOrders, Map<Id,Order> oldOrdersMap, Boolean fromTrigger){
        Set<Id> syncedQuoteIds = new Set <Id> ();
        List<Id> quoteIds = new List<Id>();
        Set<Id> orderIds = new Set<Id>();
        List<Order> orderList = new List<Order>();
        Map<Id,Id> mapOfOppIdToOdrId = new Map<Id,Id>();
        List<OrderItem> orderItemsForUpsert = new List<OrderItem>();

        for(Order o : triggeredOrders){
            if(o.OpportunityId  != null && o.Status != 'Activated'){ // New or Draft Order 
                    syncedQuoteIds.add(o.QuoteId);
                    mapOfOppIdToOdrId.put(o.OpportunityId ,o.Id);
                    orderIds.add(o.Id);
            }
        }
        
        if(syncedQuoteIds.size() > 0 ){
            quoteIds = new List<Id>(syncedQuoteIds);
            //Added Configuration_Product__r.RVN__c in query as part of LUM-2016
            List<QuoteLineItem> quoteItemList = QuoteLineItemController.getQuoteLineItemsById(quoteIds);
            List<OrderItem> orderItemExistingList = [SELECT Id,OrderId,Order.OpportunityId,QuoteLineItemId, Order.Status from OrderItem where OrderId IN:orderIds];
             
            Map<Id,Id> orderItemExistingMap= new Map<Id,Id>();
			List<OrderItem> orderItemsForDelete = new List<OrderItem>();
            
            if(!orderItemExistingList.isEmpty()){
                for(OrderItem orderLineItemExisting : orderItemExistingList){
                    orderItemsForDelete.add(orderLineItemExisting);
                }
                
                for(OrderItem orderLineItemExisting : orderItemExistingList){
                    if (!orderItemExistingMap.containsKey(orderLineItemExisting.QuoteLineItemId)){
                        orderItemExistingMap.put(orderLineItemExisting.QuoteLineItemId,orderLineItemExisting.Id);
                    } else {
                        // --------------- 07.10.2023 Would not be an expected situation 
                        orderItemExistingMap.put(orderLineItemExisting.QuoteLineItemId,orderLineItemExisting.Id);
                    }
                }
            }else{
                orderItemExistingMap = null;
            }
            
            if (!quoteItemList.isEmpty()) {
                
                for (QuoteLineItem qliToProcess: quoteItemList) {
                    
                    Id qliRecordId = qliToProcess.Id;
                    Id quoteRecordId = qliToProcess.QuoteId;
                    Id opportunityRecordId = qliToProcess.Quote.OpportunityId;  
                    if (String.isNotBlank(opportunityRecordId)) {
                        OrderItem orderItemVal = new OrderItem();
                        System.debug('--- OrderTriggerHandler - Processing QuoteLineItem ' + qliToProcess.Id);
                        if (orderItemExistingMap != NULL && orderItemExistingMap.containsKey(qliRecordId)){
                            orderItemVal.Id = orderItemExistingMap.get(qliRecordId);
                        }else if (qliToProcess.Quantity > 0) {
                            orderItemVal.OrderId = mapOfOppIdToOdrId.get(qliToProcess.Quote.OpportunityId);
                            orderItemVal.PricebookEntryId = qliToProcess.PricebookEntryId;
                            orderItemVal.Product2Id = qliToProcess.Product2Id;
                            orderItemVal.ListPrice = qliToProcess.ListPrice;
                            orderItemVal.UnitPrice = qliToProcess.UnitPrice;
                        }else {
                            System.debug('--- OrderTriggerHandler - No Available Quantity for Order Line Item');
                            break;
                        }
                        	System.debug('--- OrderTriggerHandler - QuoteLine Item Id: ' +qliRecordId);
                            orderItemVal.QuoteLineItemId = qliRecordId;
                            orderItemVal.Quantity = qliToProcess.Quantity;
                            orderItemVal.Description = qliToProcess.RVN__c+': '+qliToProcess.Product2.Name;
                            // 12.10.2023 Keep copying the custom Field Values for now
                            orderItemVal.Base_Price__c = qliToProcess.Base_Price__c != NULL ? qliToProcess.Base_Price__c : 0.00;
                            orderItemVal.Cost_Category__c = qliToProcess.Cost_Category__c != NULL ? qliToProcess.Cost_Category__c : 'Other';
                            orderItemVal.Cost_Multiplier__c = qliToProcess.Cost_Multiplier__c != NULL ? qliToProcess.Cost_Multiplier__c : 1;
                            orderItemVal.Cost_Type__c = qliToProcess.Cost_Type__c;
                            //orderItemVal.Description = qliToProcess.Description != NULL ? qliToProcess.Description : '';
                            orderItemVal.Discount__c = qliToProcess.Discount;
                            orderItemVal.Factory_Multiplier__c = qliToProcess.Factory_Multiplier__c != NULL ? qliToProcess.Factory_Multiplier__c : 1;
                            orderItemVal.fxCost__c = qliToProcess.fxCost__c;
                            orderItemVal.fxFactory__c = qliToProcess.fxFactory__c;
                            orderItemVal.fxSales__c = qliToProcess.fxSales__c;
                            orderItemVal.Product_Code__c = qliToProcess.Product_Code__c;
                            orderItemVal.Product_Group__c = qliToProcess.Product_Group__c;
                            orderItemVal.RVN_Number__c = qliToProcess.Configuration_Product__r.RVN__c;
                            orderItemVal.Sales_Code__c = qliToProcess.Sales_Code__c;
                            orderItemVal.Sales_Multiplier__c = qliToProcess.Sales_Multiplier__c;
                            orderItemVal.Subtotal__c = qliToProcess.Subtotal;
                            orderItemVal.Tax__c = qliToProcess.Tax__c;
                            System.debug('--- OrderTriggerHandler - Order Line Item '+orderItemVal);
                            orderItemsForUpsert.add(orderItemVal);
                    }
                    
                }
            }
            
        }
        System.debug('*** orderItemsForUpsert ***'+orderItemsForUpsert);
        List <Id> upsertedOrderLineItemIds = new List <Id> ();
        if(orderItemsForUpsert.size() > 0){
            try {
                upsert orderItemsForUpsert;
                upsertedOrderLineItemIds = new List < Id > (new Map < Id, OrderItem > (orderItemsForUpsert).keySet());
                System.debug('Order Line Items created successfully');
            }
            catch(Exception ex)
            {
                System.debug('Order line items insert failed'+ex.getMessage());
            }
        }

        // Get Existing Order Line Items to Delete
        List <OrderItem> obsoleteOrderLineItems = New List < OrderItem > ();
        obsoleteOrderLineItems = ([SELECT Id
            FROM OrderItem
            WHERE OrderId IN: orderIds
            AND Id NOT IN: upsertedOrderLineItemIds
            ORDER BY CreatedDate DESC
        ]);
        System.debug('--- ' + obsoleteOrderLineItems.size() + ' Order Line Item(s) to Delete');
        if (obsoleteOrderLineItems.size() > 0) {
            delete obsoleteOrderLineItems;
        }
         
    }

    public static OrderItem createOrderItems(QuoteLineItem ql, Map<Id,Id> mapOfOppIdToOdrId, Map<Id,Id> orderItemExistingMap){
        
        OrderItem oi = new OrderItem();
        if (orderItemExistingMap != NULL && orderItemExistingMap.containsKey(ql.Id)) {
            oi.Id = orderItemExistingMap.get(ql.Id);
        }
        /*else if(orderItemExistingMap == NULL){
            
        }*/
        oi.OrderId = mapOfOppIdToOdrId.get(ql.Quote.OpportunityId);
        oi.ListPrice = ql.ListPrice;
        oi.Product2Id = ql.Product2Id;
        oi.Quantity = ql.Quantity;
        oi.UnitPrice = ql.UnitPrice;
        oi.PricebookEntryId = ql.PricebookEntryId;
        oi.Base_Price__c = ql.Base_Price__c != NULL ? ql.Base_Price__c : 0.00;
        oi.Cost_Category__c = ql.Cost_Category__c != NULL ? ql.Cost_Category__c : 'Other';
        oi.Cost_Multiplier__c = ql.Cost_Multiplier__c != NULL ? ql.Cost_Multiplier__c : 1;
        oi.Cost_Type__c = ql.Cost_Type__c != NULL ? ql.Cost_Type__c : '';
        oi.Description = ql.RVN__c + ': ' + ql.Product2.Name;
        oi.Discount__c = ql.Discount;
        oi.Factory_Multiplier__c = ql.Factory_Multiplier__c != NULL ? ql.Factory_Multiplier__c : 1;
        oi.fxCost__c = ql.fxCost__c;
        oi.fxFactory__c = ql.fxFactory__c;
        oi.fxSales__c = ql.fxSales__c;
        
        oi.Product_Category__c = ql.Product_Category__c;
        oi.Product_Code__c = ql.Product_Code__c;
        oi.Product_Group__c = ql.Product_Group__c;
        oi.Product_Item__c = ql.Product_Item__c;
        oi.Product_Type__c = ql.Product_Type__c;
        //Replaced RVN Number with RVN as part of LUM-2016
        oi.RVN_Number__c = ql.Configuration_Product__r.RVN__c;
        oi.Sales_Code__c = ql.Sales_Code__c;
        oi.Sales_Multiplier__c = ql.Sales_Multiplier__c;
        oi.Subtotal__c = ql.Subtotal;
        oi.Tax__c = ql.Tax__c;        
        oi.Line_Number__c = ql.Line_Number__c;
        oi.QuoteLineItemId = ql.Id;
        return oi;
    }
    
     public static String deleteExistingOrderItems(List<OrderItem> oItemList){
        String message;
        //List<OrderItem> oliList = [SELECT Id from OrderItem where OrderId = :o.Id]; 
        try {
            if(!oItemList.isEmpty()){
                delete oItemList;
                message = 'Success';
            }
        }catch(Exception e){
            message = 'Error';
        }
        return message;
    }

}