force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <label>Cost Multiplier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factory_Price__c/Factory_Price__c.object-meta.xml
<CustomObject>
    <label>Factory Price</label>
    <nameField>
        <displayFormat>T1-{000000}</displayFormat>
        <label>Factory Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factory Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factory_Price__c/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsPriceList__c.field-meta.xml
<CustomField>
    <fullName>IsPriceList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPriceList</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>The Price on the Base PriceList</description>
    <inlineHelpText>The Price of Products and Services as Listed on the Product Catalog</inlineHelpText>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Minimum_Price__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Minimum Price of an Item, used for Special Prices for example Color
If Total Sales Price is less than minimum Price then use Minimum Price</description>
    <inlineHelpText>Minimum Price of an Item, used for Special Prices for example Color</inlineHelpText>
    <label>Minimum Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Quantity_per_Order__c.field-meta.xml
<CustomField>
    <fullName>Quantity_per_Order__c</fullName>
    <description>The Maximum Quantity of an Item on an Order</description>
    <inlineHelpText>The Maximum Quantity of an Item on an Order</inlineHelpText>
    <label>Quantity per Order OLD</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Transmission</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>T2-{000000}</displayFormat>
        <label>Cost Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Cost__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Cost__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>Base Price * Sales Multiplier</description>
    <inlineHelpText>Base Price</inlineHelpText>
    <label>Base Price OLD</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Factory_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Factory_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Factory Multiplier OLD</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Factory_Price__c.field-meta.xml
<CustomField>
    <fullName>Factory_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Factory Price OLD</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxCost__c.field-meta.xml
<CustomField>
    <fullName>fxCost__c</fullName>
    <description>Calculated Result of Base Price * Cost Multiplier * Quantity</description>
    <formula>IF(Cost_Multiplier__c &gt; 0,  fxUnitCost__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Line Item Cost</inlineHelpText>
    <label>fxCost</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxDiscount__c.field-meta.xml
<CustomField>
    <fullName>fxDiscount__c</fullName>
    <formula>IF(AND(UnitPrice&gt;0,fxUnitSalesPrice__c&gt;0),(1 - ( UnitPrice/fxUnitSalesPrice__c)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxDiscount</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxFactory__c.field-meta.xml
<CustomField>
    <fullName>fxFactory__c</fullName>
    <formula>IF(Factory_Multiplier__c &gt; 0, fxUnitFactoryPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxFactory</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxSales__c.field-meta.xml
<CustomField>
    <fullName>fxSales__c</fullName>
    <description>The ListPrice calculated from Base Price with a Sales Multiplier</description>
    <formula>IF( Sales_Multiplier__c &gt; 0,   fxUnitSalesPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Price on the PriceList aka List Price</inlineHelpText>
    <label>fxSales</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <inlineHelpText>List Price</inlineHelpText>
    <label>List Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Max_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Maximum Quantity of an Item per Product Group on a single Offer</inlineHelpText>
    <label>Max Quantity OLD</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Price__c</fullName>
    <inlineHelpText>Min Price</inlineHelpText>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Min_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Sales_Price__c</fullName>
    <inlineHelpText>Min Sales Price OLD</inlineHelpText>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Cost__c.field-meta.xml
<CustomField>
    <fullName>Product_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Cost</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Reference to the Product Model for this Item</description>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Margin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin__c</fullName>
    <formula>IF(Revenue__c&gt;0,(Gross_Profit__c / Revenue__c),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Margin OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Sales_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Sales Multiplier OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingSpareComponentsController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 11-21-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class PricingSpareComponentsController {
    @AuraEnabled
    public static SearchResult search(SearchFilter filters) {
        SearchResult result = new SearchResult();
        String freeText = '%' + filters.text + '%';
        Id priceBookId = filters.quote.Pricebook2Id;
        result.totalNumberOfRecords = Database.countQuery(
            'SELECT count() FROM PriceBookEntry'+
            'WHERE (PriceBook2Id = :priceBookId'+
            'AND IsActive = true'+
            'AND('+
            'Product2.ProductCode LIKE :freeText'+
            'OR Product2.Name LIKE :freeText'+
            'OR Product2.Product_Name__FI__c LIKE :freeText'+
            'OR Product2.Product_Name__EN__c LIKE :freeText'+
            'OR Product2.Product_Name__ES__c LIKE :freeText'+
            ')'
        );
        result.records = new List<SObject>();
        for(PriceBookEntry pbEntry : Database.query(
            String.join(
                new List<String>{
                    'SELECT',
                    String.join(new List<String> {
                        'Product2Id', 'Product2.Name', 'Product2.QuantityUnitOfMeasure', 'UnitPrice'
                    }, ', '),
                    'WHERE (PriceBook2Id = :priceBookId',
                    'AND IsActive = true',
                    'AND (Product2.Product_Group__c =: (\'TARVIKE\')',
                            'OR Product2.Cost_Type__c IN (\'tarvikeast\', \'tarvikealu\', \'tarvikekmp\')',
                    'AND(',
                    'Product2.ProductCode LIKE :freeText',
                    'OR Product2.Name LIKE :freeText',
                    'OR Product2.Product_Name__FI__c LIKE :freeText',
                    'OR Product2.Product_Name__EN__c LIKE :freeText',
                    'OR Product2.Product_Name__ES__c LIKE :freeText',
                    ')',
                    'LIMIT 200'
                },
                ' '
            )
        )) {
            result.records.add(new QuoteLineItem(
                Product2Id = pbEntry.Product2Id,
                Description = pbEntry.Product2.Name,
                Product2 = new Product2(Id = pbEntry.Product2Id, QuantityUnitOfMeasure = pbEntry.Product2.QuantityUnitOfMeasure),
                UnitPrice = pbEntry.UnitPrice // TODO get proper price
            ));
        }
        return result;
    }

    public class SearchFilter {
        @AuraEnabled
        public Id id { get; set; }
        @AuraEnabled
        public List<String> fields { get; set; }
        @AuraEnabled
        public String text { get; set; }
        @AuraEnabled
        public Quote quote { get; set; }
    }

    public class SearchResult {
        @AuraEnabled
        public List<SObject> records { get; set; }
        @AuraEnabled
        public Integer totalNumberOfRecords { get; set; }
    }

    public with sharing class ComponentData {
        @AuraEnabled
        public Quote quote { get; private set; }
        @AuraEnabled
        public Opportunity opportunity { get; private set; }
        @AuraEnabled
        public Boolean visible { get; private set; }
        @AuraEnabled
        public Boolean disabled { get; private set; }
        @AuraEnabled
        public List<QuoteLineItem> quoteLineItems { get; private set; }
        public ComponentData(Id recordId) {
            opportunity = PricingSummaryService.queryOpportunity(recordId);
            try {
                quote = PricingSummaryService.queryQuote(opportunity.SyncedQuoteId);
            } catch (Exception e) {
                throw new PricingSummaryService.PricingDataException('The synced quote can\'t be found');
            }
            visible = PricingSummaryService.queryPricingSummary(opportunity.Id, quote.Id) != null
                && PricingSummaryService.opportunityHasProductItems(quote.Id);
            disabled = PricingSummaryService.componentDisabled(opportunity);
            quoteLineItems = [
                SELECT
                    Id,
                    Description,
                    QuoteId,
                    Product2Id,
                    Product2.Name,
                    Product2.ProductCode,
                    Product2.Product_Group__c,
                    Product2.Cost_Category__c,
                    Product2.Cost_Type__c,
                    Product2.QuantityUnitOfMeasure,
                    Cost_Category__c,
                    Cost_Type__c,
                    toLabel(Cost_Type__c) costTypeLabel,
                    Product_Group__c,
                    toLabel(Product_Group__c) productGroupLabel,
                    Quantity,
                    List_Price__c,
                    UnitPrice,
                    ListPrice,
                    Min_Sales_Price__c,
                    Min_Price__c,
                    Transmission__c,
                    Discount,
                    Discount__c,
                    fxDiscount__c,
                    CurrencyIsoCode,
                    fxFactory__c,
                    Factory_Price__c,
                    fxCost__c,
                    Product_Cost__c,
                    fxSales__c,
                    Sales_Margin__c,
                    SubTotal,
                    TotalPrice,
                    Product_Code__c
                FROM QuoteLineItem
                WHERE QuoteId = :quote.Id 
                AND (Product2.Cost_Type__c IN ('tarvikeast', 'tarvikealu', 'tarvikekmp')
                OR Product2.Product_Group__c =: ('TARVIKE'))
                ORDER BY Product2.Product_Group__c, Product2.Product_Model__c, Product2.Cost_Type__c
            ];
        }
    }

    @AuraEnabled
    public static Product2 findProduct(String productId) {
        return [
            SELECT Name, QuantityUnitOfMeasure
            FROM Product2
            WHERE Id = :productId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static PricebookEntry findBasePrice(String productId) {
        return [
            SELECT UnitPrice
            FROM PricebookEntry
            WHERE Product2Id = :productId AND Pricebook2.isPriceList__c = true
            LIMIT 1
        ];
    }
    @AuraEnabled
    public static QuoteLineItem findPrices(String opportunityId, String productId, Decimal quantity) {
        Product2 product = findProduct(productId);
        return PricingSummaryService.findPrices(
            opportunityId,
            product.ProductCode,
            quantity,
            product.Product_Group__c,
            product.Cost_Type__c
        );
    }
    @AuraEnabled(cacheable=false)
    public static ComponentData getComponentData(Id recordId) {
        return new ComponentData(recordId);
    }

    @AuraEnabled
    public static void deleteItem(Id opportunityId, Id quoteLineItemId) {
        delete new QuoteLineItem(Id = quoteLineItemId);
        PricingController.upsertQuoteLines(opportunityId);
    }

    @AuraEnabled
    public static QuoteLineItem saveItem(Id opportunityId, QuoteLineItem quoteLineItem) {
        Opportunity opportunity = PricingSummaryService.queryOpportunity(opportunityId);
        Quote quote = PricingSummaryService.queryQuote(opportunity.SyncedQuoteId);
        QuoteLineItem oldQuoteLineItem = quoteLineItem.Id != null
            ? [
                  SELECT Product2Id
                  FROM QuoteLineItem
                  WHERE Id = :quoteLineItem.Id
                  LIMIT 1
              ]
            : null;
        if (oldQuoteLineItem != null && quoteLineItem.Product2Id != oldQuoteLineItem.Product2Id) {
            // This is needed as the Product2Id field can't be updated
            delete new QuoteLineItem(Id = quoteLineItem.Id);
            quoteLineItem.Id = null;
        }
        if (String.isBlank(quoteLineItem.Id)) {
            PriceBookEntry entry = [
                SELECT
                    Id,
                    Product2Id,
                    UnitPrice,
                    Minimum_Price__c,
                    Transmission__c,
                    Quantity_per_Order__c,
                    Product2.Product_Group__c,
                    Product2.Cost_Type__c,
                    Product2.QuantityUnitOfMeasure,
                    Product2.Name
                FROM PriceBookEntry
                WHERE PriceBook2Id = :quote.Pricebook2Id 
                AND Product2Id = :quoteLineItem.Product2Id 
                AND IsActive = TRUE
                LIMIT 1
            ];
            quoteLineItem.Product_Group__c = 'LISAHIN'; // TODO check if this is correct value
            quoteLineItem.PriceBookEntryId = entry.Id;
            quoteLineItem.Min_Price__c = entry.Minimum_Price__c;
            quoteLineItem.Max_Quantity__c = entry.Quantity_per_Order__c;
            // quoteLineItem. = entry.Product2.QuantityUnitOfMeasure;
            quoteLineItem.QuoteId = opportunity.SyncedQuoteId;
            quoteLineItem.Factory_Multiplier__c = 0;
            quoteLineItem.Cost_Multiplier__c = 0;
            quoteLineItem.Sales_Multiplier__c = 1;
            quoteLineItem.Cost_Type__c = entry.Product2.Cost_Type__c;
            quoteLineItem.Product2 = entry.Product2;
            // quoteLineItem.Cost_Category__c = ADDITIONAL_SALES_CATEGORY;
        }
        quoteLineItem.Base_Price__c = quoteLineItem.UnitPrice;
        quoteLineItem.List_Price__c = quoteLineItem.UnitPrice;
        upsert quoteLineItem;
        PricingController.upsertQuoteLines(opportunityId);
        return quoteLineItem;
    }

}