force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/BasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePrice__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/BatchPrice__c.field-meta.xml
<CustomField>
    <fullName>BatchPrice__c</fullName>
    <label>Batch Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/CostMultiplier__c.field-meta.xml
<CustomField>
    <fullName>CostMultiplier__c</fullName>
    <label>Cost Multiplier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/CostType__c.field-meta.xml
<CustomField>
    <fullName>CostType__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/DeliveryTime__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTime__c</fullName>
    <label>Delivery Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Emphasis__c.field-meta.xml
<CustomField>
    <fullName>Emphasis__c</fullName>
    <label>Emphasis</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <label>isActive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/ItemCode__c.field-meta.xml
<CustomField>
    <fullName>ItemCode__c</fullName>
    <label>Item Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/MaintoriId__c.field-meta.xml
<CustomField>
    <fullName>MaintoriId__c</fullName>
    <externalId>true</externalId>
    <label>Maintori Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/ManualProcessing__c.field-meta.xml
<CustomField>
    <fullName>ManualProcessing__c</fullName>
    <label>Manual Processing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/MinumumPrice__c.field-meta.xml
<CustomField>
    <fullName>MinumumPrice__c</fullName>
    <label>Minumum Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/SalestoriId__c.field-meta.xml
<CustomField>
    <fullName>SalestoriId__c</fullName>
    <externalId>true</externalId>
    <label>Salestori Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/SiteDiscount__c.field-meta.xml
<CustomField>
    <fullName>SiteDiscount__c</fullName>
    <label>Site Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/UnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasure__c</fullName>
    <label>Unit_Of_Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/VolumeDiscount__c.field-meta.xml
<CustomField>
    <fullName>VolumeDiscount__c</fullName>
    <label>Volume Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CostType__c.field-meta.xml
<CustomField>
    <fullName>CostType__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CostCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Sales Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasure__c</fullName>
    <formula>TEXT(QuantityUnitOfMeasure)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LumonTestBasePrices.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-04-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class LumonTestBasePrices {
    public static void setupBasePrices(){
        List<Base_Price__c> basePrices = new List<Base_Price__c>();
        Map<String,Map<String,List<String>>> productToItemMap = LumonTestVariables.productToItemMap;
        Integer i = 0;
        for (String productCode : productToItemMap.keySet() ) {
            Map<String,List<String>> costToItemMap = productToItemMap.get(productCode);           
            for (String costType : costToItemMap.keySet()) {     
                List<String> itemCodes = costToItemMap.get(costType);
                for (String itemCode : itemCodes) {  
                    i++;
                    Base_Price__c basePriceEntry = new Base_Price__c();
                    basePriceEntry.Name__c = productCode+'-'+costType+'-'+itemCode; 
                    basePriceEntry.Description__c = ''; 
                    basePriceEntry.UnitOfMeasure__c = costType == 'askuormitu' ? 'h' :'pcs';
                    basePriceEntry.BasePrice__c = 10;
                    //basePriceEntry.MaintoriId__c = itemCode; 
                    //basePriceEntry.isActive__c = true;
                    basePriceEntry.ProductCode__c = productCode;
                    basePriceEntry.CostType__c =costType;
                    basePriceEntry.itemCode__c = itemCode;                 
                    basePriceEntry.SalestoriId__c = i;
                    basePriceEntry.MinumumPrice__c = 0;  
                    basePriceEntry.BatchPrice__c = 0;                 
                    //basePriceEntry.ManualProcessing__c = false;
                    basePriceEntry.DeliveryTime__c = 1;
                    basePriceEntry.CostMultiplier__c = 0;
                    basePriceEntry.Commission__c = 100;                   
                    basePriceEntry.VolumeDiscount__c = 0;
                    //basePriceEntry.Emphasis__c;
                    //basePriceEntry.Variant__c;                    
                    basePriceEntry.SiteDiscount__c = 0;
                    basePrices.add(basePriceEntry);
                }
            }
        }
        insert basePrices;
    }
    public static void setupBasePriceData(){
        setupBasePrices();
        List<Base_Price__c> basePrices = LumonTestVariables.basePrices;
        System.debug('--- LumonTestBasePrices - Inserted '+basePrices.size()+' Base Prices'); 
    }  
    @TestSetup
    static void prepareData() {
        List<Product2> products = LumonTestVariables.products;
        Test.startTest();
        if(products?.size()>0){
            System.debug('--- LumonTestBasePrices - Using Existing Products');
        } else {
            LumonTestProducts.setupProductData();
        }
        Test.stopTest();
    }
    @IsTest
    static void setupBasePriceDataTest(){
        String testResult;
        Test.startTest();
        Try {
            setupBasePriceData();
            testResult = 'successfully inserted Base Prices';
        } catch (exception e){
            testResult = 'Error when inserting Base Prices: '+e.getMessage();
        }
        Test.stopTest();
        List<Base_Price__c> basePrices = LumonTestVariables.basePrices;
        System.debug('--- LumonTestPriceMultipliers - result: '+testResult);
        System.AssertNotEquals(true, testResult.contains('Error'));
        System.AssertNotEquals(0, basePrices.size(),'Expected Base Prices to be Inserted');
    }
}