force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Batch_Price__c.field-meta.xml
<CustomField>
    <fullName>Batch_Price__c</fullName>
    <label>Batch Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <label>Cost Multiplier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <label>Delivery Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Emphasis__c.field-meta.xml
<CustomField>
    <fullName>Emphasis__c</fullName>
    <label>Emphasis</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <label>isActive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Maintori_Id__c.field-meta.xml
<CustomField>
    <fullName>Maintori_Id__c</fullName>
    <externalId>true</externalId>
    <label>Maintori Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Manual_Processing__c.field-meta.xml
<CustomField>
    <fullName>Manual_Processing__c</fullName>
    <label>Manual Processing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Minumum_Price__c.field-meta.xml
<CustomField>
    <fullName>Minumum_Price__c</fullName>
    <label>Minumum Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Salestori_Id__c.field-meta.xml
<CustomField>
    <fullName>Salestori_Id__c</fullName>
    <externalId>true</externalId>
    <label>Salestori Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Site_Discount__c.field-meta.xml
<CustomField>
    <fullName>Site_Discount__c</fullName>
    <label>Site Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit_Of_Measure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Volume_Discount__c.field-meta.xml
<CustomField>
    <fullName>Volume_Discount__c</fullName>
    <label>Volume Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>The Price on the Base PriceList</description>
    <inlineHelpText>The Price of Products and Services as Listed on the Product Catalog</inlineHelpText>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PriceListController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-11-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class PriceListController {
    @AuraEnabled(cacheable=true)
    public static List<Base_Price__c> getBasePrices() {
        // Populate map from SOQL query on PricebookEntry
        List<Base_Price__c> basePrices = ([SELECT  Id,
                                                        CurrencyIsoCode, 
                                                        Item_Code__c, 
                                                        Batch_Price__c, 
                                                        Salestori_Id__c, 
                                                        Minumum_Price__c, 
                                                        Product_Code__c, 
                                                        Manual_Processing__c, 
                                                        Delivery_Time__c, 
                                                        Cost_Multiplier__c, 
                                                        Commission__c, 
                                                        Base_Price__c, 
                                                        Volume_Discount__c, 
                                                        Emphasis__c, 
                                                        Variant__c, 
                                                        IsActive__c, 
                                                        Cost_Type__c, 
                                                        Name__c, 
                                                        Description__c, 
                                                        Unit_Of_Measure__c, 
                                                        Maintori_Id__c, 
                                                        Site_Discount__c 
                                                FROM Base_Price__c 
                                            ]);
        System.debug('--- Base Price Entries: '+basePrices);                                         
        return basePrices;
    }   
    @AuraEnabled(cacheable=true)
    public static Map<String,Base_Price__c> getBasePriceToItemMap() {
        Map<String,Base_Price__c> basePriceToItemMap = new  Map<String,Base_Price__c>();
        List<Base_Price__c> basePrices = getBasePrices();
        System.debug('--- PriceListController - '+basePrices?.size()+' Prices in List');
        for (Base_Price__c basePriceEntry : basePrices){
            String productCode = basePriceEntry.product_Code__c;
            String itemCode = basePriceEntry.item_Code__c;
            basePriceToItemMap.put(productCode+'-'+itemCode, basePriceEntry);
        }
        System.debug('--- PriceListController - '+basePriceToItemMap?.keySet().size()+' Keys in Map');
        return basePriceToItemMap;
    }
}