force-app/main/default/objects/Base_Price__c/Base_Price__c.object-meta.xml
<CustomObject>
    <description>Lookup Table for Item based Pricing</description>
    <label>Base Price</label>
    <nameField>
        <label>Base Price Entry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Price__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Base_Price__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <description>The Price on the Base PriceList</description>
    <inlineHelpText>The Price of Products and Services as Listed on the Product Catalog</inlineHelpText>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Minimum_Price__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Minimum Price of an Item, used for Special Prices for example Color
If Total Sales Price is less than minimum Price then use Minimum Price</description>
    <inlineHelpText>Minimum Price of an Item, used for Special Prices for example Color</inlineHelpText>
    <label>Minimum Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Quantity_per_Order__c.field-meta.xml
<CustomField>
    <fullName>Quantity_per_Order__c</fullName>
    <description>The Maximum Quantity of an Item on an Order</description>
    <inlineHelpText>The Maximum Quantity of an Item on an Order</inlineHelpText>
    <label>Quantity per Order OLD</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Transmission</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/LumonTestPricebooks.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-09-2023
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public with sharing class LumonTestPricebooks {
	@TestVisible private static Id pricebookId{
        get{
            return Test.getStandardPricebookId();
        }
    }
    @TestVisible private static List<PricebookEntry> pricebookEntries{
        get{
            return [SELECT Id,Name,Product2Id,IsActive FROM PricebookEntry WHERE Pricebook2Id =: pricebookId];
        }
    }
    public static void setupPrices(){      
        List<Product2> products = [SELECT Id, Name,ProductCode,Product_Group__c,Cost_Type__c,IsActive FROM Product2];
        for (Product2 p : products) {
            if (p.ProductCode != p.Product_Group__c) {
            	String setting = p.ProductCode.remove(p.Product_Group__c+'-');
            	setupPricebookEntry(p.Id,setting);
            } else {
                setupPricebookEntry(p.Id,'GROUP');
            }
        }
    }
    public static void setupPricebookEntry(Id productId){
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId,
                                                Product2Id=productId,
                                                UnitPrice=5,
                                                IsActive=True,
                                                CurrencyIsoCode = 'EUR',
                                                Base_Price__c=5);
        insert pbe;
    }
    public static void setupPricebookEntry(Id productId,String setting){
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId,
                                                Product2Id=productId,
                                                UnitPrice=5,
                                                IsActive=True,
                                                CurrencyIsoCode = 'EUR',
                                                Base_Price__c=5);
        switch on setting {
            when 'GROUP' {
                pbe.Base_Price__c=0;
                pbe.UnitPrice=0;
            }
            when 'MIN' {
                pbe.Minimum_Price__c = 500;
            }
            when 'MAX' {
                pbe.Quantity_per_Order__c = 1;
            }
            when 'TRANS' {
                pbe.Transmission__c = 0;
            }
        }        
        insert pbe;
    }
    public static void setupPricebookEntries(){
        List<Product2> products = [SELECT Id,Name,ProductCode,IsActive FROM Product2];
        List<Id> productIds = new List<Id>(new Map<Id, Product2>(products).keySet()); 
        setupPricebookEntries(productIds);
    }
    public static void setupPricebookEntries(List<Id> productIds){
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        for (Integer i = 0; i<productIds.size();i++) {
            Integer counter= i+1;
            Decimal basePrice = (counter)*1;
            Decimal unitPrice = (counter)*10;
            PricebookEntry pbe = new PricebookEntry(Pricebook2Id=pricebookId,
                                                    Product2Id=productIds[i],
                                                    UnitPrice=unitPrice,
                                                    IsActive=True,
                                                    CurrencyIsoCode = 'EUR',
                                                    Base_Price__c=basePrice,
                                                    Minimum_Price__c = 0,
                                                    Quantity_per_Order__c = 0,
                                                    Transmission__c = 100
                                                   );
            pricebookEntries.add(pbe);
        }
        insert pricebookEntries;
    }
    @IsTest
    static void setupPricesTest(){
        String testResult;
        LumonTestDataFactory.setupProducts();
        Test.startTest();
        Try {
            LumonTestDataFactory.setupPricebookEntries();
            testResult = 'successfully inserted Prices';
            System.debug('--- setupPricesTest: '+pricebookEntries);
        } catch (exception e){
            testResult = 'error when inserting Prices: '+e.getMessage();
        }
        Test.stopTest();
        System.debug('--- setupPricesTest: '+testResult);
        
        System.AssertNotEquals(true, testResult.contains('error'));
    }
}