force-app/main/default/objects/Asset/fields/Asset_Warranty__c.field-meta.xml
<CustomField>
    <fullName>Asset_Warranty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Warranty OLD</label>
    <referenceTo>AssetWarranty</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Assets_related_notes__c.field-meta.xml
<CustomField>
    <fullName>Assets_related_notes__c</fullName>
    <description>Short notes regarding the customer&apos;s assets.</description>
    <formula>Account.Assets_related_notes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Short notes regarding the customer&apos;s assets.</inlineHelpText>
    <label>Assets related notes OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Combination_name__c.field-meta.xml
<CustomField>
    <fullName>Combination_name__c</fullName>
    <description>Used to provide more details in Asset selection in Reclamation/Warranty Case creation from Account.</description>
    <formula>Name  &amp; &quot; (Plan: &quot; &amp; Configuration_Product__r.Configuration__r.Plan_Name__c &amp; &quot;, RVN: &quot; &amp;  SerialNumber &amp; &quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Combination name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Configuration Product related to the WOLI.</description>
    <label>Configuration Product OLD</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation order.</description>
    <label>Order OLD</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ServiceTerritory__c.field-meta.xml
<CustomField>
    <fullName>ServiceTerritory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Service Territory which handled this Asset.</description>
    <inlineHelpText>Service Territory which handled this Asset.</inlineHelpText>
    <label>Service Territory OLD</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates the asset type. E.g. for Reclamation there is different handling in automation. 
Automation sets this when asset gets created.</description>
    <label>Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Normal installation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AssetController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-25-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class AssetController {
    /**** Methods for Finding Asset Entries ****/
    @AuraEnabled(cacheable=false)
    public static Asset getAsset(Id assetId) {
        // Populate List from SOQL query on Asset
        List<Id> assetIds = new List<Id>();
        assetIds.add(assetId);
        System.debug('--- AssetController - Get Asset with Id '+assetId); 
        List<Asset> assets =  getAssets(assetIds);  
        Asset asset = assets[0];
        System.debug('--- AssetController - Asset: '+asset.Name); 
        return asset;  
    }
    @AuraEnabled(cacheable=false)
    public static Asset getAssetByNumber(String assetNumber) {
        // Populate List from SOQL query on Asset
        Id assetId = [SELECT Id FROM Asset WHERE SerialNumber =: assetNumber LIMIT 1]?.Id; 
        List<Id> assetIds = new List<Id>();
        assetIds.add(assetId);
        Asset asset = new Asset();
        System.debug('--- AssetController - Get Customer with Id '+assetId); 
        List<Asset> assets =  getAssets(assetIds); 
        if  (assets?.size()>0) {
            asset = assets[0];
            System.debug('--- AssetController - Asset: '+asset.Name); 
        }        
        return asset;
    }
    @AuraEnabled(cacheable=false)
    public static List<Asset> getAssetsByAccount(Id accountId) {
        // Populate List from SOQL query on Asset
        List<Asset> customerAssets = new List<Asset>();
        customerAssets = getAssets(new List<Id> {accountId});
        return customerAssets;
    }
    @AuraEnabled(cacheable=false)
    public static List<Asset> getAssets(List<Id> recordIds) {
        // Populate List from SOQL query on Asset
        System.debug('--- AssetController - Get Assets'); 
        List<Asset> assets = ([  SELECT Id,Name, 
                                    OwnerId, LocationId, 
                                    ContactId, AccountId, 
                                    ParentId, RootAssetId, 
                                    Product2Id, ProductCode, 
                                    ProductFamily, ProductDescription, 
                                    IsCompetitorProduct,                                    
                                    CreatedDate, CreatedById, 
                                    LastModifiedDate, LastModifiedById, 
                                    SystemModstamp, IsDeleted, 
                                    CurrencyIsoCode, SerialNumber, 
                                    InstallDate, ManufactureDate, 
                                    PurchaseDate, UsageEndDate,
                                    Status, 
                                    StatusReason,                                     
                                    Uuid, ExternalIdentifier, 
                                    Price, Quantity, 
                                    Description, 
                                    AssetProvidedById, AssetServicedById, 
                                    IsInternal, AssetLevel, StockKeepingUnit, 
                                    Address,
                                    Street, City, State, PostalCode, 
                                    StateCode, Country, CountryCode, 
                                    Latitude, Longitude, GeocodeAccuracy 
                                    //Assets_related_notes__c, Configuration_Product__c, Order__c, ServiceTerritory__c, Type__c, Asset_Warranty__c, Combination_name__c          
                                    FROM Asset 
                                    WHERE Id IN: recordIds
                                    OR AccountId IN: recordIds
                                    OR ParentId IN: recordIds
                                    OR Product2Id IN: recordIds]);  
        System.debug('--- AssetController - Assets: '+assets.size()); 
        return assets;  
    }
}