force-app/main/default/objects/Asset/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>BuildingAssets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Configuration Product related to the WOLI.</description>
    <label>Configuration Product OLD</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Building_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Address__c</fullName>
    <label>Building Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date_Calc__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date_Calc__c</fullName>
    <formula>IF(ISBLANK( Confirmed_Delivery_Date__c ) ,  &quot;Est : &quot; &amp;  TEXT( Delivery_Date__c ) , TEXT(Confirmed_Delivery_Date__c ))</formula>
    <label>Delivery Date Calc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Installation_Comments_for_Customer__c.field-meta.xml
<CustomField>
    <fullName>Installation_Comments_for_Customer__c</fullName>
    <description>To be filled by the Installation manager ( e.g: Please clear the balcony before the glazing installation)</description>
    <label>Installation Comments for Customer OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Installation_Time_Calc__c.field-meta.xml
<CustomField>
    <fullName>Installation_Time_Calc__c</fullName>
    <formula>IF(ISBLANK( Confirmed_installation_time__c ) , &quot;Est : &quot; &amp; TEXT(Preliminary_installation_time__c ) ,  TEXT(Confirmed_installation_time__c))</formula>
    <label>Installation Time Calc OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Net_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_Price__c</fullName>
    <description>Net Total Price (incl. Tax)</description>
    <formula>Gross_Total_Price__c +  Tax_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Net Total Price (incl. Tax) OLD</inlineHelpText>
    <label>Net Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Comments_for_Customer__c.field-meta.xml
<CustomField>
    <fullName>Order_Comments_for_Customer__c</fullName>
    <description>To be filled by the Sales person while agreeing on something with the customer during customer visit (e.g. The price does not include xxx)</description>
    <label>Order Comments for Customer OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Reference to the Product Group for this Item</description>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LP_MainControllerUtil.cls
public virtual class LP_MainControllerUtil {

	public static String STATUS_SUCCESS = 'success';
	public static String STATUS_ERROR = 'error';
	public class ApexResult {
		@AuraEnabled
		public Object result;
		@AuraEnabled
		public String status;
		@AuraEnabled
		public String errorMessage;

		public ApexResult() {
			this(null, STATUS_SUCCESS, null);
		}
		public ApexResult(Exception e) {
			this(null, STATUS_ERROR, e.getTypeName() == 'System.DmlException' ? e.getDmlMessage(0) : e.getMessage());
		}

		public ApexResult(Object result, String status, String errorMessage) {
			this.result = result;
			this.status = status;
			this.errorMessage = errorMessage;
		}
	}

	public class OrderDetail{
		@AuraEnabled public String product;
		@AuraEnabled public String installDate;
		@AuraEnabled public String installAddressStreet;
		@AuraEnabled public String installAddressZipCityState;
		@AuraEnabled public Decimal totalCost;
		@AuraEnabled public String orderNo;
		@AuraEnabled public String orderContractSTR;
		@AuraEnabled public String currencyIsoCode;
		@AuraEnabled public List<OrderDetailProduct> odProducts = new List<OrderDetailProduct>();
	}

	public class OrderDetailProduct{
		public String name;
		public Date warrantyStart;
		public Date warrantyEnd;
	}

	public class OrderWrapper{
		@AuraEnabled public String orderTabLabel;
		@AuraEnabled public String orderNo;
		@AuraEnabled public String orderId;
		@AuraEnabled public String opportunityId;
		@AuraEnabled public String installAddressStreet;
		@AuraEnabled public String installAddressZipCityState;
		@AuraEnabled public String orderComment;
		@AuraEnabled public String dynamicContentCss = 'os-dynamic-content';
		@AuraEnabled public String toggleButtonCss = 'toggle-content-button';
		@AuraEnabled public String orderDatesProgressSTR;
		@AuraEnabled public String installationDataSTR;
		@AuraEnabled public String orderContractSTR;
		@AuraEnabled public List<OrderProduct> orderProducts;
		@AuraEnabled public String currencyIsoCode;
		@AuraEnabled public Decimal totalCost;
	}

	public class OrderProduct{
		public String productName;
		public String productImageName;
		//public String productDimensions;
	}

	public class OrderDatesProgress{
		public Datetime orderDate;
		public String deliveryDate;
		public String installDate;
		public OrderDatesProgress(Datetime orderDate, String deliveryDate, String installDate){
			this.orderDate = orderDate;
			this.deliveryDate = deliveryDate;
			this.installDate = installDate;
		}
	}

	public class UpcomingInstallation{
		public String iDate;
		public String iComment;
	}

	public class OrderContract{
		@AuraEnabled public Date signedDate;
		@AuraEnabled public String orderId;
		@AuraEnabled public List<SignedDocument> signedDocuments;
	}

	public class SignedDocument{
		public String name;
		public String downloadUrl;
		public SignedDocument(String name, String downloadUrl){
			this.name = name;
			this.downloadUrl = downloadUrl;
		}
	}

	public class ContactPerson{
		@AuraEnabled public String firstName;
		@AuraEnabled public String lastName;
		@AuraEnabled public String position;
		@AuraEnabled public String email;
		@AuraEnabled public String emailHref;
		@AuraEnabled public String phone;
		@AuraEnabled public String phoneHref;
		@AuraEnabled public String profileImgUrl;
		public ContactPerson(String firstName, String lastName, String position, String email, String emailHref, String phone, String phoneHref, String profileImgUrl){
			this.firstName = firstName;
			this.lastName = lastName;
			this.position = position;
			this.email = email;
			this.emailHref = 'mailto:' + emailHref;
			this.phone = phone;
			this.phoneHref = 'tel:' + phoneHref;
			this.profileImgUrl = profileImgUrl;
		}
	}

	/*Portal Util Methods*/
	public static String getOrdersContractSTR(Date customerSignDate, String oppId){
		OrderContract oContract = new OrderContract();
		oContract.signedDate = customerSignDate;
		oContract.signedDocuments = getContractDownloadLinks(oppId);
		return JSON.serialize(oContract);
	}

	public static List<SignedDocument> getContractDownloadLinks(String oppId){
		List<ContentVersion> contentVersions = new List<ContentVersion>();
		List<ContentDocumentLink> cdLinks = [
			SELECT
				ContentDocumentId,
				LinkedEntityId
			FROM ContentDocumentLink
			WHERE LinkedEntityId =: oppId
			AND  ContentDocument.FileExtension = 'pdf'
			AND ContentDocument.Title LIKE '%signed%'
			LIMIT 50
		];
		if(!cdLinks.isEmpty()) {
			contentVersions = [
				SELECT
					Id,
					Title,
					ContentDocumentId
				FROM ContentVersion
				WHERE ContentDocumentId = :cdLinks[0].ContentDocumentId
				LIMIT 50
			];
		}
		List<SignedDocument> signedDocs = new List<SignedDocument>();
		if(!contentVersions.isEmpty()){
			for(ContentVersion cV : contentVersions) {
				String baseURL = Url.getOrgDomainUrl().toExternalForm();
				String downloadLink = baseURL + '/sfc/servlet.shepherd/version/download/' + cV.Id;
				signedDocs.add(new SignedDocument(cV.Title, downloadLink));

			}
		}
		return signedDocs;
	}

	public static String getInstallAddressZipCityState(Address address){
		String iAddress = '';
		if(address?.postalCode != null){
			iAddress +=  address.postalCode + ', ';
		}
		if(address?.city != null){
			iAddress +=  address.city + ', ';
		}
		if(address?.state != null){
			iAddress +=  address.state + ', ';
		}
		if(address?.country != null){
			iAddress += address.country;
		}
		return iAddress;
	}

	public static List<OrderDetailProduct> createOrderDetailProducts(List<OrderItem> orderItems, List<Entitlement> entitlements){
		List<OrderDetailProduct> orderProducts = new List<OrderDetailProduct>();
		Set<String> alreadyAddedProduct = new Set<String>();
		for(OrderItem oItem : orderItems){
			if(!alreadyAddedProduct.contains(oItem.Product_Group__c)){
				alreadyAddedProduct.add(oItem.Product_Group__c);
				OrderDetailProduct odProduct = createOrderDetailProduct(oItem.Product_Group__c, entitlements);
				orderProducts.add(odProduct);
			}
		}
		return orderProducts;
	}

	private static OrderDetailProduct createOrderDetailProduct(String productName, List<Entitlement> entitlements){
		OrderDetailProduct odProduct = new OrderDetailProduct();
		odProduct.name = productName;
		if(!entitlements.isEmpty()){
			for(Entitlement e : entitlements){
				if(e.Asset.Configuration_Product__r.Name == productName){
					odProduct.warrantyStart = e.StartDate;
					odProduct.warrantyEnd = e.EndDate;
					break;
				}
			}
		}
		return odProduct;
	}

	/*SOQL Methods*/
	public static List<Order> queryOrder(String orderId){
		return [
			SELECT
				OpportunityId,
				Opportunity.Installation_Time_Calc__c,
				Opportunity.Building__r.Building_Address__c,
				Opportunity.Net_Total_Price__c,
				OrderNumber,
				Contract.CustomerSignedDate,
				CurrencyIsoCode
			FROM Order
			WHERE Id =: orderId
			LIMIT 1
		];
	}
	public static List<Entitlement> queryEntitlement(String assetId){
		return [
			SELECT
				StartDate,
				EndDate,
				Asset.Configuration_Product__r.Name
			FROM Entitlement
			WHERE AssetId =: assetId
			LIMIT 1
		];
	}
	public static List<Asset> queryAssets(String oppId){
		return [
			SELECT
				Name
			FROM Asset
			WHERE Id IN (
				SELECT
					AssetId
				FROM WorkOrder
				WHERE Opportunity__c =: oppId)
			LIMIT 1
		];
	}
	public static List<OrderItem> queryOrderItems(String orderId){
		return [
			SELECT
				tolabel(Product_Group__c)
			FROM OrderItem
			WHERE OrderId =: orderId
			LIMIT 500
		];
	}
	public static List<Order> queryOrders(String accId){
		return [
			SELECT
				Id,
				OpportunityId,
				Opportunity.Installation_Comments_for_Customer__c,
				Opportunity.Order_Comments_for_Customer__c,
				Opportunity.Delivery_Date_Calc__c,
				Opportunity.Installation_Time_Calc__c,
				Opportunity.Building__r.Building_Address__c,
				Opportunity.Net_Total_Price__c,
				Contract.CustomerSignedDate,
				OrderNumber,
				CreatedDate,
				CurrencyIsoCode
			FROM Order
			WHERE IsDeleted = FALSE
			AND AccountId =: accId
			ORDER BY CreatedDate DESC
			LIMIT 100
		];
	}
	public static List<Account> fetchAccount(String contactId){
		return [
			SELECT
				Id
			FROM Account
			WHERE IsPersonAccount = TRUE
			AND IsCustomerPortal = TRUE
			AND PersonContactId =: contactId
			LIMIT 1
		];
	}
}