force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_Attribute__c</fullName>
    <description>Attribute to Identify the Type of Business</description>
    <formula>Text(Business_Type__c)</formula>
    <inlineHelpText>Attribute to Identify the Type of Business e.g. Consumer, Reseller, Project</inlineHelpText>
    <label>Business Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Account Billing Country)</description>
    <formula>TEXT( Account.BillingCountryCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Level 3 Classification based on District</description>
    <inlineHelpText>Level 3 Classification based on District</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District_Attribute__c.field-meta.xml
<CustomField>
    <fullName>District_Attribute__c</fullName>
    <formula>Account.District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Opportunities (Office)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Organization_Attribute__c</fullName>
    <description>Level 1 Classification based on Organization</description>
    <formula>Owner.Organization_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 1 Classification based on Organization</inlineHelpText>
    <label>Organization Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Owner_Profit_Center__c</fullName>
    <description>Level 4 Classification based on Profit Center of the Owner</description>
    <formula>Owner.Profit_Center_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 4 Classification based on Profit Center of the Owner</inlineHelpText>
    <label>Owner Profit Center OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/Pricing_Summary__c.object-meta.xml
<CustomObject>
    <label>Pricing Summary</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Pricing Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Summaries</relationshipLabel>
    <relationshipName>Pricing_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>L2 Business Type - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>PricingSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>L1 Country - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>L3 District - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Pricing Summaries</relationshipLabel>
    <relationshipName>Pricing_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Pricing Summaries</relationshipLabel>
    <relationshipName>Pricing_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>PricingSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>L0 Organization - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <description>L4 Profit Center - Lookup Attribute for Factory Price, Product Cost and Sales Price</description>
    <inlineHelpText>Lookup Attribute for Factory Price, Product Cost and Sales Price</inlineHelpText>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>PricingSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Sales_Margin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin__c</fullName>
    <label>Sales Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Price__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Summary__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to User to Control Visibility</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pricing_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Price__c/Sales_Price__c.object-meta.xml
<CustomObject>
    <label>Sales Price</label>
    <nameField>
        <displayFormat>T3-{000000}</displayFormat>
        <label>Sales Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Price__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Espoo</fullName>
            </value>
            <value>
                <fullName>Helsinki</fullName>
            </value>
            <value>
                <fullName>Kuopio</fullName>
            </value>
            <value>
                <fullName>Kouvola</fullName>
            </value>
            <value>
                <fullName>Lahti</fullName>
            </value>
            <value>
                <fullName>Vantaa</fullName>
            </value>
            <value>
                <fullName>Kempele</fullName>
            </value>
            <value>
                <fullName>Pori</fullName>
            </value>
            <value>
                <fullName>Raisio</fullName>
            </value>
            <value>
                <fullName>Seinäjoki</fullName>
            </value>
            <value>
                <fullName>Tampere</fullName>
            </value>
            <value>
                <fullName>Vaasa</fullName>
            </value>
            <value>
                <fullName>Vantaa East</fullName>
            </value>
            <value>
                <fullName>Vantaa West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Price__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FI</fullName>
        <label>Finland</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <label>Sweden</label>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
        <label>Norway</label>
    </customValue>
    <customValue>
        <fullName>DK</fullName>
        <label>Denmark</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
        <label>Netherlands</label>
    </customValue>
    <masterLabel>Lumon Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PricingSummaryController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 03-18-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class PricingSummaryController {
    @AuraEnabled(cacheable=true)
    public static Pricing_Summary__c getPricingSummary(Id recordId) {
        Pricing_Summary__c summary = New Pricing_Summary__c();    
        List<Pricing_Summary__c> summaries = New List<Pricing_Summary__c>(); 
        List<Id> recordIds = new List<Id>();
        recordIds.add(recordId);
        summaries = getPricingSummaries(recordIds);
        if (summaries?.size()>0){
            summary = summaries[0];
        }
        return summary;
    } 
    @AuraEnabled(cacheable=true)
    public static List<Pricing_Summary__c> getPricingSummaries(List<Id> recordIds) {
        // Populate map from SOQL query on Product2
        List<Pricing_Summary__c> summaries = ([SELECT  Id, 
                                                        Account__c,
                                                        Contract__c,
                                                        Opportunity__c,
                                                        Quote__c,
                                                        Organization__c,
                                                        Country_Code__c,
                                                        District__c,
                                                        Profit_Center__c,
                                                        Office__c,
                                                        Sales_Margin__c,
                                                        Sales_Price__c 
                                                FROM Pricing_Summary__c 
                                                WHERE Id IN:recordIds
                                                OR Opportunity__c IN: recordIds
                                                ]);
        System.debug('--- PricingSummaryController - Summary Record Count : '+summaries.size());
        return summaries;
    } 

    @AuraEnabled(cacheable=false)
    public static Id createPricingSummary(Id recordId) {
        Id summaryId;
        String flowSummaryId;
        Map<String, Object> params = new Map<String, Object>{
            'recordId' => recordId
        };
        // Create Pricing Summary if none exists using a Flow
        Flow.Interview.Assign_Summary_SubFlow summaryFlow = new Flow.Interview.Assign_Summary_SubFlow(params);
        summaryFlow.start();
        flowSummaryId = (String)summaryFlow.getvariableValue('pricingSummaryId');
        if (String.isEmpty(flowSummaryId)) {
            throw new PricingSummaryService.PricingDataException('Unable to create Pricing Summary');
        } else {
            summaryId = (Id)flowSummaryId;
            System.debug('--- PricingSummaryController - created summary: '+summaryId);
        }
        return summaryId;
    }
    @AuraEnabled(cacheable=false)
        public static Id upsertPricingSummary(Id opportunityId) {
        Opportunity opportunityRecord = new Opportunity();
        Pricing_Summary__c pricingSummaryExisting = new Pricing_Summary__c();
        Pricing_Summary__c pricingSummaryToUpsert = new Pricing_Summary__c();
        Id summaryId;
        // Check for Existing Summary
        if (String.isNotBlank(opportunityId)){
            opportunityRecord = OpportunityController.getOpportunityRecord(opportunityId);
            pricingSummaryExisting = getPricingSummary(opportunityId);
        }
        // Prepare Summary to Update
        if (String.isNotBlank(pricingSummaryExisting?.Id)){
            pricingSummaryToUpsert.Id = pricingSummaryExisting?.Id;
            pricingSummaryToUpsert.Sales_Price__c = pricingSummaryExisting?.Sales_Price__c;
        } else {
            pricingSummaryToUpsert.Opportunity__c = opportunityRecord?.Id; // Related Record
        }
            pricingSummaryToUpsert.Organization__c = opportunityRecord?.Organization_Attribute__c; // Related Record
            pricingSummaryToUpsert.Country_Code__c = opportunityRecord?.Country_Attribute__c; // Related Record
            pricingSummaryToUpsert.Business_Type__c = opportunityRecord?.Business_Type_Attribute__c;
            pricingSummaryToUpsert.District__c = opportunityRecord?.District_Attribute__c; // Related Record
            pricingSummaryToUpsert.Profit_Center__c = opportunityRecord?.Owner_Profit_Center__c; // Related Record
            //pricingSummaryToUpsert.Office__c = opportunityRecord.Office__c; // Related Record
            pricingSummaryToUpsert.User__c = opportunityRecord?.OwnerId;// Related Record
            pricingSummaryToUpsert.Account__c = opportunityRecord?.AccountId; // Related Record
            pricingSummaryToUpsert.Quote__c = opportunityRecord?.SyncedQuoteId; // Related Record
            pricingSummaryToUpsert.Order__c = opportunityRecord?.Order__c; // Related Record
            pricingSummaryToUpsert.Contract__c = opportunityRecord?.contractId; // Related Record
            pricingSummaryToUpsert.currencyIsoCode = opportunityRecord?.CurrencyIsoCode;
            pricingSummaryToUpsert.pricebookId__c = opportunityRecord?.Pricebook2Id;
        try {
            upsert (pricingSummaryToUpsert);
            summaryId = pricingSummaryToUpsert.Id;
            System.debug('--- Pricing Summary '+pricingSummaryToUpsert.Id+' Created or Updated');
        } catch(DmlException e) {
            System.debug('Exception on Pricing Summary Upsert: ' + e.getMessage());
        }
        return summaryId;
    }
}