force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Installation Address Country)</description>
    <formula>TEXT(OfficeAddress__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenterAttribute__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenterAttribute__c</fullName>
    <formula>TEXT( ProfitCenter__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Center Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/AD_Manager_Id__c.field-meta.xml
<CustomField>
    <fullName>AD_Manager_Id__c</fullName>
    <description>Field used by AzureAD to populate MepcoManager Id</description>
    <label>AD Manager Id OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/AD_Office__c.field-meta.xml
<CustomField>
    <fullName>AD_Office__c</fullName>
    <description>User head office, with unique identifier coming from Mepco</description>
    <inlineHelpText>User head office, with unique identifier coming from Mepco</inlineHelpText>
    <label>AD Office</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/AD_Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>AD_Profit_Center__c</fullName>
    <label>AD Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_AD_Profit_Center_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/AD_Short_Username__c.field-meta.xml
<CustomField>
    <fullName>AD_Short_Username__c</fullName>
    <description>AD Short Username</description>
    <inlineHelpText>AD Short Username OLD</inlineHelpText>
    <label>AD Short Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <formula>TEXT(CountryCode)</formula>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/DistrictAttribute__c.field-meta.xml
<CustomField>
    <fullName>DistrictAttribute__c</fullName>
    <formula>TEXT(District__c)</formula>
    <label>District Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Offices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/OfficeAttribute__c.field-meta.xml
<CustomField>
    <fullName>OfficeAttribute__c</fullName>
    <formula>TEXT(Office__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/OrganizationAttribute__c.field-meta.xml
<CustomField>
    <fullName>OrganizationAttribute__c</fullName>
    <formula>TEXT(Organization__c)</formula>
    <label>Organization Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ProfitCenterAttribute__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenterAttribute__c</fullName>
    <formula>TEXT(ProfitCenter__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Center Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/UserController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-05-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class UserController {
    @AuraEnabled(cacheable=false)
    public static User getUser(Id userId) {
        // Populate List from SOQL query on User
        List<Id> userIds = new List<Id>();
        userIds.add(userId);
        List<User> users =  getUsers(userIds);  
        User user = users[0];
        System.debug('--- UserController - User: '+user.Name); 
        return user;  
    }
    @AuraEnabled(cacheable=false)
    public static User getUserByName(String userShortName) {
        // Populate List from SOQL query on User
        Id userId = [SELECT Id FROM User WHERE AD_Short_Username__c =: userShortName LIMIT 1]?.Id; 
        List<Id> userIds = new List<Id>();
        userIds.add(userId);
        User user = new User();
        List<User> users =  getUsers(userIds); 
        if  (users?.size()>0) {
            user = users[0];
            System.debug('--- UserController - User: '+user.Name); 
        }        
        return user;
    }
    @AuraEnabled(cacheable=false)
    public static List<User> getUsers(List<Id> UserIds) {
        // Populate List from SOQL query on User
        System.debug('--- UserController - Get Users'); 
        List<User> users = ([  SELECT  Id,Name,
                                        AD_Short_Username__c, 
                                        AD_Manager_Id__c, 
                                        AD_Profit_Center__c, 
                                        AD_Office__c,                                        
                                        UserName,Email,
                                        UserRoleId, UserRole.DeveloperName,
                                        ProfileId, Profile.Name,
                                        IsActive, 
                                        Organization__c, OrganizationAttribute__c,
                                        CountryCode, CountryAttribute__c,
                                        District__c, DistrictAttribute__c, 
                                        ProfitCenter__c, ProfitCenterAttribute__c,  
                                        Office__c, OfficeAttribute__c                     
                                    FROM User 
                                    WHERE Id IN: userIds
                                    AND IsActive = true]);  
        System.debug('--- Users: '+users.size()); 
        return users;  
    }
}