force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Offices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LumonTestAdmin.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public with sharing class LumonTestAdmin {
    public class CustomException extends Exception {}
    @TestVisible public static Id adminProfileId{
        get{
            return [SELECT Id FROM Profile WHERE Name='System Administrator']?.Id;
        }
    }
    @TestVisible public static User adminUser{
        get{
            return  [SELECT Id, Name, FirstName, LastName,
                            ProfileId, Profile.Name, 
                            UserName, UserRoleId,UserRole.Name, 
                            Country, Organization__c, ProfitCenter__c, District__c, Office__c 
                     FROM User WHERE(username='admin.testuser@sandbox.com')];
        }
    }
    public static void setupAdmin(){
        List<Profile> profiles = [SELECT Id,Name FROM Profile WHERE Name = 'System Administrator'];
        for (Profile profile : profiles) {
            String alias = 'admin';
            User testAdmin = new User(alias = alias
                                    ,email=alias+'.testuser@mail.me'
                                    ,emailencodingkey='UTF-8'
                                    ,firstname=alias
                                    ,lastname='TestUser'
                                    ,languagelocalekey='en_US'
                                    ,localesidkey='en_GB'
                                    ,profileId = profile.Id
                                    ,timezonesidkey='Europe/Helsinki'
                                    ,username=alias+'.testuser@sandbox.com'
            );
            System.debug('--- LumonTestAdmin - setupAdmin - admin to Insert: '+testAdmin);
            insert testAdmin;
            System.debug('--- LumonTestAdmin - setupAdmin - testAdmin: '+testAdmin);
        }
        
        System.debug('--- LumonTestAdmin - setupAdmin - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestAdmin - setupAdmin - SOQL USED: ' + LIMITS.getQueries());
    }
    public static void setupAdminData(){
        setupAdmin();
    }
    /********** User Data Tests***********/
    @TestSetup
    public static void prepareData(){
        Test.startTest();
        
        Test.stopTest();
    }   
    @isTest
    public static void setupAdminDataTest(){
        String testResult;
        Test.startTest();
        try {
            setupAdminData();
            testResult = 'successfully inserted Admin';
        } catch (exception e){
            testResult = 'Error when inserting Admin: '+e.getMessage();
        }
        System.debug('--- LumonTestAdmin - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestAdmin - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();       
        System.AssertNotEquals(true, testResult.contains('Error'));
    }
}