force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Installation Address Country)</description>
    <formula>TEXT(OfficeAddress__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenterAttribute__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenterAttribute__c</fullName>
    <formula>TEXT( ProfitCenter__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Center Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Appointment_Booking_Offset__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Booking_Offset__c</fullName>
    <label>Appointment Booking Offset</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/AppointmentBookingOffset__c.field-meta.xml
<CustomField>
    <fullName>AppointmentBookingOffset__c</fullName>
    <label>Appointment Booking Offset</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Installation Address Country)</description>
    <formula>TEXT(CountryCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/DispatchingOffset__c.field-meta.xml
<CustomField>
    <fullName>DispatchingOffset__c</fullName>
    <description>The offset for automatic dispatching for this Territory</description>
    <label>Dispatching Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/LUM_Dispatching_Offset__c.field-meta.xml
<CustomField>
    <fullName>LUM_Dispatching_Offset__c</fullName>
    <description>The offset for automatic dispatching for this Territory</description>
    <label>Dispatching Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Offices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Parent_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Name__c</fullName>
    <formula>ParentTerritory.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Parents_Parent_Name__c.field-meta.xml
<CustomField>
    <fullName>Parents_Parent_Name__c</fullName>
    <formula>ParentTerritory.ParentTerritory.Parent_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent&apos;s Parent Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/PropertyTypeAttribute__c.field-meta.xml
<CustomField>
    <fullName>PropertyTypeAttribute__c</fullName>
    <description>Level 6 Classification based on Property Type</description>
    <formula>Text(PropertyType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 6 Classification based on Property Type</inlineHelpText>
    <label>Property Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Related_Case_Queue_name__c.field-meta.xml
<CustomField>
    <fullName>Related_Case_Queue_name__c</fullName>
    <description>This needs to contain the Case Queue name of the queue where all the ST related Reclamation/Quality Event cases will be sent to when they are created.</description>
    <inlineHelpText>This needs to contain the Case Queue name of the queue where all the ST related Reclamation/Quality Event cases will be sent to when they are created.</inlineHelpText>
    <label>Related Case Queue name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Scheduling_Calendar__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Operating Hours timeslot calendar for the custom Scheduling Component to use. Base value comes from the Metadata, but this can be overridden by linking another Operating Hours calendar here.</description>
    <inlineHelpText>Defines the Operating Hours timeslot calendar for the custom Scheduling Component to use. Base value comes from the Metadata, but this can be overridden by linking another Operating Hours calendar here.</inlineHelpText>
    <label>Scheduling Calendar</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Service Territories</relationshipLabel>
    <relationshipName>Service_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/SchedulingCalendar__c.field-meta.xml
<CustomField>
    <fullName>SchedulingCalendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the Operating Hours timeslot calendar for the custom Scheduling Component to use. Base value comes from the Metadata, but this can be overridden by linking another Operating Hours calendar here.</description>
    <inlineHelpText>Defines the Operating Hours timeslot calendar for the custom Scheduling Component to use. Base value comes from the Metadata, but this can be overridden by linking another Operating Hours calendar here.</inlineHelpText>
    <label>Scheduling Calendar</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Service Territories</relationshipLabel>
    <relationshipName>ServiceTerritories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/ServiceAttribute__c.field-meta.xml
<CustomField>
    <fullName>ServiceAttribute__c</fullName>
    <formula>/* Services Area */
SUBSTITUTE(
	TRIM(
		/* 1. Organization - LSU INCLUDED*/
		IF(NOT(ISBLANK(OrganizationAttribute__c )),
			OrganizationAttribute__c ,&apos;&apos;)
		/* 2. Country - LSU_FI */
		+IF(AND(NOT(ISBLANK(CountryAttribute__c )),NOT(ISBLANK(OrganizationAttribute__c ))),
			&apos;_&apos;+CountryAttribute__c ,&apos;&apos;)
		+IF(AND(NOT(ISBLANK(CountryAttribute__c )),ISBLANK(OrganizationAttribute__c )),
			CountryAttribute__c ,&apos;&apos;)
		/* 3. District/Sales Area - LSU_FI_South */
		+IF(AND(NOT(ISBLANK(DistrictAttribute__c )),NOT(ISBLANK(CountryAttribute__c )),ISBLANK(ProfitCenterAttribute__c ),ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+ SUBSTITUTE(DistrictAttribute__c , CountryAttribute__c+&apos;_&apos;, &apos;&apos;) ,&apos;&apos;)
		/* 4. Profit Center - LSU_FI_402 */
		+IF(AND(NOT(ISBLANK(ProfitCenterAttribute__c )),ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+ProfitCenterAttribute__c ,&apos;&apos;)
		/* 5. Office - LSU_FI_402_12345 */
		+IF(NOT(ISBLANK(OfficeAttribute__c )),
			&apos;_&apos;+SUBSTITUTE(OfficeAttribute__c , CountryAttribute__c+&apos;-&apos;, &apos;&apos;),&apos;&apos;)
		/* 6. Business Type - LSU_FI_402_12345_1 */
		+IF(AND(NOT(ISBLANK( BusinessTypeAttribute__c )),ISBLANK(CustomerSegmentAttribute__c ),ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+BusinessTypeAttribute__c ,&apos;&apos;)
		/* 7. Customer Segment - LSU_FI_402_12345_1100 */
		+IF(NOT(ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+CustomerSegmentAttribute__c ,&apos;&apos;)
	),
&apos; &apos;, &apos;_&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/ServiceTerritoryCode__c.field-meta.xml
<CustomField>
    <fullName>ServiceTerritoryCode__c</fullName>
    <label>Service Territory Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceTerritoryController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-04-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ServiceTerritoryController {
    /**** Methods for Finding ServiceTerritory Entries ****/
    @AuraEnabled(cacheable=false)
    public static ServiceTerritory getServiceTerritory(Id serviceTerritoryId) {
        // Populate List from SOQL query on ServiceTerritory
        List<Id> serviceTerritoryIds = new List<Id>();
        serviceTerritoryIds.add(serviceTerritoryId);
        System.debug('--- ServiceTerritoryController - Get ServiceTerritory with Id '+serviceTerritoryId); 
        List<ServiceTerritory> serviceTerritories =  getServiceTerritories(serviceTerritoryIds);  
        ServiceTerritory serviceTerritory = serviceTerritories[0];
        System.debug('--- ServiceTerritoryController - ServiceTerritory: '+serviceTerritory.Name); 
        return serviceTerritory;  
    }
    @AuraEnabled(cacheable=false)
    public static ServiceTerritory getServiceTerritoryByNumber(String serviceTerritoryCode) {
        // Populate List from SOQL query on ServiceTerritory
        Id serviceTerritoryId = [SELECT Id FROM ServiceTerritory WHERE ServiceAttribute__c =: serviceTerritoryCode LIMIT 1]?.Id; 
        List<Id> serviceTerritoryIds = new List<Id>();
        serviceTerritoryIds.add(serviceTerritoryId);
        ServiceTerritory serviceTerritory = new ServiceTerritory();
        System.debug('--- ServiceTerritoryController - Get Service Territory with Id '+serviceTerritoryId); 
        List<ServiceTerritory> serviceTerritories =  getServiceTerritories(serviceTerritoryIds); 
        if  (serviceTerritories?.size()>0) {
            serviceTerritory = serviceTerritories[0];
            System.debug('--- ServiceTerritoryController - ServiceTerritory: '+serviceTerritory.Name); 
        }        
        return serviceTerritory;
    }
    @AuraEnabled(cacheable=false)
    public static List<ServiceTerritory> getServiceTerritoriesByUser(Id userId) {
        // Populate List from SOQL query on ServiceTerritory
        List<ServiceTerritory> customerServiceTerritories = new List<ServiceTerritory>();
        customerServiceTerritories = getServiceTerritories(new List<Id> {userId});
        return customerServiceTerritories;
    }
    @AuraEnabled(cacheable=false)
    public static List<ServiceTerritory> getServiceTerritories(List<Id> recordIds) {
        // Populate List from SOQL query on ServiceTerritory
        System.debug('--- ServiceTerritoryController - Get ServiceTerritories'); 
        List<ServiceTerritory> serviceTerritories = ([  SELECT Id,Name,  
                                                            OwnerId,
                                                            ParentTerritoryId, 
                                                            TopLevelTerritoryId, 
                                                            OperatingHoursId, 
                                                            Description, 
                                                            Address,
                                                            Street, City, State, PostalCode, Country, StateCode, CountryCode, Latitude, Longitude, GeocodeAccuracy,                                                            
                                                            IsActive,                                                        
                                                            TypicalInTerritoryTravelTime, 
                                                            SchedulingConstraintId, 
                                                            TravelModeId, 
                                                            //AvgTravelTime, 
                                                            FSL__Hide_Emergency_Map__c, 
                                                            FSL__Internal_SLR_Geolocation__Latitude__s, 
                                                            FSL__Internal_SLR_Geolocation__Longitude__s, 
                                                            FSL__Internal_SLR_Geolocation__c, 
                                                            FSL__NumberOfServicesToDripFeed__c, 
                                                            FSL__O2_Enabled__c, 
                                                            FSL__Service_Cluster_Min_Size__c, 
                                                            FSL__Service_Cluster_Proximity__c, 
                                                            FSL__System_Jobs__c, 
                                                            FSL__TerritoryLevel__c,                                                            
                                                            //Parent_Name__c, Appointment_Booking_Offset__c, LUM_Dispatching_Offset__c, Scheduling_Calendar__c, 
                                                            //Parents_Parent_Name__c, Related_Case_Queue_name__c, 
                                                            AppointmentBookingOffset__c, 
                                                            DispatchingOffset__c, 
                                                            ServiceTerritoryCode__c, 
                                                            SchedulingCalendar__c,
                                                            BusinessType__c, BusinessTypeAttribute__c,
                                                            CountryAttribute__c, 
                                                            CustomerSegment__c, CustomerSegmentAttribute__c,
                                                            District__c, DistrictAttribute__c,
                                                            Office__c, OfficeAttribute__c,
                                                            Organization__c,OrganizationAttribute__c,
                                                            ProfitCenter__c, ProfitCenterAttribute__c,
                                                            PropertyType__c, PropertyTypeAttribute__c,
                                                            ServiceAttribute__c
                                                            
                                                        FROM ServiceTerritory
                                                        WHERE Id IN: recordIds
                                                        OR OwnerId IN: recordIds
                                                        ]);  
        System.debug('--- ServiceTerritoryController - ServiceTerritories: '+serviceTerritories.size()); 
        return serviceTerritories;  
    }
}