force-app/main/default/objects/Building_Project__c/Building_Project__c.object-meta.xml
<CustomObject>
    <description>The Main Project Record</description>
    <label>Building Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Buying Account</description>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <description>The Organization in Charge of the Project</description>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/ProjectEndDate__c.field-meta.xml
<CustomField>
    <fullName>ProjectEndDate__c</fullName>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/ProjectManager__c.field-meta.xml
<CustomField>
    <fullName>ProjectManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Projects_Supervised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/ProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Project Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/ProjectStartDate__c.field-meta.xml
<CustomField>
    <fullName>ProjectStartDate__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <description>The Date the Project was Initiated (First Order Placed)</description>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <description>The Type of Project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Project_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building_Project__c/fields/SalesManager__c.field-meta.xml
<CustomField>
    <fullName>SalesManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/Delivery_Project__c.object-meta.xml
<CustomObject>
    <label>Delivery Project</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Project__c/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <description>The Main Project</description>
    <label>Building Project</label>
    <referenceTo>Building_Project__c</referenceTo>
    <relationshipLabel>Delivery Projects</relationshipLabel>
    <relationshipName>LumonDeliveryProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Projects</relationshipLabel>
    <relationshipName>Delivery_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/CustomerAddress__c.field-meta.xml
<CustomField>
    <fullName>CustomerAddress__c</fullName>
    <label>Customer Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/InstallationAddress__c.field-meta.xml
<CustomField>
    <fullName>InstallationAddress__c</fullName>
    <description>The Address where the Balcony or Terrace Glazing is Installed</description>
    <inlineHelpText>The Address where the Balcony or Terrace Glazing is Installed</inlineHelpText>
    <label>Installation Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/InvoicingAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoicingAddress__c</fullName>
    <description>The Address where the Invoice is Send</description>
    <inlineHelpText>The Address where the Invoice is Send</inlineHelpText>
    <label>Invoicing Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/isChargeable__c.field-meta.xml
<CustomField>
    <fullName>isChargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isChargeable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/ProjectCategory__c.field-meta.xml
<CustomField>
    <fullName>ProjectCategory__c</fullName>
    <label>Project Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Project_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/ProjectCost__c.field-meta.xml
<CustomField>
    <fullName>ProjectCost__c</fullName>
    <label>Project Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/ProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ProjectNumber__c</fullName>
    <description>Unique Main Project Number</description>
    <inlineHelpText>Project Number Reference</inlineHelpText>
    <label>Project Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/ProjectType__c.field-meta.xml
<CustomField>
    <fullName>ProjectType__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Project_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Project__c/fields/underWarranty__c.field-meta.xml
<CustomField>
    <fullName>underWarranty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>underWarranty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Project_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>WAR</fullName>
        <label>Warranty</label>
    </customValue>
    <customValue>
        <fullName>DELIV</fullName>
        <label>Delivery</label>
    </customValue>
    <customValue>
        <fullName>SALES</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>CON</fullName>
        <label>Consumer Sales</label>
    </customValue>
    <customValue>
        <fullName>AFT</fullName>
        <label>After Sales</label>
    </customValue>
    <customValue>
        <fullName>REC</fullName>
        <label>Reclamation</label>
    </customValue>
    <masterLabel>Lumon Project Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Project_Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONSALES</fullName>
    </customValue>
    <customValue>
        <fullName>CONSDELIV</fullName>
    </customValue>
    <customValue>
        <fullName>CONWAR</fullName>
    </customValue>
    <customValue>
        <fullName>GROUPSA</fullName>
    </customValue>
    <customValue>
        <fullName>INTWAR</fullName>
    </customValue>
    <customValue>
        <fullName>PRODELIV</fullName>
    </customValue>
    <customValue>
        <fullName>PROPROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>PROWAR</fullName>
    </customValue>
    <customValue>
        <fullName>PROWIP</fullName>
    </customValue>
    <customValue>
        <fullName>RESDELIV</fullName>
    </customValue>
    <customValue>
        <fullName>WEBDELIV</fullName>
    </customValue>
    <masterLabel>Lumon Project Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Project_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NB</fullName>
        <label>Construction</label>
    </customValue>
    <customValue>
        <fullName>REN</fullName>
        <label>Renovation</label>
    </customValue>
    <customValue>
        <fullName>RES</fullName>
        <label>Reseller Sales</label>
    </customValue>
    <customValue>
        <fullName>CON</fullName>
        <label>Consumer Sales</label>
    </customValue>
    <customValue>
        <fullName>AFT</fullName>
        <label>After Sales</label>
    </customValue>
    <customValue>
        <fullName>REC</fullName>
        <label>Reclamation</label>
    </customValue>
    <masterLabel>Lumon Project Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-25-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ProjectController {
    @AuraEnabled(cacheable=false)
    public static Building_Project__c getCustomerProject(Id projectId) {
        // Populate List from SOQL query on Building_Project__c
        List<Id> projectIds = new List<Id>();
        projectIds.add(projectId);
        Building_Project__c project = new Building_Project__c();
        System.debug('--- ProjectController - Get Building Project with Id '+projectId); 
        List<Building_Project__c> projects =  getCustomerProjects(projectIds); 
        if  (projects?.size()>0) {
            project = projects[0];
            System.debug('--- ProjectController - Building Project: '+project.Name); 
        }        
        return project;  
    }
    @AuraEnabled(cacheable=false)
    public static Building_Project__c getCustomerProjectByNumber(String projectNumber) {
        // Populate List from SOQL query on Building_Project__c
        Id projectId;// = [SELECT Id FROM Building_Project__c WHERE Project_Number__c =: projectNumber LIMIT 1]?.Id; 
        List<Id> projectIds = new List<Id>();
        projectIds.add(projectId);
        Building_Project__c project = new Building_Project__c();
        System.debug('--- ProjectController - Get Building Project with Id '+projectId); 
        List<Building_Project__c> projects =  getCustomerProjects(projectIds); 
        if  (projects?.size()>0) {
            project = projects[0];
            System.debug('--- ProjectController - Building Project: '+project.Name); 
        }        
        return project;
    }
    @AuraEnabled(cacheable=false)
    public static List<Building_Project__c> getCustomerProjects(List<Id> projectIds) {
        // Populate List from SOQL query on Building_Project__c
        System.debug('--- ProjectController - Get Projects'); 
        List<Building_Project__c> projects = ([  SELECT Id,
                                                        OwnerId, 
                                                        Name, 
                                                        CurrencyIsoCode, 
                                                        CreatedDate, 
                                                        CreatedById, 
                                                        LastModifiedDate, 
                                                        LastModifiedById, 
                                                        ProjectNumber__c,                                                         
                                                        Customer__c, 
                                                        Organization__c,     
                                                        ProfitCenter__c,
                                                        ProjectManager__c,
                                                        SalesManager__c,
                                                        ProjectType__c,
                                                        ProjectStartDate__c,
                                                        ProjectEndDate__c
                                                    FROM Building_Project__c 
                                                    WHERE Id IN: projectIds]);  
        System.debug('--- ProjectController - Building Projects: '+projects.size()); 
        return projects;  
    }
    @AuraEnabled(cacheable=false)
    public static Delivery_Project__c getDeliveryProject(Id projectId) {
        // Populate List from SOQL query on Delivery_Project__c
        List<Id> projectIds = new List<Id>();
        projectIds.add(projectId);
        Delivery_Project__c subProject = new Delivery_Project__c();
        System.debug('--- ProjectController - Get Delivery Project with Id '+projectId); 
        List<Delivery_Project__c> subProjects =  getSubProjects(projectIds); 
        if  (subProjects?.size()>0) {
            subProject = subProjects[0];
            System.debug('--- ProjectController - Delivery Project: '+subProject.Name); 
        }        
        return subProject;  
    }
    @AuraEnabled(cacheable=false)
    public static Delivery_Project__c getDeliveryProjectByNumber(String projectNumber) {
        // Populate List from SOQL query on Delivery_Project__c
        Id projectId;// = [SELECT Id FROM Building_Project__c WHERE Project_Number__c =: projectNumber LIMIT 1]?.Id; 
        List<Id> projectIds = new List<Id>();
        projectIds.add(projectId);
        Delivery_Project__c subProject = new Delivery_Project__c();
        System.debug('--- ProjectController - Get Delivery Project with Id '+projectId); 
        List<Delivery_Project__c> subProjects =  getSubProjects(projectIds); 
        if  (subProjects?.size()>0) {
            subProject = subProjects[0];
            System.debug('--- ProjectController - Delivery Project: '+subProject.Name); 
        }        
        return subProject;
    }
    @AuraEnabled(cacheable=false)
    public static List<Delivery_Project__c> getSubProjects(List<Id> projectIds) {
        // Populate List from SOQL query on Building_Project__c
        System.debug('--- ProjectController - Get Delivery Projects'); 
        List<Delivery_Project__c> subProjects = ([  SELECT Id,
                                                        Name, 
                                                        //ProjectCategory__c, 
                                                        ProjectType__c, 
                                                        ProjectCost__c,
                                                        BuildingProject__c,
                                                        OrderType__c,
                                                        Customer__c, 
                                                        ProjectNumber__c,  
                                                        CustomerAddress__c,                                                         
                                                        InvoicingAddress__c,
                                                        InstallationAddress__c, 
                                                        DeliveryAddress__c,
                                                        Status__c,
                                                        isChargeable__c,
                                                        underWarranty__c            
                                                    FROM Delivery_Project__c 
                                                    WHERE Id IN: projectIds]);  
        System.debug('--- ProjectController - Delivery Projects: '+subProjects.size()); 
        return subProjects;  
    }
}