force-app/main/default/objects/Product2/fields/Configurator__c.field-meta.xml
<CustomField>
    <fullName>Configurator__c</fullName>
    <label>Configurator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Configurators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Sales Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkType/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates if this is a new product installation work or something else. Note that in the new product installation work, the completion of the WOLI also creates new Asset.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Product installation</fullName>
            </value>
            <value>
                <fullName>Reclamation work</fullName>
            </value>
            <value>
                <fullName>Maintenance and Accessories</fullName>
            </value>
            <value>
                <fullName>Other work</fullName>
            </value>
            <value>
                <fullName>Internal Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Configurators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Salestori</fullName>
    </customValue>
    <masterLabel>Lumon Configurators</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InboundDataApiControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-08-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class InboundDataApiControllerTest {
    @TestSetup
    public static void prepareData(){
        Test.startTest();
        Product2 mainProduct = new Product2(Name='Lumon Glazing Retractable', 
                                   IsActive=True,
                                   ProductCode='LG',
                                   ProductGroup__c='LG',
                                   ProductCategory__c='Product Groups',
                                   ProductCode__c = '90240001',
                                   Installation__c = true,
                                   Configurator__c = 'Visual');
        insert mainProduct;
        WorkType workType = new WorkType(Name = 'Installation',
                                            Type__c = 'New Product installation',
                                            ShouldAutoCreateSvcAppt = true,
                                            FSL__Due_Date_Offset__c = 60*24*7, // 1 week in minutes
                                            DurationType = 'Minutes',
                                            EstimatedDuration = 60);
        insert workType;
    }
    @isTest
	static void testDoPost(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
		StaticResource sr= [SELECT id, body FROM StaticResource WHERE Name = 'orderMessage_project_batch1' LIMIT 1];
        req.requestURI = '/services/apexrest/InboundDataApi/';  
		req.requestBody = sr.body;
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
		
        Test.startTest();
        InboundDataApiController.doPost();
        Test.stopTest();

    }   
    @isTest
	static void testDoPostCatch(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/InboundDataApi/';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;		
        Test.startTest();
        InboundDataApiController.doPost();
        Test.stopTest();
    }   

  }