force-app/main/default/objects/Product2/fields/Configurator__c.field-meta.xml
<CustomField>
    <fullName>Configurator__c</fullName>
    <label>Configurator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Configurators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates if this is a new product installation work or something else. Note that in the new product installation work, the completion of the WOLI also creates new Asset.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Product installation</fullName>
            </value>
            <value>
                <fullName>Reclamation work</fullName>
            </value>
            <value>
                <fullName>Maintenance and Accessories</fullName>
            </value>
            <value>
                <fullName>Other work</fullName>
            </value>
            <value>
                <fullName>Internal Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Configurators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Salestori</fullName>
    </customValue>
    <masterLabel>Lumon Configurators</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FieldServiceWorkControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 07-04-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class FieldServiceWorkControllerTest {
    @TestSetup
    public static void prepareData(){
        Test.startTest();
        Product2 p1 = new Product2(Name='Lumon Glazing Retractable', 
                                   IsActive=True,
                                   ProductCode='LG',
                                   Product_Group__c='LG',
                                   Product_Category__c='Product Groups',
                                   Sales_Code__c = '90240001',
                                   Installation__c = true,
                                   Configurator__c = 'Visual');
        insert p1;
        WorkType wt = new WorkType(Name = 'Installation',
                                   Type__c = 'New Product installation',
        						   ShouldAutoCreateSvcAppt = true,
        						   FSL__Due_Date_Offset__c = 60*24*7, // 1 week in minutes
        						   DurationType = 'Minutes',
        						   EstimatedDuration = 60);
        insert wt;
    }
    @isTest
	static void testDoPost(){
		
        RestRequest req = new RestRequest(); 

        RestResponse res = new RestResponse();
		StaticResource sr= [SELECT id, body FROM StaticResource WHERE Name = 'plantori_test2_json' limit 1];
        req.requestURI = '/services/apexrest/FieldServiceInstallationApi/';  
		req.requestBody = sr.body;
        req.httpMethod = 'POST';

        RestContext.request = req;

        RestContext.response = res;
		
        Test.startTest();

        FieldServiceWorkApi.processOrderMessage();

        Test.stopTest();

    }   
    @isTest
	static void testDoPostCatch(){
		
        RestRequest req = new RestRequest(); 

        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/FieldServiceInstallationApi/';  
        req.httpMethod = 'POST';

        RestContext.request = req;

        RestContext.response = res;
		
        Test.startTest();

        FieldServiceWorkApi.processOrderMessage();

        Test.stopTest();

    }   

  }