force-app/main/default/objects/Product2/fields/Configurator__c.field-meta.xml
<CustomField>
    <fullName>Configurator__c</fullName>
    <label>Configurator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Configurators</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CostCategory__c.field-meta.xml
<CustomField>
    <fullName>CostCategory__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CostType__c.field-meta.xml
<CustomField>
    <fullName>CostType__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CostCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isAdditionalCost__c.field-meta.xml
<CustomField>
    <fullName>isAdditionalCost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if this is a Additional Cost Product</description>
    <inlineHelpText>Indicates if this is a Additional Cost Product</inlineHelpText>
    <label>Additional Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isExtraSales__c.field-meta.xml
<CustomField>
    <fullName>isExtraSales__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if this is a Extra Sales Product</description>
    <inlineHelpText>Indicates if this is a Extra Sales Product</inlineHelpText>
    <label>Extra Sales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isManualProcessing__c.field-meta.xml
<CustomField>
    <fullName>isManualProcessing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to Indicate if the Product needs Manual Processing</description>
    <inlineHelpText>Indicates if the Product needs Manual Processing</inlineHelpText>
    <label>Manual Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isReclamation__c.field-meta.xml
<CustomField>
    <fullName>isReclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isService__c.field-meta.xml
<CustomField>
    <fullName>isService__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Service</description>
    <inlineHelpText>Indicates if the Product is a Service</inlineHelpText>
    <label>Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isSovelia__c.field-meta.xml
<CustomField>
    <fullName>isSovelia__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Sovelia Product</description>
    <inlineHelpText>Indicates if the Product is a Sovelia Product</inlineHelpText>
    <label>Sovelia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isSparePart__c.field-meta.xml
<CustomField>
    <fullName>isSparePart__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if this is a Spare Part Product</description>
    <inlineHelpText>Indicates if this is a Spare Part Product</inlineHelpText>
    <label>isSparePart</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isSpecial__c.field-meta.xml
<CustomField>
    <fullName>isSpecial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Special Product</description>
    <inlineHelpText>indicates if the Product needs Special Handling</inlineHelpText>
    <label>Special</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/isVisual__c.field-meta.xml
<CustomField>
    <fullName>isVisual__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Visual Product</description>
    <inlineHelpText>Indicates if the Product is a Visual Product</inlineHelpText>
    <label>Visual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OrderBatchSize__c.field-meta.xml
<CustomField>
    <fullName>OrderBatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Sales Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <inlineHelpText>Third Level Grouping of Products and Services</inlineHelpText>
    <label>Product Item</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductModel__c.field-meta.xml
<CustomField>
    <fullName>ProductModel__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductVendor__c.field-meta.xml
<CustomField>
    <fullName>ProductVendor__c</fullName>
    <label>Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lumon</fullName>
                <default>true</default>
                <label>Lumon</label>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ReclamationCode__c.field-meta.xml
<CustomField>
    <fullName>ReclamationCode__c</fullName>
    <description>Main Product SalesCode to use for Reclamation</description>
    <externalId>true</externalId>
    <inlineHelpText>Main Product SalesCode to use for Reclamation</inlineHelpText>
    <label>Reclamation Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SalesCode__c.field-meta.xml
<CustomField>
    <fullName>SalesCode__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Configurators.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Salestori</fullName>
    </customValue>
    <masterLabel>Lumon Configurators</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>F-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing Beads</fullName>
    </customValue>
    <customValue>
        <fullName>h-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>L-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Rectangular Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Telescopic Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>U-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Upper Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Wall Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Screws</fullName>
    </customValue>
    <customValue>
        <fullName>Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 1</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 2</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 3</fullName>
    </customValue>
    <customValue>
        <fullName>Special Colors</fullName>
    </customValue>
    <customValue>
        <fullName>Sand Blasting</fullName>
    </customValue>
    <customValue>
        <fullName>Special Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Edge Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Items</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-09-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ProductController {
    @AuraEnabled(cacheable=true)
    public static Product2 getProduct(Id recordId) {
        List<Product2> products = New List<Product2>(); 
        // Find Projects based on recordId
        List<Id> recordIds = new List<Id>();
        recordIds.add(recordId);
        products = getProducts(recordIds);
        return products[0];
    } 
    @AuraEnabled(cacheable=false)
    public static Product2 getProductByNumber(String productNumber) {
        // Populate List from SOQL query on Product
        Id productId = [SELECT Id, ProductCode, ProductCode__c FROM Product2 WHERE ProductCode =: productNumber OR ProductCode__c =: productNumber LIMIT 1]?.Id; 
        List<Id> productIds = new List<Id>();
        productIds.add(productId);
        Product2 product = new Product2();
        System.debug('--- ProductController - Get Product with Id '+productId); 
        List<Product2> products =  getProducts(productIds); 
        if  (products?.size()>0) {
            product = products[0];
            System.debug('--- ProductController - Product: '+product.Name); 
        }        
        return product;
    }
    @AuraEnabled(cacheable=true)
    public static List<Product2> getProducts(List<Id> recordIds) {
        // Populate map from SOQL query on Product2
        List<Product2> products = ([SELECT  Id, 
                                            Name, 
                                            ProductCode, 
                                            Description, 
                                            IsActive, 
                                            Family, 
                                            ExternalDataSourceId, 
                                            ExternalId, 
                                            QuantityUnitOfMeasure, 
                                            // Product CTI
                                            ProductCategory__c, 
                                            ProductType__c,
                                            ProductItem__c,
                                            // SalesTori/MainTori CTI
                                            ProductGroup__c,  
                                            ProductModel__c,
                                            CostCategory__c, 
                                            CostType__c, 
                                            // AX Code
                                            SalesCode__c,
                                            Installation__c, 
                                            isReclamation__c, 
                                            ReclamationCode__c,                                          
                                            // Salesforce Product Flags
                                            ProductVendor__c,
                                            Configurator__c, 
                                            isSovelia__c, 
                                            isVisual__c, 
                                            isAdditionalCost__c,
                                            isExtraSales__c,
                                            isService__c, 
                                            isSparePart__c,
                                            isManualProcessing__c, 
                                            OrderBatchSize__c, 
                                            isSpecial__c 
                                    FROM Product2 
                                    WHERE Id IN:recordIds
                                    AND IsActive = true
                                    ]);
        System.debug('--- ProductController - Product2 Record Count : '+products.size());
        return products;
    } 
    @AuraEnabled(cacheable=true)
    public static Map<String,List<Product2>> getProductsByGroup(List<String> productGroups) {
        // Populate map from SOQL query on Product2
        List<Product2> groupedProducts = ([SELECT  Id 
                                    FROM Product2 
                                    WHERE ProductGroup__c IN:productGroups
                                    AND IsActive = true
                                    ]);
        List<Id> groupedProductIds = new List<Id>(new Map<Id, Product2>(groupedProducts).keySet()); 
        List<Product2> products = getProducts(groupedProductIds);
        Map<String,List<Product2>> productsByGroup = new Map<String,List<Product2>> ();
        if(products?.size()>0 ) {
            for (Product2 prod : products) {
                String prodGroup = prod.Product_Group__c;
                if(!productsByGroup.containsKey(prodGroup)) {
                    productsByGroup.put(prodGroup,new List<Product2>());
                }
                List<Product2> prods = productsByGroup.get(prodGroup);
                prods.add(prod);
                productsByGroup.put(prodGroup,prods);
            }
        }
        return productsByGroup;
    } 
}