force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/Production_Time__c.object-meta.xml
<CustomObject>
    <description>Holds a reference to the estimated/expected Times to produce a Finished Good</description>
    <label>Production Time</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Production Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Time__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT(Product__r.Product_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductionTimeControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-05-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
public with sharing class ProductionTimeControllerTest {
    @TestSetup
    static void PrepareData(){   
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupProductionTimes();
        Test.stopTest();
    }
    private static List<product2> products = [SELECT Id, Name, ProductCode, Cost_Type__c, Product_Group__c, Product_Model__c, Sales_Code__c, isActive FROM Product2];
    private static List<Production_Time__c> productionTimes = LumonTestDataFactory.productionTimes;
    @IsTest
    static void getProductionTimesTest(){
        Boolean isActive = true;
        System.debug('--- getProductionTimesTest - isActive: '+isActive); 
        Test.startTest();
        List<Production_Time__c> factoryTimes = ProductionTimeController.getProductionTimes(isActive);
        System.assertNotEquals(0, factoryTimes.size(), 'Expecting atleast 1 Production Time to be returned');
        System.debug('--- getProductionTimesTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getProductionTimesTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getProductionTimeMapTest(){
        Boolean isActive = true;
        System.debug('--- getProductionTimeMapTest - isActive: '+isActive); 
        Test.startTest();
        Map<String,Production_Time__c> productCode2factoryTime = ProductionTimeController.getProductionTimeMap(isActive);
        System.assertNotEquals(0, productCode2factoryTime.values().size(), 'Expecting atleast 1 Installation Time to be returned');
        System.debug('--- getProductionTimeMapTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getProductionTimeMapTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }

}