force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Cost__c/Product_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>T2-{000000}</displayFormat>
        <label>Cost Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Cost__c.field-meta.xml
<CustomField>
    <fullName>Product_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Product Cost</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricingExtraSalesControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
private with sharing class PricingExtraSalesControllerTest {
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;

    @TestSetup
    static void prepareData() {
        Test.startTest();
        LumonTestProducts.setupExtraSales();
        LumonTestPricebooks.setupPrices();
        LumonTestPriceParameters.setupPriceParameters();
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();
        LumonTestDataFactory.setupSyncedQuoteB2C();
        LumonTestDataFactory.setupConfigurationB2C();
        //LumonTestDataFactory.setupPriceParameters();
        LumonTestDataFactory.setupPricingSummaryB2C();
        Test.stopTest();
    }

    @IsTest
    static void getComponentDataTest() {
        Product2 product = [
            SELECT Id, Cost_Type__c, Product_Group__c, Product_Category__c, ProductCode
            FROM Product2
            WHERE Product_Group__c = 'LISAHIN'
            	AND Product_Category__c = 'Product Groups'
            LIMIT 1
        ];

        Test.startTest();
        PricingExtraSalesController.ComponentData data = PricingExtraSalesController.getComponentData(b2cOpportunityId);

        Assert.isNotNull(PricingExtraSalesController.findProduct(product.Id), 'There should be a product');
        PricingExtraSalesController.findPrices(data.opportunity.Id, product.Id, 1.0);

        Test.stopTest();
    }

    @IsTest
    static void saveExtraSalesTest() {
        Product2 product = [
            SELECT Id, Cost_Type__c, Product_Group__c, Product_Category__c, ProductCode
            FROM Product2
            WHERE Product_Group__c = 'LISAHIN'
            AND Product_Category__c = 'Product Groups'
            LIMIT 1
        ];
        
        Opportunity opportunity = OpportunityProductController.getOpportunityRecord(b2cOpportunityId);
        Id quoteId = opportunity.SyncedQuoteId;
        Id pbeId = [SELECT Id FROM PricebookEntry WHERE Product2Id = :product.Id AND Pricebook2Id = :opportunity.PriceBook2Id LIMIT 1]?.Id;
        opportunity.StageName = 'Quoting';
        update opportunity;

        Test.startTest();
        PricingExtraSalesController.ComponentData data = PricingExtraSalesController.getComponentData(b2cOpportunityId);
        QuoteLineItem qli = new QuoteLineItem(
            Product_Cost__c = 1,
            Product2 = product,
            PriceBookEntryId = pbeId,
            QuoteId = quoteId,
            Quantity = 1.0,
            UnitPrice = 1.0
        );

        QuoteLineItem newQuoteLineItem = PricingExtraSalesController.saveItem(data.opportunity.Id, qli);
        Assert.areNotEqual(null, newQuoteLineItem.Id, 'Quote Line Item should have been created');
        PricingExtraSalesController.deleteItem(data.opportunity.Id, newQuoteLineItem.Id);
        Assert.areEqual(0, [SELECT Id FROM QuoteLineItem WHERE Id = :newQuoteLineItem.Id].size(),
            'Quote Line Item should have been deleted');
        Test.stopTest();
    }
}