force-app/main/default/objects/ProcessEvent__e/ProcessEvent__e.object-meta.xml
<CustomObject>
    <label>Process Event</label>
    <pluralLabel>Process Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProcessEvent__e/fields/activity__c.field-meta.xml
<CustomField>
    <fullName>activity__c</fullName>
    <description>The Process related Activity to Initiate</description>
    <label>Process Activity</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__e/fields/jsonString__c.field-meta.xml
<CustomField>
    <fullName>jsonString__c</fullName>
    <description>The JSON relevant to the Process Step</description>
    <label>JSON String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__e/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <description>The Type of Object of the Record from where the Event is Triggered</description>
    <label>Object Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>The Id of the Record from where the Event is Triggered</description>
    <label>recordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__e/fields/stage__c.field-meta.xml
<CustomField>
    <fullName>stage__c</fullName>
    <description>The Stage of the Process</description>
    <label>Process Stage</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessEventController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-12-2024
 * @last modified by  : Henk Reynders
**/
public class ProcessEventController {
    @AuraEnabled
    public static void publishEvent(ProcessEventData eventData){
        List<ProcessEvent__e> processEvents = new List<ProcessEvent__e>();    
        ProcessEvent__e  processEvent  = new ProcessEvent__e ();        
        processEvent.stage__c = eventData.stage;
        processEvent.activity__c = eventData.activity;
        processEvent.recordId__c = eventData.recordId;
        processEvent.objectType__c = eventData.objectType;
        processEvent.jsonString__c = eventData.jsonString;
        processEvent.documentId__c = eventData.documentId;
        System.Debug('--- ProcessEventController - publishEvent Stage '+eventData.stage);
        System.Debug('--- ProcessEventController - publishEvent Activity '+eventData.activity);                                                                               
        processEvents.add(processEvent);
        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(processEvents);
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('--- Successfully published Process Event');
            } else {
                for(Database.Error e : sr.getErrors()) {
                    System.debug('--- Failed to publish Process Event with Error: ' +
                                e.getStatusCode() +
                                ' - ' +
                                e.getMessage());
                    throw new CustomException(e.getMessage());
                }
            }       
        }
    }
}