force-app/main/default/objects/Account/fields/Account_Office__c.field-meta.xml
<CustomField>
    <fullName>Account_Office__c</fullName>
    <description>Account Office, this will be populated by a flow based on the postal code of the account</description>
    <inlineHelpText>Account Office, this field will be populated based on the postal code field chosen for the account.</inlineHelpText>
    <label>Account Office</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingToShipping__c.field-meta.xml
<CustomField>
    <fullName>BillingToShipping__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag to control whether Shipping Address is equal to Billing Address</description>
    <label>Use Billing as Shipping Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Location__c.field-meta.xml
<CustomField>
    <fullName>Customer_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Location Type is not an Account Location</errorMessage>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Method__c</fullName>
    <description>Delivery method selected for the installation</description>
    <inlineHelpText>Delivery method selected for the installation</inlineHelpText>
    <label>Delivery Method OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Delivery_Methods</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <description>Logistic Delivery Terms for the order</description>
    <inlineHelpText>Logistic Delivery Terms for the order</inlineHelpText>
    <label>Delivery Terms OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Delivery_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/District_Type__c.field-meta.xml
<CustomField>
    <fullName>District_Type__c</fullName>
    <label>District Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_District_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Financing_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Financing_Customer_Number__c</fullName>
    <label>Financing Customer Number OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MailingToBilling__c.field-meta.xml
<CustomField>
    <fullName>MailingToBilling__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag to control whether Billing Address is equal to Mailing Address (B2C)</description>
    <label>Use Mailing as Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Municipality__c.field-meta.xml
<CustomField>
    <fullName>Municipality__c</fullName>
    <label>Municipality</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <description>VAT value respective to the corporate interface</description>
    <label>VAT-%</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Delivery_Methods.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BYGunifau</fullName>
    </customValue>
    <customValue>
        <fullName>Collection</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Inst.Deliv</fullName>
        <default>true</default>
        <label>Inst.Deliv</label>
    </customValue>
    <customValue>
        <fullName>Inst.Visor</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Matkahuolto</fullName>
    </customValue>
    <customValue>
        <fullName>Matka-MH10</fullName>
    </customValue>
    <customValue>
        <fullName>Matka-MH30</fullName>
    </customValue>
    <customValue>
        <fullName>MH LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nouto</fullName>
    </customValue>
    <customValue>
        <fullName>PO2104</fullName>
    </customValue>
    <customValue>
        <fullName>Posti-PO21</fullName>
    </customValue>
    <customValue>
        <fullName>Posti-PO22</fullName>
    </customValue>
    <customValue>
        <fullName>Posti-PO23</fullName>
    </customValue>
    <customValue>
        <fullName>Posti-PO24</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-DPDF</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-P17F</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-P181</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-P182</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-P19</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-P19FI</fullName>
    </customValue>
    <customValue>
        <fullName>Postn-P521</fullName>
    </customValue>
    <customValue>
        <fullName>Schen-KLGR</fullName>
    </customValue>
    <customValue>
        <fullName>Smartpost</fullName>
    </customValue>
    <customValue>
        <fullName>TNT-TNT4</fullName>
    </customValue>
    <customValue>
        <fullName>UPS-UPS1</fullName>
    </customValue>
    <customValue>
        <fullName>UPS-UPSS</fullName>
    </customValue>
    <description>System used for the delivery</description>
    <masterLabel>Lumon Delivery Methods</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_District_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
        <label>P1 Organization</label>
    </customValue>
    <customValue>
        <fullName>P10</fullName>
        <label>P10 Business Unit</label>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
        <label>P2 Country</label>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
        <label>P3 Business Type</label>
    </customValue>
    <customValue>
        <fullName>P4</fullName>
        <label>P4 Region</label>
    </customValue>
    <customValue>
        <fullName>P5</fullName>
        <label>P5 State/Province</label>
    </customValue>
    <customValue>
        <fullName>P6</fullName>
        <label>P6 County</label>
    </customValue>
    <customValue>
        <fullName>P7</fullName>
        <label>P7 Municipality</label>
    </customValue>
    <customValue>
        <fullName>P8</fullName>
        <label>P8 City</label>
    </customValue>
    <customValue>
        <fullName>P9</fullName>
        <label>P9 Neighborhood</label>
    </customValue>
    <customValue>
        <fullName>P11</fullName>
        <label>P11 Office</label>
    </customValue>
    <masterLabel>Lumon District Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-02-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class AccountController {
    /**** Methods for Finding Account Entries ****/
    @AuraEnabled(cacheable=false)
    public static Account getAccount(Id accountId) {
        // Populate List from SOQL query on Account
        List<Id> accountIds = new List<Id>();
        accountIds.add(accountId);
        System.debug('--- AccountController - Get Account with Id '+accountId); 
        List<Account> accounts =  getAccounts(accountIds);  
        Account account = accounts[0];
        System.debug('--- AccountController - Account: '+account.Name); 
        return account;  
    }
    @AuraEnabled(cacheable=false)
    public static Account getAccountByNumber(String accountNumber) {
        // Populate List from SOQL query on Account
        Id accountId = [SELECT Id FROM Account WHERE AccountNumber =: accountNumber LIMIT 1]?.Id; 
        List<Id> accountIds = new List<Id>();
        accountIds.add(accountId);
        Account account = new Account();
        System.debug('--- AccountController - Get Customer with Id '+accountId); 
        List<Account> accounts =  getAccounts(accountIds); 
        if  (accounts?.size()>0) {
            account = accounts[0];
            System.debug('--- AccountController - Account: '+account.Name); 
        }        
        return account;
    }
    @AuraEnabled(cacheable=false)
    public static List<Account> getAccounts(List<Id> AccountIds) {
        // Populate List from SOQL query on Account
        System.debug('--- AccountController - Get Accounts'); 
        List<Account> accounts = ([  SELECT  Id,
                                             Name,
                                             Type, 
                                             RecordTypeId, 
                                             ParentId, 
                                             OwnerId,
                                             //VAT__c,
                                             AccountSource,
                                             CustomerSegment__c, 
                                             BusinessType__c, 
                                             BusinessTypeAttribute__c, 
                                             //Account_Office__c, 
                                             //Financing_Customer_Number__c, 
                                             District__c, 
                                             County__c, 
                                             Region__c, 
                                             Municipality__c, 
                                             State__c, 
                                             //District_Type__c, 
                                             //Customer_Location__c, 
                                             //Delivery_Method__c, 
                                             //Delivery_Terms__c,
                                             BillingStreet, 
                                             BillingCity, 
                                             BillingState, 
                                             BillingPostalCode, 
                                             BillingCountry, 
                                             BillingStateCode, 
                                             BillingCountryCode, 
                                             BillingLatitude, 
                                             BillingLongitude, 
                                             BillingGeocodeAccuracy,  
                                             BillingToShipping__c,
                                             ShippingStreet, 
                                             ShippingCity, 
                                             ShippingState, 
                                             ShippingPostalCode, 
                                             ShippingCountry, 
                                             ShippingStateCode, 
                                             ShippingCountryCode, 
                                             ShippingLatitude, 
                                             ShippingLongitude, 
                                             ShippingGeocodeAccuracy, 
                                             Phone, 
                                             Fax, 
                                             AccountNumber, 
                                             Website, 
                                             Industry, 
                                             AnnualRevenue, 
                                             NumberOfEmployees, 
                                             Ownership, 
                                             Description, 
                                             Rating, 
                                             Site, 
                                             CurrencyIsoCode, 
                                             PersonContactId,
                                             IsPersonAccount,
                                             PersonMailingStreet, 
                                             PersonMailingCity, 
                                             PersonMailingState, 
                                             PersonMailingPostalCode, 
                                             PersonMailingCountry, 
                                             PersonMailingStateCode, 
                                             PersonMailingCountryCode, 
                                             PersonMailingLatitude, 
                                             PersonMailingLongitude, 
                                             PersonMailingGeocodeAccuracy, 
                                             MailingToBilling__c, 
                                             PersonOtherStreet, 
                                             PersonOtherCity, 
                                             PersonOtherState, 
                                             PersonOtherPostalCode, 
                                             PersonOtherCountry, 
                                             PersonOtherStateCode, 
                                             PersonOtherCountryCode, 
                                             PersonOtherLatitude, 
                                             PersonOtherLongitude, 
                                             PersonOtherGeocodeAccuracy, 
                                             PersonMobilePhone, 
                                             PersonHomePhone, 
                                             PersonOtherPhone, 
                                             PersonAssistantPhone, 
                                             PersonEmail, 
                                             PersonTitle, 
                                             PersonDepartment, 
                                             PersonAssistantName, 
                                             PersonLeadSource, 
                                             PersonBirthdate, 
                                             PersonHasOptedOutOfEmail, 
                                             PersonHasOptedOutOfFax, 
                                             PersonDoNotCall, 
                                             PersonLastCURequestDate, 
                                             PersonLastCUUpdateDate, 
                                             PersonEmailBouncedReason, 
                                             PersonEmailBouncedDate                      
                                    FROM Account 
                                    WHERE Id IN: accountIds]);  
        System.debug('--- AccountController - Accounts: '+accounts.size()); 
        return accounts;  
    }
    @AuraEnabled(cacheable=false)
    public static List<Account> getPersonAccounts(List<Id> AccountIds) {
        // Populate List from SOQL query on Account
        System.debug('--- Get AccountController - Person Accounts'); 
        List<Account> personAccounts = ([  SELECT  Id,
                                             Name,
                                             Type, 
                                             RecordTypeId, 
                                             ParentId, 
                                             BillingStreet, 
                                             BillingCity, 
                                             BillingState, 
                                             BillingPostalCode, 
                                             BillingCountry, 
                                             BillingStateCode, 
                                             BillingCountryCode, 
                                             BillingLatitude, 
                                             BillingLongitude, 
                                             BillingGeocodeAccuracy,  
                                             ShippingStreet, 
                                             ShippingCity, 
                                             ShippingState, 
                                             ShippingPostalCode, 
                                             ShippingCountry, 
                                             ShippingStateCode, 
                                             ShippingCountryCode, 
                                             ShippingLatitude, 
                                             ShippingLongitude, 
                                             ShippingGeocodeAccuracy, 
                                             Phone, 
                                             Fax, 
                                             AccountNumber, 
                                             Website, 
                                             Industry, 
                                             AnnualRevenue, 
                                             NumberOfEmployees, 
                                             Ownership, 
                                             Description, 
                                             Rating, 
                                             Site, 
                                             CurrencyIsoCode, 
                                             PersonContactId,
                                             IsPersonAccount,
                                             PersonMailingStreet, 
                                             PersonMailingCity, 
                                             PersonMailingState, 
                                             PersonMailingPostalCode, 
                                             PersonMailingCountry, 
                                             PersonMailingStateCode, 
                                             PersonMailingCountryCode, 
                                             PersonMailingLatitude, 
                                             PersonMailingLongitude, 
                                             PersonMailingGeocodeAccuracy, 
                                             PersonOtherStreet, 
                                             PersonOtherCity, 
                                             PersonOtherState, 
                                             PersonOtherPostalCode, 
                                             PersonOtherCountry, 
                                             PersonOtherStateCode, 
                                             PersonOtherCountryCode, 
                                             PersonOtherLatitude, 
                                             PersonOtherLongitude, 
                                             PersonOtherGeocodeAccuracy, 
                                             PersonMobilePhone, 
                                             PersonHomePhone, 
                                             PersonOtherPhone, 
                                             PersonAssistantPhone, 
                                             PersonEmail, 
                                             PersonTitle, 
                                             PersonDepartment, 
                                             PersonAssistantName, 
                                             PersonLeadSource, 
                                             PersonBirthdate, 
                                             PersonHasOptedOutOfEmail, 
                                             PersonHasOptedOutOfFax, 
                                             PersonDoNotCall, 
                                             PersonLastCURequestDate, 
                                             PersonLastCUUpdateDate, 
                                             PersonEmailBouncedReason, 
                                             PersonEmailBouncedDate, 
                                             AccountSource                             
                                    FROM Account 
                                    WHERE IsPersonAccount = true
                                    AND Id IN: accountIds]);  
        System.debug('--- AccountController - Person Accounts: '+personAccounts.size()); 
        return personAccounts;  
    }
    @AuraEnabled(cacheable=false)
    public static List<Account> getBusinessAccounts(List<Id> accountIds) {
        // Populate List from SOQL query on Account
        System.debug('--- AccountController - Get Business Accounts'); 
        List<Account> businessAccounts = ([  SELECT  Id,
                                             Name,
                                             Type, 
                                             RecordTypeId, 
                                             ParentId, 
                                             BillingStreet, 
                                             BillingCity, 
                                             BillingState, 
                                             BillingPostalCode, 
                                             BillingCountry, 
                                             BillingStateCode, 
                                             BillingCountryCode, 
                                             BillingLatitude, 
                                             BillingLongitude, 
                                             BillingGeocodeAccuracy,  
                                             ShippingStreet, 
                                             ShippingCity, 
                                             ShippingState, 
                                             ShippingPostalCode, 
                                             ShippingCountry, 
                                             ShippingStateCode, 
                                             ShippingCountryCode, 
                                             ShippingLatitude, 
                                             ShippingLongitude, 
                                             ShippingGeocodeAccuracy, 
                                             Phone, 
                                             Fax, 
                                             AccountNumber, 
                                             Website, 
                                             Industry, 
                                             AnnualRevenue, 
                                             NumberOfEmployees, 
                                             Ownership, 
                                             Description, 
                                             Rating, 
                                             Site, 
                                             CurrencyIsoCode,   
                                             AccountSource                          
                                    FROM Account 
                                    WHERE IsPersonAccount = false
                                    AND Id IN: accountIds]);  
        System.debug('--- AccountController - Business Accounts: '+businessAccounts.size()); 
        return businessAccounts;  
    }
    @AuraEnabled(cacheable=false)
    public static List<Account> getAccountAddresses() {
        // Populate List from SOQL query on Account
        System.debug('--- AccountController - Get Business Accounts'); 
        List<Account> Accounts = ([  SELECT  Id,
                                             Name, 
                                             AccountNumber,
                                             BillingStreet, 
                                             BillingCity, 
                                             BillingState, 
                                             BillingPostalCode, 
                                             BillingCountry, 
                                             BillingStateCode, 
                                             BillingCountryCode, 
                                             BillingLatitude, 
                                             BillingLongitude, 
                                             BillingGeocodeAccuracy,  
                                             ShippingStreet, 
                                             ShippingCity, 
                                             ShippingState, 
                                             ShippingPostalCode, 
                                             ShippingCountry, 
                                             ShippingStateCode, 
                                             ShippingCountryCode, 
                                             ShippingLatitude, 
                                             ShippingLongitude, 
                                             ShippingGeocodeAccuracy, 
                                             IsPersonAccount,
                                             PersonMailingStreet, 
                                             PersonMailingCity, 
                                             PersonMailingState, 
                                             PersonMailingPostalCode, 
                                             PersonMailingCountry, 
                                             PersonMailingStateCode, 
                                             PersonMailingCountryCode, 
                                             PersonMailingLatitude, 
                                             PersonMailingLongitude, 
                                             PersonMailingGeocodeAccuracy, 
                                             PersonOtherStreet, 
                                             PersonOtherCity, 
                                             PersonOtherState, 
                                             PersonOtherPostalCode, 
                                             PersonOtherCountry, 
                                             PersonOtherStateCode, 
                                             PersonOtherCountryCode, 
                                             PersonOtherLatitude, 
                                             PersonOtherLongitude, 
                                             PersonOtherGeocodeAccuracy                                             
                                    FROM Account 
                                    ORDER BY BillingCountry, BillingPostalCode]);  
        System.debug('--- AccountController - Accounts: '+Accounts.size()); 
        return Accounts;  
    }
}