force-app/main/default/objects/Account/fields/Business_Type_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_Attribute__c</fullName>
    <formula>IF(IsPersonAccount,&quot;Consumer&quot;,
IF(ISBLANK(TEXT( Business_Type__c )),TEXT(Type),TEXT( Business_Type__c)))</formula>
    <label>Business Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <formula>TEXT(BillingCountryCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Owner_Profit_Center__c</fullName>
    <formula>Owner.Profit_Center_Attribute__c</formula>
    <label>Owner Profit Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <description>VAT value respective to the corporate interface</description>
    <label>VAT-%</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Shows the Oportunity Number related to the Configuration Plan</description>
    <formula>Opportunity__r.Opportunity_Number__c</formula>
    <inlineHelpText>The Oportunity Number related to the Configuration Plan</inlineHelpText>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_Attribute__c</fullName>
    <description>Attribute to Identify the Type of Business</description>
    <formula>Text(Business_Type__c)</formula>
    <inlineHelpText>Attribute to Identify the Type of Business e.g. Consumer, Reseller, Project</inlineHelpText>
    <label>Business Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Account Billing Country)</description>
    <formula>TEXT( Account.BillingCountryCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Customer_Attribute__c</fullName>
    <formula>IF( NOT(ISNULL(Account.AccountNumber)), Account.AccountNumber,&quot;&quot;)</formula>
    <label>Customer Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District_Attribute__c.field-meta.xml
<CustomField>
    <fullName>District_Attribute__c</fullName>
    <formula>Account.District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Auto number to have a unique 8 digit number that links Sales Objects. Used as sales reference</description>
    <displayFormat>{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number OLD</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Organization_Attribute__c</fullName>
    <description>Level 1 Classification based on Organization</description>
    <formula>Owner.Organization_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 1 Classification based on Organization</inlineHelpText>
    <label>Organization Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Owner_Profit_Center__c</fullName>
    <description>Level 4 Classification based on Profit Center of the Owner</description>
    <formula>Owner.Profit_Center_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 4 Classification based on Profit Center of the Owner</inlineHelpText>
    <label>Owner Profit Center OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Territory_Attribute__c</fullName>
    <description>Attribute to Identify the Sales Area (based on Account Territory)</description>
    <formula>Territory2.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Sales Area</inlineHelpText>
    <label>Territory Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Cost Type</description>
    <formula>TEXT(PricebookEntry.Product2.Cost_Type__c)</formula>
    <inlineHelpText>Product Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Shows the Unique Opportunity Number this Item belongs to</description>
    <formula>Opportunity.Opportunity_Number__c</formula>
    <inlineHelpText>Shows the Unique Opportunity Number</inlineHelpText>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Cost_Multiplier__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Cost Multiplier OLD</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxCost__c.field-meta.xml
<CustomField>
    <fullName>fxCost__c</fullName>
    <description>Calculated Result of Base Price * Cost Multiplier * Quantity</description>
    <formula>IF(Cost_Multiplier__c &gt; 0,  fxUnitCost__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Line Item Cost</inlineHelpText>
    <label>fxCost</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxFactory__c.field-meta.xml
<CustomField>
    <fullName>fxFactory__c</fullName>
    <formula>IF(Factory_Multiplier__c &gt; 0, fxUnitFactoryPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fxFactory</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fxSales__c.field-meta.xml
<CustomField>
    <fullName>fxSales__c</fullName>
    <description>The ListPrice calculated from Base Price with a Sales Multiplier</description>
    <formula>IF( Sales_Multiplier__c &gt; 0,   fxUnitSalesPrice__c *  Quantity, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Price on the PriceList aka List Price</inlineHelpText>
    <label>fxSales</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <inlineHelpText>List Price</inlineHelpText>
    <label>List Price</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Shows the Oportunity Number related to the QuoteLineItem</description>
    <formula>Quote.Opportunity.Opportunity_Number__c</formula>
    <inlineHelpText>The Oportunity Number related to the QuoteLineItem</inlineHelpText>
    <label>Opportunity Number OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Sales_Margin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Margin__c</fullName>
    <formula>IF(Revenue__c&gt;0,(Gross_Profit__c / Revenue__c),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Margin OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityProductController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
public class OpportunityProductController {
    @AuraEnabled(cacheable=false)
    public static Opportunity getOpportunityRecord(Id opportunityId) {
        // Populate map from SOQL query on Opportunity
        System.debug('--- Get Data for Opportunity: '+opportunityId);
        Opportunity opportunityRecord = ([SELECT    Id, Name, Order_type__c, Type, //Information
                                                    StageName, isClosed, // Status
                                                    Amount, CurrencyIsoCode, // Totals
                                                    Pricebook2Id,SyncedQuoteId, //Pricing Records
                                                    Opportunity_Number__c, //RVN Number
                                                    Organization_Attribute__c,Country_Attribute__c,//Tier 1 Factory Prices
                                                    District_Attribute__c,Territory_Attribute__c,Business_Type_Attribute__c,//Tier 2 Product Costs
                                                    Owner_Profit_Center__c, Customer_Attribute__c, //Tier 3 Sales Prices   
                                                    closeDate,
                                                    AccountId,
                                                    Order__c,
                                                    ContractId,
                                                    OwnerId,
                                                    Account.VAT__c
                                    FROM Opportunity 
                                    WHERE Id = :opportunityId]);
        System.debug('--- Opportunity Record: '+opportunityRecord);
        return opportunityRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<OpportunityLineItem> getOpportunityLineItems(Id opportunityId) {
        // Populate map from SOQL query on OpportunityLineItem
        List<OpportunityLineItem> opportunityLineItems = ([SELECT  Id,
                                                            OpportunityId,
                                                            Product2Id,
                                                            Product2.ProductCode,
                                                            Quantity,
                                                            ListPrice,
                                                            UnitPrice,
                                                            CurrencyIsoCode
                                                            FROM OpportunityLineItem 
                                                            WHERE OpportunityId = :opportunityId]);
        System.debug('--- Opportunity Line Items: '+opportunityLineItems);                                         
        return opportunityLineItems;
    } 
    @AuraEnabled(cacheable=false)
    public static Map<String,OpportunityLineItem> getOpportunityLineItemMap(Id opportunityId,String currencyCode) {
        // Populate List from SOQL query on OpportunityLineItem
        Boolean isActive = True;
        System.debug('--- Get Opportunity Line Items for Opportunity '+opportunityId); 
        List<OpportunityLineItem> opportunityLineItems = ([SELECT  Id,
                                                            OpportunityId,
                                                            Product2Id,
                                                            Product2.ProductCode,
                                                            Quantity,
                                                            ListPrice,
                                                            UnitPrice,
                                                            CurrencyIsoCode
                                                            FROM OpportunityLineItem 
                                                            WHERE OpportunityId = :opportunityId]);
        System.debug('--- Existing Opportunity Line Items: '+opportunityLineItems.size()); 
        Map<String,OpportunityLineItem> oliMap = New Map<String,OpportunityLineItem>();     
        if (opportunityLineItems.size()>0) {                                
            for (OpportunityLineItem opportunityLineItem :opportunityLineItems) {
                String productCode = opportunityLineItem.Product2.ProductCode;
                String product2Id = opportunityLineItem.Product2Id;
                Decimal quantity = opportunityLineItem.Quantity;
                oliMap.put(productCode,opportunityLineItem);
            }
        }  
        return oliMap;  
    }

    @AuraEnabled
    public static List<ProductWrapper> getData(String recordId) {
        List<ProductWrapper> productsWrapper = new List<ProductWrapper>();
        List<OpportunityLineItem> opportunityLineItems = ([SELECT Id,
                OpportunityId,
                Product2Id,
                Product2.Name,
                Product2.ProductCode,
                Product2.Product_Group__c,
                Product2.Cost_Category__c,
                tolabel(Product2.Cost_Type__c),
                Quantity,
                UnitPrice,
                ListPrice,
                TotalPrice,
                CurrencyIsoCode
        FROM OpportunityLineItem
        WHERE OpportunityId = :recordId
        ]);

        Set<String> productGroups = new Set<String>();
        Map<String, Set<String>> productGroupToCostType = new Map<String, Set<String>>();
        Map<String, List<OpportunityLineItem>> productGroupAndCostToOLI = new Map<String, List<OpportunityLineItem>>();

        for (OpportunityLineItem oli : opportunityLineItems) {
            productGroups.add(oli.Product2.Product_Group__c);
            if (productGroupToCostType.get(oli.Product2.Product_Group__c) == null) {
                productGroupToCostType.put(oli.Product2.Product_Group__c, new Set<String>());
            }
            Set<String> current = productGroupToCostType.get(oli.Product2.Product_Group__c);
            current.add(oli.Product2.Cost_Type__c);
            productGroupToCostType.put(oli.Product2.Product_Group__c, current);

            String keyVal = oli.Product2.Product_Group__c + '-' + oli.Product2.Cost_Type__c;
            if (productGroupAndCostToOLI.get(keyVal) == null) {
                productGroupAndCostToOLI.put(keyVal, new List<OpportunityLineItem>());
            }
            List<OpportunityLineItem> currentOLIs = productGroupAndCostToOLI.get(keyVal);
            currentOLIs.add(oli);
            productGroupAndCostToOLI.put(keyVal, currentOLIs);
        }
        System.debug('aa: ' + productGroups);
        for (String prodGr : productGroupToCostType.keySet()) {
            ProductWrapper wrapper = new ProductWrapper();
            wrapper.name = prodGr;
            wrapper.productName = prodGr;
            Decimal listPrice = 0;
            Decimal salesPrice = 0;
            Decimal salesMargin = 0;
            List<ProductWrapper> children = new List<ProductWrapper>();
            for (String key : productGroupToCostType.get(prodGr)) {
                Decimal listPriceChild = 0;
                Decimal salesPriceChild = 0;
                Decimal salesMarginChild = 0;
                String keyVal = prodGr + '-' + key;
                ProductWrapper wrapperChild = new ProductWrapper();
                wrapperChild.name = key;
                wrapperChild.productName = key;
                List<ProductWrapper> children2ndLevel = new List<ProductWrapper>();
                for (OpportunityLineItem oliRecord : productGroupAndCostToOLI.get(keyVal)) {
                    ProductWrapper wrapperChild2nd = new ProductWrapper();
                    wrapperChild2nd.name = oliRecord.Id;
                    wrapperChild2nd.productName = oliRecord.Product2.Name;
                    wrapperChild2nd.factory = 1;
                    wrapperChild2nd.costs = 1;
                    wrapperChild2nd.listPrice = oliRecord.ListPrice.setScale(2);
                    listPrice += oliRecord.ListPrice;
                    listPriceChild += oliRecord.ListPrice;
                    wrapperChild2nd.salesPrice = oliRecord.UnitPrice.setScale(2);
                    salesPrice += oliRecord.UnitPrice;
                    salesPriceChild += oliRecord.UnitPrice;
                    wrapperChild2nd.salesMargin = oliRecord.TotalPrice.setScale(2);
                    salesMargin += oliRecord.TotalPrice;
                    salesMarginChild += oliRecord.UnitPrice;
                    wrapperChild2nd.discount = 1;
                    children2ndLevel.add(wrapperChild2nd);
                }
                wrapperChild.factory = 3;
                wrapperChild.costs = 4;
                wrapperChild.listPrice = listPriceChild.setScale(2);
                wrapperChild.salesPrice = salesPriceChild.setScale(2);
                wrapperChild.salesMargin = salesMarginChild.setScale(2);
                wrapperChild.discount = 8;
                wrapperChild.children = children2ndLevel;
                children.add(wrapperChild);
            }
            wrapper.children = children;
            wrapper.factory = 1;
            wrapper.costs = 2;
            wrapper.listPrice = listPrice.setScale(2);
            wrapper.salesPrice = salesPrice.setScale(2);
            wrapper.salesMargin = salesMargin.setScale(2);
            wrapper.discount = 6;
            productsWrapper.add(wrapper);
        }
        System.debug('bb: ' + productsWrapper);
        return productsWrapper;
    }
/*
    public class ProductWrapper {
        @AuraEnabled public String name {public get; public set;}
        @AuraEnabled public String productName {public get; public set;}
        @AuraEnabled public Decimal factory {public get; public set;}
        @AuraEnabled public Decimal costs {public get; public set;}
        @AuraEnabled public Decimal listPrice {public get; public set;}
        @AuraEnabled public Decimal listPriceName {public get; public set;}
        @AuraEnabled public Decimal salesPrice {public get; public set;}
        @AuraEnabled public Decimal salesMargin {public get; public set;}
        @AuraEnabled public Decimal discount {public get; public set;}
        @AuraEnabled public List<ProductWrapper> children {public get; public set;}
    }*/
    
    @AuraEnabled
    public static ResponseWrapper getData2(String recordId) {
        Opportunity opp = [SELECT Id,SyncedQuoteId FROM Opportunity WHERE Id = :recordId];
        Id quoteId = opp.SyncedQuoteId;
        List<ProductWrapper> productsWrapper = new List<ProductWrapper>();
        ProductWrapper summaryProduct = new ProductWrapper();
        ProductWrapper summaryProductWithVAT = new ProductWrapper();
        List<QuoteLineItem> quoteLineItems = ([SELECT Id, LineNumber, 
                                CurrencyIsoCode,
                                //Configuration__c, // Config this Item belongs to
                                QuoteId, // Parent Quote RecordId
                                Product2Id, // Product2 Entry
                                Product2.Name,
                                Product2.ProductCode,
                                Product2.Cost_Category__c, // Grouping on Cost Category
                                tolabel(Cost_Type__c) ,// Grouping on Cost Type
                                Product_Group__c, // Grouping on Cost Type
                                //PricebookEntryId, //Pricebook Entry
                                //OpportunityLineItemId, // (Synced) Opportunity Line Item
                                Quantity, // Amount 
                                ListPrice, // Pricebook Entry Price
                                UnitPrice, // Sales Price
                                fxCost__c,
                                fxFactory__c,
                                fxSales__c,
                                List_Price__c,
                                Discount, //% Discount
                                Discount__c, 
                                Sales_Margin__c,
                                Subtotal, // ?
                                TotalPrice //Quantity * SalesPrice
                                //Cost_Multiplier__c, // Lookup to Org Price Parameters
                                //Price_Multiplier__c, // Lookup to District Price Parameters
                                //Margin__c, // Total Price / Total Cost
                                //Hidden__c
                          FROM QuoteLineItem 
                          WHERE QuoteId = :quoteId 
                          ORDER BY Product2.Cost_Type__c]);

        Set<String> productGroups = new Set<String>();
        Map<String, Set<String>> productGroupToCostType = new Map<String, Set<String>>();
        Map<String, List<QuoteLineItem>> productGroupAndCostToQLI = new Map<String, List<QuoteLineItem>>();

        for (QuoteLineItem qli : quoteLineItems) {
            productGroups.add(qli.Product_Group__c); //Get the product group value (LGR,LGS ...)
            if (productGroupToCostType.get(qli.Product_Group__c) == null) {
                productGroupToCostType.put(qli.Product_Group__c, new Set<String>());
            }
            Set<String> current = productGroupToCostType.get(qli.Product_Group__c);
            current.add(qli.Cost_Type__c);
            productGroupToCostType.put(qli.Product_Group__c, current); //Map of product along with cost types

            String keyVal = qli.Product_Group__c + '-' + qli.Cost_Type__c;
            if (productGroupAndCostToQLI.get(keyVal) == null) {
                productGroupAndCostToQLI.put(keyVal, new List<QuoteLineItem>());
            }
            List<QuoteLineItem> currentQLIs = productGroupAndCostToQLI.get(keyVal);
            currentQLIs.add(qli);
            productGroupAndCostToQLI.put(keyVal, currentQLIs); //Map of keyval(prod-costtype, qli)
        }

        Decimal factorySum = 0;
        Decimal costsSum = 0;
        Decimal listPriceSum = 0;
        Decimal salesPriceSum = 0;
        Decimal salesMarginSum = 0;

        System.debug('aa: ' + productGroups);
        for (String prodGr : productGroupToCostType.keySet()) {
            //Product	Factory	Costs	List Price	Sales price	Sales margin	Discount %
            ProductWrapper wrapper = new ProductWrapper();
            wrapper.name = prodGr;
            wrapper.productName = prodGr;
            Decimal factory = 0.00;
            Decimal costs = 0.00;
            Decimal listPrice = 0;
            Decimal salesPrice = 0;
            Decimal salesMargin = 0;
            Decimal discount = 0;
            List<ProductWrapper> children = new List<ProductWrapper>();
            
            for (String key : productGroupToCostType.get(prodGr)) {
                Decimal factoryChild = 0.00;
            	Decimal costsChild = 0.00;
                Decimal listPriceChild = 0;
                Decimal salesPriceChild = 0;
                Decimal salesMarginChild = 0;
                Decimal discountChild = 0;
                String keyVal = prodGr + '-' + key;
                ProductWrapper wrapperChild = new ProductWrapper();
                wrapperChild.name = key;
                wrapperChild.productName = key;
                List<ProductWrapper> children2ndLevel = new List<ProductWrapper>();
                for (QuoteLineItem qliRecord : productGroupAndCostToQLI.get(keyVal)) {
                    ProductWrapper wrapperChild2nd = new ProductWrapper();
                    wrapperChild2nd.name = qliRecord.Id;
                    wrapperChild2nd.productName = qliRecord.Product2.Name;
                    wrapperChild2nd.factory = qliRecord.fxFactory__c.setScale(2);
                    factory += qliRecord.fxFactory__c;
                    factoryChild += qliRecord.fxFactory__c;
                    wrapperChild2nd.costs = qliRecord.fxCost__c.setScale(2);
                    costs += qliRecord.fxCost__c;
                    costsChild += qliRecord.fxCost__c;
                    wrapperChild2nd.listPrice = qliRecord.fxSales__c.setScale(2);
                    listPrice += qliRecord.fxSales__c;
                    listPriceChild += qliRecord.fxSales__c;
                    wrapperChild2nd.salesPrice = qliRecord.Subtotal.setScale(2);
                    salesPrice += qliRecord.Subtotal;
                    salesPriceChild += qliRecord.Subtotal;
                    if(qliRecord.Sales_Margin__c != null){
                        wrapperChild2nd.salesMargin = qliRecord.Sales_Margin__c.setScale(2);
                        salesMargin += qliRecord.Sales_Margin__c;
                        salesMarginChild += qliRecord.Sales_Margin__c;
                    }
                    if(qliRecord.Discount__c != null){
                    	wrapperChild2nd.discount = qliRecord.Discount__c;
                        discount += qliRecord.Discount__c;
                    	discountChild += qliRecord.Discount__c;
                    }
                    
                    children2ndLevel.add(wrapperChild2nd);
                    
                }
                wrapperChild.factory = factoryChild.setScale(2);
                wrapperChild.costs = costsChild.setScale(2);
                wrapperChild.listPrice = listPriceChild.setScale(2);
                wrapperChild.salesPrice = salesPriceChild.setScale(2);
                wrapperChild.salesMargin = salesMarginChild.setScale(2);
                wrapperChild.discount = discountChild.setScale(2);
                wrapperChild.children = children2ndLevel;
                children.add(wrapperChild);
            }
            wrapper.children = children;
            wrapper.factory = factory.setScale(2);
            wrapper.costs = costs.setScale(2);
            wrapper.listPrice = listPrice.setScale(2);
            wrapper.salesPrice = salesPrice.setScale(2);
            wrapper.salesMargin = salesMargin.setScale(2);
            wrapper.discount = discount.setScale(2);
            productsWrapper.add(wrapper);

            factorySum += factory;
            costsSum += costs;
            listPriceSum += listPrice;
            salesPriceSum += salesPrice;
            salesMarginSum += salesMargin;
        }
        System.debug('bb: ' + productsWrapper);

        ResponseWrapper wrapper = new ResponseWrapper();
        wrapper.products = productsWrapper;
        summaryProduct.factory = factorySum.setScale(2);
        summaryProduct.costs = costsSum.setScale(2);
        summaryProduct.listPrice = listPriceSum.setScale(2);
        summaryProduct.salesPrice = salesPriceSum.setScale(2);
        summaryProduct.salesMargin = salesMarginSum.setScale(2);
        wrapper.summaryProduct = summaryProduct;

        if (factorySum > 0) {
            summaryProductWithVAT.factory = (factorySum * 1.24).setScale(2);
        }
        if (costsSum > 0) {
            summaryProductWithVAT.costs = (costsSum * 1.24).setScale(2);
        }
        if (listPriceSum > 0) {
            summaryProductWithVAT.listPrice = (listPriceSum * 1.24).setScale(2);
        }
        if (salesPriceSum > 0) {
            summaryProductWithVAT.salesPrice = (salesPriceSum * 1.24).setScale(2);
        }
        if (salesMarginSum > 0) {
            summaryProductWithVAT.salesMargin = (salesMarginSum * 1.24).setScale(2);
        }

        wrapper.summaryProductWithVAT = summaryProductWithVAT;
        return wrapper;
    }

    public class ResponseWrapper {
        @AuraEnabled public List<ProductWrapper> products {public get; set;}
        @AuraEnabled public ProductWrapper summaryProduct {public get; set;}
        @AuraEnabled public ProductWrapper summaryProductWithVAT {public get; set;}
    }

    public class ProductWrapper {
        @AuraEnabled public String name {public get; public set;}
        @AuraEnabled public String productName {public get; public set;}
        @AuraEnabled public Decimal factory {public get; public set;}
        @AuraEnabled public Decimal costs {public get; public set;}
        @AuraEnabled public Decimal listPrice {public get; public set;}
        @AuraEnabled public Decimal listPriceName {public get; public set;}
        @AuraEnabled public Decimal salesPrice {public get; public set;}
        @AuraEnabled public Decimal salesMargin {public get; public set;}
        @AuraEnabled public Decimal discount {public get; public set;}
        @AuraEnabled public List<ProductWrapper> children {public get; public set;}
    }
}