force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <formula>TEXT(BillingCountryCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Account Billing Country)</description>
    <formula>TEXT( Account.BillingCountryCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Level 3 Classification based on District</description>
    <inlineHelpText>Level 3 Classification based on District</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LumonTestOpportunities.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-09-2023
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public with sharing class LumonTestOpportunities {
    @TestVisible private static Id pricebookId{
        get{
            return Test.getStandardPricebookId();
        }
    }
	@TestVisible private static Id b2cOpportunityId{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Account.IsPersonAccount = true AND Order_Type__c = 'Normal') LIMIT 1]?.Id;
        }
    }
    @TestVisible private static Opportunity b2cOpportunity{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Id =: b2cOpportunityId) LIMIT 1];
        }
    }
    @TestVisible private static Id b2cReclamationId{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Account.IsPersonAccount = true AND Order_Type__c = 'Reclamation') LIMIT 1]?.Id;
        }
    }
    @TestVisible private static List<Opportunity> b2cOpportunities{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Account.IsPersonAccount = true)];
        }
    }
    @TestVisible private static Id b2bOpportunityId{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Account.IsPersonAccount = false) LIMIT 1]?.Id;
        }
    }
     @TestVisible private static Opportunity b2bOpportunity{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Id =: b2bOpportunityId) LIMIT 1];
        }
    }
    @TestVisible private static List<Opportunity> b2bOpportunities{
        get{
            return [SELECT Id,Pricebook2Id,SyncedQuoteId,AccountId FROM Opportunity WHERE (Account.IsPersonAccount = false)];
        }
    }
    //@future 
    public static void setupOpportunityB2C(){
        LumonTestAccounts.setupAccountB2C();
        Id accountId = LumonTestAccounts.b2cAccountId;
        // Create B2C Opportunity
		setupOpportunityB2C(accountId,'LSU', 'FI_South', 'Consumer');
        System.debug('--- setupOpportunityB2C - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- setupOpportunityB2C - Queries used: '+LIMITS.getQueries());
    }
    //@future 
    public static void setupOpportunityB2C(Id accountId, String org, String district, String businessType){        
        // Create B2C Opportunity
        Opportunity b2cOpp = new Opportunity(Name=('B2C Opportunity '+org+' '+district+' '+businessType),
                                             Description = ('B2C Opportunity '+org+' '+district+' '+businessType), 
                                            StageName='Quoting',
                                            CloseDate=system.Today()+10,
                                            Pricebook2Id=pricebookId,
                                            AccountId = accountId,
                                            Organization__c = org,
                                            //Country_Attribute__c,
                                            Business_Type__c =businessType,
                                            District__c = district,
                                            Order_Type__c = 'Normal'
                                            );
        insert b2cOpp;
        System.debug('--- setupOpportunityB2C - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- setupOpportunityB2C - Queries used: '+LIMITS.getQueries());
    }
        //@future 
    public static void setupOpportunityB2B(){
        LumonTestAccounts.setupAccountB2B();
        Id accountId = LumonTestAccounts.b2bAccountId;
        // Create B2B Opportunity
		setupOpportunityB2B(accountId,'LSU', 'FI_South', 'Reseller');
        System.debug('--- setupOpportunityB2B - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- setupOpportunityB2B - Queries used: '+LIMITS.getQueries());
    }
    //@future 
    public static void setupOpportunityB2B(Id accountId, String org, String district, String businessType){        
        // Create B2B Opportunity
        Opportunity b2bOpp = new Opportunity(Name=('B2B Opportunity '+org+' '+district+' '+businessType),
                                             Description = ('B2B Opportunity '+org+' '+district+' '+businessType), 
                                            StageName='Quoting',
                                            CloseDate=system.Today()+30,
                                            Pricebook2Id=pricebookId,
                                            AccountId = accountId,
                                            Organization__c = org,
                                            //Country_Attribute__c,
                                            Business_Type__c =businessType,
                                            District__c = district,
                                            Order_Type__c = 'Normal'
                                            );
        insert b2bOpp;
        System.debug('--- setupOpportunityB2C - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- setupOpportunityB2C - Queries used: '+LIMITS.getQueries());
    }
    @IsTest
    static void setupOpportunityB2CTest(){
        String testResult;
        Test.startTest();
        Try {
            setupOpportunityB2C();
            testResult = 'successfully inserted B2C Opportunity';
            System.Debug('--- setupOpportunityB2CTest - Opportunity: '+b2cOpportunity);
        } catch (exception e){
            testResult = 'error when inserting B2C Opportunity: '+e.getMessage();
        }
        Test.stopTest();
        System.Debug('--- setupOpportunityB2CTest - Opportunity After Test: '+b2cOpportunity);
        System.AssertNotEquals(true, testResult.contains('error'));
    } 
    /*@IsTest
    static void setupOpportunityB2BTest(){
        String testResult;
        Test.startTest();
        Try {
            setupOpportunityB2B();
            testResult = 'successfully inserted B2B Opportunity';
            System.Debug('--- setupOpportunityB2BTest - Opportunity: '+b2bOpportunity);
        } catch (exception e){
            testResult = 'error when inserting B2B Opportunity: '+e.getMessage();
        }
        Test.stopTest();
        System.AssertNotEquals(true, testResult.contains('error'));
    } */
}