force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer Account</description>
    <inlineHelpText>Please choose the type of customer segment.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/B2B_Account.recordType-meta.xml
<RecordType>
    <fullName>B2B_Account</fullName>
    <active>true</active>
    <description>B2B Business account</description>
    <label>B2B Account</label>
</RecordType>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Delivery_Batch__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Batch</label>
    <referenceTo>Delivery_Batch__c</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Delivery_Batch__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Batch</label>
    <referenceTo>Delivery_Batch__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/Country_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Country Mapping</label>
    <pluralLabel>Country Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_Mapping__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/fields/CountryCodeAlpha2__c.field-meta.xml
<CustomField>
    <fullName>CountryCodeAlpha2__c</fullName>
    <label>Country Alpha2</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_Mapping__mdt/fields/CountryCodeAlpha3__c.field-meta.xml
<CustomField>
    <fullName>CountryCodeAlpha3__c</fullName>
    <label>CountryCodeAlpha3</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/Delivery_Batch__c.object-meta.xml
<CustomObject>
    <description>Contains details about project work part (delivery batch).</description>
    <label>Delivery Batch</label>
    <nameField>
        <displayFormat>DB-{00000000}</displayFormat>
        <label>Delivery Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Batch__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Delivery Batches</relationshipLabel>
    <relationshipName>DeliveryBatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <description>Id of the Delivery Batch from Salestori.</description>
    <label>Batch Id OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>Name of the Batch</description>
    <label>Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <description>Batch Number Reference in Opportunity</description>
    <label>Batch Number OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Batches</relationshipLabel>
    <relationshipName>LumonDeliveryBatches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Delivery_Date__c</fullName>
    <label>Planned Delivery OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Planned_Installation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Installation_End_Date__c</fullName>
    <label>Planned Installation End Date OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Planned_Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Installation_Start_Date__c</fullName>
    <label>Planned Installation Start Date OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/SalesToriUniqueKey__c.field-meta.xml
<CustomField>
    <fullName>SalesToriUniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>SalesToriUniqueKey OLD</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer opportunity</description>
    <inlineHelpText>Please choose which type of customer engagement is about.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate whether Opportunity can be updated</description>
    <label>IsLocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>This field is used to identify the opportunity in salesforce for the FSL</description>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/B2B_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>B2B_Opportunity</fullName>
    <active>true</active>
    <businessProcess>B2B Sales Process</businessProcess>
    <description>This is record type for B2B opportunities (Projects and Resellers)</description>
    <label>B2B Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/B2C_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>B2C_Opportunity</fullName>
    <active>true</active>
    <businessProcess>B2C Sales Process</businessProcess>
    <description>This is record type for B2C opportunities (Consumers)</description>
    <label>B2C Opportunity</label>
</RecordType>

force-app/main/default/objects/User/fields/AD_Short_Username__c.field-meta.xml
<CustomField>
    <fullName>AD_Short_Username__c</fullName>
    <description>AD Short Username</description>
    <inlineHelpText>AD Short Username OLD</inlineHelpText>
    <label>AD Short Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Delivery_Batch__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Delivery Batch for the Project work&apos;s Work Order.</description>
    <label>Delivery Batch OLD</label>
    <referenceTo>Delivery_Batch__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/SalesToriUniqueKey__c.field-meta.xml
<CustomField>
    <fullName>SalesToriUniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>SalesToriUniqueKey</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates if this is a new product installation work or something else. Note that in the new product installation work, the completion of the WOLI also creates new Asset.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Product installation</fullName>
            </value>
            <value>
                <fullName>Reclamation work</fullName>
            </value>
            <value>
                <fullName>Maintenance and Accessories</fullName>
            </value>
            <value>
                <fullName>Other work</fullName>
            </value>
            <value>
                <fullName>Internal Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Customer_Segments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>Consumer Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>Consumer Single House</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>Project construction</label>
    </customValue>
    <customValue>
        <fullName>4100</fullName>
        <label>Project renovation</label>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
        <label>Reseller project</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>Reseller consumer</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
        <label>Aftersales</label>
    </customValue>
    <masterLabel>Lumon Customer Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderMessageProcessor.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 06-19-2024
 * @last modified by  : Henk Reynders
**/
public class OrderMessageProcessor {
    public static String B2BOpportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('B2B_Opportunity').getRecordTypeId();
    public static String B2COpportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('B2C_Opportunity').getRecordTypeId();
    public static String B2BAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('B2B_Account').getRecordTypeId();
    public static String B2CAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
    
    
   	public static Map<String,Country_Mapping__mdt> countryMap = new Map<String,Country_Mapping__mdt>();
    public static List<Country_Mapping__mdt> countryMapList = [SELECT CountryCodeAlpha3__c, CountryCodeAlpha2__c ,Country_Name__c  FROM Country_Mapping__mdt];
    
    public static String processInboundOrderMessage (String orderMessageJSON){
        try{
            OrderData orderdata = OrderData.parse(orderMessageJSON);
            return 'OrderMessage Processed!';
        } catch(Exception e){            
            System.debug(e);
            return 'OrderMessage Processing Failed!';
        }
    }   
    public static OrderData.OrderMessage deserializeOrderMessage (String orderMessageJSON){
        
        OrderData.OrderMessage orderMessage = 
          (OrderData.OrderMessage)JSON.deserialize(orderMessageJSON, OrderData.OrderMessage.class);
          return orderMessage;
    }
    /*public static void getOrderDetails(OrderData.OrderMessage orderMessage){
        OrderData.OrderDetails orderDetails = orderMessage.orderDetails;
        OrderData.SalesPerson salesPersonDetails = orderDetails.sales_person;
        User salesPerson;
        User installationManager;
        String languagePreference;
        String leadSource;
        String currencyCode;
        Account existingAccount;
        if(countryMapList.size() > 0){
            for(Country_Mapping__mdt ctry : countryMapList){
                countryMap.put(ctry.CountryCodeAlpha3__c, ctry);
            }
        }
        // Step 1: Check for Account based on accountNumber
        existingAccount = findAccount(orderData);
        // Find Existing Salesforce Users to Assign
        installationManager = findUser(salesPersonDetails.supervisor); // Find User by Employee_Id Mepco_SuperVisor Id 
        salesPerson = findUser(salesPersonDetails.username); // Find User by Employee_Id

        languagePreference = String.isNotBlank(orderDetails.language_code) ? orderDetails.language_code : ''; // Use Default??
        leadSource = orderDetails.leadSource;
        currencyCode = orderDetails.currencyCode;
        
        
        Opportunity opportunityRecord = checkOpportunityRecord(orderData, existingAccount);
        
        Delivery_Batch__c deliveryBatchRecord = createDeliveryBatch(orderData,existingAccount,opportunityRecord);
        manageConfigurationPlanAndProduct(orderData,existingAccount,opportunityRecord,deliveryBatchRecord);
        
        WorkOrder workOrderRecord = createWorkOrder(orderData,existingAccount, opportunityRecord, deliveryBatchRecord);
        List<WorkOrderLineItem> woliList =  createWorkOrderLines( orderData, workOrderRecord, deliveryBatchRecord);
        
        Map<String,ContentDocumentLink> existingPDFMap = getExistingInstallationPDFFiles(woliList);
        createInstallationPDFFiles(orderData,existingPDFMap,woliList);
    }
    public static Account findAccount(String accountNumber){
        Account accountRecord = new Account();
        if(String.isNotBlank(accountNumber)) {
            List<Account> accounts = [SELECT Id,Name,AccountNumber,IsPersonAccount FROM Account Where AccountNumber =:accountNumber LIMIT 1 ];
            if(accounts?.size() >0){
                accountRecord  = accounts[0];
            }
        }
        return accountRecord;
    }
    public static Opportunity findOpportunity(InboundOrderData.Order orderData, Id accountId){
        opportunity opportunityRecord;
        String orderNumber = String.isNotBlank(orderData.order_info.order_number) ? orderData.order_info.order_number : ''; 
        List<Opportunity> opportunities = [SELECT Id,Name 
                                            FROM Opportunity 
                                            WHERE Account =: accountId 
                                                AND Order_Number__c =:orderNumber LIMIT 1 ];
        if(opportunities?.size() >0){
            System.debug('--- OrderMessageProcessor - findOpportunity - Opportunity Existing');
            opportunityRecord = opportunities[0];
        } else {
            System.debug('--- OrderMessageProcessor - findOpportunity - Creating New Opportunity');
            opportunityRecord =  createOpportunity(orderData, accountId);
        }
        return opportunityRecord;
    }
    public static User findUser(String adUserName){
        User userRecord = new User();
        List<User> users =[SELECT Id,Name FROM User WHERE AD_Short_Username__c =:adUserName LIMIT 1];
        if(users.size() > 0){
            userRecord = users[0]; 
        }
        return userRecord;
    }

    public static Opportunity createOpportunity(OrderData.OrderDetails orderDetails, Id accountId){
        Opportunity opportunityToCreate = new Opportunity();
        String accountName;
        List<Schema.PicklistEntry> values = Opportunity.Property_Type__c.getDescribe().getPicklistValues();
        Map<String,String> propertyApiToLabelMap = new Map<String,String>();
       
        for(Schema.PicklistEntry sp :values){
            //Map to hold Picklist API as Key and Picklist Label as Value
            propertyApiToLabelMap.put(sp.getLabel(),sp.getValue());
        }
        System.debug('*** propertyApiToLabelMap ***'+propertyApiToLabelMap);
        
        accountName = orderDetails.customer_address.customerName;
        opportunityToCreate.Name = existingAccount.Name; // Should not be Account Name
        opportunityToCreate.Customer_Segment__c = String.valueOf(orderData.order_info.customer_segmentid);
        opportunityToCreate.Order_Number__c = String.valueOf(orderData.order_info.order_number);
        opportunityToCreate.Order_Type__c = orderData.order_info.order_type;

        opportunityToCreate.AccountId =  existingAccount.Id;
        if(existingAccount.Business_Type__c == 'Consumer'){
            opportunityToCreate.recordtypeId = B2COpportunityRecordTypeId;
        }else{
            opportunityToCreate.recordtypeId = B2BOpportunityRecordTypeId;
        }
        
        opportunityToCreate.Property_Type__c  = propertyApiToLabelMap.get(orderData.order_info.propertytype);
        opportunityToCreate.OwnerId = salesPerson != NULL ? salesPerson.Id : UserInfo.getUserId();
        opportunityToCreate.closeDate = system.today().adddays(30);
        opportunityToCreate.IsLocked__c  = true;
        //opportunityToCreate.StageName ='Closed Won';
        upsert opportunityToCreate;
        //Database.UpsertResult upsertOpportunityResult = Database.upsert(opportunityRecord, Opportunity.Order_Number__c);
        return opportunityToCreate;
    }
    

    
    public static Delivery_Batch__c createDeliveryBatch(InboundOrderData.Order orderData, Account existingAccount, Opportunity opportunityRecord){
        System.debug('createDeliveryBatch');
        Delivery_Batch__c  delBatchRecord = new Delivery_Batch__c();
        delBatchRecord.Account__c = existingAccount.Id;
       	delBatchRecord.Batch_Id__c = orderData.groups.grouplist[0].OrderLine.DlvBatchID;
        delBatchRecord.Batch_number__c = Integer.valueOf(orderData.groups.grouplist[0].delivery_batch);
        delBatchRecord.Opportunity__c = opportunityRecord.Id;
        //////
        delBatchRecord.Planned_Installation_Address__City__s = orderData.order_info.install_address.city;
        delBatchRecord.Planned_Installation_Address__PostalCode__s = String.valueOf(orderData.order_info.install_address.postal_code);
        delBatchRecord.Planned_Installation_Address__Street__s = orderData.order_info.install_address.street_address;
        //////////////////
        delBatchRecord.SalesToriUniqueKey__c = String.valueOf(orderData.order_info.order_number)+orderData.groups.grouplist[0].delivery_batch;
        //delBatchRecord.Installation_address__CountryCode__s = countryMap.get(orderData.order_info.install_address.country);
        delBatchRecord.OwnerId = installationManager != NULL ? installationManager.Id : UserInfo.getUserId();
        if(orderData.groups.groupList.size() > 0 ){
            delBatchRecord.Planned_installation_start_date__c  = Date.parse(orderData.groups.groupList[0].install_start_date);
            delBatchRecord.Planned_installation_end_date__c  = Date.parse(orderData.groups.groupList[0].install_end_date);
            delBatchRecord.Planned_delivery_date__c  = Date.parse(orderData.groups.groupList[0].delivery_batch_delivery_date);
            delBatchRecord.Batch_Name__c = orderData.groups.grouplist[0].salestori_plan_name;
        }
        Database.UpsertResult upsertResult = Database.upsert(delBatchRecord, Delivery_Batch__c.SalesToriUniqueKey__c);
        return delBatchRecord;
    }
    
    public static void manageConfigurationPlanAndProduct(InboundOrderData.Order orderData, Account existingAccount, Opportunity opportunityRecord, Delivery_Batch__c delbatchRecord){
        Map<String,List<String>>  exisistingData = getExisitingConfigPlanMap(orderData.order_info.order_number);
        system.debug(exisistingData);
        List<String> configProdsToBeDeleted = new List<String>();
        List<configuration__c> configurationPlanList = new List<configuration__c>();
        List<Configuration_Product__c> configurationProductList = new List<Configuration_Product__c>();
        
        Map<String, List<InboundOrderData.GroupRecord>> configMap = getConfigurationPlanMap(orderData);
        for(String configKey: configMap.keySet()){
            List<String> rvns = new List<String>();
            if(exisistingData.containsKey(configKey)){
                rvns = exisistingData.get(configKey);
                exisistingData.remove(configKey);
            }
            
            List<InboundOrderData.GroupRecord> groupRecordList =  configMap.get(configKey);
            configurationPlanList.add(assignConfigurationPlan(groupRecordList[0],configKey, existingAccount, opportunityRecord, delbatchRecord));
            
            for(InboundOrderData.GroupRecord groupRecord :groupRecordList ){
                configurationProductList.add(assignConfigurationProduct(groupRecord ,configKey, rvns));
            }
            configProdsToBeDeleted.addAll(rvns);
        }
        
        
        List<Configuration_Product__c> configurationProducts =[SELECT id,Name from Configuration_Product__c where RVN_Number__c IN:configProdsToBeDeleted];
        delete configurationProducts;
        
        List<Configuration__c> configurationPlans =[SELECT id,Name,SalesToriConfigKey__c from Configuration__c where SalesToriConfigKey__c IN:exisistingData.keySet()];
        delete configurationPlans;
        
        List<Database.upsertResult> upsertConfigPlanResult = Database.upsert(configurationPlanList, configuration__c.SalesToriConfigKey__c);
        List<Database.upsertResult> upsertConfigProdResult = Database.upsert(configurationProductList, Configuration_Product__c.RVN_Number__c);
        
    }
    
    public static void getExistingContent(List<Configuration_Product__c> configurationProductList){
        Set<Id> configProdIds = new Set<Id>();
        Map<String,Id> fileToRVN = new Map<String,Id>();
        for(Configuration_Product__c cp : configurationProductList){
            configProdIds.add(cp.Id);
        }
        List<ContentDocumentLink> cdlsForRVNs = [SELECT ContentDocumentId,ContentDocument.title, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :configProdIds];
        if(cdlsForRVNs.size() > 0){
           for (ContentDocumentLink cdlRVN : cdlsForRVNs) {
                fileToRVN.put(cdlRVN.ContentDocument.title, cdlRVN.LinkedEntityId);
            }
        }
        
        
    }
    public static void createInstallationFiles(OrderData.Order orderData, Map<String,ContentDocumentLink> existingPDFMap, List<WorkOrderLineItem> woliList){
        
        // If the incoming file name already exists in the existing PDF then the file already exists in the system
        // Next step is to check is this file already part of a WOLI. If so is it the right WOLI ?
        //Map<Id,WorkOrderLineItem> woliListMap = new Map<Id,WorkOrderLineItem>(
            									//[SELECT Id,Configuration_Product__r.RVN_Number__c
                                                 //FROM WorkOrderLineItem 
                                                 //WHERE Id IN : woliList limit 1000]);
        
        
        List<ContentVersion> documentsToUpsert = new List<ContentVersion>();
        Set<String> fileNames = new Set<String>();
        for(InboundOrderData.GroupRecord groupRecord: orderData.groups.groupList){
            String attachment = groupRecord.AssemblyInstructions.Attachments.Attachment;
            String rvn = attachment.substringBefore('.pdf');
            rvn = rvn.RIGHT(16);
            System.debug('*** existingPDFMap.keyset ***'+existingPDFMap.keyset());
            System.debug('*** existingPDFMap.value ***'+existingPDFMap.get(attachment));
            for(WorkOrderLineItem wl : woliList){
                if(wl.RVN_Number__c  == rvn){
                   if(existingPDFMap.keyset().contains(groupRecord.AssemblyInstructions.Attachments.Attachment)){
                        ContentVersion cv = new ContentVersion();
                        cv.Title = attachment;
                        cv.ContentLocation= 's';
                        cv.ContentDocumentId = existingPDFMap.get(attachment).ContentDocumentId;
                        cv.PathOnClient= attachment;
                        cv.VersionData = Blob.valueOf('test');
                        cv.RVN_Number__c = rvn;
                        fileNames.add(rvn);
                        documentsToUpsert.add(cv);
                       // createInstallationPDFFiles(groupRecord,existingPDFMap, woliList);
                    }else {
                        ContentVersion cv = new ContentVersion();
                        cv.Title = attachment;
                        cv.ContentLocation= 's';
                        cv.PathOnClient= attachment;
                        cv.VersionData = Blob.valueOf('test');
                        cv.RVN_Number__c = rvn;
                        fileNames.add(rvn);
                        documentsToUpsert.add(cv);
                    } 
                }
            }
        }
        System.debug('*** documentsToUpsert ***'+documentsToUpsert);
        System.debug('*** fileNames ***'+fileNames);
        List<Database.UpsertResult> upsertContentForIC = Database.upsert(documentsToUpsert);
        List<ContentVersion> docs = [SELECT ContentDocumentId, Title, PathOnClient,RVN_Number__c FROM ContentVersion WHERE RVN_Number__c IN: fileNames and IsLatest = TRUE];
        
        List<ContentDocumentLink> contDocLinks = new List<ContentDocumentLink>();
        Map<Id,ContentDocumentLink> cdlMap = new Map<Id,ContentDocumentLink>();
        Map<String,WorkOrderLineItem> woliMap = new Map<String,WorkOrderLineItem>();
        
        Set<Id> conDocIds = new Set<Id>();
        for(ContentVersion cv1 : docs){
            conDocIds.add(cv1.ContentDocumentId);
        }
        
        // Get the content versions that has been upserted
        // Get contentdocumentlinks for that contentdocumentids
        // Store them in a map with contentdocumentid, rvn
        // If there is an existing cdl then no actions needed for that contentdocument
        // If there is no existing cdl then new cdl has to be created where the content version will be linked to the WOLI for that rvn
        if (conDocIds.size() > 0) {
            List<ContentDocumentLink> documentLinks = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId IN:conDocIds and LinkedEntityId in ( SELECT Id FROM WorkOrderLineItem)];
            List<WorkOrderLineItem> woliItems = [SELECT Id,RVN_Number__c FROM WorkOrderLineItem WHERE RVN_Number__c IN: fileNames];
            for(ContentDocumentLink cdl : documentLinks){
                cdlMap.put(cdl.ContentDocumentId,cdl);
            }
            System.debug('*** cdlMap ***'+cdlMap);
            for(WorkOrderLineItem wli : woliItems){
                woliMap.put(wli.RVN_Number__c,wli);
            }
			          
            for (ContentVersion statsFile : docs) {
                System.debug('*** cdlMap keyset ***'+cdlMap.keyset());
                System.debug('*** statsFile.ContentDocumentId ***'+statsFile.ContentDocumentId);
                if(cdlMap.keyset().contains(statsFile.ContentDocumentId) && !(String.valueOf(cdlMap.get(statsFile.ContentDocumentId).LinkedEntityId).startsWith('005'))){
                    System.debug('*** cdl already exists ***');
                }else{
                    if(woliMap.keyset().contains(statsFile.RVN_Number__c)){
                        contDocLinks.add(new ContentDocumentLink(ContentDocumentId = statsFile.ContentDocumentId, ShareType = 'V', LinkedEntityId = woliMap.get(statsFile.RVN_Number__c).Id));
                    }
                    System.debug('*** cdl not exists ***');
                }
                
                system.debug('contDocLinks---'+contDocLinks);
            }
        }
        
        if (!contDocLinks.isEmpty()) {
            upsert contDocLinks;
        }
    }
    
    // Method to create configurationPlan
    public static configuration__c assignConfigurationPlan(InboundOrderData.GroupRecord groupRecord, String uniqueKey, Account existingAccount, Opportunity opportunityRecord, Delivery_Batch__c delbatchRecord){
        
        configuration__c configPlanRecord = new configuration__c();
        configPlanRecord.Account__c = existingAccount.Id;
        configPlanRecord.Name = groupRecord.salestori_plan_name;
        configPlanRecord.Opportunity__c = opportunityRecord.Id;
        configPlanRecord.Delivery_Batch__c= delbatchRecord.Id;
        configPlanRecord.SalesToriConfigKey__c = uniqueKey;
        configPlanRecord.OwnerId = salesPerson != NULL ? salesPerson.Id : UserInfo.getUserId();
        return configPlanRecord;
    }
    // Method to create configuration Plan
    public static Map<String, List<InboundOrderData.GroupRecord>> getConfigurationPlanMap(InboundOrderData.Order orderData){
        Map<String, List<InboundOrderData.GroupRecord>> configMap = new Map<String, List<InboundOrderData.GroupRecord>>();
        for(InboundOrderData.GroupRecord groupRecord: orderData.groups.groupList){
            String uniqueKey = orderData.order_info.order_number+groupRecord.delivery_batch+groupRecord.unit+groupRecord.line+groupRecord.floor;
            if(!configMap.containsKey(uniqueKey)){
                configMap.put(uniqueKey, new List<InboundOrderData.GroupRecord>{groupRecord});
            }else{
                configMap.get(uniqueKey).add(groupRecord);
            }
        }
        return configMap;
    }
    
    // Method to create configuration product
    public static Configuration_Product__c assignConfigurationProduct(InboundOrderData.GroupRecord groupRecord, String configurationKey, List<String> rvnList){
        
        Configuration_Product__c  configProdRecord = new Configuration_Product__c ();
        Configuration__c configurationRecord = new Configuration__c(SalesToriConfigKey__c = configurationKey);
        configProdRecord.Configuration__r = configurationRecord;
        //Product2 productRecord = new Product2(Sales_Code__c= String.valueOf(groupRecord.OrderLine.ItemID)); 
        Product2 productRecord = [SELECT Id,Name,Product_Group__c from Product2 where Sales_Code__c = : String.valueOf(groupRecord.OrderLine.ItemID) limit 1];
        
        if(productRecord != NULL){
            configProdRecord.Product__c = productRecord.Id;
            configProdRecord.Name = productRecord.Name;
            configProdRecord.Product_Group__c = productRecord.Product_Group__c;
            configProdRecord.Delivery_Batch__c = Integer.valueOf(groupRecord.delivery_batch);
        }
        configProdRecord.Quantity__c   = 1.00;
        configProdRecord.RVN_Number__c = String.valueOf(groupRecord.OrderLine.BOMVersion);
        configProdRecord.Plan_Line__c =  String.valueOf(groupRecord.OrderLine.Line);
        configProdRecord.Plan_Floor__c  = !String.isBlank(groupRecord.OrderLine.Floor) ? Integer.valueOf(groupRecord.OrderLine.Floor) : 0 ;
        configProdRecord.Plan_Apartment__c  = groupRecord.OrderLine.Apartment;
        if(rvnList.contains(groupRecord.OrderLine.BOMVersion)){
            rvnList.remove(rvnList.indexOf(groupRecord.OrderLine.BOMVersion));
        }
        return configProdRecord;
    }
    // Method to create work order
    public static WorkOrder createWorkOrder(InboundOrderData.Order orderData,  Account existingAccount, Opportunity opportunityRecord,  Delivery_Batch__c delbatchRecord){
        WorkOrder workRecord = new WorkOrder();
        workRecord.AccountId = existingAccount.Id;
        workRecord.Opportunity__c = opportunityRecord.Id;
        workRecord.Delivery_Batch__c = delbatchRecord.Id;
        workRecord.IsIntegrationData__c =true;
        workRecord.OwnerId = installationManager != NULL ? installationManager.Id : UserInfo.getUserId();
        workRecord.SalesToriUniqueKey__c = delbatchRecord.SalesToriUniqueKey__c;
        workRecord.Soft_Reserved_Date__c  = Date.parse(orderData.groups.groupList[0].install_start_date);
        workRecord.StartDate = Date.parse(orderData.groups.groupList[0].install_start_date);
        workRecord.EndDate = Date.parse(orderData.groups.groupList[0].install_end_date);
        workRecord.City = orderData.order_info.install_address.city;
        System.debug('*** countryMap.get(orderData.order_info.install_address.country) ***'+countryMap.get(orderData.order_info.install_address.country).Country_Name__c);
        workRecord.Country = countryMap.get(orderData.order_info.install_address.country).Country_Name__c ;
        workRecord.PostalCode = String.valueOf(orderData.order_info.install_address.postal_code);
        workRecord.Street = orderData.order_info.install_address.street_address;
        database.upsert(workRecord,WorkOrder.SalesToriUniqueKey__c);
        return workRecord;
    }
    
    public static List<WorkOrderLineItem> createWorkOrderLines(InboundOrderData.Order orderData, WorkOrder workRecord, Delivery_Batch__c delbatchRecord){
        Map<String, WorkOrderLineItem> workOrderLineMaps = getExisitingWorkOrderLines(delbatchRecord.SalesToriUniqueKey__c);
        List<WorkOrderLineItem> workOrderLineListToUpdate = new List<WorkOrderLineItem>();
        System.debug('createWorkOrderLines');
        for(InboundOrderData.GroupRecord groupRecord: orderData.groups.groupList){
            WorkOrderLineItem workLineRecord = new WorkOrderLineItem();
            workLineRecord.WorkOrderId = workRecord.Id;
            Configuration_Product__c configProduct = new Configuration_Product__c(RVN_Number__c = String.valueOf(groupRecord.OrderLine.BOMVersion));
            WorkType wType = [SELECT Id,Type__c from WorkType where Type__c = 'New Product installation' limit 1]; 
            workLineRecord.Configuration_Product__r = configProduct;
            //workLineRecord.Line__c = String.valueof(groupRecord.OrderLine.Line);
            //workLineRecord.Floor__c = !String.isBlank(groupRecord.OrderLine.Floor) ? Integer.valueOf(groupRecord.OrderLine.Floor) : 0 ;
            //workLineRecord.Apartment_Number__c = groupRecord.OrderLine.Apartment;
            workLineRecord.RVN_Number__c  = String.valueOf(groupRecord.OrderLine.BOMVersion);
            workLineRecord.Is_installable__c  = TRUE;
            workLineRecord.WorkType = wType;
            workLineRecord.Duration = Decimal.valueOf(groupRecord.OrderLine.InstallHours);
            workLineRecord.DurationType = 'Hours';
            workLineRecord.StartDate  = Date.parse(groupRecord.install_start_date);
            workLineRecord.EndDate  = Date.parse(groupRecord.install_end_date);
            if(workOrderLineMaps.containsKey(groupRecord.OrderLine.BOMVersion)){
                workLineRecord.Id = workOrderLineMaps.get(groupRecord.OrderLine.BOMVersion).Id;
            }
            workOrderLineListToUpdate.add(workLineRecord);
        }
        System.debug('workOrderLineListToUpdate'+workOrderLineListToUpdate);
        Database.UpsertResult[] saveResult = Database.upsert(workOrderLineListToUpdate,false) ;
        System.debug('saveResult'+saveResult);
        for (Database.UpsertResult sr : saveResult) {
            if(sr.isSuccess()){
                System.debug('*** sr ***'+sr);
                delbatchRecord.Batch_Status__c = 'Data imported';
            }else{
                delbatchRecord.Batch_Status__c = 'New';
            }
        }
        System.debug('*** delbatchRecord.Batch_Status__c ***'+delbatchRecord.Batch_Status__c);
        update delbatchRecord;
        return workOrderLineListToUpdate;
    }
    
    
    public static Map<String,List<String>> getExisitingConfigPlanMap(String orderNumber){
        Map<String,List<String>> exsistingConfigProdMap = new Map<String,List<String>>();
        List<Configuration__c> configurationRecords = [SELECT Id,Name,Opportunity__c,Opportunity__r.order_number__c,SalesToriConfigKey__c,
                                                       (SELECT ID,Name,RVN_Number__c FROM configuration_Products__r) 
                                                       FROM Configuration__c  WHERE Opportunity__r.order_number__c != null ];
        
        for(Configuration__c configPlan: configurationRecords){
            List<String> productRvns = new List<String>();
            for(configuration_Product__c configProd:  configPlan.configuration_Products__r){
                productRvns.add(configProd.RVN_Number__c);
            }
            exsistingConfigProdMap.put(configPlan.SalesToriConfigKey__c, productRvns);
        }
        return exsistingConfigProdMap;
    }
    
    public static Map<String, WorkOrderLineItem> getExisitingWorkOrderLines(String salesToriKey){
        Map<String, WorkOrderLineItem> workOrderLineItemMap = new  Map<String, WorkOrderLineItem>();
        List<WorkOrderLineItem> workOrderLineItems = [SELECT Id, Configuration_Product__c,Configuration_Product__r.RVN_Number__c,
                                                      WorkOrder.SalesToriUniqueKey__c, WorkOrderId, WorkOrder.Delivery_Batch__r.SalesToriUniqueKey__c  
                                                      FROM WorkOrderLineItem WHERE WorkOrder.Delivery_Batch__r.SalesToriUniqueKey__c =:salesToriKey];
        
        for(WorkOrderLineItem workLineRecord : workOrderLineItems){
            if(workLineRecord.Configuration_Product__c != null && workLineRecord.Configuration_Product__r.RVN_Number__c != null
               && !workOrderLineItemMap.containsKey(workLineRecord.Configuration_Product__r.RVN_Number__c)){
                   workOrderLineItemMap.put(workLineRecord.Configuration_Product__r.RVN_Number__c, workLineRecord);
               }
        }
        return workOrderLineItemMap;
    }
    

    
    public static Account createAccountRecord(InboundOrderData.Customer_address custAddress){
        System.debug('*** acc country ***'+countryMap.get(custAddress.country).CountryCodeAlpha2__c);
        try{
            Account b2cAcc = new Account(
            RecordTypeID=B2CAccountRecordTypeId,
            FirstName= custAddress.firstname,
            LastName= custAddress.lastname,
            PersonEmail= custAddress.email,
            PersonMobilePhone = custAddress.phone_number,
            PersonMailingCity= custAddress.city,
           	PersonMailingCountryCode = countryMap.get(custAddress.country).CountryCodeAlpha2__c,
            PersonMailingPostalCode = custAddress.postal_code,
            PersonMailingStreet= custAddress.street_address,
            District__c = custAddress.city,
            Language_Preference__c = langPrefered,
            PersonLeadSource = leadSource,
            Business_Type__c = 'Consumer',
            CurrencyIsoCode	= currency_Z,
            OwnerId = salesPerson.Id);
        	Database.SaveResult saveResult =  Database.insert(b2cAcc,false) ;
            System.debug('saveResult: ' + saveResult);
            if (!saveResult.isSuccess()) {
                List<Database.Error> error = saveResult.getErrors();
                if (error[0] instanceof Database.DuplicateError) {
                    Database.DuplicateError duplicateError = (Database.DuplicateError)error[0];
                    Datacloud.DuplicateResult duplicateResult = duplicateError.getDuplicateResult();
                    Datacloud.MatchResult[] matchResults = duplicateResult.getMatchResults();
                    Datacloud.MatchResult matchResult = matchResults[0];
                    System.debug('matchResult: ' + matchResult);
                    Datacloud.MatchRecord[] matchRecords = matchResult.getMatchRecords();
                    for (Datacloud.MatchRecord matchRecord : matchRecords) {
                        System.debug('MatchRecord: ' + (Account)matchRecord.getRecord());
                        b2cAcc = (Account)matchRecord.getRecord();
                    }
                }
                return b2cAcc;
            }else{
                return b2cAcc;
            }
            
        }catch(Exception e){
            return null;
        }
    }
    

	
	public static Map<String,ContentDocumentLink> getExistingInstallationPDFFiles(List<WorkOrderLineItem> woliList){
        Set<Id> woliIds = new Map<Id, WorkOrderLineItem>(woliList).keySet();
        Map<String,ContentDocumentLink> fileToWOLI = new Map<String,ContentDocumentLink>();
        List<ContentDocumentLink> cdlsForWOLI = [SELECT Id, ContentDocumentId,
                                                 ContentDocument.Title,LinkedEntityId
                                             	 FROM ContentDocumentLink WHERE LinkedEntityId IN :woliIds LIMIT 10000];
        
        if(cdlsForWOLI.size() > 0){
           for (ContentDocumentLink cdl : cdlsForWOLI) {
                fileToWOLI.put(cdl.ContentDocument.title, cdl);
            }
        }
       	return fileToWOLI;
    }
    public Static CustomException__c assignCustomException(String className, String message,double LineNumber,String methodName,String type, boolean doInsert){
        CustomException__c  customException = new CustomException__c ();
        customException.ClassName__c = className;
        customException.Exception_Message__c = message;
        customException.Line_Number__c = lineNumber; 
        customException.MethodName__c = methodName; 
        customException.Exception_Type__c = type;
        if(doInsert){
            insert customException;
        }
        return customException;
    }*/
    
}