force-app/main/default/objects/Account/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Installation Address Country)</description>
    <formula>TEXT(ShippingCountryCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DistrictAttribute__c.field-meta.xml
<CustomField>
    <fullName>DistrictAttribute__c</fullName>
    <formula>District__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Offices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ServiceAttribute__c.field-meta.xml
<CustomField>
    <fullName>ServiceAttribute__c</fullName>
    <formula>SUBSTITUTE(TRIM(
IF(NOT(ISBLANK(OrganizationAttribute__c )),OrganizationAttribute__c ,&apos;&apos;)
+IF(NOT(ISBLANK(CountryAttribute__c )),&apos;_&apos;+CountryAttribute__c ,&apos;&apos;)
+IF(NOT(ISBLANK( DistrictAttribute__c )),&apos;_&apos;+ SUBSTITUTE(DistrictAttribute__c , CountryAttribute__c+&apos;_&apos;, &apos;&apos;) ,&apos;&apos;)
+IF(NOT(ISBLANK( ProfitCenterAttribute__c )),&apos;_&apos;+ProfitCenterAttribute__c ,&apos;&apos;)
+IF(NOT(ISBLANK( OfficeAttribute__c )),&apos;_&apos;+SUBSTITUTE(OfficeAttribute__c , CountryAttribute__c+&apos;-&apos;, &apos;&apos;),&apos;&apos;)
+IF(NOT(ISBLANK( CustomerSegmentAttribute__c )),&apos;_&apos;+CustomerSegmentAttribute__c ,&apos;&apos;)
+IF(AND(ISBLANK( CustomerSegmentAttribute__c ),NOT(ISBLANK( BusinessTypeAttribute__c ))),&apos;_&apos;+BusinessTypeAttribute__c ,&apos;&apos;)
),&apos; &apos;, &apos;_&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Installation Address Country)</description>
    <formula>TEXT(OfficeAddress__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenterAttribute__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenterAttribute__c</fullName>
    <formula>TEXT( ProfitCenter__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Center Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessTypeAttribute__c.field-meta.xml
<CustomField>
    <fullName>BusinessTypeAttribute__c</fullName>
    <description>Attribute to Identify the Type of Business</description>
    <formula>Text(BusinessType__c)</formula>
    <inlineHelpText>Attribute to Identify the Type of Business e.g. Consumer, Reseller, Project</inlineHelpText>
    <label>Business Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CountryAttribute__c.field-meta.xml
<CustomField>
    <fullName>CountryAttribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Installation Address Country)</description>
    <formula>TEXT(DeliveryAddress__CountryCode__s)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CurrentOfferNumber__c.field-meta.xml
<CustomField>
    <fullName>CurrentOfferNumber__c</fullName>
    <description>Shows the Offer Number of the current Syncing Quote</description>
    <formula>NULLVALUE( Order_Number__c,SyncedQuote.OfferNumber__c)</formula>
    <inlineHelpText>The Offer Number of Synced Quote</inlineHelpText>
    <label>Current Offer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CustomerAddress__c.field-meta.xml
<CustomField>
    <fullName>CustomerAddress__c</fullName>
    <label>Customer Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CustomerSegment__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegment__c</fullName>
    <description>This selection segments the customer opportunity</description>
    <inlineHelpText>Please choose which type of customer engagement is about.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CustomerSegmentAttribute__c.field-meta.xml
<CustomField>
    <fullName>CustomerSegmentAttribute__c</fullName>
    <formula>TEXT(CustomerSegment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Segment Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddress__c</fullName>
    <label>Delivery Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Level 3 Classification based on District</description>
    <inlineHelpText>Level 3 Classification based on District</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DistrictAttribute__c.field-meta.xml
<CustomField>
    <fullName>DistrictAttribute__c</fullName>
    <formula>TEXT(District__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InstallationAddress__c.field-meta.xml
<CustomField>
    <fullName>InstallationAddress__c</fullName>
    <label>Installation Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InvoicingAddress__c.field-meta.xml
<CustomField>
    <fullName>InvoicingAddress__c</fullName>
    <label>Invoicing Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isMigrated__c.field-meta.xml
<CustomField>
    <fullName>isMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Record is created in Salesforce or Migrated</description>
    <label>isMigrated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Opportunities (Office)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OfficeAttribute__c.field-meta.xml
<CustomField>
    <fullName>OfficeAttribute__c</fullName>
    <formula>TEXT(Office__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityNumber__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNumber__c</fullName>
    <description>Auto number to have a unique 8 digit number that links Sales Objects. Used as sales reference</description>
    <displayFormat>8-{0000000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OrganizationAttribute__c.field-meta.xml
<CustomField>
    <fullName>OrganizationAttribute__c</fullName>
    <formula>TEXT(Organization__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organization Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProfitCenterAttribute__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenterAttribute__c</fullName>
    <formula>TEXT( ProfitCenterCode__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit Center Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PropertyTypeAttribute__c.field-meta.xml
<CustomField>
    <fullName>PropertyTypeAttribute__c</fullName>
    <description>Level 6 Classification based on Property Type</description>
    <formula>Text(PropertyType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 6 Classification based on Property Type</inlineHelpText>
    <label>Property Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ServiceAttribute__c.field-meta.xml
<CustomField>
    <fullName>ServiceAttribute__c</fullName>
    <formula>/* Field Service Area Oppty Field*/ 
/* Service Attribute LSU_FI_45130_1000 */
SUBSTITUTE(
	TRIM(
		/* 1. Organization - LSU */
		IF(NOT(ISBLANK(OrganizationAttribute__c)),
			OrganizationAttribute__c ,&apos;&apos;)
		/* 2. Country - LSU_FI */
		+IF(AND(NOT(ISBLANK(CountryAttribute__c)),NOT(ISBLANK(OrganizationAttribute__c ))),
			&apos;_&apos;+CountryAttribute__c ,&apos;&apos;)
		+IF(AND(NOT(ISBLANK(CountryAttribute__c )),ISBLANK(OrganizationAttribute__c )),
			CountryAttribute__c ,&apos;&apos;)
		/* 3. District/Sales Area - LSU_FI_South */
		+IF(AND(NOT(ISBLANK(DistrictAttribute__c )),NOT(ISBLANK(CountryAttribute__c )),ISBLANK(ProfitCenterAttribute__c ),ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+ SUBSTITUTE(DistrictAttribute__c, CountryAttribute__c+&apos;_&apos;, &apos;&apos;) ,&apos;&apos;)
		/* 4. Profit Center - LSU_FI_402 */
		+IF(AND(NOT(ISBLANK(ProfitCenterAttribute__c )),ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+ProfitCenterAttribute__c ,&apos;&apos;)
			
		/* 5. Office - LSU_FI_402_12345 */
		+IF(NOT(ISBLANK(OfficeAttribute__c)),
			&apos;_&apos;+SUBSTITUTE(OfficeAttribute__c , CountryAttribute__c+&apos;-&apos;, &apos;&apos;),&apos;&apos;)
		/* 6. Business Type - LSU_FI_402_12345_1 */
		+IF(AND(NOT(ISBLANK( BusinessTypeAttribute__c )),ISBLANK(CustomerSegmentAttribute__c ),ISBLANK(CustomerSegmentAttribute__c )),
			&apos;_&apos;+BusinessTypeAttribute__c ,&apos;&apos;)
		/* 7. Customer Segment - LSU_FI_402_12345_1100 */
		+IF(NOT(ISBLANK(CustomerSegmentAttribute__c)),
			&apos;_&apos;+CustomerSegmentAttribute__c ,&apos;&apos;)
	),
&apos; &apos;, &apos;_&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Customer_Segments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>Consumer Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>Consumer Single House</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>Project construction</label>
    </customValue>
    <customValue>
        <fullName>4100</fullName>
        <label>Project renovation</label>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
        <label>Reseller project</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>Reseller consumer</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
        <label>Aftersales</label>
    </customValue>
    <masterLabel>Lumon Customer Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-04-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class OpportunityController {
    @AuraEnabled(cacheable=false)
    public static Opportunity getOpportunityRecord(Id opportunityId) {
        // Populate map from SOQL query on Opportunity
        List<Id> recordIds = new List<Id>{opportunityId};
        List<Opportunity> opportunities = getOpportunities(recordIds);
        Opportunity opportunityRecord = opportunities[0];
        System.debug('--- OpportunityController - Opportunity Record: '+opportunityRecord);
        return opportunityRecord;
    } 
    @AuraEnabled(cacheable=false)
    public static Opportunity getOpportunityByNumber(String opportunityNumber) {
        // Populate List from SOQL query on Account
        Id opportunityId = [SELECT Id FROM Opportunity WHERE OpportunityNumber__c =: opportunityNumber LIMIT 1]?.Id; 
        List<Id> opportunityIds = new List<Id>();
        opportunityIds.add(opportunityId);
        Opportunity opportunity = new Opportunity();
        List<Opportunity> opportunities =  getOpportunities(opportunityIds); 
        if  (opportunities?.size()>0) {
            opportunity = opportunities[0];
            System.debug('--- OpportunityController - Opportunity: '+opportunity.Name); 
        }        
        return opportunity;
    }
    @AuraEnabled(cacheable=false)
    public static List<Opportunity> getOpportunities(List<Id> recordIds) {
        // Populate map from SOQL query on Opportunity
        List<Opportunity> opportunities = ([SELECT  Id, Name, 
                                                        AccountId,                                                           
                                                        ContractId,
                                                        OwnerId,
                                                        Type, //Information
                                                        StageName, 
                                                        CloseDate,isClosed, // Status
                                                        Amount, CurrencyIsoCode, // Totals                                                       
                                                        Pricebook2Id,
                                                        SyncedQuoteId, CurrentOfferNumber__c,
                                                        OpportunityNumber__c,
                                                        isMigrated__c,
                                                        Account.BillingAddress, 
                                                        Account.ShippingAddress, 
                                                        Account.PersonMailingAddress, 
                                                        Account.PersonOtherAddress,
                                                        CustomerAddress__c, 
                                                        //CustomerAddress__Country__s,
                                                        CustomerAddress__CountryCode__s,
                                                        CustomerAddress__PostalCode__s,
                                                        CustomerAddress__Street__s,
                                                        CustomerAddress__City__s,
                                                        //CustomerAddress__State__s,
                                                        CustomerAddress__StateCode__s,
                                                        CustomerAddress__Latitude__s,
                                                        CustomerAddress__Longitude__s,
                                                        CustomerAddress__GeocodeAccuracy__s,
                                                        InvoicingAddress__c, 
                                                        //InvoicingAddress__Country__s,
                                                        InvoicingAddress__CountryCode__s,
                                                        InvoicingAddress__PostalCode__s,
                                                        InvoicingAddress__Street__s,
                                                        InvoicingAddress__City__s,
                                                        //InvoicingAddress__State__s,
                                                        InvoicingAddress__StateCode__s,
                                                        InvoicingAddress__Latitude__s,
                                                        InvoicingAddress__Longitude__s,
                                                        InvoicingAddress__GeocodeAccuracy__s,
                                                        DeliveryAddress__c,
                                                        //DeliveryAddress__Country__s,
                                                        DeliveryAddress__CountryCode__s,
                                                        DeliveryAddress__PostalCode__s,
                                                        DeliveryAddress__Street__s,
                                                        DeliveryAddress__City__s,
                                                        //DeliveryAddress__State__s,
                                                        DeliveryAddress__StateCode__s,
                                                        DeliveryAddress__Latitude__s,
                                                        DeliveryAddress__Longitude__s,
                                                        DeliveryAddress__GeocodeAccuracy__s, 
                                                        InstallationAddress__c,
                                                        //InstallationAddress__Country__s,
                                                        InstallationAddress__CountryCode__s,
                                                        InstallationAddress__PostalCode__s,
                                                        InstallationAddress__Street__s,
                                                        InstallationAddress__City__s,
                                                        //InstallationAddress__State__s,
                                                        InstallationAddress__StateCode__s,
                                                        InstallationAddress__Latitude__s,
                                                        InstallationAddress__Longitude__s,
                                                        InstallationAddress__GeocodeAccuracy__s,
                                                        // Attributes
                                                        BusinessType__c, BusinessTypeAttribute__c,
                                                        CountryAttribute__c, 
                                                        CustomerSegment__c, CustomerSegmentAttribute__c,
                                                        District__c, DistrictAttribute__c,
                                                        //Office__c, OfficeAttribute__c,
                                                        Organization__c,OrganizationAttribute__c,
                                                        ProfitCenter__c, ProfitCenterAttribute__c,
                                                        PropertyType__c, PropertyTypeAttribute__c,
                                                        ServiceAttribute__c                                           
                                    FROM Opportunity 
                                    WHERE Id IN :recordIds
                                      OR accountId IN : recordIds]);
        System.debug('--- OpportunityController - Opportunity Records: '+opportunities.size());
        return opportunities;
    } 
}