force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer Account</description>
    <inlineHelpText>Please choose the type of customer segment.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Chargeable__c.field-meta.xml
<CustomField>
    <fullName>Chargeable__c</fullName>
    <description>Chargeable field used for integration</description>
    <formula>IF(
TEXT(Opportunity__r.Order_type__c) == &apos;Normal&apos;, 
IF(Opportunity__r.Project_Number__r.Chargeable__c = TRUE ,&apos;chargeable&apos;,&apos;non-chargeable&apos;), 

IF(TEXT(Opportunity__r.Order_type__c) == &apos;Reclamation&apos;,
IF(TEXT(Opportunity__r.Case__r.Process_Class__c) == &apos;Additional_order_11&apos;,&apos;chargeable&apos;,&apos;non-chargeable&apos;),&apos;&apos;))</formula>
    <label>Chargeable OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>Customer segment code from Opportunity</description>
    <formula>TEXT(Opportunity__r.Customer_Segment__c)</formula>
    <label>Customer Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Promised Date from Quote</description>
    <formula>IF(TEXT(DATEVALUE(Opportunity__r.Preliminary_installation_time__c)) != &apos;&apos;,
TEXT(DATEVALUE(Opportunity__r.Preliminary_installation_time__c)),&apos;&apos;)</formula>
    <label>Delivery Date OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Delivery_week__c.field-meta.xml
<CustomField>
    <fullName>Delivery_week__c</fullName>
    <description>Delivery week from Delivery Date</description>
    <formula>IF(TEXT(Opportunity__r.Delivery_Date__c) != &apos;&apos;, 
TEXT(YEAR( Opportunity__r.Delivery_Date__c )) &amp; &quot;/&quot; &amp; 
TEXT
(IF( CEILING(( Opportunity__r.Delivery_Date__c  - DATE( YEAR( Opportunity__r.Delivery_Date__c ), 1, 1) + 1) / 7) &gt; 52,52,
CEILING( ( Opportunity__r.Delivery_Date__c - DATE( YEAR( Opportunity__r.Delivery_Date__c ), 1, 1) + 1) / 7)
))
,&apos;&apos;)</formula>
    <label>Delivery week OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Main_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Main_Contractor__c</fullName>
    <description>Main Contractor from Opportunity</description>
    <formula>IF(Opportunity__r.Main_Contractor__c = TRUE ,&apos;Yes&apos;,
IF(Opportunity__r.Main_Contractor__c = FALSE,&apos;No&apos;,&apos;No&apos;))</formula>
    <label>Main Contractor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Order number for integration from Opportunity</description>
    <formula>Opportunity__r.Opportunity_Number__c</formula>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <formula>TEXT(Opportunity__r.Order_type__c)</formula>
    <label>Order type OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <description>Parent project value for subproject used for integration</description>
    <formula>IF(Opportunity__r.Parent_Project__c != NULL, Opportunity__r.Project_Number__r.Parent_Project__r.Project_Value__c  ,&apos;&apos;)</formula>
    <label>Parent Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PriceBook_Name__c.field-meta.xml
<CustomField>
    <fullName>PriceBook_Name__c</fullName>
    <description>Pricebook used for Quote. Field used only for integration</description>
    <formula>Opportunity__r.Pricebook2.Name</formula>
    <label>PriceBook Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project_Group__c.field-meta.xml
<CustomField>
    <fullName>Project_Group__c</fullName>
    <description>Project group value for integration from Opportunity/Project</description>
    <formula>TEXT(Opportunity__r.Project_Number__r.Project_Group__c)</formula>
    <label>Project Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <description>Project number from Opportunity used for Integration</description>
    <formula>Opportunity__r.Project_Number__r.Project_Value__c</formula>
    <label>Opportunity Project OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Sales_reference__c.field-meta.xml
<CustomField>
    <fullName>Sales_reference__c</fullName>
    <description>Sales Reference/Order number for integration from Opportunity</description>
    <formula>Opportunity__r.Sales_reference__c</formula>
    <label>Sales reference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chargeable__c.field-meta.xml
<CustomField>
    <fullName>Chargeable__c</fullName>
    <formula>IF(
   TEXT(Order_type__c) == &apos;Normal&apos;,
   IF(Project_Number__r.Chargeable__c = TRUE ,True,False),
   IF(TEXT(Order_type__c) == &apos;Reclamation&apos;,
       IF(TEXT(Case__r.Process_Class__c) == &apos;Additional_order_11&apos;,True,false),
       true
   )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chargeable OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <label>Customer Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer opportunity</description>
    <inlineHelpText>Please choose which type of customer engagement is about.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Address__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Address__c</fullName>
    <label>Delivery Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Week__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Week__c</fullName>
    <formula>IF(NOT(ISNULL(Delivery_Date__c)),TEXT(Year(Delivery_Date__c))&amp;&quot;/&quot;&amp;TEXT(ISOWEEK(Delivery_Date__c)),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Week OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Installation_Address__c.field-meta.xml
<CustomField>
    <fullName>Installation_Address__c</fullName>
    <label>Installation Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_type__c</fullName>
    <label>Invoice type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoicing_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Address__c</fullName>
    <label>Invoicing Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Contractor__c.field-meta.xml
<CustomField>
    <fullName>Main_Contractor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to mention whether main contractor or sub contractor</description>
    <label>Main Contractor OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Auto number to have a unique 8 digit number that links Sales Objects. Used as sales reference</description>
    <displayFormat>{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number OLD</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Organization_Attribute__c</fullName>
    <description>Level 1 Classification based on Organization</description>
    <formula>Owner.Organization_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 1 Classification based on Organization</inlineHelpText>
    <label>Organization Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <description>Parent project from Project</description>
    <formula>Project_Number__r.Parent_Project__r.Project_Number__c</formula>
    <label>Parent Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Project_Number__r.Project_Number__c</formula>
    <label>Project Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Project number for the order</description>
    <label>Project OLD</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_reference__c.field-meta.xml
<CustomField>
    <fullName>Sales_reference__c</fullName>
    <description>Sales Order number (8 digits number, previsously 50XXXXXX)</description>
    <displayFormat>{00000000}</displayFormat>
    <inlineHelpText>Sales Order number</inlineHelpText>
    <label>Sales reference</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Organization_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Organization_Attribute__c</fullName>
    <formula>TEXT(Organization__c )</formula>
    <label>Organization Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Umbrella Object that existing for the complete &quot;life&quot; of an Installation
For New Installations as new Project is created
For Claims or AfterSales on Existing Installations an Existing Project is linked to Opportunity

The Project Number (8 digits) is used to uniquely Identify all Related Opportunities, Quotes and Orders</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Chargeable__c.field-meta.xml
<CustomField>
    <fullName>Chargeable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to show whether the order is chargeable or non-chargeable</description>
    <label>Chargeable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Main Project related to the current project</description>
    <inlineHelpText>Parent project related to the current</inlineHelpText>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Group__c.field-meta.xml
<CustomField>
    <fullName>Project_Group__c</fullName>
    <description>Internal Parameter for order classification</description>
    <label>Project Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Project_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <description>Project Number for the order</description>
    <displayFormat>{0000000}</displayFormat>
    <label>Project Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Customer_Segments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>Consumer Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>Consumer Single House</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>Project construction</label>
    </customValue>
    <customValue>
        <fullName>4100</fullName>
        <label>Project renovation</label>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
        <label>Reseller project</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>Reseller consumer</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
        <label>Aftersales</label>
    </customValue>
    <masterLabel>Lumon Customer Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Project_Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONSALES</fullName>
    </customValue>
    <customValue>
        <fullName>CONSDELIV</fullName>
    </customValue>
    <customValue>
        <fullName>CONWAR</fullName>
    </customValue>
    <customValue>
        <fullName>GROUPSA</fullName>
    </customValue>
    <customValue>
        <fullName>INTWAR</fullName>
    </customValue>
    <customValue>
        <fullName>PRODELIV</fullName>
    </customValue>
    <customValue>
        <fullName>PROPROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>PROWAR</fullName>
    </customValue>
    <customValue>
        <fullName>PROWIP</fullName>
    </customValue>
    <customValue>
        <fullName>RESDELIV</fullName>
    </customValue>
    <customValue>
        <fullName>WEBDELIV</fullName>
    </customValue>
    <masterLabel>Lumon Project Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-05-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class ContractController {
    @AuraEnabled(cacheable=true)
    public static Contract getContractRecord(Id recordId) {
        // Populate map from SOQL query on Contract
        List<Id> recordIds = new List<Id>{recordId};
        List<Contract> contractRecords = getContracts(recordIds);        
        Contract contractRecord = contractRecords[0];
        System.debug('--- Contract Record: '+contractRecord);
        return contractRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<Contract> getContracts(List<Id> recordIds) {
        List<Contract> contracts = ([SELECT  Id,
                                            Name,
                                            ContractNumber,
                                            CurrencyIsoCode,
                                            RecordTypeId,
                                            RecordType.Name,
                                            Status, 
                                            AccountId,
                                            Account.Customer_Segment__c,
                                            Account.AccountNumber,
                                            Opportunity__c, // This assumes one Contract has one Opportunity
                                            Opportunity__r.Sales_reference__c ,
                                            Opportunity__r.Opportunity_Number__c,
                                            Opportunity__r.Project_Number__c,
                                            Opportunity__r.Project_Number__r.Project_Number__c,
                                            Opportunity__r.Project_Number__r.Project_Group__c,
                                            Opportunity__r.Project_Number__r.Chargeable__c,
                                            Opportunity__r.Project_Number__r.Parent_Project__c,
                                            Opportunity__r.Project_Number__r.Parent_Project__r.Project_Number__c,
                                            //Opportunity__r.Project__c,
                                            //Opportunity__r.Project__r.Project_Number__c,
                                            //Opportunity__r.Project__r.Project_Group__c,
                                            //Opportunity__r.Project__r.Chargeable__c,
                                            //Opportunity__r.Project__r.Parent_Project__c,
                                            //Opportunity__r.Project__r.Parent_Project__r.Project_Number__c,
                                            Opportunity__r.Organization_Attribute__c,
                                            Opportunity__r.Customer_Address__c,
                                            Opportunity__r.Delivery_Address__c,
                                            Opportunity__r.Installation_Address__c,
                                            Opportunity__r.Invoicing_Address__c,
                                            Opportunity__r.Invoice_type__c,
                                            Opportunity__r.Order_type__c, // Not using Global picklist
                                            //Opportunity__r.OrderType__c, // TO be added to fix above issue
                                            Delivery_week__c, Delivery_Date__c, 
                                            Pricebook2Id,
                                            Pricebook2.Name,
                                            Pricebook2.CurrencyIsoCode
                                            //PriceBook_Name__c
                                            //Main_Contractor__c,Business_Unit__c,Opportunity__c,Payment_Term__c,Method_of_Payment__c,
                                            //Opportunity__r.Preliminary_installation_time__c,Opportunity__r.Phone__c,Opportunity__r.Contact_Email__c                              
                                    FROM Contract 
                                    WHERE Id IN :recordIds
                                    OR AccountId IN: recordIds
                                    OR Opportunity__c IN: recordIds
                                    ]);
        System.debug('--- Contract Record Count : '+contracts.size());
        return contracts;
    } 
}