force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer Account</description>
    <inlineHelpText>Please choose the type of customer segment.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Version__c.field-meta.xml
<CustomField>
    <fullName>Visual_Version__c</fullName>
    <description>1 for Old Visual
2 for New Visual</description>
    <label>Visual Version OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <formula>Configuration_Product__r.Configuration__r.RVN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN Number OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Local_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Local_Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Local Supplier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <formula>Configuration_Product__r.RVN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <formula>Configuration_Product__r.Configuration__r.Visual_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visual Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Features_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Features_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce representation of hasFeaturesBeenConfirmed</description>
    <label>Features Confirmed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Inspection_Code__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Code__c</fullName>
    <description>Salesforce equivalent of productInspectCode</description>
    <label>Inspection Code OLD</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Measurements_Verified__c.field-meta.xml
<CustomField>
    <fullName>Measurements_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce equivalent of hasMeasurementsBeenVerified</description>
    <label>Measurements Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Line__c.field-meta.xml
<CustomField>
    <fullName>Plan_Line__c</fullName>
    <description>Plan Line used in the configuration</description>
    <label>Plan Line OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Length__c.field-meta.xml
<CustomField>
    <fullName>Product_Length__c</fullName>
    <label>Product Length OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Visual_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Product_Id__c</fullName>
    <label>Visual Product Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <label>RVN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer opportunity</description>
    <inlineHelpText>Please choose which type of customer engagement is about.</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Location__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Delivery Location is not of allowed Type</errorMessage>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Warehouse, Site, Factory, Building, Warehouse, Factory, Building, Account</value>
        </filterItems>
        <infoMessage>Site/Warehouse Location</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Customer_Segments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>Consumer Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>Consumer Single House</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>Project construction</label>
    </customValue>
    <customValue>
        <fullName>4100</fullName>
        <label>Project renovation</label>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
        <label>Reseller project</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>Reseller consumer</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
        <label>Aftersales</label>
    </customValue>
    <masterLabel>Lumon Customer Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSLTestDataFactory.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 06-19-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public with sharing class FSLTestDataFactory { 
    /** Determine if person account is enabled in current org **/
    @TestVisible
    private static Boolean isPersonAccountEnabled{
        get{
            return Schema.SObjectType.Account.fields.getMap().containsKey( 'isPersonAccount' );
        }
    }
    private static final Date Today = system.today();
     
    public static void setupAccountRecords(){
        // Create B2C Account
        if(isPersonAccountEnabled) {
            String B2CRecordTypeId = [SELECT Id FROM RecordType WHERE (IsPersonType = true) and (SobjectType='Account') LIMIT 1].Id;
            Account p = new Account(      
                RecordTypeID=B2CRecordTypeId,
                FirstName='B2C',
                LastName='Account',
                PersonEmail='test@factory.com',
                PersonMailingCountry ='Finland',
                PersonMailingCity='Kaupunki',
                PersonMailingPostalCode = '1111',
                PersonMailingStreet='Katu 1');
            insert p;   
            system.debug ('*** accountRecordsSetup Person Account: '+p.id);
        }
        // Create B2BAccount
        String B2BRecordTypeId= [SELECT Id FROM RecordType WHERE (IsPersonType = false) and (SobjectType='Account')LIMIT 1].Id;
            Account a = new Account(
                RecordTypeID=B2BRecordTypeId,
                Name='B2B Account',
                BillingCountry ='Finland',
                BillingCity='Kaupunki',
                BillingPostalCode = '22222',
                BillingStreet = 'Katu 2');
            insert a;     
        system.debug ('*** accountRecordsSetup Account: '+a.id);
    }       
    public static void setupWorkOrderRecords() {
        Product2 p1 = new Product2(Name='Test Config Product 1', IsActive=True,ProductCode='COST',Product_Category__c='Product Models');
        Product2 p2 = new Product2(Name='Test Config Product 2', IsActive=True,ProductCode='Option 1',Product_Category__c='Product Options');
        Product2 p3 = new Product2(Name='Test Config Product 3', IsActive=True,ProductCode='Option 2',Product_Category__c='Product Options');
        insert new List<Product2> {p1,p2,p3};
        system.debug ('*** setupWorkOrderRecords product 1: '+p1);
        system.debug ('*** setupWorkOrderRecords product 2: '+p2);
        system.debug ('*** setupWorkOrderRecords product 3: '+p3);
        Id pbid = Test.getStandardPricebookId();
        PricebookEntry pbe1 = new PricebookEntry(Pricebook2Id=pbid, Product2Id=p1.id, UnitPrice=1, IsActive=True,CurrencyIsoCode = 'EUR');
        PricebookEntry pbe2 = new PricebookEntry(Pricebook2Id=pbid, Product2Id=p2.id, UnitPrice=2, IsActive=True,CurrencyIsoCode = 'EUR');
        PricebookEntry pbe3 = new PricebookEntry(Pricebook2Id=pbid, Product2Id=p3.id, UnitPrice=3, IsActive=True,CurrencyIsoCode = 'EUR');     
        insert new List<PricebookEntry> {pbe1,pbe2,pbe3};
        system.debug ('*** setupWorkOrderRecords PricebookEntry 1: '+pbe1);
        system.debug ('*** setupWorkOrderRecords PricebookEntry 2: '+pbe2);
        system.debug ('*** setupWorkOrderRecords PricebookEntry 3: '+pbe3);
        String B2CRecordTypeId= [SELECT Id FROM RecordType WHERE (Name='B2C Account') and (SobjectType='Account')].Id;
        String B2BRecordTypeId= [SELECT Id FROM RecordType WHERE (Name='B2B Account') and (SobjectType='Account')].Id;
        Schema.Location l = new Schema.Location(Name = 'TestL');
        insert l;
        l = [SELECT Id FROM Location Limit 1];
        List<Account> accts = new List<Account>();
        // Create B2C Account
        Account p = new Account(      
            RecordTypeID=B2CRecordTypeId,
            FirstName='My',
            LastName='Person Account',
            PersonEmail='test@workorder.com',
            PersonMailingCountry ='Finland',
            PersonMailingCity='Kaupunki',
            PersonMailingPostalCode = '33333',
            PersonMailingStreet='Katu 3');
        accts.add(p);    
        Account a = new Account(
            RecordTypeID=B2BRecordTypeId,
            Name='Business Account',
            BillingCountry ='Finland',
            BillingCity='Kaupunki',
            BillingPostalCode = '33333',
            BillingStreet = 'Katu 33');
        accts.add(a);
        insert accts;        
        system.debug ('*** setupWorkOrderRecords Person Account: '+p.id);
        system.debug ('*** setupWorkOrderRecords Account: '+a.id);
        Opportunity o1 = new Opportunity(
            Name='B2C Opportunity', 
            StageName='Quoting', 
            CloseDate=system.Today()+10,
            Pricebook2Id=pbid,
            AccountId = p.Id,
            Customer_Segment__c = '1000',
            //Delivery_Location__c = l.Id, 
            Delivery_date__c = System.today().addDays(5),
            Property_Type__c = 'ROW'
            //Installation_Address__City__s = 'Espoo',
            //Installation_Address__Street__s = 'Test Espoo Street',
            //Installation_Address__PostalCode__s = '00100'
            );
        insert o1;
        System.debug('*** location ***'+o1.Delivery_Location__c);
        System.debug('*** o1 city ***'+o1.Installation_Address__City__s);
        Opportunity o2 = new Opportunity(
            Name='B2B Opportunity', 
            StageName='Quoting', 
            CloseDate=system.Today()+30,
            Pricebook2Id=pbid,
            AccountId = a.Id
            //Installation_Address__City__s = 'Helsinki',
            //Installation_Address__Street__s = 'Test Helsinki Street',
            //Installation_Address__PostalCode__s = '00200'
            );
        insert o2;
        system.debug ('*** setupWorkOrderRecords B2C Opportunity: '+o1.id);
        system.debug ('*** setupWorkOrderRecords B2B Opportunity: '+o2.id);
        // Create Parent Config
        Configuration__c cfg1 = new Configuration__c(
            Opportunity__c = o1.Id,
            Name='Test Config 1',
            Plan_Apartment__c = 'A1',// public String apartment; // Door Nbr in Apartment
            Plan_Floor__c = '1',// public Integer floor; // Floor Nbr in Building
            Visual_Id__c = 'ABCDE1',//public String id; // Unique Visual Configuration Id
            Plan_Line__c = '100',// public String line; //?
            Plan_Name__c = 'NAME',// public String name; // Name of the Configuration
            //public List<Products> products; // Product Model aka Configurable Product
            Visual_Version__c = 1);//public Integer version; // Configuration Version);
        insert cfg1;
        Configuration__c cfg2 = new Configuration__c(
            Opportunity__c = o2.Id,
            Name='Test Config 2',
            Plan_Apartment__c = 'B2',// public String apartment; // Door Nbr in Apartment
            Plan_Floor__c = '2',// public Integer floor; // Floor Nbr in Building
            Visual_Id__c = 'ABCDE2',//public String id; // Unique Visual Configuration Id
            Plan_Line__c = '200',// public String line; //?
            Plan_Name__c = 'NAME',// public String name; // Name of the Configuration
            //public List<Products> products; // Product Model aka Configurable Product
            Visual_Version__c =2);//public Integer version; // Configuration Version);
        insert cfg2;
        // Create Config Product
        Configuration_Product__c cfgProd1 = new Configuration_Product__c(
            Name='LG', //public String name; // Name of the Product Model
            Configuration__c = cfg1.Id, // Parent Configuration
            Quantity__c = 1, // Amount must be 1 for each Product in a configuration
            Features_Confirmed__c = False,//public Boolean hasFeaturesBeenConfirmed;
            Measurements_Verified__c = False,// public Boolean hasMeasurementsBeenVerified;
            Visual_Product_Id__c = 'abcde12345',//public String id; // Product Code of Product Model
            Inspection_Code__c = 2,//public Integer productInspectCode;
            Product_Length__c = 2.5, //public Double productLength;
            RVN_Number__c = '12345678'); // public String rvn; //ProjectNbr + Structure);
        insert cfgProd1;
        // Create Config Option
        Configuration_Option__c cfgOpt1 = new Configuration_Option__c(
            Name='Test Config Option 1',
            Configuration_Product__c = cfgProd1.Id,
            Quantity__c = 1.23, //public Double Amount;
            Local_Supplier__c = FALSE, //public Boolean LocalSupplier;
            Parameter_code__c = '123456',// public String ParameterCode;
            Sales_Code__c = 'Option 1',// public String SalesCode;
            //unique_id__c = 1,// public Integer UniqueId;
            Unit_Of_Measure__c = 'M');// public String Unit;)
        insert cfgOpt1; 
        Configuration_Option__c cfgOpt2 = new Configuration_Option__c(
            Name='Test Config Option 2',
            Configuration_Product__c = cfgProd1.Id,
            Quantity__c = 22.23, //public Double Amount;
            Local_Supplier__c = FALSE, //public Boolean LocalSupplier;
            Parameter_code__c = '123456',// public String ParameterCode;
            Sales_Code__c = 'Option 2',// public String SalesCode;
            //unique_id__c = 1,// public Integer UniqueId;
            Unit_Of_Measure__c = 'h');// public String Unit;)
        insert cfgOpt2;       
        // Create Config Message
        Configuration_Message__c cfgMsg1 = new Configuration_Message__c(
            Name='Test Config Message',
            Configuration_Product__c = cfgProd1.Id,
            Message_Key__c = 'E11111',
            Space_Side_Number__c = 1);
        insert cfgMsg1;  
        Configuration_Message__c cfgMsg2 = new Configuration_Message__c(
            Name='Test Config Message',
            Configuration_Product__c = cfgProd1.Id,
            Message_Key__c = 'E22222',
            Space_Side_Number__c = 2);
        insert cfgMsg2; 
        // Create Content Document Version
        ContentVersion imageFileVersion = new ContentVersion();
        imageFileVersion.Title='Picture'; 
        imageFileVersion.ContentLocation= 's';
        imageFileVersion.PathOnClient = imageFileVersion.Title + '.jpg';
        Blob imageBody=Blob.valueOf('*** setupWorkOrderRecords Picture File'); 
        imageFileVersion.VersionData=imageBody; 
        insert imageFileVersion;
        system.debug ('*** setupWorkOrderRecords Image File Version : '+imageFileVersion.id);
        ContentVersion newFileVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =:imageFileVersion.Id];
        // Create Content Document Version to Configuration
        ContentDocumentLink imageFileLink = new ContentDocumentLink();
        imageFileLink.ContentDocumentId = newFileVersion.ContentDocumentId;
        imageFileLink.ShareType = 'V';
        imageFileLink.LinkedEntityId = cfg1.id;
        insert imageFileLink;
        system.debug ('*** setupWorkOrderRecords Image File Link : '+imageFileLink.id);
        // Create Content Document Version
        ContentVersion pricingFileVersion = new ContentVersion();
        pricingFileVersion.Title='Visual Pricing'; 
        pricingFileVersion.ContentLocation= 's';
        pricingFileVersion.PathOnClient = pricingFileVersion.Title + '.json';
        String ConfigString = '{'+
        '    \"apartment\": \"A1\",'+
        '    \"floor\": \"6\",'+
        '    \"id\": \"ABCDE3\",'+
        '    \"line\": \"123\",'+
        '    \"name\": \"Test Plan 3\",'+
        '    \"version\": 3,'+
        '    \"products\": ['+
        '      {'+
        '        \"id\": \"visualProductId1\",'+
        '        \"name\": \"COST\",'+
        '        \"productLength\": 0.0,'+
        '        \"priceParameters\": ['+
        '          {'+
        '            \"Amount\": 1.0,'+
        '            \"LocalSupplier\": true,'+
        '            \"ParameterCode\": \"\",'+
        '            \"SalesCode\": \"Option 1\",'+
        '            \"UniqueId\": 1,'+
        '            \"Unit\": \"PCS\"'+
        '          }'+
        '        ],'+
        '        \"rvn\": \"12345678\",'+
        '        \"hasFeaturesBeenConfirmed\": true,'+
        '        \"hasMeasurementsBeenVerified\": true,'+
        '        \"productInspectCode\": 2,'+
        '        \"productInspectMessageKeys\": ['+
        '          {'+
        '            \"MessageKey\": \"E11111\",'+
        '            \"SpaceSideNumber\": 1'+
        '          }'+
        '        ],'+
        '        \"reclaimedFeatureMessageKeys\": []'+
        '      }'+
        '    ]'+
        '  }'; 
        Blob bodyBlob=Blob.valueOf(ConfigString); 
        pricingFileVersion.VersionData=bodyBlob; 
        insert pricingFileVersion;
        system.debug ('*** setupWorkOrderRecords Pricing File Version : '+pricingFileVersion.id);
        ContentVersion newPricingFileVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =:pricingFileVersion.Id];
        // Create Content Document Version to Configuration
        ContentDocumentLink pricingFileLink = new ContentDocumentLink();
        pricingFileLink.ContentDocumentId = newPricingFileVersion.ContentDocumentId;
        pricingFileLink.ShareType = 'V';
        pricingFileLink.LinkedEntityId = cfg1.id;
        insert pricingFileLink;
        system.debug ('*** setupWorkOrderRecords Image File Link : '+pricingFileLink.id);
        
        OperatingHours oh = new OperatingHours(Name = 'Operating Hours Test');
        insert oh;
        system.debug ('*** setupWorkOrderRecords Operating Hours : '+oh.id);
        FSL__Scheduling_Policy__c sp = new FSL__Scheduling_Policy__c(Name = 'Custom Component Reservation');
        insert sp;
        system.debug ('*** setupWorkOrderRecords Scheduling Policy : '+sp.id);
        ServiceTerritory st = new ServiceTerritory(Name = 'testT', 
                                                   Appointment_Booking_Offset__c = 5, 
                                                   OperatingHoursId = oh.Id, IsActive = true);
        insert st;
        system.debug ('*** setupWorkOrderRecords Service Territory : '+st.id);
        st = [SELECT Id, Appointment_Booking_Offset__c FROM ServiceTerritory Limit 1];
        WorkOrder wo = new WorkOrder(Subject = o1.Name, 
                                     Opportunity__c = o1.Id, 
                                     AccountId = o1.AccountId, 
                                     ContactId = a.PersonContactId, 
                                     LocationId = o1.Delivery_Location__c, 
                                     Duration = o1.Installation_duration__c, 
                                     DurationType = 'Hours', 
                                     ServiceTerritoryId = st.Id);
        insert wo;
        system.debug ('*** setupWorkOrderRecords Work Order : '+wo);
        ServiceAppointment sa = new ServiceAppointment(ParentRecordId = wo.Id, 
                                                       EarliestStartTime = system.Today(),//o1.Delivery_date__c, 
                                                       DueDate = system.Today()+5,//o1.Delivery_date__c.addDays(5), 
                                                       Duration = 20);//o1.Installation_duration__c);
        insert sa;
        system.debug ('*** setupWorkOrderRecords Service Appointment : '+wo.id);
    } 
}