force-app/main/default/objects/Account/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/ApartmentOwnedBy__c.field-meta.xml
<CustomField>
    <fullName>ApartmentOwnedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>ApartmentOwners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Door__c.field-meta.xml
<CustomField>
    <fullName>Door__c</fullName>
    <label>Door</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>The Horizontal Placement of the Unit in the Apartment Building</description>
    <inlineHelpText>The Horizontal Placement of the Unit in the Apartment Building</inlineHelpText>
    <label>Line</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/StreetAddress__c.field-meta.xml
<CustomField>
    <fullName>StreetAddress__c</fullName>
    <label>Building Street Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Building_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Address__c</fullName>
    <label>Building Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Building_Height__c.field-meta.xml
<CustomField>
    <fullName>Building_Height__c</fullName>
    <inlineHelpText>Indication of the Building Highest Level (mm)</inlineHelpText>
    <label>Building Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Building_Location__c.field-meta.xml
<CustomField>
    <fullName>Building_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Building</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/BuildingOwnedBy__c.field-meta.xml
<CustomField>
    <fullName>BuildingOwnedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>BuildingOwners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Number_of_Floors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Floors__c</fullName>
    <label>Number of Floors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/NumberOfFloors__c.field-meta.xml
<CustomField>
    <fullName>NumberOfFloors__c</fullName>
    <label>Number of Floors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/On_Hill_or_Slope__c.field-meta.xml
<CustomField>
    <fullName>On_Hill_or_Slope__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indication whether Building is on a Hill or Slope</inlineHelpText>
    <label>On Hill or Slope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Owned_By__c.field-meta.xml
<CustomField>
    <fullName>Owned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <description>The Type of Property</description>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Terrain_Type__c.field-meta.xml
<CustomField>
    <fullName>Terrain_Type__c</fullName>
    <label>Terrain Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Terrain_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Terrain_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Terrain Class 0</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class I</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class II</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class III</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class IV</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class V</fullName>
        <isActive>false</isActive>
        <label>Terrain Class V</label>
    </customValue>
    <masterLabel>Lumon Terrain Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LumonTestBuildings.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-02-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class LumonTestBuildings {
    public class CustomException extends Exception {}
    @TestVisible public static List<Product2> mainProducts = LumonTestProducts.mainProducts;
    @TestVisible public static List<Account> accounts = LumonTestAccounts.accounts;
    @TestVisible public static Id b2cAccountId = LumonTestAccounts.b2cAccountId;
    @TestVisible public static Id b2bAccountId = LumonTestAccounts.b2bAccountId;
    @TestVisible public static List<Building__c> buildings{
        get{
            return [SELECT Id,Name FROM Building__c];
        }
    }
    /********** Building__c Data Setup ***********/
    public static void setupApartmentBuilding(){
        // Create Building__c of Record Type Building
        System.debug('--- LumonTestBuildings - setupBuilding - Building');
        Building__c building = new Building__c( Name='Apartment Building 1',
                                            //StreetAddress__c,
                                            PropertyType__c = 'APA',
                                            BuildingOwnedBy__c = b2cAccountId,
                                            NumberOfFloors__c = 3
                                            /*Building_Address__Street__s, 
                                            Building_Address__City__s, 
                                            Building_Address__PostalCode__s, 
                                            Building_Address__StateCode__s, 
                                            Building_Address__CountryCode__s, 
                                            Building_Address__Latitude__s, 
                                            Building_Address__Longitude__s, 
                                            Building_Address__GeocodeAccuracy__s, 
                                            Building_Address__c, 
                                            Building_Height__c, 
                                            Building_Location__c, 
                                            Number_of_Floors__c, 
                                            On_Hill_or_Slope__c, 
                                            Owned_By__c, 
                                            Property_Type__c,
                                            Terrain_Type__c, */
                                            );
        insert building;
        List<Apartment__c> apartments = new List<Apartment__c>();
        Integer unit = 1;
        for (Integer floor = 1; floor<5; floor++) {
            for (Integer line = 1; line<5; line++) {
                Apartment__c apartment = new Apartment__c( Name='Apartment Building 1',
                                            //StreetAddress__c,
                                            Building__c = building.Id, 
                                            ApartmentOwnedBy__c = b2cAccountId,
                                            Floor__c = String.Valueof(floor),
                                            Door__c = String.Valueof(unit),
                                            Line__c = String.Valueof(line)
                );
                apartments.add(apartment);
                unit++;
            }
        }
        if (apartments.size()>0) {
            insert apartments;
        }
        System.debug('--- LumonTestBuildings - setupApartmentBuilding - '+apartments.size()+ ' Apartments Created');
        System.debug('--- LumonTestBuildings - setupApartmentBuilding - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestBuildings - setupApartmentBuilding - SOQL USED: ' + LIMITS.getQueries());
    }
    public static void setupSingleHouse(){
        // Create Building__c of Record Type Building
        System.debug('--- LumonTestBuildings - setupSingleHouse - Building');
        Building__c building = new Building__c( Name='Single House 1',
                                            //StreetAddress__c,
                                            PropertyType__c = 'APA',
                                            BuildingOwnedBy__c = b2cAccountId
                                            /*Building_Address__Street__s, 
                                            Building_Address__City__s, 
                                            Building_Address__PostalCode__s, 
                                            Building_Address__StateCode__s, 
                                            Building_Address__CountryCode__s, 
                                            Building_Address__Latitude__s, 
                                            Building_Address__Longitude__s, 
                                            Building_Address__GeocodeAccuracy__s, 
                                            Building_Address__c, 
                                            Building_Height__c, 
                                            Building_Location__c, 
                                            Number_of_Floors__c, 
                                            On_Hill_or_Slope__c, 
                                            Owned_By__c, 
                                            Property_Type__c,
                                            Terrain_Type__c, */
                                            );
        insert building;
        List<Apartment__c> apartments = new List<Apartment__c>();
        Integer unit = 1;
        Integer floor = 1;
        Integer door = 1;
        Integer line = 1;
        Apartment__c apartment = new Apartment__c( Name='Apartment Building 1',
                                            //StreetAddress__c,
                                            Building__c = building.Id, 
                                            ApartmentOwnedBy__c = b2cAccountId,
                                            Floor__c = String.Valueof(floor),
                                            Door__c = String.Valueof(unit),
                                            Line__c = String.Valueof(line)
                );
                apartments.add(apartment);
        if (apartments.size()>0) {
            insert apartments;
        }
        System.debug('--- LumonTestBuildings - setupSingleHouse - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestBuildings - setupSingleHouse - SOQL USED: ' + LIMITS.getQueries());
    }
    public static void setupBuildingData(){ 
        if (accounts.size()>0) {
        } else {
            LumonTestAccounts.setupAccountData();
        }
        setupSingleHouse();
        setupApartmentBuilding();
        System.debug('--- LumonTestBuildings - Setup Buildings CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestBuildings - Setup Buildings SOQL USED: ' + LIMITS.getQueries());
        System.debug('--- LumonTestBuildings - Inserted '+buildings.size()+' Buildings'); 
    }  
    @TestSetup
    static void prepareData() {
        Test.startTest();
        Test.stopTest();
    }
    @Istest
    public static void setupBuildingDataTest(){
        String testResult;  
        Test.startTest();
        try {
            setupBuildingData();
            testResult = ('Inserted '+buildings?.size()+' Test Buildings');
            System.assertNotEquals(0,buildings?.size(), 'Expected Buildings to be Created');
            
        } catch (exception e){
            testResult =('Error when inserting Buildings: '+e.getMessage());
        }
        System.debug('--- LumonTestBuildings - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- LumonTestBuildings - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
        System.debug('--- LumonTestBuildings - Test Result = '+testResult);
        System.AssertNotEquals(true, testResult.contains('Error'));
    }
}