force-app/main/default/objects/Delivery_Batch__c/Delivery_Batch__c.object-meta.xml
<CustomObject>
    <description>Contains details about project work part (delivery batch).</description>
    <label>Delivery Batch</label>
    <nameField>
        <displayFormat>DB-{00000000}</displayFormat>
        <label>Delivery Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <description>Batch Number Reference in Opportunity</description>
    <label>Batch Number OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/BatchName__c.field-meta.xml
<CustomField>
    <fullName>BatchName__c</fullName>
    <description>Name of the Batch</description>
    <label>Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/BatchNumber__c.field-meta.xml
<CustomField>
    <fullName>BatchNumber__c</fullName>
    <description>The Number of the Delivery Batch</description>
    <inlineHelpText>The Number of the Delivery Batch</inlineHelpText>
    <label>Delivery Batch Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/OfferNumber__c.field-meta.xml
<CustomField>
    <fullName>OfferNumber__c</fullName>
    <description>The Identifier of the Offer in Salestori</description>
    <inlineHelpText>The Identifier of the Offer in Salestori</inlineHelpText>
    <label>Offer Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OfferNumber__c.field-meta.xml
<CustomField>
    <fullName>OfferNumber__c</fullName>
    <description>Reference to the Offer Number in Salestori</description>
    <externalId>true</externalId>
    <label>OfferNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeliveryBatchController.cls
/**
 * @description       : FSL Delivery Batch
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-09-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class DeliveryBatchController {
    @AuraEnabled(cacheable=false)
    public static Delivery_Batch__c getDeliveryBatch(Id batchId) {
        // Populate List from SOQL query on Delivery_Batch__c
        List<Id> batchIds = new List<Id>();
        batchIds.add(batchId);
        System.debug('--- DeliveryBatchController - Get Delivery Batch with Id '+batchId); 
        List<Delivery_Batch__c> batches =  getDeliveryBatches(batchIds);  
        Delivery_Batch__c batch = batches[0];
        System.debug('--- DeliveryBatchController - Delivery Batch: '+batch.Name); 
        return batch;  
    }
    @AuraEnabled(cacheable=false)
    public static List<Delivery_Batch__c> getDeliveryBatchesByNumber(String offerNumber) {
        // Populate List from SOQL query on Batch
        List<Delivery_Batch__c> offerBatches = new List<Delivery_Batch__c>(); 
        List<Id> offerBatchIds = new List<Id>(new Map<Id, Delivery_Batch__c>(offerBatches).keySet()); 
        List<Delivery_Batch__c> batches =  getDeliveryBatches(offerBatchIds);  
        return batches;  
    }
    public static List<Delivery_Batch__c> getDeliveryBatches (Id recordId) {
        List<Delivery_Batch__c> deliveryBatches = new List<Delivery_Batch__c>();
        deliveryBatches = getDeliveryBatches(new List<Id> {recordId});
        return deliveryBatches;
    }
    public static List<Delivery_Batch__c> getDeliveryBatches (List<Id> recordIds) {
        List<Delivery_Batch__c> deliveryBatches = new List<Delivery_Batch__c>();
        deliveryBatches = [SELECT  Id
                                    ,Name
                                    ,BatchNumber__c
                                    ,BatchName__c
                                    ,OfferNumber__c
                                    ,isMigrated__c
                                    ,CreatedDate
                                    ,CreatedById
                                    ,LastModifiedDate
                                    ,LastModifiedById
                        FROM Delivery_Batch__c 
                        WHERE Id IN: recordIds 
                        ORDER BY OfferNumber__c, Batch_Number__c DESC];
        return deliveryBatches;
    }
}