force-app/main/default/objects/Delivery_Batch__c/Delivery_Batch__c.object-meta.xml
<CustomObject>
    <description>Contains details about project work part (delivery batch).</description>
    <label>Delivery Batch</label>
    <nameField>
        <displayFormat>DB-{00000000}</displayFormat>
        <label>Delivery Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Delivery_Date__c</fullName>
    <label>Delivery Date OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Description__c.field-meta.xml
<CustomField>
    <fullName>Batch_Description__c</fullName>
    <description>Description from Salestori.</description>
    <label>Description OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Installation_Date__c</fullName>
    <label>Installation Date OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Installation_End__c.field-meta.xml
<CustomField>
    <fullName>Batch_Installation_End__c</fullName>
    <label>Installation End OLD</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Installation_Hours__c.field-meta.xml
<CustomField>
    <fullName>Batch_Installation_Hours__c</fullName>
    <description>Total Installation Time for all Products (RVN) in Batch</description>
    <label>Batch Installation Hours OLD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Installation_Start__c.field-meta.xml
<CustomField>
    <fullName>Batch_Installation_Start__c</fullName>
    <label>Installation Start OLD</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Order_Date__c</fullName>
    <label>Order Date OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Batch_Release_Date__c</fullName>
    <label>Release Date OLD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Status__c</fullName>
    <description>Status</description>
    <label>Status OLD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Data imported</fullName>
            </value>
            <value>
                <fullName>Work partially scheduled</fullName>
            </value>
            <value>
                <fullName>All work scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/BatchName__c.field-meta.xml
<CustomField>
    <fullName>BatchName__c</fullName>
    <description>Name of the Batch</description>
    <label>Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/BatchNumber__c.field-meta.xml
<CustomField>
    <fullName>BatchNumber__c</fullName>
    <description>The Number of the Delivery Batch</description>
    <inlineHelpText>The Number of the Delivery Batch</inlineHelpText>
    <label>Delivery Batch Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Batch__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Quote (Offer) this Delivery Batch belongs to</description>
    <inlineHelpText>The Quote (Offer) this Delivery Batch belongs to</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Delivery Batches</relationshipLabel>
    <relationshipName>Delivery_Batches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LumonTestDeliveryBatches.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 07-07-2024
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public class LumonTestDeliveryBatches {
    public static void setupDeliveryBatches(){
        List<Quote> quotes = LumonTestVariables.quotes;
        List<Delivery_Batch__c> batches = new List<Delivery_Batch__c>();        
        for (Quote q : quotes) {
            System.debug('--- LumonTestDeliveryBatches - Quote: '+quote.id);
            for (Integer batchCounter= 0; batchCounter<3;batchCounter++) {
                Delivery_Batch__c batch = new Delivery_Batch__c();
                batch.Quote__c = q.Id;
                batch.BatchName__c = q.Name + ' Batch '+ batchCounter;
                batch.BatchNumber__c = batchCounter;                             
                //batch.Batch_Description__c;
                //batch.Batch_Status__c;
                //batch.Batch_Delivery_Date__c;
                //batch.Batch_Installation_Date__c;
                //batch.Batch_Installation_Start__c;
                //batch.Batch_Installation_End__c;
                //batch.Batch_Installation_Hours__c;
                //batch.Batch_Order_Date__c;
                //batch.Batch_Release_Date__c;    
            batches.add(batch);
            System.debug('--- LumonTestDeliveryBatches - Delivery Batch: '+batch.id);
            }
        }
        if (batches?.size()>0){
            System.debug('--- LumonTestDeliveryBatches - '+batches?.size()+' Batches to Insert');
            insert batches;
        }
    } 
    public static void setupDeliveryBatchData() {
        setupDeliveryBatches();
    }
    @TestSetup
    static void prepareData() {
        Test.startTest();
        List<Quote> quotes = LumonTestVariables.quotes;
        if(quotes?.size()>0){
            System.debug('--- LumonTestDeliveryBatches - Using existing Quotes');
        } else {
            System.debug('--- LumonTestDeliveryBatches - Creating New Quotes');
            LumonTestQuotes.setupQuoteData();
        }
        Test.stopTest();
    }
    @isTest
    public static void setupDeliveryBatchDataTest(){
        String testResult;
        Test.startTest();
        try {
            setupDeliveryBatchData();
            testResult = 'successfully inserted Delivery Batches';
        } catch (exception e){
            testResult = 'Error when inserting Delivery Batches: '+e.getMessage();
        }
        System.debug('--- LumonTestDeliveryBatches - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestDeliveryBatches - Queries used: '+LIMITS.getQueries());
        Test.stopTest();       
        System.AssertNotEquals(true, testResult.contains('Error'));
    }
}