force-app/main/default/objects/AutomationBypass__c/fields/OrgDomain__c.field-meta.xml
<CustomField>
    <fullName>OrgDomain__c</fullName>
    <label>Org Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AutomationBypass__c/fields/SkipAccountApproval__c.field-meta.xml
<CustomField>
    <fullName>SkipAccountApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Account Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomationBypass__c/fields/SkipAutomation__c.field-meta.xml
<CustomField>
    <fullName>SkipAutomation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomationBypass__c/fields/SkipValidation__c.field-meta.xml
<CustomField>
    <fullName>SkipValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Offices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LumonTestPermissions.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public with sharing class LumonTestPermissions {
    @TestVisible private static User adminUser{
        get{
            return  [SELECT Id, Name, FirstName, LastName,
                            Alias, UserName,
                            ProfileId, Profile.Name, 
                            UserRoleId,UserRole.Name, 
                            Country, Organization__c, ProfitCenter__c, District__c, Office__c 
                     FROM User WHERE(Alias='admin' OR username='admin.testuser@sandbox.com')];
        }
    }
    @TestVisible private static List<User> testUsers{
        get{
            return  [SELECT Id, Name, FirstName, LastName,
                            Alias, UserName,
                            ProfileId, Profile.Name, 
                             UserRoleId,UserRole.Name, 
                            Country, Organization__c, ProfitCenter__c, District__c, Office__c 
                     FROM User
                     WHERE UserName LIKE '%sandbox%'];
        }
    }
    @testVisible private static List<PermissionSetAssignment> groupAssignments {
        get {
            return [SELECT id, Assignee.alias, AssigneeId, PermissionSetGroupId, PermissionSetId FROM PermissionSetAssignment];
        }
    }
    @testVisible private static List<AutomationBypass__c> bypassSettings {
        get {
            return [SELECT Id, Name,SetupOwnerId, OrgDomain__c, SkipAccountApproval__c, SkipAutomation__c, SkipValidation__c FROM AutomationBypass__c ];
        }
    }
    

    public static Map<String,Id> setupPermissionSetGroups(){
        List<PermissionSet> permissionSetGroups = [SELECT Id,Name, permissionSetGroupId, permissionSetGroup.DeveloperName FROM PermissionSet WHERE Name LIKE 'Lumon%' AND permissionsetgroupId != null];
        Map<String,Id> groupsMap = new Map<String,Id>();
        for (PermissionSet permissionSetGroup : permissionSetGroups) {
            String alias;
            switch on (permissionSetGroup.Name){
                when 'System_Administrator' {
                    groupsMap.put('admin',permissionSetGroup.Id);
                } when 'Lumon_Salesforce_Admin' {
                    groupsMap.put('ladmin',permissionSetGroup.Id);
                } when 'Lumon_Marketing' { 
                    groupsMap.put('lmarket',permissionSetGroup.Id);
                } when 'Lumon_Customer_Service' { 
                    groupsMap.put('lcustom',permissionSetGroup.Id);
                } when 'Lumon_Installer' { 
                    groupsMap.put('linstal',permissionSetGroup.Id);
                } when 'Lumon_Installation_Manager' { 
                    groupsMap.put('lsuper',permissionSetGroup.Id);
                } when 'Lumon_Sales_B2C' { 
                    groupsMap.put('lsalb2c',permissionSetGroup.Id);
                } when 'Lumon_Sales_B2B' { 
                    groupsMap.put('lsalb2b',permissionSetGroup.Id);
                } when 'Lumon_Sales_Manager' { 
                    groupsMap.put('lsalesm',permissionSetGroup.Id);
                } when 'Lumon_ICT_Support' { 
                    groupsMap.put('lictsup',permissionSetGroup.Id);
                } when 'Lumon_Technical_Support' { 
                    groupsMap.put('ltecsup',permissionSetGroup.Id);
                } when 'Lumon_System_Admin' { 
                    groupsMap.put('lsysadm',permissionSetGroup.Id);
                } when else {
                    continue;
                }
            }
        }
        return groupsMap;
    }
    public static void setupUserPermissions(Map<String,Id> groupsMap){       
        List<PermissionSetAssignment> groupAssignmentsToInsert = new List<PermissionSetAssignment>();
        for (User testUser : testUsers) {
            System.debug('--- LumonTestPermissions - setupPermissionAssignments - user Id: '+testUser?.Id);
            System.debug('--- LumonTestPermissions - setupPermissionAssignments - user Alias: '+testUser?.Alias);
            PermissionSetAssignment groupAssignment = new PermissionSetAssignment();
            groupAssignment.AssigneeId = testUser.Id;
            if (groupsMap.containsKey(testUser?.alias)){
                System.debug('--- LumonTestPermissions - setupPermissionAssignments - group: '+groupsMap.get(testUser?.alias));
                groupAssignment.PermissionSetGroupId = groupsMap.get(testUser.alias);
                groupAssignments.add(groupAssignment); 
            }
        }
        if (groupAssignmentsToInsert.size()>0) {
            System.debug('--- LumonTestPermissions - setupPermissionAssignments - '+groupAssignmentsToInsert.size()+' groupAssignments');
            System.RunAs(adminUser) {
                insert groupAssignmentsToInsert;
                System.debug('--- LumonTestPermissions - setupPermissionAssignments - groupAssignments: '+groupAssignmentsToInsert);
            }
            System.debug('--- LumonTestPermissions - setupPermissionAssignments - CPU TIME: '+LIMITS.getCpuTime());
            System.debug('--- LumonTestPermissions - setupPermissionAssignments - SOQL USED: ' + LIMITS.getQueries());
        }
    }
    public static void setupPermissionData(){
        if(testUsers.size()>0) {
            LumonTestUsers.setupUserData();
        }
        Map<String,Id> groupMap = setupPermissionSetGroups();
        if (groupMap.keySet().size()>0) {
            setupUserPermissions(groupMap);
        }
    }
    /********** User Data Tests***********/
    @TestSetup
    public static void prepareData(){
        Test.startTest();
            LumonTestUsers.setupUserData(); // create Users
        Test.stopTest();
    }   

    
    @isTest
    public static void setupPermissionDataTest(){
        String testResult;
        
        Test.startTest();
        try {
            setupPermissionData();
            testResult = 'successfully inserted Permission Assignments';
        } catch (exception e){
            testResult = 'Error when inserting Permission Assignments: '+e.getMessage();
            System.debug('--- LumonTestPermissions - '+testResult);
        }
        System.debug('--- LumonTestPermissions - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestPermissions - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();       
        System.AssertNotEquals(true, testResult.contains('Error'));
    }
}