force-app/main/default/objects/AutomationBypass__c/fields/SkipAccountApproval__c.field-meta.xml
<CustomField>
    <fullName>SkipAccountApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Account Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomationBypass__c/fields/SkipAutomation__c.field-meta.xml
<CustomField>
    <fullName>SkipAutomation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AutomationBypass__c/fields/SkipValidation__c.field-meta.xml
<CustomField>
    <fullName>SkipValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>District where the office belongs to</description>
    <inlineHelpText>District where the office belongs to</inlineHelpText>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office__c/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Offices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ProfitCenter__c.field-meta.xml
<CustomField>
    <fullName>ProfitCenter__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Organization__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LumonTestBypassSettings.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 09-23-2024
 * @last modified by  : Henk Reynders
**/
@istest
public with sharing class LumonTestBypassSettings {
    @TestVisible private static User adminUser{
        get{
            return  [SELECT Id, Name, FirstName, LastName,
                            ProfileId, Profile.Name, 
                            Alias, UserName,
                            UserRoleId,UserRole.Name, 
                            Country, Organization__c, ProfitCenter__c, District__c, Office__c 
                     FROM User 
                     WHERE(Alias ='admin' OR username='admin.testuser@sandbox.com') 
                     LIMIT 1];
        }
    }
    @testVisible private static AutomationBypass__c automationBypassOrg {
        get {
            return AutomationBypass__c.getOrgDefaults();
        }
    }
    @testVisible private static AutomationBypass__c automationBypassProfile {
        get {
            return AutomationBypass__c.getValues(adminUser?.ProfileId);
        }
    }
    @testVisible private static AutomationBypass__c automationBypassUser {
        get {
            return AutomationBypass__c.getValues(adminUser?.Id);
        }
    }   
    public static void enableBypassSettingsForAdmin(){  
        Boolean automation = true;
        Boolean validation = true;
        setupBypassSettingsForAdmin(automation, validation); 
    }
    public static void disableBypassSettingsForAdmin(){  
        Boolean automation = false;
        Boolean validation = false;
        setupBypassSettingsForAdmin(automation, validation); 
    }
    public static void setupBypassSettingsForAdmin(Boolean automation, Boolean validation){  
        Profile adminProfile = [SELECT Id,Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        List<AutomationBypass__c> bypassSettingsToUpsert = new List<AutomationBypass__c>();
        List<AutomationBypass__c>  existingAdminBypass = [SELECT Id, 
                                                        Name, 
                                                        SkipAccountApproval__c, 
                                                        SkipAutomation__c, 
                                                        SkipValidation__c,
                                                        SetupOwnerId,
                                                        SetupOwner.Name,
                                                        SetupOwner.alias,
                                                        SetupOwner.ProfileId,
                                                        SetupOwner.Profile.Name
                                                    FROM AutomationBypass__c
                                                    WHERE SetupOwnerId =: adminProfile.Id];
        AutomationBypass__c bypassSettingProfile = new AutomationBypass__c();    
        
        if (existingAdminBypass.size()>0) {
            System.debug('--- LumonTestBypassSettings - setupBypassSettingsForAdmin - existing Bypass Setting');
            bypassSettingProfile.Id = existingAdminBypass[0].Id;
        } else {
            System.debug('--- LumonTestBypassSettings - setupBypassSettingsForAdmin - new Bypass Setting');
            bypassSettingProfile.SetupOwnerId = adminProfile.Id;
        }
        bypassSettingProfile.Name = 'Admin Bypass Setting';
        bypassSettingProfile.SkipAutomation__c = automation;
        bypassSettingProfile.SkipValidation__c = validation;
        bypassSettingsToUpsert.add(bypassSettingProfile);
        if ( bypassSettingsToUpsert?.size()>0) {
            System.debug('--- LumonTestBypassSettings - setupBypassSettingsForAdmin - Bypass to Insert '+bypassSettingsToUpsert);
            upsert bypassSettingsToUpsert;
        }
    }

    @TestSetup
    public static void prepareData(){
        Test.startTest();
            LumonTestAdmin.setupAdminData();
        Test.stopTest();
    } 
    @IsTest
    public static void enableBypassSettingsTest(){
        String testresult;
        try {
            System.debug('--- LumonTestBypassSettings - enableBypassSettingsTest - Org Automation Bypass: '+automationBypassOrg?.SkipAutomation__c);
            System.debug('--- LumonTestBypassSettings - enableBypassSettingsTest - Profile Automation Bypass: '+automationBypassProfile?.SkipAutomation__c);
            System.debug('--- LumonTestBypassSettings - enableBypassSettingsTest - User Automation Bypass: '+automationBypassUser?.SkipAutomation__c);
            enableBypassSettingsForAdmin();            
        	testresult = ('Inserted Bypass Settings'); 
		} catch (Exception e) {
            //Any other exceptions that occur will go here
            String errorMessage = e.getMessage(); 
            testresult = ('Error - An Exception Occured:'+errorMessage);
        }
        System.debug('--- LumonTestBypassSettings - Test Result: '+testresult );
        System.assertNotEquals('Error',testresult,' Expected Bypass Settings to be Inserted without Error');
    }
    @IsTest
    public static void disableBypassSettingsTest(){
        String testresult;
        try {
            System.debug('--- LumonTestBypassSettings - disableBypassSettingsTest - Org Automation Bypass: '+automationBypassOrg?.SkipAutomation__c);
            System.debug('--- LumonTestBypassSettings - disableBypassSettingsTest - Profile Automation Bypass: '+automationBypassProfile?.SkipAutomation__c);
            System.debug('--- LumonTestBypassSettings - disableBypassSettingsTest - User Automation Bypass: '+automationBypassUser?.SkipAutomation__c);
            disableBypassSettingsForAdmin();            
        	testresult = ('Inserted Bypass Settings'); 
		} catch (Exception e) {
            //Any other exceptions that occur will go here
            String errorMessage = e.getMessage(); 
            testresult = ('Error - An Exception Occured:'+errorMessage);
        }
        System.debug('--- LumonTestBypassSettings - Test Result: '+testresult );
        System.assertNotEquals('Error',testresult,' Expected Bypass Settings to be Inserted without Error');
    }
}