force-app/main/default/objects/AutomationBypass__c/fields/SkipAutomation__c.field-meta.xml
<CustomField>
    <fullName>SkipAutomation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Automation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the Product within a Configuration Plan.</description>
    <label>Configuration Product DELETE</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product Entry in product2 Table</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Special Product</description>
    <inlineHelpText>indicates if the Product needs Special Handling</inlineHelpText>
    <label>Special OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RVN is marked as special which means that additional configuration items will be added to configuration</description>
    <label>Special</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product is a Special Product</description>
    <inlineHelpText>indicates if the Product needs Special Handling</inlineHelpText>
    <label>Special OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OfferContentControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-03-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
private class OfferContentControllerTest {
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;

    @TestSetup
    static void prepareData() {
        Test.startTest();
        AutomationBypass__c bypass = new AutomationBypass__c();
        bypass.SkipAutomation__c = true;
        insert bypass;
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();
        Test.stopTest();
    }

    @IsTest
    static void getComponentDataTest() {
        Test.startTest();
        OfferContentController.ComponentData data = OfferContentController.getComponentData(
                b2cOpportunityId
        );
        Assert.isNotNull(data);
        try {
            OfferContentController.caseOpportunityId(b2cOpportunityId);
        } catch (Exception e) {
            Assert.isTrue(true, 'This should have failed as the case doesn\'t exist');
        }
        List<Id> configurationProductIds = new List<Id>{
                [SELECT Id FROM Configuration_Product__c LIMIT 1].Id
        };
        OfferContentController.deleteConfigurationProducts(configurationProductIds);
        Assert.areEqual(
                0,
                [SELECT Id FROM Configuration_Product__c WHERE Id IN :configurationProductIds].size(),
                'All configuration products should have been deleted'
        );
        Test.stopTest();
    }

//     @IsTest
//     static void addRemoveManuallySpecialProductsTest() {
//         Test.startTest();
//         Configuration_Product__c configurationProduct = [SELECT Id, Special__c FROM Configuration_Product__c LIMIT 1];
//         OfferContentController.addManuallySpecialItems(new List<Id>{
//                 configurationProduct.Id
//         },
//                 [SELECT Id, StageName FROM Opportunity WHERE Id = :b2cOpportunityId LIMIT 1].Id);
//         Assert.areEqual(true, [SELECT Id, Special__c FROM Configuration_Product__c WHERE Id = :configurationProduct.Id].Special__c);
//         Assert.areNotEqual(0, [
//                 SELECT Id
//                 FROM Configuration_Option__c
//                 WHERE Configuration_Product__c = :configurationProduct.Id
//                 AND Product__r.Additional_special_product__c = true
//         ].size());

//         OfferContentController.removeManuallyAddedSpecialItems(new List<Id>{
//                 configurationProduct.Id
//         },
//                 [SELECT Id, StageName FROM Opportunity WHERE Id = :b2cOpportunityId LIMIT 1].Id);
//         Assert.areEqual(false, [SELECT Id, Special__c FROM Configuration_Product__c WHERE Id =:configurationProduct.Id].Special__c);
//         Assert.areEqual(0, [
//                 SELECT Id
//                 FROM Configuration_Option__c
//                 WHERE Configuration_Product__c = :configurationProduct.Id
//                 AND Product__r.Additional_special_product__c = true
//         ].size());

//         Test.stopTest();
//     }
}