force-app/main/default/objects/LP_Footer_Link__mdt/LP_Footer_Link__mdt.object-meta.xml
<CustomObject>
    <description>Used in Lumon Customer Portal, each country will have different urls in footer</description>
    <label>LP Footer Link</label>
    <pluralLabel>LP Footer Links</pluralLabel>
</CustomObject>

force-app/main/default/objects/LP_Footer_Link__mdt/fields/Country_Language__c.field-meta.xml
<CustomField>
    <fullName>Country_Language__c</fullName>
    <defaultValue>&quot;English&quot;</defaultValue>
    <inlineHelpText>Select country language for which the link should be generated. (default is English)</inlineHelpText>
    <label>Country Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en-US</fullName>
                <default>true</default>
                <label>English US</label>
            </value>
            <value>
                <fullName>fi</fullName>
                <label>Finnish</label>
            </value>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LP_Footer_Link__mdt/fields/Is_Main_Footer_Section__c.field-meta.xml
<CustomField>
    <fullName>Is_Main_Footer_Section__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, link will be displayed in one of the main footers column section.</inlineHelpText>
    <label>Is Main Footer Section</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LP_Footer_Link__mdt/fields/Link_Order__c.field-meta.xml
<CustomField>
    <fullName>Link_Order__c</fullName>
    <inlineHelpText>Specify order of the link displayed in individual footer section</inlineHelpText>
    <label>Link Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LP_Footer_Link__mdt/fields/Link_Section__c.field-meta.xml
<CustomField>
    <fullName>Link_Section__c</fullName>
    <description>Each value from picklist represents footer area and its title. This way we can group individual links to footer columns and sections.</description>
    <inlineHelpText>Select what section should the footer URL be placed in.</inlineHelpText>
    <label>Link Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Privacy</fullName>
                <label>Registry and Privacy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LP_Footer_Link__mdt/fields/Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Link_URL__c</fullName>
    <label>Link URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LP_Footer.cls
public with sharing class LP_Footer {
	public class FooterSection{
		@AuraEnabled public String name;
		@AuraEnabled public Boolean isMainSection;
		@AuraEnabled public List<FooterLink> footerLinks;
	}
	public class FooterLink{
		@AuraEnabled public String url;
		@AuraEnabled public String label;
		@AuraEnabled public String socialIcon;
		public FooterLink(String url, String label, String icon){
			this.url = url;
			this.label = label;
			this.socialIcon = icon;
		}
	}

	@AuraEnabled public static String fetchFooterData(String portalLanguage){
		Map<String, FooterSection> footerSectionLinksMap = new Map<String, FooterSection>();
		if(portalLanguage != null){
			List<LP_Footer_Link__mdt> footerLinks = [
				SELECT
					Label,
					Country_Language__c,
					Is_Main_Footer_Section__c,
					Link_Order__c,
					Link_Section__c,
					Link_URL__c
				FROM LP_Footer_Link__mdt
				WHERE Country_Language__c = :portalLanguage
				ORDER BY Link_Section__c, Link_Order__c
				LIMIT 500
			];
			if(footerLinks.size() > 0){
				for(LP_Footer_Link__mdt fL : footerLinks){
					if(!footerSectionLinksMap.containsKey(fL.Link_Section__c)){
						FooterSection fSection = new FooterSection();
						fSection.name = fL.Link_Section__c;
						fSection.isMainSection = fL.Is_Main_Footer_Section__c;
						fSection.footerLinks = new List<FooterLink>{
							new FooterLink(fL.Link_URL__c, fL.Label, generateIconClass(fL.Link_Section__c, fL.Label)
							)
						};
						footerSectionLinksMap.put(fL.Link_Section__c, fSection);
					}else{
						footerSectionLinksMap.get(fL.Link_Section__c).footerLinks.add(
							new FooterLink(fL.Link_URL__c, fL.Label, generateIconClass(fL.Link_Section__c, fL.Label)
							)
						);
					}
				}
			}
		}
		return JSON.serialize(footerSectionLinksMap.values());
	}
	private static String generateIconClass(String linkSection, String linkLabel){
		if(linkSection.toUpperCase() != 'SOCIAL'){
			return null;
		}
		String socialMedia = linkLabel.toLowerCase().split(' ')[0];
		return 'icon-' + socialMedia;
	}
}