force-app/main/default/objects/Installation_Time__c/Installation_Time__c.object-meta.xml
<CustomObject>
    <label>Installation Time</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Installation Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installation Times</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Installation_Time__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Installation_Time__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <formula>Hours__c *60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minutes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Installation_Time__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Installation Times</relationshipLabel>
    <relationshipName>Installation_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installation_Time__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT( Product__r.Product_Group__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/LumonTestInstallationTimes.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-10-2023
 * @last modified by  : Henk Reynders
**/
@isTest
public with sharing  class LumonTestInstallationTimes {
	@TestVisible private static List<Installation_Time__c> installationTimes{
        get{
            return [SELECT Id,Product__c, Hours__c,Minutes__c,IsActive__c FROM Installation_Time__c WHERE (IsActive__c = true)];
        }
    }
    public static void setupInstallationTimes(){
        List<Product2> products = [SELECT Id, ProductCode,Product_Group__c,Cost_Type__c,IsActive FROM Product2];
        List<Id> productIds = new List<Id>(new Map<Id, Product2>(products).keySet()); 
        setupInstallationTimes(productIds);
    }
    public static void setupInstallationTimes(list<Id> productIds) {
        List<Product2> products = [SELECT Id, ProductCode,Product_Group__c,Cost_Type__c,IsActive FROM Product2 WHERE Id IN:productIds];
        Map<String,List<String>> productGroupMap = new Map<String,List<String>>();
        List<String> productGroups = new List<String>();
        List<String> costTypes = new List<String>();
        List<AggregateResult> aggrGroupCosttype = [SELECT Count(Id) productCount, Product_Group__c productGroup,Cost_Type__c costType FROM Product2
                                                   group by Product_Group__c, Cost_Type__c];
        if(aggrGroupCosttype != null && aggrGroupCosttype.size() > 0){ 
            for(AggregateResult agr : aggrGroupCosttype){
                String productGroup = (STRING) agr.get('productGroup');
                String costType = (STRING) agr.get('costType');
                //System.debug('--- productGroup: '+productGroup);
                //System.debug('--- costType: '+costType);
                if (costType == 'askuormitu') {
                    if (!productGroups.contains(productGroup)) {
                        productGroups.add(productGroup);
                    }
                    if (!costTypes.contains(costType)) {
                        costTypes.add(costType);  
                    }         
                    if (!productGroupMap.containsKey(productGroup)){
                        productGroupMap.put(productGroup,new List<String>());
                    } else {
                        List<String> groupCostTypes = productGroupMap.get(productGroup);
                        groupCostTypes.add(costType);
                        productGroupMap.put(productGroup,groupCostTypes);
                    }      
                }
                //System.debug('--- productGroupMap:'+productGroupMap);
            }
            System.debug('--- productGroups: '+productGroups);
        }
        List<Product2> validProducts = [SELECT Id, ProductCode,Product_Group__c,Cost_Type__c,IsActive FROM Product2 WHERE Id IN:productIds AND Product_Group__c IN: productGroups];
        List<Installation_Time__c> its = new List<Installation_Time__c>();
        for (Product2 p : validProducts) {
            Installation_Time__c it = new Installation_Time__c();
            it.Hours__c=1;
            it.Product__c=p.Id;
            it.IsActive__c=true;
            its.add(it);
        }
        insert its;
    }
    @IsTest
    static void setupInstallationTimesTest(){
        String testResult;
        LumonTestProducts.setupProducts();
        Test.startTest();
        Try {
            setupInstallationTimes();
            testResult = 'successfully inserted Installation Times';
            System.debug('--- setupInstallationTimesTest - Times: '+installationTimes);
        } catch (exception e){
            testResult = 'error when inserting Installation Times: '+e.getMessage();
        }
        Test.stopTest();
        System.debug('--- setupInstallationTimesTest: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
    }
}