force-app/main/default/objects/Installation_Time__c/Installation_Time__c.object-meta.xml
<CustomObject>
    <label>Installation Time</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Installation Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installation Times</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InstallationTimeControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
public with sharing class InstallationTimeControllerTest {
    @TestSetup
    static void PrepareData(){
        Test.startTest();
        //LumonTestProducts.setupTestProducts();
        LumonTestProducts.setupProducts('LG');
        LumonTestDataFactory.setupInstallationTimes();
        Test.stopTest();
    }
    private static List<product2> products = LumonTestProducts.testProducts;
    private static List<Installation_Time__c> installationTimes = LumonTestDataFactory.installationTimes;
    @IsTest
    static void getInstallationTimesTest(){
        Boolean isActive = true;
        System.debug('--- getInstallationTimesTest - isActive: '+isActive);
        System.debug('--- getInstallationTimesTest - products: '+products); 
        Test.startTest();
        List<Installation_Time__c> installTimes = InstallationTimeController.getInstallationTimes(isActive);
        System.assertNotEquals(0, installTimes.size(), 'Expecting atleast 1 Installation Time to be returned');
        System.debug('--- getInstallationTimesTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getInstallationTimesTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getInstallationTimeMapTest(){
        Boolean isActive = true;
        System.debug('--- getInstallationTimeMapTest - isActive: '+isActive); 
        Test.startTest();
        Map<String,Installation_Time__c> productCode2installTime = InstallationTimeController.getInstallationTimeMap(isActive);
        System.assertNotEquals(0, productCode2installTime.values().size(), 'Expecting atleast 1 Installation Time to be returned');
        System.debug('--- getInstallationTimeMapTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getInstallationTimeMapTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getInstallationTimeProductsTest(){
        Boolean isActive = true;
        System.debug('--- getInstallationTimeProductsTest - isActive: '+isActive); 
        Test.startTest();
        List<Product2> installTimeProducts = InstallationTimeController.getInstallationTimeProducts(isActive);
        System.assertNotEquals(0, installTimeProducts.size(), 'Expecting atleast 1 Installation Time Products to be returned');
        System.debug('--- getInstallationTimeProductsTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getInstallationTimeProductsTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getInstallationTimeProductMapTest(){
        Product2 p4 = new Product2(Name='Test Installation Times Product 4', IsActive=True,ProductCode='LG-Time3',Sales_Code__c='Time3',Cost_Category__c='Manhours',Cost_Type__c='askuormitu');
        Product2 p5 = new Product2(Name='Test Installation Times Product 5', IsActive=True,ProductCode='LG-Time4',Sales_Code__c='Time4',Cost_Category__c='Manhours',Cost_Type__c='askuormitu');
        Product2 p6 = new Product2(Name='Test Installation Times Product 6', IsActive=True,ProductCode='LG-Time5',QuantityUnitOfMeasure='h',Sales_Code__c='Time5');
        insert new List<Product2> {p4,p5,p6};
        Boolean isActive = true;
        System.debug('--- getInstallationTimeProductMapTest - isActive: '+isActive); 
        Test.startTest();
        Map<String,Product2> productCode2installProduct = InstallationTimeController.getInstallationTimeProductMap(isActive);
        System.assertNotEquals(0, productCode2installProduct.values().size(), 'Expecting atleast 1 Installation Time Products to be returned');
        System.debug('--- getInstallationTimeProductMapTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getInstallationTimeProductMapTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
}