force-app/main/default/objects/Lead/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_meeting_booked__c.field-meta.xml
<CustomField>
    <fullName>Customer_meeting_booked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates whether customer meeting is booked with the lead and serves as a source for a validation rule</description>
    <label>Customer meeting booked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer Lead</description>
    <inlineHelpText>Please choose the type of customer segment.</inlineHelpText>
    <label>Customer Segment OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Opt_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Date_Time__c</fullName>
    <label>Email Opt In Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Finland_Sync_to_MC__c.field-meta.xml
<CustomField>
    <fullName>Finland_Sync_to_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to be used by marketing cloud to define MC region/country</description>
    <inlineHelpText>To define MC region/country</inlineHelpText>
    <label>Finland Sync to MC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Other_Countries_Sync_to_MC__c.field-meta.xml
<CustomField>
    <fullName>Other_Countries_Sync_to_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to be used by marketing cloud to define MC region/country.</description>
    <inlineHelpText>To define MC region/country.</inlineHelpText>
    <label>Other Countries Sync to MC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SMS_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SMS_Opt_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_In_Date_Time__c</fullName>
    <label>SMS Opt In Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Spain_Sync_to_MC__c.field-meta.xml
<CustomField>
    <fullName>Spain_Sync_to_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to be used by marketing cloud to define MC region/country.</description>
    <inlineHelpText>To define MC region/country.</inlineHelpText>
    <label>Spain Sync to MC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Visit_Booked__c.field-meta.xml
<CustomField>
    <fullName>Visit_Booked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Lumon web2lead form optional field for fairs &amp; events</description>
    <label>Visit Booked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Customer_Segments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>Consumer Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>Consumer Single House</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>Project construction</label>
    </customValue>
    <customValue>
        <fullName>4100</fullName>
        <label>Project renovation</label>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
        <label>Reseller project</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>Reseller consumer</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
        <label>Aftersales</label>
    </customValue>
    <masterLabel>Lumon Customer Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>fr</fullName>
        <label>french</label>
    </customValue>
    <customValue>
        <fullName>nl</fullName>
        <label>dutch</label>
    </customValue>
    <customValue>
        <fullName>de</fullName>
        <label>german</label>
    </customValue>
    <customValue>
        <fullName>es</fullName>
        <label>spanish</label>
    </customValue>
    <customValue>
        <fullName>da</fullName>
        <label>danish</label>
    </customValue>
    <customValue>
        <fullName>nb</fullName>
        <label>norwegian</label>
    </customValue>
    <customValue>
        <fullName>en_US</fullName>
        <label>english US</label>
    </customValue>
    <customValue>
        <fullName>fi</fullName>
        <label>finnish</label>
    </customValue>
    <customValue>
        <fullName>de_CH</fullName>
        <label>german (Swiss)</label>
    </customValue>
    <customValue>
        <fullName>en_CA</fullName>
        <label>english (Canada)</label>
    </customValue>
    <customValue>
        <fullName>en</fullName>
        <label>english (Default)</label>
    </customValue>
    <customValue>
        <fullName>pl</fullName>
        <label>polish</label>
    </customValue>
    <customValue>
        <fullName>swedish</fullName>
    </customValue>
    <customValue>
        <fullName>fr_CA</fullName>
        <label>french (Canada)</label>
    </customValue>
    <description>Language picklist values</description>
    <masterLabel>Lumon Languages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 03-26-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class LeadController {
    /**** Methods for Finding Lead Entries ****/
    @AuraEnabled(cacheable=false)
    public static Lead getLead(Id recordId ) {
        // Populate List from SOQL query on Lead
        //System.Debug('--- Get Lead with Id: '+recordId); 
        List<Id> recordIds = new List<Id>();
        recordIds.add(recordId);
        List<Lead> leads = getLeads(recordIds);
        Lead lead = leads[0];

        //System.Debug('--- Lead: '+lead.Name); 
        return lead;  
    }
    @AuraEnabled(cacheable=false)
    public static List<Lead> getLeads(List<Id> recordIds ) {
        // Populate List from SOQL query on Lead
        //System.Debug('--- Get Leads'); 
        List<Lead> leads = ([  SELECT  Id, 
                                        MasterRecordId, 
                                        LastName, 
                                        FirstName, 
                                        Salutation, 
                                        Name, 
                                        RecordTypeId, 
                                        Phone, MobilePhone, Fax, 
                                        Email, EmailBouncedReason, EmailBouncedDate,
                                        Description, LeadSource, Status,
                                        IsConverted, ConvertedDate, 
                                        ConvertedAccountId, ConvertedContactId, ConvertedOpportunityId,
                                        Customer_meeting_booked__c, Visit_Booked__c,
                                        Customer_Segment__c, Business_Type__c, Property_Type__c,
                                        Language__c,
                                        Title,
                                        Company, Industry, Rating, 
                                        Address,Street,City,State, PostalCode, Country,StateCode, CountryCode, Latitude, Longitude, GeocodeAccuracy,
                             			SMS_Opt_In_Date_Time__c,SMS_Opt_In__c, Email_Opt_In_Date_Time__c,Email_Opt_In__c,
                             			Finland_Sync_to_MC__c,Other_Countries_Sync_to_MC__c,Spain_Sync_to_MC__c,
                             			ConvertedAccount.Finland_Sync_to_MC__pc, ConvertedAccount.Other_Countries_Sync_to_MC__pc,ConvertedAccount.Spain_Sync_to_MC__pc,
                             			ConvertedContact.Finland_Sync_to_MC__c, ConvertedContact.Other_Countries_Sync_to_MC__c,ConvertedContact.Spain_Sync_to_MC__c,
                             			ConvertedOpportunity.Finland_Sync_to_MC__c, ConvertedOpportunity.Other_Countries_Sync_to_MC__c,ConvertedOpportunity.Spain_Sync_to_MC__c
                                    FROM Lead 
                                    WHERE Id IN: recordIds
                                    ]);  
        //System.Debug('--- Leads: '+leads.size()); 
        return leads;  
    }
    @InvocableMethod (label='Convert Leads' description='Converts Leads to Accounts and Opportunities' category='Lead')
    public static List<List<String>> convertLeads(List<Id> leadIds) {
    //public static List<String> convertLeads(List<Id> leadIds) {
        List<String> toReturn = new List<String>();
        List<List<string>> colToReturn = new List<List<String>>();
        List<Lead> leadsToConvert = [SELECT Id FROM Lead WHERE Id =: leadIds];
        LeadStatus leadConvertedStatus = [SELECT ApiName FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];
        List<Database.LeadConvert> dbLeads = new List<Database.LeadConvert>();
        List<Database.LeadConvert> dbDuplicates = new List<Database.LeadConvert>();

        if (String.isNotBlank(leadConvertedStatus?.ApiName)) {
            String convertedStatus = leadConvertedStatus.ApiName;        
            for (Lead currentLead: leadsToConvert){
                Id currentLeadId = currentLead.Id;
                // Check first for Possible Duplicates
                List<Lead> duplicateLeads = findDuplicateRecordsForLead(currentLead);
                if(duplicateLeads.size() == 0){
                    //System.Debug('--- LeadConverter - No Duplicates Found!');
                    Database.LeadConvert dbLead = new Database.LeadConvert();
                    dbLead.setLeadId(currentLeadId);
                    dbLead.setConvertedStatus(convertedStatus);
                    //leadConvert.setDoNotCreateOpportunity(true);
                    dbLeads.add(dbLead);
                } else {
                    //System.Debug('--- LeadConverter - '+duplicateLeads.size()+' Possible Duplicates Found!');
                    Database.LeadConvert dbDuplicate = new Database.LeadConvert();
                    dbDuplicate.setLeadId(currentLeadId);
                    dbDuplicate.setConvertedStatus(convertedStatus);
                    //leadConvert.setDoNotCreateOpportunity(true);
                    dbDuplicates.add(dbDuplicate);         
                } 
            }

            if (!dbLeads.isEmpty()) {
                List<Database.LeadConvertResult> lcr = Database.convertLead(dbLeads);
                for (Database.LeadConvertResult l : lcr) {
                    toReturn.add(l.getAccountId() + ';' + l.getOpportunityId());
                    colToReturn.add(toReturn);
                }
            }
            if (!dbDuplicates.isEmpty()) {
                Database.DMLOptions dml = new Database.DMLOptions();
                dml.DuplicateRuleHeader.AllowSave = true;
                List<Database.LeadConvertResult> lcr = Database.convertLead(dbDuplicates,dml);
                for (Database.LeadConvertResult l : lcr) {
                    toReturn.add(l.getAccountId() + ';' + l.getOpportunityId());
                    colToReturn.add(toReturn);
                }
            }
        }
        //return toReturn;
        return colToReturn;
    }
    public static List<Lead> findDuplicateRecordsForLead(Lead leadToConvert){ 
        List<Lead> leadsToConvert = new List<Lead>{leadToConvert};
        List<Datacloud.FindDuplicatesResult>  findDuplicatesResults = Datacloud.FindDuplicates.findDuplicates(leadsToConvert); 
        List<Lead> leadsWithDuplicates = new List<Lead>();
        if (findDuplicatesResults?.size()>0) {
            //System.Debug('--- LeadConverter - '+findDuplicatesResults.size()+' Possible Duplicates Found!');
            for (Integer i=0; i<findDuplicatesResults.size(); i++) {
            //for (Datacloud.DuplicateResult duplicateResult :  findDuplicatesResults) { 
                Datacloud.FindDuplicatesResult findDuplicateResult = findDuplicatesResults.get(i);    
                for (Integer j=0; j<findDuplicateResult.getDuplicateResults().size();j++) {
                    Datacloud.DuplicateResult duplicateResult = findDuplicatesResults.get(i).getDuplicateResults().get(j);
                    //System.Debug('--- LeadConverter - Duplicate Result: ' + duplicateResult);
                    List<Datacloud.MatchResult> matchResults = duplicateResult.getMatchResults();
                    //System.Debug('--- LeadConverter - Match Results: ' + matchResults);
                    for (Datacloud.MatchResult matchResult : matchResults){
                        //System.Debug('--- LeadConverter - Match Result: ' + matchResult);
                        List<Datacloud.MatchRecord> matchRecords = matchResult.getMatchRecords();  
                        //System.Debug('--- LeadConverter - Match Records: ' + matchRecords);
                        List<SObject> matchedRecords = new List<SObject>();
                        for(Datacloud.MatchRecord matchRecord : matchRecords){
                            SObject matchedRecord = matchRecord.getRecord();
                            //System.Debug('--- LeadConverter - Matched Record: ' + matchedRecord);
                            matchedRecords.add(matchedRecord);
                        }
                    }
                }
            }
            leadsWithDuplicates.add(leadToConvert);
        } else {
            //System.Debug('--- No Duplicates!');

        }
        return leadsWithDuplicates;
    }
}