force-app/main/default/objects/Lead/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This selection segments the customer Lead</description>
    <inlineHelpText>Please choose the type of customer segment.</inlineHelpText>
    <label>Customer Segment OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Customer_Segments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Customer_Segments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>Consumer Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>Consumer Single House</label>
    </customValue>
    <customValue>
        <fullName>4000</fullName>
        <label>Project construction</label>
    </customValue>
    <customValue>
        <fullName>4100</fullName>
        <label>Project renovation</label>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
        <label>Reseller project</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>Reseller consumer</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
        <label>Aftersales</label>
    </customValue>
    <masterLabel>Lumon Customer Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadConverterTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-01-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
private class LeadConverterTest {
	/*@IsTest
	static void convertLeadsB2BTest () {
		RecordType rt = [SELECT Id FROM RecordType WHERE Name = 'B2B Lead' LIMIT 1];
        Lead leadToCreate = new Lead(RecordTypeId = rt.Id, FirstName = 'My',
                                    LastName = 'Test Conversion', 
                                    Company = 'SFDC', MobilePhone = '+48500500500', 
                                    PostalCode = '97979', Country = 'Finland', 
                                    City = 'Kaupunki',Street = 'Katu 1',
                                    Business_Type__c = 'Reseller', Property_Type__c = 'APA',
                                    Customer_Segment__c = '1000');
        insert leadToCreate;
        Test.startTest();
        List<List<String>> converterOutput = new List<List<String>>();
		System.debug('*** Converter Input : '+leadToCreate.Id);
        System.debug('*** Converter Input Lead Business Type : '+leadToCreate.Business_Type__c);
        System.debug('*** Converter Input Lead Business Type : '+leadToCreate.Property_Type__c);
        System.debug('*** Converter Input Lead Business Type : '+leadToCreate.Customer_Segment__c);
        try {
        	converterOutput = LeadConverter.convertLeads(new List<Id>{leadToCreate.Id});
        } catch (Exception e) {
            System.debug('*** The following exception has occurred: ' + e.getMessage());
            throw new CustomException(e.getMessage());
        }
		System.debug('*** Converter Output : '+converterOutput);
        Test.stopTest();
	}*/
    @IsTest
	static void convertLeadsB2CTest () {
		RecordType rt = [SELECT Id FROM RecordType WHERE Name = 'B2C Lead' LIMIT 1];
        Lead leadToCreate = new Lead(RecordTypeId = rt.Id, FirstName = 'My',
                                    LastName = 'Test Conversion',
									MobilePhone = '+34800500500', 
                                    PostalCode = '97979', Country = 'Finland', 
                                    City = 'City',Street = 'Street 123',
                                    Business_Type__c = 'Consumer', Property_Type__c = 'COT',
                                    Customer_Segment__c = '1100');
        insert leadToCreate;
        Test.startTest();
        List<List<String>> converterOutput = new List<List<String>>();
		System.debug('*** Converter Input : '+leadToCreate.Id);
        System.debug('*** Converter Input Lead Business Type : '+leadToCreate.Business_Type__c);
        System.debug('*** Converter Input Lead Business Type : '+leadToCreate.Property_Type__c);
        System.debug('*** Converter Input Lead Business Type : '+leadToCreate.Customer_Segment__c);
        try {
        	converterOutput = LeadConverter.convertLeads(new List<Id>{leadToCreate.Id});
        } catch (Exception e) {
            System.debug('*** The following exception has occurred: ' + e.getMessage());
            throw new CustomException(e.getMessage());
        }
		System.debug('*** Converter Output : '+converterOutput);
        Test.stopTest();
	}
}