force-app/main/default/objects/CustomException__c/CustomException__c.object-meta.xml
<CustomObject>
    <label>CustomException</label>
    <nameField>
        <label>CustomException Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomExceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomException__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message OLD</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomException__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomException__c/fields/Govt_Limit_in_Executing_Code__c.field-meta.xml
<CustomField>
    <fullName>Govt_Limit_in_Executing_Code__c</fullName>
    <label>Govt Limit in Executing Code</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomException__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomException__c/fields/Related_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Number__c</fullName>
    <label>Related To Number OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomExceptionController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-09-2024
 * @last modified by  : Henk Reynders
**/
public class CustomExceptionController{
    public static CustomException__c throwCustomException(CustomExceptionData exceptionData){
        CustomException__c  customException = new CustomException__c();
        customException.ClassName__c = exceptionData.className;
        customException.Exception_Message__c = exceptionData.message;
        customException.Line_Number__c = exceptionData.lineNumber; 
        customException.MethodName__c = exceptionData.method; 
        customException.Exception_Type__c = exceptionData.type;
        if(exceptionData.doInsert){
            insert customException;
        }
        return customException;
    }
    public static CustomException__c getCustomException(){
        CustomException__c  customException = new CustomException__c();
        customException = [SELECT Id, Name, 
                                    CreatedDate, CreatedById,  
                                    ClassName__c, Exception_Message__c, 
                                    Exception_Type__c, Govt_Limit_in_Executing_Code__c, 
                                    Line_Number__c, MethodName__c, 
                                    Related_To_Number__c, StackTrace__c
                            FROM CustomException__c
                            ORDER BY CreatedDate DESC 
                            LIMIT 1];
        return customException;
    }
    public static List<CustomException__c> getCustomExceptions(){
        List<CustomException__c>  customExceptions = new List<CustomException__c>();
        customExceptions = [SELECT Id, Name, 
                                    CreatedDate, CreatedById,  
                                    ClassName__c, Exception_Message__c, 
                                    Exception_Type__c, Govt_Limit_in_Executing_Code__c, 
                                    Line_Number__c, MethodName__c, 
                                    Related_To_Number__c, StackTrace__c
                            FROM CustomException__c
                            ORDER BY CreatedDate DESC 
                            LIMIT 25];
        return customExceptions;
    }
    public static List<CustomException__c> getCustomExceptionsByClass(String className){
        String classString = '%'+className+'%';
        List<CustomException__c>  customExceptions = new List<CustomException__c>();
        customExceptions = [SELECT Id, Name, 
                                    CreatedDate, CreatedById,  
                                    ClassName__c, Exception_Message__c, 
                                    Exception_Type__c, Govt_Limit_in_Executing_Code__c, 
                                    Line_Number__c, MethodName__c, 
                                    Related_To_Number__c, StackTrace__c
                            FROM CustomException__c
                            WHERE ClassName__c LIKE : classString
                            ORDER BY CreatedDate DESC 
                            LIMIT 25];
        return customExceptions;
    }
    public static List<CustomException__c> getCustomExceptionsByMethod(String methodName){
        String methodString = '%'+methodName+'%';
        List<CustomException__c>  customExceptions = new List<CustomException__c>();
        customExceptions = [SELECT Id, Name, 
                                    CreatedDate, CreatedById,  
                                    ClassName__c, Exception_Message__c, 
                                    Exception_Type__c, Govt_Limit_in_Executing_Code__c, 
                                    Line_Number__c, MethodName__c, 
                                    Related_To_Number__c, StackTrace__c
                            FROM CustomException__c
                            WHERE MethodName__c LIKE : methodString
                            ORDER BY CreatedDate DESC 
                            LIMIT 25];
        return customExceptions;
    }
}