force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Sovelia_Structure_Number__c.field-meta.xml
<CustomField>
    <fullName>Sovelia_Structure_Number__c</fullName>
    <description>&quot;structure_number&quot; from Sovelia Output</description>
    <externalId>true</externalId>
    <label>Sovelia Structure Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Structure_Number__c.field-meta.xml
<CustomField>
    <fullName>Visual_Structure_Number__c</fullName>
    <description>&quot;structure_number&quot; from Visual Output</description>
    <externalId>true</externalId>
    <label>Visual Structure Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Attribute__c/Configuration_Attribute__c.object-meta.xml
<CustomObject>
    <label>Configuration Attribute</label>
    <nameField>
        <label>Configuration Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Attribute__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Attributes</relationshipLabel>
    <relationshipName>Configuration_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Attribute__c/fields/Glass_Thickness__c.field-meta.xml
<CustomField>
    <fullName>Glass_Thickness__c</fullName>
    <description>Source Visual Documentation.xml</description>
    <inlineHelpText>Source Visual Documentation.xml</inlineHelpText>
    <label>Glass Thickness</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Features_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Features_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce representation of hasFeaturesBeenConfirmed</description>
    <label>Features Confirmed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Inspection_Code__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Code__c</fullName>
    <description>Salesforce equivalent of productInspectCode</description>
    <label>Inspection Code OLD</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Measurements_Verified__c.field-meta.xml
<CustomField>
    <fullName>Measurements_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce equivalent of hasMeasurementsBeenVerified</description>
    <label>Measurements Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sovelia_Structure_Number__c.field-meta.xml
<CustomField>
    <fullName>Sovelia_Structure_Number__c</fullName>
    <description>The Unique Id of the Structure (Space) used in the Plan</description>
    <inlineHelpText>The Unique Id of the Structure (Space) used in the Plan</inlineHelpText>
    <label>Sovelia Structure Number OLD</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Visual_Structure_Number__c.field-meta.xml
<CustomField>
    <fullName>Visual_Structure_Number__c</fullName>
    <description>The Unique Id of the Structure (Space) used in the Plan</description>
    <inlineHelpText>The Unique Id of the Structure (Space) used in the Plan</inlineHelpText>
    <label>Visual Structure Number OLD</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationDataControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-20-2023
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public class ConfigurationDataControllerTest { 
    @TestSetup
    static void prepareData(){
        Test.startTest();
        //LumonTestDataFactory.setupProducts();
        LumonTestProducts.setupProducts('LG');
        //LumonTestProducts.setupProducts('LGS');
        //LumonTestProducts.setupProducts('LFIXEDWALL');
        LumonTestProducts.setupProducts('VT3');
        //LumonTestProducts.setupProducts('VT4');    
        //LumonTestProducts.setupProducts('VISORBLINDSALES');
        LumonTestProducts.setupSoveliaProducts();
        //LumonTestProducts.setupRetractableProducts();
        LumonTestPricebooks.setupPricebookEntries();
        LumonTestPriceParameters.setupPriceParameters();
        LumonTestInstallationTimes.setupInstallationTimes();
        LumonTestProductionTimes.setupProductionTimes();
        LumonTestConfigurations.setupConfigurationData();
        // B2C Setup
        /*LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();*/
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
    
    @IsTest
    static void getVisualPricingFilesTest(){
        Test.startTest();
        Id  configurationId =  [SELECT Id FROM Configuration__c WHERE opportunity__c =: b2cOpportunityId]?.Id;
        System.debug('--- getVisualPricingFilesTest - configurationId: '+configurationId); 
        
        Map<ID, String> pricingFileMap = ConfigurationDataController.getVisualPricingFiles(b2cOpportunityId);
        System.debug('--- getVisualPricingFilesTest - pricingFileMap: '+pricingFileMap); 
        System.assertNotEquals(null, pricingFileMap, 'Expecting atleast 1 File to be returned');
        System.debug('--- getVisualPricingFilesTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getVisualPricingFilesTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }

    @IsTest
    static void loadVisualPricingFileTest(){
        Id configurationId =  [SELECT Id FROM Configuration__c WHERE opportunity__c =: b2cOpportunityId]?.Id;
        Id pricingDocId =  [SELECT Id,ContentDocumentId FROM ContentDocumentLink WHERE linkedEntityId =: configurationId AND ContentDocument.Title Like '%Pricing%']?.ContentDocumentId;
        String result;
        System.debug('--- getVisualPricingFilesTest - configurationId: '+configurationId); 
        Test.startTest();
        try {
            ConfigurationDataController.loadVisualPricingFile(pricingDocId,b2cOpportunityId, 'Opportunity', configurationId);
        } catch (exception e) {
            result = e.getMessage();
        }
        System.assertEquals(null, result, 'Expecting File to be Loaded to be returned');
        System.debug('--- loadVisualPricingFileTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- loadVisualPricingFileTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    
    @isTest
    static void loadBlindsReportsFileTest(){
        Id configurationId =  [SELECT Id FROM Configuration__c WHERE opportunity__c =: b2cOpportunityId]?.Id;
        
        Id pricingDocId =  [SELECT Id,ContentDocumentId FROM ContentDocumentLink WHERE linkedEntityId =: configurationId AND ContentDocument.Title Like '%Report%']?.ContentDocumentId;
        String result;
        
        List<Configuration_Product__c> cpList = new List<Configuration_Product__c>();
        Configuration_Product__c cp = new Configuration_Product__c();
        cp.Name='VISORBLINDSALES'; //public String name; // Name of the Product Model
        cp.Configuration__c = configurationId; // Parent Configuration
        cp.Quantity__c = 1; // Amount must be 1 for each Product in a configuration
        cp.Sovelia_Structure_Number__c = '60001678';
        cp.Features_Confirmed__c = False;//public Boolean hasFeaturesBeenConfirmed;
        cp.Measurements_Verified__c = False;// public Boolean hasMeasurementsBeenVerified;                                       
        cp.Inspection_Code__c = 2;//public Integer productInspectCode;
        insert cp;
        cpList.add(cp);
        
        String blindsTitle = 'Blinds_Report_60001678';
         ContentVersion blindsStructureFile = new ContentVersion(
            Title = blindsTitle,
            PathOnClient = blindsTitle + '.json',
            VersionData = Blob.valueOf([SELECT Body FROM StaticResource WHERE Name = 'Sovelia_Report'].Body.toString())
        );
        insert blindsStructureFile;
        insert new List<ContentDocumentLink> {
            new ContentDocumentLink(
                ShareType = 'V',
                LinkedEntityId = cp.Configuration__c,
                ContentDocumentId = [
                    SELECT ContentDocumentId FROM ContentVersion WHERE Id = :blindsStructureFile.Id LIMIT 1
                ].ContentDocumentId
            )
        };
        
        Test.startTest();
        try {
            ConfigurationDataController.populateAdditionalProductParameters(cpList);
        } catch (exception e) {
            result = e.getMessage();
        }
		Test.stopTest();
        
    }

    @IsTest
    static void populateConfigurationAttributesTest() {
        List<Configuration_Product__c> configurationProducts = [
            SELECT Id, Configuration__c, Configuration__r.Visual_Structure_Number__c
            FROM Configuration_Product__c WHERE Configuration__r.Opportunity__c = :b2cOpportunityId
        ];

        Configuration_Product__c configurationProduct = configurationProducts.get(0);
        System.debug('--- populateConfigurationAttributesTest - configurationProduct: '+configurationProduct);

        Test.startTest(); 
        ConfigurationDataController.populateAdditionalProductParameters(b2cOpportunityId);
        System.debug('--- populateConfigurationAttributesTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- populateConfigurationAttributesTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
        
        List<Configuration_Attribute__c> attributes = [
            SELECT Id, Glass_Thickness__c FROM Configuration_Attribute__c
        ];
        System.debug('--- populateConfigurationAttributesTest -attributes: '+attributes); 
        Assert.isFalse(attributes.isEmpty(), 'Attributes should have been created');
    }
    /*@IsTest
    static void populateFromStructureFile() {
        List<Configuration_Product__c> configurationProducts = [
            SELECT Id, Configuration__c, Configuration__r.Visual_Structure_Number__c
            FROM Configuration_Product__c WHERE Configuration__r.Opportunity__c = :b2cOpportunityId
        ];
        Configuration_Product__c configurationProduct = configurationProducts.get(0);
        String documentationTitle = 'Visual_Documentation.xml';
        String visualStructureNumber = configurationProduct.Configuration__r.Visual_Structure_Number__c;
        String structureTitle = 'Visual_Structure_' + visualStructureNumber;
        ContentVersion visualStructureFile = new ContentVersion(
            Title = structureTitle,
            PathOnClient = structureTitle + '.json',
            VersionData = Blob.valueOf([SELECT Body FROM StaticResource WHERE Name = 'retractableStructure'].Body.toString())
        );
        insert visualStructureFile;
        insert new List<ContentDocumentLink> {
            new ContentDocumentLink(
                ShareType = 'V',
                LinkedEntityId = configurationProducts.get(0).Configuration__c,
                ContentDocumentId = [
                    SELECT ContentDocumentId FROM ContentVersion WHERE Id = :visualStructureFile.Id LIMIT 1
                ].ContentDocumentId
            )
        };

        Test.startTest(); 
        ConfigurationDataController.populateAdditionalProductParameters(b2cOpportunityId);
        System.debug('--- populateFromStructureFile - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- populateFromStructureFile - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
        List<Configuration_Attribute__c> attributes = [
            SELECT Id, Glass_Thickness__c FROM Configuration_Attribute__c
        ];
        Assert.isFalse(attributes.isEmpty(), 'Attributes should have been created');
    }*/

}