force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terrain_Type__c.field-meta.xml
<CustomField>
    <fullName>Terrain_Type__c</fullName>
    <inlineHelpText>Classification of the Terrain Type
0 - Sea, coastal exposed to the open sea
I - Lakes or area with negligible vegetation
II - Area with low vegetation such as grass and isolated obstacles (trees, buildings) with separations of at least 20 obstacle heights
III - Area with regular cover of vegetation or buildings or with isolated obstacles with separations of maximum 20 obstacle heights (such as villages, suburban terrain, forest)
IV - Area in which at least 15 % of surface is cove</inlineHelpText>
    <label>Terrain Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Terrain_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Terrain_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Terrain Class 0</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class I</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class II</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class III</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class IV</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class V</fullName>
        <isActive>false</isActive>
        <label>Terrain Class V</label>
    </customValue>
    <masterLabel>Lumon Terrain Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VisualContainerControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-01-2023
 * @last modified by  : Henk Reynders
**/
 @IsTest
 private class VisualContainerControllerTest {
	@TestSetup
	static void prepareData(){
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPriceBookEntries();
        // B2C Setup
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
	private static Id b2cConfigurationPlanId =LumonTestDataFactory.b2cConfigurationPlanId;

     @IsTest
     static void getStartupParamsTest() {
         Opportunity opp = [SELECT Id FROM Opportunity WHERE Id =: b2cOpportunityId LIMIT 1];
         opp.CloseDate = Date.today().addDays(1);
         opp.Delivery_Date__c = Date.today();
         opp.Terrain_Type__c = 'Terrain Class 0';
         update opp;
         String response;
         Test.startTest();
         response = VisualContainerController.getStartupParams(opp.Id);
         Test.stopTest();
         System.assert(response != null, 'Response should be returned');
     }

     @IsTest
     static void getStartupParamsFromConfigurationTest() {
         Opportunity opp = [SELECT Id FROM Opportunity WHERE Id =: b2cOpportunityId LIMIT 1];
         opp.CloseDate = Date.today().addDays(1);
         opp.Delivery_Date__c = Date.today();
         opp.Terrain_Type__c = 'Terrain Class 0';
         update opp;
         String response;
         Test.startTest();
         response = VisualContainerController.getStartupParamsFromConfiguration(b2cConfigurationPlanId);
         Test.stopTest();
         System.assert(response != null, 'Response should be returned');
     }
 }