force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Installer_Message__c.field-meta.xml
<CustomField>
    <fullName>Installer_Message__c</fullName>
    <description>Information regarding the installation from Sales Person to the Installer. This is RVN specific information.</description>
    <label>Installer Message OLD</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Side__c/Configuration_Side__c.object-meta.xml
<CustomObject>
    <description>Configuration Side Object to hold the Side information from the Configuration Products(Glazing, Terrace, Railing etc )</description>
    <label>Configuration Side</label>
    <nameField>
        <label>Configuration Side Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Sides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Side__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Sides</relationshipLabel>
    <relationshipName>Configuration_Sides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Side__c/fields/Side_Number__c.field-meta.xml
<CustomField>
    <fullName>Side_Number__c</fullName>
    <label>Side Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/Configuration_Side_Pane__c.object-meta.xml
<CustomObject>
    <label>Configuration Side Pane</label>
    <nameField>
        <label>Configuration Side Pane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Side Panes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Blind_Id__c.field-meta.xml
<CustomField>
    <fullName>Blind_Id__c</fullName>
    <label>Blind Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Blinds_Color__c.field-meta.xml
<CustomField>
    <fullName>Blinds_Color__c</fullName>
    <label>Blinds Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Blinds_Profile_Color__c.field-meta.xml
<CustomField>
    <fullName>Blinds_Profile_Color__c</fullName>
    <label>Blinds Profile Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Blinds_Type__c.field-meta.xml
<CustomField>
    <fullName>Blinds_Type__c</fullName>
    <label>Blinds Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Case_Profile_Color__c.field-meta.xml
<CustomField>
    <fullName>Case_Profile_Color__c</fullName>
    <label>Case Profile Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Configuration_Side__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Side__c</fullName>
    <label>Configuration Side</label>
    <referenceTo>Configuration_Side__c</referenceTo>
    <relationshipLabel>Configuration Side Panes</relationshipLabel>
    <relationshipName>Configuration_Side_Panes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Edge_Profile_Color__c.field-meta.xml
<CustomField>
    <fullName>Edge_Profile_Color__c</fullName>
    <label>Edge Profile Color</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Glass_Number__c.field-meta.xml
<CustomField>
    <fullName>Glass_Number__c</fullName>
    <label>Glass Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <description>Upholstery Height for Railing</description>
    <label>Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Side_Pane__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <description>Upholstery Width for Railing</description>
    <label>Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Configuration_Plan__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Plan OLD</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product OLD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Unique number (Sales Order Number + Visual given number) coming from Opportunity Product.</description>
    <label>RVN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BlindInstructionPdfController.cls
public class BlindInstructionPdfController {
    
    public Static List<ConfigurationWrapper> blindsData {get; set;}
    public Static String workOrderId {get; set;}
    
    public BlindInstructionPdfController(){
        workOrderId = ApexPages.currentPage().getParameters().get('workorderId');
        getBlindData(workOrderId);
    }
    
    public Static List<ConfigurationWrapper> getBlindData(String workOrderId){
        Set<Id> configurationPlanIdSet = new Set<Id>();
        String configurationPlanId;
        List<WorkOrder> workOrderRec = [SELECT Id, Opportunity__c, Configuration_Plan__c,
                                        (SELECT ID, Configuration_Product__c,Configuration_Product__r.Configuration__r.Plan_Type__c,Configuration_Product__r.Configuration__r.Id FROM WorkOrderLineItems 
                                         WHERE Configuration_Product__r.Configuration__r.Plan_Type__c ='Blinds')
                                        FROM WorkOrder  WHERE Id = :workOrderId];
        System.debug('*** workOrderRec ***'+workOrderRec);
        System.debug('*** workOrderRec ***'+workOrderRec[0].WorkOrderLineItems);
        if(workOrderRec.size() >0 && workOrderRec[0].WorkOrderLineItems.size() > 0){
            for(WorkOrderLineItem workLineRec : workOrderRec[0].WorkOrderLineItems){
                configurationPlanIdSet.add(workLineRec.Configuration_Product__r.Configuration__r.Id);
            }
        }
        System.debug('*** configurationPlanIdSet ***'+configurationPlanIdSet);
        Map<Id,Configuration_Product__c> configProdMap = new Map<Id,Configuration_Product__c>([SELECT Id,Name, RVN_Number__c, Product__r.Name, Installer_Message__c, Configuration__c,
                                                                                               Configuration__r.Plan_Type__c, Configuration__r.Name,opportunity__c,
                                                                                               (SELECT Id,NAME FROM Configuration_Sides__r ) 
                                                                                               FROM Configuration_Product__c  WHERE  Configuration__r.Plan_Type__c = 'Blinds'
                                                                                               AND Configuration__r.Id IN :configurationPlanIdSet]);
        
        
        Map<Id,Configuration_Side__c>  configSideRecordMap = new Map<Id,Configuration_Side__c>([SELECT Id,Name,Configuration_Product__c,Configuration_Product__r.Name,Side_Number__c, 
                                                                                                (SELECT Id, Glass_Number__c, Blinds_Type__c, Blinds_Color__c, Blinds_Profile_Color__c, 
                                                                                                 Case_Profile_Color__c, Edge_Profile_Color__c, Height__c, Width__c, Blind_Id__c, Quantity__c  
                                                                                                 FROM  Configuration_Side_Panes__r) 
                                                                                                from Configuration_Side__c  Where 
                                                                                                Configuration_Product__c  IN:configProdMap.keyset()]);
        List<ConfigurationWrapper> conWrapRecList = new List<ConfigurationWrapper>();
        
        for(Configuration_Product__c configProdRec : configProdMap.values()){
            //Adding product to the wrapper
            ConfigurationWrapper conWrapRec = new ConfigurationWrapper();
            
            conWrapRec.configProduct = configProdRec;
            System.debug('*** conWrapRec configProduct ***'+conWrapRec.configProduct);
            if(configProdRec.Configuration_Sides__r.size() > 0){
                List<ConfigurationSidesWrapper> configSideList = new List<ConfigurationSidesWrapper>();
                for(Configuration_Side__c configSideRec : configProdRec.Configuration_Sides__r){
                    if(configSideRecordMap.containsKey(configSideRec.Id)){
                        Configuration_Side__c configSide =configSideRecordMap.get(configSideRec.Id);
                        // adding configuration sides to the wrapper
                        ConfigurationSidesWrapper configsideWrap = new ConfigurationSidesWrapper();
                        configsideWrap.configside = configSideRecordMap.get(configSideRec.Id);
                        // adding config side panes to the wrapper
                        if(configSide.Configuration_Side_Panes__r.size() > 0){
                            configsideWrap.sidePanes = configSide.Configuration_Side_Panes__r;
                        }
                        configSideList.add(configsideWrap);
                    }
                }
                conWrapRec.configSideList = configSideList;
                System.debug('*** conWrapRec ***'+conWrapRec);
                conWrapRecList.add(conWrapRec);
            }
        }
        System.debug('*** conWrapRecList ***'+conWrapRecList);
        blindsData = conWrapRecList;
        return conWrapRecList;
    }
    
    @AuraEnabled
    public static Boolean checkBlindsData(String recordId){
        List<ConfigurationWrapper> blindsData = getBlindData(recordId);
        if(blindsData.size() > 0 ){
            return false;
        }else{
            return true;
        }
    } 
    
    public class ConfigurationWrapper {
        public Configuration_Product__c configProduct{ get; set; }
        public List<ConfigurationSidesWrapper> configSideList { get;set;}
    }
    
    public class ConfigurationSidesWrapper {
        public Configuration_Side__c configside {get; set;}
        public List<Configuration_Side_Pane__c> sidePanes {get; set;}
    }
    
}