force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the Contract to which this Configuration belongs.
Set when Quote is Accepted and Contract Signed</description>
    <inlineHelpText>Reference to the Contract to which this Configuration belongs</inlineHelpText>
    <label>Plan Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order OLD</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>Configuration_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product Entry in product2 Table</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <formula>Configuration_Product__r.RVN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <label>Sales Code OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <formula>Configuration_Product__r.Configuration__r.Visual_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visual Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Features_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Features_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce representation of hasFeaturesBeenConfirmed</description>
    <label>Features Confirmed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Code of the Product as using in External Systems</description>
    <formula>Product__r.Sales_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Code of the Product as using in External Systems</inlineHelpText>
    <label>Sales Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Option__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Item OLD</label>
    <referenceTo>Configuration_Option__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationItemController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class ConfigurationItemController {
    @AuraEnabled(cacheable=true)
    public static String getObjectType(String IdOrPrefix){
        String sObjectName = '';
        try{
            //Get prefix from record ID
            String recordIdPrefix = String.valueOf(IdOrPrefix).substring(0,3);     
            System.debug('--- PricingItemController - Get ObjectAPIName for prefix ' + recordIdPrefix);           
            //Get schema information
            Map<String, Schema.SObjectType> sObjectDescribeSchema =  Schema.getGlobalDescribe(); 
            //Loop through all the sObject types returned by Schema
            for(Schema.SObjectType sObjType : sObjectDescribeSchema.values()){
                //if (!sObjType.contains('__')) to exclude managed package objects
                Schema.DescribeSObjectResult sObjectDescribeResult = sObjType.getDescribe();
                String objectTypePrefix = sObjectDescribeResult.getKeyPrefix();
                 //Check if the prefix matches with requested prefix
                if(objectTypePrefix!=null && objectTypePrefix.equals(recordIdPrefix)){
                    sObjectName = sObjectDescribeResult.getName();
                    System.debug('--- PricingItemController - Set ObjectAPIName ' + sObjectName);
                    break;
                }
            }
        }catch(Exception e){
            System.debug(e);
        }
        return sObjectName;
    }
    @AuraEnabled(cacheable=true)
    public static Configuration__c getConfigurationPlan(String configId){
        Configuration__c configPlan =  [ SELECT Id,
                                                Name,
                                                Account__c,
                                                Opportunity__c,
                                                Quote__c,
                                                Contract__c,
                                                Order__c,
                                                Work_Order__c,
                                                Case__c
                                        FROM Configuration__c 
                                        WHERE Id =: configId
                                        LIMIT 1];
        System.debug('--- Configuration Plan: '+configPlan);
        return configPlan;
    }
    @AuraEnabled(cacheable=true)
    public static List<Configuration__c> getConfigurationPlans(String recordId){
        List<Configuration__c> configPlans = [ SELECT Id,
                                                        Name,
                                                        Account__c,
                                                        Opportunity__c,
                                                        Quote__c,
                                                        Contract__c,
                                                        Order__c,
                                                        Work_Order__c,
                                                        Case__c
                                                FROM Configuration__c 
                                                WHERE Account__c =: recordId
                                                OR Opportunity__c =: recordId
                                                OR Quote__c =: recordId
                                                OR Contract__c =: recordId
                                                OR Order__c =: recordId
                                                OR Work_Order__c =: recordId
                                                OR Case__c =: recordId];
        System.debug('--- Found '+configPlans.size()+' Configuration Plan(s)');
        return configPlans;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Configuration_Product__c> getConfigurationProducts(List<String> configIds){
        List<Configuration_Product__c> configProducts = new List<Configuration_Product__c>();
        configProducts = [  SELECT  Id,
                                    Name,
                                    Quantity__c,
                                    Sales_Code__c,
                                    Product__c,
                                    Product_Group__c,
                                    Configuration__c,
                                    RVN_Number__c
                            FROM Configuration_Product__c 
                            WHERE Configuration__c IN: configIds];
        return configProducts;
    }
    @AuraEnabled(cacheable=true)
    public static List<Configuration_Option__c> getConfigurationOptions(List<String> configProductIds){
        List<Configuration_Option__c> configOptions = new List<Configuration_Option__c>();
        configOptions = [   SELECT Id,
                                    Name,
                                    Quantity__c,
                                    Sales_Code__c,
                                    Product__c,
                                    Product__r.ProductCode,
                                    Product__r.Name,
                                    Product__r.Cost_Type__c,
                                    Product__r.QuantityUnitOfMeasure,
                                    Product_Group__c,
                                    Configuration_Product__c,
                                    RVN_Number__c
                            FROM Configuration_Option__c 
                            WHERE Configuration_Product__c IN: configProductIds];
        return configOptions;
    }   
    @AuraEnabled(cacheable=true)
    public static String getConfigurationObject(String recordId) {
        System.debug('--- Get Configuration Items');
        // Get all Plans for Record
        List<Configuration__c> cfgPlans= getConfigurationPlans(recordId);
        List<Id> cfgPlanIds = new List<Id>(new Map<Id, Configuration__c>(cfgPlans).keySet());
        // Get all Products for Each Plan
        List<Configuration_Product__c> cfgProducts = getConfigurationProducts(cfgPlanIds);
        List<Id> cfgProductIds = new List<Id>(new Map<Id, Configuration_Product__c>(cfgProducts).keySet());
        // Get all Items for Each Product
        List<Configuration_Option__c> cfgItems = getConfigurationOptions(cfgProductIds);
        List<Id> cfgItemIds = new List<Id>(new Map<Id, Configuration_Option__c>(cfgItems).keySet());
        System.debug('--- '+cfgItems.size()+' Configuration Item(s)');
        String itemJSON = JSON.serialize(cfgItems, true);
        // Get Configuration Items Summary
        List<sObject> cfgItemSummary =   [SELECT    Product_Group__c,
                                                    Product__r.Cost_Type__c,
                                                    Product__r.ProductCode,
                                                    Product__r.Name,
                                                    Product__r.Sales_Code__c,
                                                    Quantity__c,
                                                    Product__r.QuantityUnitOfMeasure
                                                FROM Configuration_Option__c
                                                WHERE Id IN : cfgItemIds];
        System.debug(JSON.serializePretty(cfgItemSummary));
        // Get Configuration Summary
        List<Object> cfgTableData =   [SELECT  Configuration__c,
                                                Configuration__r.Id,
                                                Configuration__r.Plan_Floor__c,
                                                Configuration__r.Plan_Apartment__c,
                                                Configuration__r.Visual_Id__c,
                                                RVN_Number__c,
                                                Name,
                                                Product__r.ProductCode,
                                                Product__r.Name,
                                                Product__r.Cost_Type__c,
                                                Product__r.QuantityUnitOfMeasure,
                                                Product_Group__c,
                                                (SELECT Product_Group__c,
                                                        Product__r.Cost_Type__c,
                                                        Product__r.ProductCode,
                                                        Product__r.Name,
                                                        Product__r.Sales_Code__c,
                                                        Quantity__c,
                                                        Product__r.QuantityUnitOfMeasure
                                                FROM Configuration_Options__r)
                                                Quantity__c,
                                                Features_Confirmed__c,
                                                Measurements_Verified__c,
                                                Visual_Product_Id__c,
                                                Inspection_Code__c,
                                                Product_Length__c,
                                                (SELECT Message_Key__c,
                                                        Space_Side_Number__c 
                                                FROM Configuration_Messages__r)
                                        FROM Configuration_Product__c WHERE Id IN : cfgPlanIds];
        System.debug(JSON.serializePretty(cfgTableData));
        ConfigurationItems configItemsObject = new ConfigurationItems ();// Parsed Result Object 
        System.debug('--- Configuration Item Object:  '+configItemsObject);
        return JSON.serialize(cfgItemSummary);
    }
    @AuraEnabled(cacheable=true)
    public static String getItemJSON(String recordId) {
        System.debug('--- Get Line Items');
        // Get all Plans for Record
        List<Configuration__c> cfgPlans= getConfigurationPlans(recordId);
        List<Id> cfgPlanIds = new List<Id>(new Map<Id, Configuration__c>(cfgPlans).keySet());
        // Get all Products for Each Plan
        List<Configuration_Product__c> cfgProducts = getConfigurationProducts(cfgPlanIds);
        List<Id> cfgProductIds = new List<Id>(new Map<Id, Configuration_Product__c>(cfgProducts).keySet());
        // Get all Items for Each Product
        List<Configuration_Option__c> cfgItems = getConfigurationOptions(cfgProductIds);
        List<Id> cfgItemIds = new List<Id>(new Map<Id, Configuration_Option__c>(cfgItems).keySet());
        System.debug('--- '+cfgItems.size()+' Configuration Item(s)');
        
        // Get Configuration Items Summary
        List<sObject> lineItems =   [SELECT    Product_Group__c,
                                                    Product__r.Cost_Type__c,
                                                    Product__r.ProductCode,
                                                    Product__r.Name,
                                                    Product__r.Sales_Code__c,
                                                    Quantity__c,
                                                    Product__r.QuantityUnitOfMeasure
                                                FROM Configuration_Option__c
                                                WHERE Id IN : cfgItemIds];
        System.debug('--- JSON: '+JSON.serializePretty(lineItems));
        String itemJSON=JSON.serialize(lineItems);
        System.debug('--- Configuration Item Object:  '+itemJSON);
        List<QuoteLineItem> quotelines = (List<QuoteLineItem>) JSON.deserialize(itemJSON,List<QuoteLineItem>.class);
        System.debug('--- QuoteLineItems:  '+quotelines);
        return itemJSON;
    }
    public class lineItemWrapper {
        List<QuoteLineItem> lineItems;
        
    }

}