force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Local_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Local_Supplier__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Local Supplier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Parameter_Code__c.field-meta.xml
<CustomField>
    <fullName>Parameter_Code__c</fullName>
    <label>Parameter Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <label>Sales Code OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <label>Unique Id OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit Of Measure OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Code of the Product as using in External Systems</description>
    <formula>Product__r.Sales_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Code of the Product as using in External Systems</inlineHelpText>
    <label>Sales Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <formula>TEXT(QuantityUnitOfMeasure)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LumonTestConfigurationOptions.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-15-2024
 * @last modified by  : Henk Reynders
**/
@IsTest 
public class LumonTestConfigurationOptions { 
    private static List<Product2> products = LumonTestVariables.products;
    private static List<Configuration__c> configPlans = LumonTestVariables.configPlans; 
    private static List<Configuration_Product__c> configProducts = LumonTestVariables.configProducts; 
    private static List<Configuration_Option__c> configOptions = LumonTestVariables.configOptions;  
    public static void setupConfigurationOptions() {
        if (configProducts.size()>0){
            System.debug('--- LumonTestConfigurationProducts - Using existing Test Configuration Products');
        } else {
            LumonTestConfigurationProducts.setupConfigurationProductData();
        }
        for (Configuration_Product__c configProduct : configProducts){
            setupConfigurationOptions(configProduct);
        }
        if (configProducts.size()>0){
            System.debug('No Parent Record existing');
            return;
        }
    }
    public static void setupConfigurationOptions(Configuration_Product__c configProduct) {
        List<Configuration_Option__c> configOptionsToUpsert = new List<Configuration_Option__c>();
        List<Product2 >configurableProducts = LumonTestVariables.configurableProducts;
        String productGroup = configProduct.Product_Group__c;
        for (Product2 configurableProduct : configurableProducts) {
            Id configurationProductId = configProduct.Id;
            Id productId = configurableProduct.Id;
            String productName = configurableProduct.Name;     
            String productCode = configurableProduct.ProductCode;
            String salesCode = configurableProduct.Sales_Code__c;
            Configuration_Option__c configOption = new Configuration_Option__c(
                                                    Name=productName,
                                                    Configuration_Product__c = configurationProductId,
                                                    //co.Local_Supplier__c = FALSE; //public Boolean LocalSupplier;
                                                    //co.Parameter_code__c = 'param1';// public String ParameterCode;
                                                    Product_Code__c = productCode,// public String SalesCode;
                                                    Sales_Code__c =  salesCode,// public String SalesCode;
                                                    Unique_Id__c = productCode,// public Integer UniqueId;
                                                    Quantity__c = 10, //public Double Amount;
                                                    Unit_Of_Measure__c = 'pcs'//public String Unit
            );
            configOptionsToUpsert.add(configOption);   
        }
        if (configOptionsToUpsert?.size()>0){
            upsert configOptionsToUpsert;
            System.debug('--- LumonTestConfigurationOptions - Upserted '+configOptionsToUpsert?.size()+' Configuration Options');
            
        }       
        System.debug('--- LumonTestConfigurationOptions - setup Options CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestConfigurationOptions - setup Options Queries used: '+LIMITS.getQueries());
    }

    public static void setupConfigurationOptionData() {
        try {           
            setupConfigurationOptions();
        } catch (Exception e){
            System.debug('--- LumonTestConfigurationOptions - Exception '+e);
        } 
    }
    @TestSetup
    static void prepareData() {
        Test.startTest();
        if(products?.size()>0){
            System.debug('--- LumonTestConfigurationOptions - Using existing Products');
        } else {
            LumonTestProducts.setupProductData();
        }
        if(configPlans?.size()>0){
            System.debug('--- LumonTestConfigurationOptions - Using existing Configuration Plans');
        } else {
            LumonTestConfigurations.setupConfigurationData();
        }
        if(configProducts?.size()>0){
            System.debug('--- LumonTestConfigurationOptions - Using existing Configuration Products');
        } else {
            LumonTestConfigurationProducts.setupConfigurationProductData();
        }
        Test.stopTest();
    }
    @isTest
    public static void setupConfigurationOptionDataTest(){
        String testResult;
        Test.startTest();
        try {
            setupConfigurationOptionData();
            testResult = 'successfully inserted Configuration Options';
        } catch (exception e){
            testResult = 'Error when inserting Configuration Options: '+e.getMessage();
        }
        System.debug('--- LumonTestConfigurationOptions - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestConfigurationOptions - Queries used: '+LIMITS.getQueries());
        Test.stopTest();       
        System.AssertNotEquals(true, testResult.contains('Error'));
        List<Configuration__c> configPlans = LumonTestVariables.configPlans;
        System.AssertNotEquals(0, configPlans.size(), ' Expected Configuration Plans to be Inserted');
        List<Configuration_Product__c> configProducts = LumonTestVariables.configProducts;
        System.AssertNotEquals(0, configProducts.size(), ' Expected Configuration Products to be Inserted');
        List<Configuration_Option__c> configOptions = LumonTestVariables.configOptions;
        System.AssertNotEquals(0, configOptions.size(), ' Expected Configuration Options to be Inserted');
    }
}