force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Installer_Message__c.field-meta.xml
<CustomField>
    <fullName>Installer_Message__c</fullName>
    <description>Information regarding the installation from Sales Person to the Installer. This is RVN specific information.</description>
    <label>Installer Message OLD</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/LUM_Parent_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>LUM_Parent_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InstallationPdfPageController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
public without sharing class InstallationPdfPageController {

    public List<Content> contents { get; private set; }

    public class Content {
        public String contentTitle { get; private set; }
        public String contentBody { get; private set; }
        public Content(String contentTitle, String contentBody) {
            this.contentTitle = contentTitle;
            this.contentBody = contentBody;
        }
    }

    public InstallationPdfPageController(){
        contents = new List<Content>();
        Id opportunityId;
        String spRecordId = ApexPages.currentPage().getParameters().get('service-appointment-id');
        String workOrderId = ApexPages.currentPage().getParameters().get('workorder-id');
        if (workOrderId != null) {
            opportunityId = [
                    SELECT Id, Opportunity__c
                    FROM WorkOrder
                    WHERE Id = :workOrderId
            ].Opportunity__c;

        } else if (spRecordId != null) {
            opportunityId = [
                    SELECT Id, LUM_Parent_Work_Order__r.Opportunity__c
                    FROM ServiceAppointment
                    WHERE Id = :spRecordId
            ].LUM_Parent_Work_Order__r.Opportunity__c;
        }

        /*if (opportunityId == null) {
            Log.get().publish('Unable to find opportunity for record id ' + workOrderId + ', or ' + spRecordId +
                    'unable to create installer instruction pdf',
                    new LogDetail(InstallerPDFController.class.toString()));
        }*/
        List<Configuration_Product__c> configurationProducts = [
                SELECT Id, RVN_Number__c, Product__r.Name, Installer_Message__c
                FROM Configuration_Product__c
                WHERE Configuration__r.Opportunity__c = :opportunityId
        ];
        for (Configuration_Product__c configurationProduct : configurationProducts) {
            if (configurationProduct.Installer_Message__c == null) {
                continue;
            }
            this.contents.add(new Content('<h3><b>' + configurationProduct.RVN_Number__c + ' - ' + configurationProduct.Product__r.Name + '</b></h3>',
                    '<p>' + configurationProduct.Installer_Message__c));
        }
    }
}