force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <formula>Configuration_Product__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types</description>
    <formula>Configuration_Product__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessSoveliaOutputTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-11-2023
 * @last modified by  : Henk Reynders
**/

@IsTest
private class ProcessSoveliaOutputTest {
	@TestSetup
	static void prepareData(){
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPriceBookEntries();
        // B2C Setup
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
	private static Id b2cConfigurationPlanId =LumonTestDataFactory.b2cConfigurationPlanId;

	@isTest
	static void processSoveliaOutputTest() {
		String rvn = [SELECT Id,RVN__c FROM Configuration_Product__c WHERE Configuration__c =: b2cConfigurationPlanId]?.get(0).RVN__c;
		String configString = '{"id":"1234", "name":"test123", "products":[{"rvn":"' + rvn + '"}]}';
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		req.requestURI = '/services/apexrest/soveliaOutput/' + b2cOpportunityId + '/pricing/json';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueOf(EncodingUtil.base64Encode(Blob.valueOf(configString)));
		RestContext.request = req;
		RestContext.response= res;
		Test.startTest();
		ProcessSoveliaOutput.doPost();
		Test.stopTest();
		System.assert([SELECT count() FROM ContentDocumentLink WHERE LinkedEntityId =: b2cConfigurationPlanId] > 0, 'There should be document created');
	}

	@isTest
	static void processSoveliaOutputReportTest() {
		String rvn = [SELECT Id,RVN__c FROM Configuration_Product__c WHERE Configuration__c =: b2cConfigurationPlanId]?.get(0).RVN__c;
		String configString = '{"RVN":"' + rvn + '"}';
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		req.requestURI = '/services/apexrest/soveliaOutput/' + b2cOpportunityId + '/report/json';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueOf(EncodingUtil.base64Encode(Blob.valueOf(configString)));

		RestContext.request = req;
		RestContext.response= res;

		Test.startTest();

		ProcessSoveliaOutput.doPost();

		Test.stopTest();

		System.assert([SELECT count() FROM ContentDocumentLink WHERE LinkedEntityId =: b2cConfigurationPlanId] > 0, 'There should be document created');
	}

	@isTest
	static void processSoveliaOutputCatchTest() {
		String rvn = [SELECT Id,RVN__c FROM Configuration_Product__c WHERE Configuration__c =: b2cConfigurationPlanId LIMIT 1]?.RVN__c;
		String configString = '{"RVN":"WRONG_RVN"}';
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		req.requestURI = '/services/apexrest/soveliaOutput/' + b2cOpportunityId + '/report/json';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueOf(EncodingUtil.base64Encode(Blob.valueOf(configString)));

		RestContext.request = req;
		RestContext.response= res;

		Test.startTest();

		ProcessSoveliaOutput.doPost();

		Test.stopTest();
	}

	@isTest
	static void processSoveliaOutputCatch2Test() {
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Id =: b2cOpportunityId LIMIT 1];
		Configuration__c config = [SELECT Id FROM Configuration__c WHERE Id =:b2cConfigurationPlanId LIMIT 1];

		String configString = '{"test":"test123"}';
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();
		req.requestURI = '/services/apexrest/soveliaOutput/' + b2cOpportunityId + '/pricing/json';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueOf(EncodingUtil.base64Encode(Blob.valueOf(configString)));

		RestContext.request = req;
		RestContext.response= res;

		Test.startTest();

		ProcessSoveliaOutput.doPost();

		Test.stopTest();
	}
}