force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/ConfigurationEvent__e.object-meta.xml
<CustomObject>
    <description>Event to initiate and control processing of Configurations and Prices</description>
    <label>Configuration Event</label>
    <pluralLabel>Configuration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfigurationEvent__e/fields/configAction__c.field-meta.xml
<CustomField>
    <fullName>configAction__c</fullName>
    <label>configAction</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configId__c.field-meta.xml
<CustomField>
    <fullName>configId__c</fullName>
    <description>Reference to the Salesforce Configuration (Plan) Record</description>
    <label>configId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configType__c.field-meta.xml
<CustomField>
    <fullName>configType__c</fullName>
    <description>Indicates the Type of Configuration this Event Relates to
-&gt; Any,Visual, Blinds, Pricing, Items</description>
    <label>configType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <description>The Type of Record</description>
    <label>objectType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/pricingJSON__c.field-meta.xml
<CustomField>
    <fullName>pricingJSON__c</fullName>
    <description>String that contains the JSON representation of the Pricing Items as received from Visual</description>
    <label>pricingJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the Current Record</description>
    <label>recordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/visualPlanId__c.field-meta.xml
<CustomField>
    <fullName>visualPlanId__c</fullName>
    <label>visualPlanId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationEventTriggerHandlerTest.cls
/**
 * @description       : NOT IN USE ConfigurationEventTriggerHandler commented Out
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-08-2024
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public class ConfigurationEventTriggerHandlerTest {
    /*@TestSetup
    static void prepareData(){
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPriceBookEntries();
        // B2C Setup
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;  
	@IsTest
	static void ProcessConfigurationEventsTest () {
        List<ConfigurationEvent__e> configChangeEvents = new List<ConfigurationEvent__e>();
        ConfigurationEvent__e configChangeEvent = new ConfigurationEvent__e();
        configChangeEvent.configId__c='123'; 
        configChangeEvent.recordId__c=b2cOpportunityId; 
        configChangeEvent.objectType__c='Opportunity'; 
        configChangeEvents.add(configChangeEvent);
		Test.startTest();
			ConfigurationEventTriggerHandler.processConfiguration(configChangeEvents);
		Test.stopTest();
	}
    @IsTest
	static void ProcessConfigurationEventsVisualTest () {
        List<ConfigurationEvent__e> configChangeEvents = new List<ConfigurationEvent__e>();
        ConfigurationEvent__e configChangeEvent = new ConfigurationEvent__e();
        configChangeEvent.configType__c='Test'; 
        configChangeEvent.configAction__c='Price'; 
        configChangeEvent.configId__c='123'; 
        configChangeEvent.recordId__c=b2cOpportunityId; 
        configChangeEvent.visualPlanId__c='789'; 
        configChangeEvent.pricingJSON__c='some text'; 
        configChangeEvents.add(configChangeEvent);
		Test.startTest();
			ConfigurationEventTriggerHandler.processConfiguration(configChangeEvents);
		Test.stopTest();
	}*/
}