force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Installer_Message__c.field-meta.xml
<CustomField>
    <fullName>Installer_Message__c</fullName>
    <description>Information regarding the installation from Sales Person to the Installer. This is RVN specific information.</description>
    <label>Installer Message OLD</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Configuration_Plan__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Plan OLD</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateInstallerPdfController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-05-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class GenerateInstallerPdfController {
    @AuraEnabled
    public static List<Configuration_Product__c> getConfigurationProducts(String recordId){
        System.debug('*** recordId ***'+recordId);
        Id opportunityId;
        String parentObject;
        String errorMessage;
        if (String.isNotBlank(recordId)){
            parentObject = DynamicObjectUtils.getObjectType(recordId);
        } else {
            errorMessage = 'No Parent Record Available!';
            System.debug('--- ABORT '+errorMessage);
            throw new CustomException(errorMessage);
        }
        System.debug('--- parentObject: '+parentObject);
        if (parentObject=='Opportunity' && String.isNotBlank(recordId)){  
            opportunityId = recordId;
        } else if (parentObject=='WorkOrder' && String.isNotBlank(recordId)){  
            opportunityId = [SELECT Id, Opportunity__c FROM WorkOrder WHERE Id = :recordId]?.Opportunity__c;
        }    
        System.debug('--- opportunityId: '+opportunityId);
        return [SELECT Id, RVN_Number__c, Product__r.Name, Installer_Message__c
                FROM Configuration_Product__c
                WHERE Configuration__r.Opportunity__c = :opportunityId];
    }
    
    /*@AuraEnabled
    public static List<Configuration_Product__c> getConfigBlindProducts(String recordId){
        String parentObject;
        String errorMessage;
        String configurationPlanId;
        if (String.isNotBlank(recordId)){
            parentObject = DynamicObjectUtils.getObjectType(recordId);
        }
        if (parentObject == 'WorkOrder' && String.isNotBlank(recordId)){  
            WorkOrder workOrderRec= [SELECT Id, Opportunity__c, Configuration_Plan__c,
                                     (SELECT ID, Configuration_Product__c,Configuration_Product__r.Configuration__r.Plan_Type__c,Configuration_Product__r.Configuration__r.Id FROM WorkOrderLineItems 
                                      WHERE Configuration_Product__r.Configuration__r.Plan_Type__c ='Blinds')
                                     FROM WorkOrder  WHERE Id = :recordId];
            if(workOrderRec.WorkOrderLineItems.size() > 0){
                configurationPlanId = workOrderRec.WorkOrderLineItems[0].Configuration_Product__r.Configuration__r.Id;
            }  
        }    
        return [SELECT Id, RVN_Number__c, Product__r.Name, Installer_Message__c, Configuration__c,Configuration__r.Plan_Type__c 
                FROM Configuration_Product__c  WHERE  Configuration__r.Plan_Type__c = 'Blinds'
                AND Configuration__r.Id = :configurationPlanId];
    }
*/
}