force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Visual_Version__c.field-meta.xml
<CustomField>
    <fullName>Visual_Version__c</fullName>
    <description>1 for Old Visual
2 for New Visual</description>
    <label>Visual Version OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <formula>Configuration_Product__r.Configuration__r.Visual_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visual Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Features_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Features_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce representation of hasFeaturesBeenConfirmed</description>
    <label>Features Confirmed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Measurements_Verified__c.field-meta.xml
<CustomField>
    <fullName>Measurements_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce equivalent of hasMeasurementsBeenVerified</description>
    <label>Measurements Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Line__c.field-meta.xml
<CustomField>
    <fullName>Plan_Line__c</fullName>
    <description>Plan Line used in the configuration</description>
    <label>Plan Line OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Visual_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Product_Id__c</fullName>
    <label>Visual Product Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_type__c.field-meta.xml
<CustomField>
    <fullName>Contract_type__c</fullName>
    <description>this defines contract type</description>
    <inlineHelpText>please mark contract type</inlineHelpText>
    <label>Contract type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preliminary Contract</fullName>
            </value>
            <value>
                <fullName>Final Contract</fullName>
                <default>true</default>
                <label>Final Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Promised Date from Quote</description>
    <formula>IF(TEXT(DATEVALUE(Opportunity__r.Preliminary_installation_time__c)) != &apos;&apos;,
TEXT(DATEVALUE(Opportunity__r.Preliminary_installation_time__c)),&apos;&apos;)</formula>
    <label>Delivery Date OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <description>To plan for installation, a Confirmed installation date &amp; time will show in this field. 
This data is captured from the Installation Capacity component. 
This custom field is part of the B2C lead to order process.</description>
    <inlineHelpText>The Confirmed installation date and time.</inlineHelpText>
    <label>Confirmed installation time DEL</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date when Finished Goods are delivered to Site or Warehouse</description>
    <inlineHelpText>This is automatic calculation of estimated earliest delivery date</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>The Type of Building</description>
    <inlineHelpText>The Type of Building</inlineHelpText>
    <label>Property Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terrain_Type__c.field-meta.xml
<CustomField>
    <fullName>Terrain_Type__c</fullName>
    <inlineHelpText>Classification of the Terrain Type
0 - Sea, coastal exposed to the open sea
I - Lakes or area with negligible vegetation
II - Area with low vegetation such as grass and isolated obstacles (trees, buildings) with separations of at least 20 obstacle heights
III - Area with regular cover of vegetation or buildings or with isolated obstacles with separations of maximum 20 obstacle heights (such as villages, suburban terrain, forest)
IV - Area in which at least 15 % of surface is cove</inlineHelpText>
    <label>Terrain Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Terrain_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Confirmed_installation_time__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_installation_time__c</fullName>
    <label>Confirmed installation time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceTerritory/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Terrain_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Terrain Class 0</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class I</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class II</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class III</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class IV</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class V</fullName>
        <isActive>false</isActive>
        <label>Terrain Class V</label>
    </customValue>
    <masterLabel>Lumon Terrain Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderTestDataFactory.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 06-19-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public with sharing class OrderTestDataFactory {
    @TestVisible
    private static Boolean isPersonAccountEnabled{
        get{
            return Schema.SObjectType.Account.fields.getMap().containsKey( 'isPersonAccount' );
        }
    }
    private static final Date Today = system.today(); 
    @future
    public static void setupOrderRecords() {
        Product2 p1 = new Product2(Name='Test Order Product 1', IsActive=True,ProductCode='COST',Product_Category__c='Product Models');
        Product2 p2 = new Product2(Name='Test Order Product 2', IsActive=True,ProductCode='Option 1',Product_Category__c='Product Options');
        Product2 p3 = new Product2(Name='Test Order Product 3', IsActive=True,ProductCode='Option 2',Product_Category__c='Product Options');
        insert new List<Product2> {p1,p2};
        system.debug ('*** setupOrderRecords product 1: '+p1);
        system.debug ('*** setupOrderRecords product 2: '+p2);
        system.debug ('*** setupOrderRecords product 2: '+p3);
        Id pbid = Test.getStandardPricebookId();
        PricebookEntry pbe1 = new PricebookEntry(Pricebook2Id=pbid, Product2Id=p1.id, UnitPrice=1, IsActive=True,CurrencyIsoCode = 'EUR');
        PricebookEntry pbe2 = new PricebookEntry(Pricebook2Id=pbid, Product2Id=p2.id, UnitPrice=2, IsActive=True,CurrencyIsoCode = 'EUR');
        PricebookEntry pbe3 = new PricebookEntry(Pricebook2Id=pbid, Product2Id=p3.id, UnitPrice=3, IsActive=True,CurrencyIsoCode = 'EUR');
        
        insert new List<PricebookEntry> {pbe1,pbe2};
        system.debug ('*** setupOrderRecords PricebookEntry 1: '+pbe1);
        system.debug ('*** setupOrderRecords PricebookEntry 2: '+pbe2);
        system.debug ('*** setupOrderRecords PricebookEntry 3: '+pbe3);
        String B2CRecordTypeId= [SELECT Id FROM RecordType WHERE (Name='B2C Account') and (SobjectType='Account')].Id;
        String B2BRecordTypeId= [SELECT Id FROM RecordType WHERE (Name='B2B Account') and (SobjectType='Account')].Id;
        List<Account> accts = new List<Account>();
        // Create B2C Account
        Account p = new Account(      
            RecordTypeID=B2CRecordTypeId,
            FirstName='My',
            LastName='Person Account',
            PersonEmail='test.order@factory.com',
            PersonMailingCountry ='Finland',
            PersonMailingCity='City',
            PersonMailingPostalCode = '33333',
            PersonMailingStreet='Street 1');
        accts.add(p);    
        Account a = new Account(
            RecordTypeID=B2BRecordTypeId,
            Name='Account Test Order',
            BillingCountry ='Finland',
            BillingCity='City',
            BillingPostalCode = '44444',
            BillingStreet = 'Street 2');
        accts.add(a);
        insert accts;        
        system.debug ('*** setupOrderRecords Person Account: '+p.id);
        system.debug ('*** setupOrderRecords Account: '+a.id);
        // Prepare Offer
        Opportunity o1 = new Opportunity(
            Name='B2C Opportunity 1', 
            StageName='Quoting', 
            CloseDate=system.Today()+10,
            Delivery_Date__c=System.Today()+90,
            Terrain_Type__c = 'Terrain Class I', // Not sure where needed
            Confirmed_installation_time__c = system.today()+90,
            Property_Type__c = 'ROW',
            Pricebook2Id=pbid,
            AccountId = p.Id
            );
        insert o1;
        Opportunity o2 = new Opportunity(
            Name='B2C Opportunity 2', 
            StageName='Quoting', 
            CloseDate=system.Today()+10,
            Delivery_Date__c=System.Today()+90,
            Terrain_Type__c = 'Terrain Class II', // Not sure where needed
            Confirmed_installation_time__c = system.today()+90,
            Property_Type__c = 'ROW',
            Pricebook2Id=pbid,
            AccountId = p.Id
            );
        insert o2;
        // Offer Send Pending Customer
        system.debug ('*** setupOrderRecords B2C Opportunity 1: '+o1.id);
        Contract c1 = new Contract(
            Name = 'B2C Draft Contract 1',
            AccountId = p.Id, 
            Status = 'Draft', 
            Contract_type__c = 'Final Contract',
            StartDate = Date.today(),
            Opportunity__c = o1.Id
            );
        insert c1;
        Contract c2 = new Contract(
            Name = 'B2C Draft Contract 2',
            AccountId = p.Id, 
            Status = 'Draft', 
            Contract_type__c = 'Final Contract',
            StartDate = Date.today(),
            Opportunity__c = o2.Id
            );
        insert c2;
        // Create Parent Config B2C
        Configuration__c cfg1 = new Configuration__c(
            Opportunity__c = o1.Id,
            Name='Test Order Config 1',
            Plan_Apartment__c = 'A1',// public String apartment; // Door Nbr in Apartment
            Plan_Floor__c = '6',// public Integer floor; // Floor Nbr in Building
            Visual_Id__c = 'ABCDE1',//public String id; // Unique Visual Configuration Id
            Plan_Line__c = '100',// public String line; //?
            Plan_Name__c = 'plan 1',// public String name; // Name of the Configuration
            //public List<Products> products; // Product Model aka Configurable Product
            Visual_Version__c = 1);//public Integer version; // Configuration Version);
        insert cfg1;
            // Create Parent Config B2C
            Configuration__c cfg2 = new Configuration__c(
                Opportunity__c = o2.Id,
                Name='Test Order Config 2',
                Plan_Apartment__c = 'A2',// public String apartment; // Door Nbr in Apartment
                Plan_Floor__c = '6',// public Integer floor; // Floor Nbr in Building
                Visual_Id__c = 'ABCDE2',//public String id; // Unique Visual Configuration Id
                Plan_Line__c = '100',// public String line; //?
                Plan_Name__c = 'plan 2',// public String name; // Name of the Configuration
                //public List<Products> products; // Product Model aka Configurable Product
                Visual_Version__c = 2);//public Integer version; // Configuration Version);
            insert cfg2;
        // Create Config Product(s)
        Configuration_Product__c cfgProd1 = new Configuration_Product__c(
            Name='LG', //public String name; // Name of the Product Model
            Configuration__c = cfg1.Id, // Parent Configuration
            Quantity__c = 1, // Amount must be 1 for each Product in a configuration
            Features_Confirmed__c = False,//public Boolean hasFeaturesBeenConfirmed;
            Measurements_Verified__c = False,// public Boolean hasMeasurementsBeenVerified;
            Visual_Product_Id__c = 'abcde1x',//public String id; // Product Code of Product Model
            Product_Type__c = 'Glazing',
            Inspection_Code__c = 2,//public Integer productInspectCode;
            Product_Length__c = 2.5, //public Double productLength;
            RVN_Number__c = '11111-1'); // public String rvn; //ProjectNbr + Structure);
        Configuration_Product__c cfgProd2 = new Configuration_Product__c(
            Name='COST', //public String name; // Name of the Product Model
            Configuration__c = cfg2.Id, // Parent Configuration
            Quantity__c = 1, // Amount must be 1 for each Product in a configuration
            Features_Confirmed__c = False,//public Boolean hasFeaturesBeenConfirmed;
            Measurements_Verified__c = False,// public Boolean hasMeasurementsBeenVerified;
            Visual_Product_Id__c = 'abcde2x',//public String id; // Product Code of Product Model
            Product_Type__c = 'Glazing',
            Inspection_Code__c = 2,//public Integer productInspectCode;
            Product_Length__c = 2.5, //public Double productLength;
            RVN_Number__c = '22222-2'); // public String rvn; //ProjectNbr + Structure);
        insert new List<Configuration_Product__c>{cfgProd1,cfgProd2};
        // Create Config Option
        Configuration_Option__c cfgOpt1 = new Configuration_Option__c(
            Name='Test Order Config Option 1',
            Configuration_Product__c = cfgProd1.Id,
            Quantity__c = 11.11, //public Double Amount;
            Local_Supplier__c = FALSE, //public Boolean LocalSupplier;
            Parameter_code__c = 'param1',// public String ParameterCode;
            Sales_Code__c = 'Option 1',// public String SalesCode;
            //unique_id__c = 1,// public Integer UniqueId;
            Unit_Of_Measure__c = 'M');//public String Unit
            //RVN_Number__c = '11111-1'// (oppty Number+) Visual Structure nbr  
        Configuration_Option__c cfgOpt2 = new Configuration_Option__c(
            Name='Test Order Config Option 2',
            Configuration_Product__c = cfgProd1.Id,
            Quantity__c = 11.22, //public Double Amount;
            Local_Supplier__c = FALSE, //public Boolean LocalSupplier;
            Parameter_code__c = 'param2',// public String ParameterCode;
            Sales_Code__c = 'Option 2',// public String SalesCode;
            //unique_id__c = 1,// public Integer UniqueId;
            Unit_Of_Measure__c = 'h');//public String Unit
            //RVN_Number__c = '11111-1'// (oppty Number+) Visual Structure nbr   
        Configuration_Option__c cfgOpt3 = new Configuration_Option__c(
            Name='Test Order Config Option 3',
            Configuration_Product__c = cfgProd2.Id,
            Quantity__c = 22.11, //public Double Amount;
            Local_Supplier__c = FALSE, //public Boolean LocalSupplier;
            Parameter_code__c = 'param3',// public String ParameterCode;
            Sales_Code__c = 'Option 3',// public String SalesCode;
            //unique_id__c = 1,// public Integer UniqueId;
            Unit_Of_Measure__c = 'pcs');//public String Unit
            //RVN_Number__c = '22222-2'// (oppty Number+) Visual Structure nbr   
        Configuration_Option__c cfgOpt4 = new Configuration_Option__c(
            Name='Test Order Config Option 4',
            Configuration_Product__c = cfgProd2.Id,
            Quantity__c = 22.22, //public Double Amount;
            Local_Supplier__c = FALSE, //public Boolean LocalSupplier;
            Parameter_code__c = 'param4',// public String ParameterCode;
            Sales_Code__c = 'Option 4',// public String SalesCode;
            //unique_id__c = 1,// public Integer UniqueId;
            Unit_Of_Measure__c = 'M2');//public String Unit
            //RVN_Number__c = '22222-2'// (oppty Number+) Visual Structure nbr   
        insert new List<Configuration_Option__c>{cfgOpt1,cfgOpt2,cfgOpt3,cfgOpt4};    
        // Create Config Message
        Configuration_Message__c cfgMsg1 = new Configuration_Message__c(
            Name='Test Order Config Message',
            Configuration_Product__c = cfgProd1.Id,
            Message_Key__c = 'E12345',
            Space_Side_Number__c = 1);
        Configuration_Message__c cfgMsg2 = new Configuration_Message__c(
            Name='Test Order Config Message',
            Configuration_Product__c = cfgProd2.Id,
            Message_Key__c = 'E12345',
            Space_Side_Number__c = 3);
        insert new List<Configuration_Message__c>{cfgMsg1,cfgMsg2}; 

        // Prepare FSL Appointment
        OperatingHours oh = new OperatingHours(Name = 'testOH');
		insert oh;

		FSL__Scheduling_Policy__c sp = new FSL__Scheduling_Policy__c(Name = 'Custom Component Reservation');
		insert sp;

		ServiceTerritory st = new ServiceTerritory(Name = 'testT', Appointment_Booking_Offset__c = 5, OperatingHoursId = oh.Id, IsActive = true);
		insert st;
		st = [SELECT Id, Appointment_Booking_Offset__c FROM ServiceTerritory Limit 1];

		WorkOrder wo = new WorkOrder(Subject = o1.Name, Opportunity__c = o1.Id, AccountId = o1.AccountId, ContactId = p.PersonContactId, LocationId = o1.Delivery_Location__c, Duration = o1.Installation_duration__c, DurationType = 'Hours', ServiceTerritoryId = st.Id);
        insert wo;

		ServiceAppointment sa = new ServiceAppointment(ParentRecordId = wo.Id, EarliestStartTime = o1.Delivery_date__c, DueDate = o1.Delivery_date__c.addDays(5), Duration = o1.Installation_duration__c);
        insert sa;
        
        
    }
}