force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product Entry in product2 Table</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types</description>
    <formula>Configuration_Product__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Sales Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Option__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Item OLD</label>
    <referenceTo>Configuration_Option__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types retrieved from related Configuration Option</description>
    <formula>Configuration_Option__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LumonTestQuoteLines.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class LumonTestQuoteLines {
    private static List<Product2> products = LumonTestProducts.products;
    private static List<PricebookEntry> pricebookEntries = LumonTestVariables.pricebookEntries;
    private static List<Configuration__c> configPlans = LumonTestConfigurationPlans.configurationPlans; 
    private static List<Configuration_Product__c> configProducts = LumonTestConfigurationProducts.configurationProducts; 
    private static List<Configuration_Option__c> configOptions = LumonTestConfigurationOptions.configurationOptions;
    private static List<Quote> quotes = LumonTestQuotes.quotes;
    
    public static List<Configuration_Option__c> configurationOptions {
        get{
            return [ SELECT Id,Name, Configuration_Product__c, Product__c,RVN__c,Quantity__c, 
                            Product__r.QuantityUnitOfMeasure, Product__r.ProductGroup__c,Product__r.ProductCode__c 
                        FROM Configuration_Option__c];
        }
    }
    public static void setupQuoteLineItems() {     
        if (quotes.size()>0){
            System.debug('--- LumonTestQuoteLines - Using existing Test Quotes');
        } else {
            LumonTestQuotes.setupQuoteData();
        }
        for (Quote quote : quotes){
            setupQuoteLineItems(quote.Id);
        }
    }
    public static void setupQuoteLineItems(Id quoteId) {
        setupQuoteLineItems(quoteId,configOptions);
    }
    public static void setupQuoteLineItems(Id quoteId, List<Configuration_Option__c> configOptions) {

        List<QuoteLineItem> quoteLineItems = new List<QuoteLineItem>();
        Map<String,PricebookEntry> priceMap = new Map<String,PricebookEntry>();
        for (PricebookEntry pbe : pricebookEntries) {
            String productCode = pbe.Product2.ProductCode;
            priceMap.put(productCode,pbe);
        }
        if(!configOptions.isEmpty()){
            for (Configuration_Option__c configOption : configOptions){         
                QuoteLineItem qli = new QuoteLineItem();
                qli.QuoteId=quoteId;
                qli.Product2Id=configOption.Product__c;               
                qli.PricebookEntryId=priceMap.get(configOption.Product__r.ProductCode)?.Id;
                qli.Quantity=1;
                qli.UnitPrice=priceMap.get(configOption.Product__r.ProductCode)?.UnitPrice;
                quoteLineItems.add(qli);
            }
        }
        insert quoteLineItems;
    }


    public static void setupQuoteLineData() {
        if (quotes.size()>0) {
            System.debug('--- LumonTestQuoteLines - Using existing Quotes');
        } else {
            LumonTestQuotes.setupQuoteData();
        }
        if (configOptions.size()>0) {
            System.debug('--- LumonTestQuoteLines - Using existing Configuration Options');
        } else {
            LumonTestConfigurationOptions.setupConfigurationOptionData();
        }
        try {
            setupQuoteLineItems();
        }catch (Exception e){
            System.debug('--- LumonTestQuoteLines - Error setupConfigurationData Exception '+e);
        } 
    }
    @TestSetup
    static void prepareData() {
        Test.startTest();
        Test.stopTest();
    }
    @IsTest
    static void setupQuoteLineDataTest(){
        String testResult;
        Test.startTest();
        try {
            setupQuoteLineData();
            testResult = 'successfully inserted Quote Lines';
        } catch (exception e){
            testResult = 'Error when inserting Quote Lines: '+e.getMessage();
        }
        System.debug('--- LumonTestQuotes - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestQuotes - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();       
        System.AssertNotEquals(true, testResult.contains('Error'));
    }
}