force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/ConfigurationEvent__e.object-meta.xml
<CustomObject>
    <description>Event to initiate and control processing of Configurations and Prices</description>
    <label>Configuration Event</label>
    <pluralLabel>Configuration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfigurationEvent__e/fields/blindsJSON__c.field-meta.xml
<CustomField>
    <fullName>blindsJSON__c</fullName>
    <label>blindsJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configAction__c.field-meta.xml
<CustomField>
    <fullName>configAction__c</fullName>
    <label>configAction</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configId__c.field-meta.xml
<CustomField>
    <fullName>configId__c</fullName>
    <description>Reference to the Salesforce Configuration (Plan) Record</description>
    <label>configId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configJSON__c.field-meta.xml
<CustomField>
    <fullName>configJSON__c</fullName>
    <description>JSON Representation of the Configuration Objects</description>
    <label>configJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configType__c.field-meta.xml
<CustomField>
    <fullName>configType__c</fullName>
    <description>Indicates the Type of Configuration this Event Relates to
-&gt; Any,Visual, Blinds, Pricing, Items</description>
    <label>configType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/documentId__c.field-meta.xml
<CustomField>
    <fullName>documentId__c</fullName>
    <label>documentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/externalId__c.field-meta.xml
<CustomField>
    <fullName>externalId__c</fullName>
    <label>externalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/itemJSON__c.field-meta.xml
<CustomField>
    <fullName>itemJSON__c</fullName>
    <description>JSON Representation of the Line Items</description>
    <label>itemJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <description>The Type of Record</description>
    <label>objectType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/pricingJSON__c.field-meta.xml
<CustomField>
    <fullName>pricingJSON__c</fullName>
    <description>String that contains the JSON representation of the Pricing Items as received from Visual</description>
    <label>pricingJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the Current Record</description>
    <label>recordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/structureJSON__c.field-meta.xml
<CustomField>
    <fullName>structureJSON__c</fullName>
    <description>The String to hold the JSON of the Structure</description>
    <label>structureJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/visualPlanId__c.field-meta.xml
<CustomField>
    <fullName>visualPlanId__c</fullName>
    <label>visualPlanId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationEventTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
@isTest(isParallel=false)
public class ConfigurationEventTest {
    public class CustomException extends Exception {}
    private static Id b2cAccountId = LumonTestVariables.b2cAccountId;
    private static Id b2bAccountId = LumonTestVariables.b2bAccountId;
    private static Id b2cOpportunityId = LumonTestVariables.b2cOpportunityId;
    private static Id b2bOpportunityId = LumonTestVariables.b2cOpportunityId;
    
	private static List<Id> configurationPlanIds = LumonTestVariables.configurationPlanIds;
    private static List<Id> configurationProductIds = LumonTestVariables.configurationProductIds;
    private static List<Id> configurationOptionIds = LumonTestVariables.configurationOptionIds;

    private static List<Configuration__c> configurationPlans = LumonTestVariables.configurationPlans;
    private static List<Configuration_Product__c> configurationProducts = LumonTestVariables.configurationProducts;
    private static List<Configuration_Option__c> configurationOptions = LumonTestVariables.configurationOptions;
    private static List<Configuration_Message__c> configurationMessages = LumonTestVariables.configurationMessages;
    private static String visualPricingJSON = LumonTestData.visualPricing;
    private static String soveliaPricingJSON = LumonTestData.soveliaPricing;
    @TestSetup
    static void prepareData(){
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPrices();
        LumonTestDataFactory.setupConfigurations();
        Test.stopTest();
    }
    @isTest static void validEventTest() {
        List<Opportunity> opps = ([SELECT Id FROM Opportunity LIMIT 1]);
        String recordId = opps[0].Id;
        // Create a test event instance
        ConfigurationEvent__e cfgEvent = new ConfigurationEvent__e(recordId__c=recordId, 
                                                                    configId__c=null, 
                                                                    visualPlanId__c='12345',
                                                                    configJSON__c='');
        Test.startTest();       
        // Publish test event
        Database.SaveResult sr = EventBus.publish(cfgEvent);          
        Test.stopTest();       
        System.assertEquals(true, sr.isSuccess());
    }

    @isTest static void allParamsEventTest() {
        List<Opportunity> opps = ([SELECT Id FROM Opportunity LIMIT 1]);
        String recordId = opps[0].Id;
        // Create a test event instance
        ConfigurationEvent__e cfgEvent = new ConfigurationEvent__e(configType__c='Type',
                                                                    configAction__c ='Action',
                                                                    recordId__c=recordId, 
                                                                    objectType__c = 'Opportunity',
                                                                    configId__c='123', 
                                                                    externalId__c='123ABC',
                                                                    visualPlanId__c='ABCDE',
                                                                    documentId__c='456',
                                                                    blindsJSON__c='',
                                                                    configJSON__c='',
                                                                    itemJSON__c='',
                                                                    pricingJSON__c='',
                                                                    structureJSON__c='');
        Test.startTest();       
        // Publish test event
        Database.SaveResult sr = EventBus.publish(cfgEvent);          
        Test.stopTest();       
        System.assertEquals(true, sr.isSuccess());
    }
    
    @isTest static void invalidEventTest() {     
        // Create a test event instance with invalid data.
        // We assume for this test that the Serial_Number__c field is required.
        // Publishing with a missing required field should fail.
        ConfigurationEvent__e cfgEvent = new ConfigurationEvent__e(recordId__c=null, 
                                                                    configId__c=null, 
                                                                    visualPlanId__c='12345',
                                                                    configJSON__c='');
        
        Test.startTest(); 
        // Publish test event
        Database.SaveResult sr = EventBus.publish(cfgEvent);
        Test.stopTest();       
        System.assertEquals(false, sr.isSuccess());      
        // Log the error message
        for(Database.Error err : sr.getErrors()) {
            System.debug('Error returned: ' +
                        err.getStatusCode() +
                        ' - ' +
                        err.getMessage()+' - '+err.getFields());
        }
        // Verify that something did not happen
    }
}