force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <description>Unique Configuration Id from Visual</description>
    <externalId>true</externalId>
    <label>Visual Id OLD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Visual_Id__c.field-meta.xml
<CustomField>
    <fullName>Visual_Id__c</fullName>
    <formula>Configuration_Product__r.Configuration__r.Visual_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visual Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConfigurationPlanControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-01-2023
 * @last modified by  : Henk Reynders
**/
@IsTest(isParallel=false)
public with sharing class ConfigurationPlanControllerTest {
    @TestSetup
    static void prepareData(){
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPrices();
        // B2C Setup
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
    @IsTest
    static void getConfigurationsByIdTest(){
        List<Configuration__c> configurationPlans = b2cConfigurations;
        Id configId = configurationPlans[0].Id;
        Id relatedRecordId = b2cOpportunityId;
        String planId = configurationPlans[0].Visual_Id__c;
        System.debug('--- getConfigurationsByIdTest - configId: '+configId);
        System.debug('--- getConfigurationsByIdTest - relatedRecordId: '+relatedRecordId); 
        System.debug('--- getConfigurationsByIdTest - planId: '+planId);  
        Test.startTest();
        List<Configuration__c> configPlans = ConfigurationPlanController.getConfigurationPlans(configId,relatedRecordId,planId);
        System.assertNotEquals(0, configPlans.size(), 'Expecting atleast 1 Configuration to be returned');
        System.debug('--- getConfigurationsByIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getConfigurationsByIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    
    @IsTest
    static void getConfigurationPlansByIdsTest(){ 
        List<Configuration__c> configPlans = b2cConfigurations; 
        List<Id> configIds = new List<Id>(new Map<Id, Configuration__c>(configPlans).keySet()); 
        Test.startTest();
        List<Configuration__c> configurationPlans = ConfigurationPlanController.getConfigurationPlansByIds(configIds);
        System.assertNotEquals(0, configurationPlans.size(), 'Expecting atleast 1 Configuration to be returned');
        System.debug('--- getConfigurationPlansByIdsTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getConfigurationPlansByIdsTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }     
            
    @IsTest
    static void getConfigurationsByRelatedIdTest(){
        List<Configuration__c> configurationPlans = b2cConfigurations;
        Id configId;
        Id relatedRecordId = b2cOpportunityId;
        String planId;
        System.debug('--- getConfigurationsByRelatedIdTest - configId: '+configId);
        System.debug('--- getConfigurationsByRelatedIdTest - relatedRecordId: '+relatedRecordId); 
        System.debug('--- getConfigurationsByRelatedIdTest - planId: '+planId);     
        Test.startTest();
        List<Configuration__c> configPlans = ConfigurationPlanController.getConfigurationPlans(configId,relatedRecordId,planId);
        System.assertNotEquals(0, configPlans.size(), 'Expecting atleast 1 Configuration to be returned');
        System.debug('--- getConfigurationsByRelatedIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getConfigurationsByRelatedIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }  
    
    @IsTest
    static void getVisualIdsToPlanMapTest(){
        List<Configuration__c> configurationPlans = b2cConfigurations;     
        Test.startTest();
        Map<String,Configuration__c> visualToPlanMap = ConfigurationPlanController.getVisualIdsToPlanMap(configurationPlans);
        System.assertNotEquals(null, visualToPlanMap, 'Expecting atleast 1 entry to be returned');
        System.debug('--- getVisualIdsToPlanMapTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getVisualIdsToPlanMapTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }  
    @IsTest
    static void getOpportunitiesToPlanMapTest(){
        List<Configuration__c> configurationPlans = b2cConfigurations;     
        Test.startTest();
        Map<Id,Configuration__c> oppToPlanMap = ConfigurationPlanController.getOpportunitiesToPlanMap(configurationPlans);
        System.assertNotEquals(null, oppToPlanMap, 'Expecting atleast 1 entry to be returned');
        System.debug('--- getOpportunitiesToPlanMapTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getOpportunitiesToPlanMapTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }     
    @IsTest
    static void getConfigurationsByPlanIdTest(){
        List<Configuration__c> configurationPlans = b2cConfigurations;
        Id configId;
        Id relatedRecordId;
        String planId = configurationPlans[0].Visual_Id__c;
        System.debug('--- getConfigurationsByRelatedIdTest - configId: '+configId);
        System.debug('--- getConfigurationsByRelatedIdTest - relatedRecordId: '+relatedRecordId); 
        System.debug('--- getConfigurationsByRelatedIdTest - planId: '+planId);     
        Test.startTest();
        List<Configuration__c> configPlans = ConfigurationPlanController.getConfigurationPlans(configId,relatedRecordId,planId);
        System.assertNotEquals(0, configPlans.size(), 'Expecting atleast 1 Configuration to be returned');
        System.debug('--- getConfigurationsByRelatedIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getConfigurationsByRelatedIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }  
}