force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Configured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Planning Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Configured</fullName>
            </value>
            <value>
                <fullName>Offered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SoveliaContainerController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 02-05-2024
 * @last modified by  : Henk Reynders
**/

public with sharing class SoveliaContainerController {
    @AuraEnabled
    public static InitWrapper getRVN(Id recordId) {  
        InitWrapper wrapper = new InitWrapper();
        wrapper.isSandbox = ([SELECT IsSandbox FROM Organization LIMIT 1]?.IsSandbox);
        wrapper.rvn = '';
        wrapper.errorMessage = '';
        wrapper.opportunityId = '';
        wrapper.configurationProductId = '';
        Savepoint savePoint = Database.setSavepoint();
        try {
            String configurationProductId = '';
            if (recordId.getSobjectType() == Opportunity.getSObjectType()) {
                Configuration__c config = new Configuration__c(
                    Opportunity__c = recordId,
                    Plan_Type__c = 'Blinds',
                    Plan_Name__c = 'After Sales Blinds',
                    Status__c = 'Draft'
                );
                insert config;
                Configuration_Product__c configProduct = new Configuration_Product__c(
                    Configuration__c = config.Id,
                    Quantity__c = 1
                );
                insert configProduct;
                configurationProductId = configProduct.Id;
            } else if (recordId.getSobjectType() == Configuration_Product__c.getSObjectType()) {
                configurationProductId = recordId;
                wrapper.configurationProductId = recordId;
            }
            System.debug('--- configurationProductId: '+configurationProductId);
            Configuration_Product__c configurationProduct = [
                SELECT RVN__c, Configuration__r.Opportunity__c
                FROM Configuration_Product__c
                WHERE Id = :configurationProductId
                LIMIT 1
            ];
            wrapper.rvn = configurationProduct.RVN__c;
            wrapper.opportunityId = configurationProduct.Configuration__r.Opportunity__c;
            
            System.debug('--- recordId: '+recordId);
            System.debug('--- configurationProduct: '+configurationProduct);
        } catch (DmlException ex) {
            Database.rollback(savePoint);
            wrapper.errorMessage = ex.getDmlMessage(0);
        } catch (Exception e) {
            Database.rollback(savePoint);
            wrapper.errorMessage = e.getMessage();
        }
        System.debug(JSON.serialize(wrapper));
        return wrapper;
    }

    public class InitWrapper {
        @AuraEnabled
        public Boolean isSandbox { public get; set; }     
        @AuraEnabled
        public String rvn { public get; set; }
        @AuraEnabled
        public String opportunityId { public get; set; }
        @AuraEnabled
        public String configurationProductId { public get; set; }
        @AuraEnabled
        public String errorMessage { public get; set; }
    }
}