force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Option__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Item OLD</label>
    <referenceTo>Configuration_Option__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 03-13-2024
 * @last modified by  : Henk Reynders
**/
@IsTest
public class QuoteLineItemControllerTest {
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static Id b2cSyncedQuoteId = LumonTestDataFactory.b2cSyncedQuoteId;
    private static Id b2cQuoteId = LumonTestDataFactory.b2cQuoteId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
    @TestSetup
    static void prepareData() {
        Test.startTest();
        LumonTestDataFactory.setupGlazingSliding();
        LumonTestDataFactory.setupGlazingRetractable();
        LumonTestDataFactory.setupAdditionalCosts();
        LumonTestDataFactory.setupExtraSales();
        // B2C Setup
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();
        LumonTestDataFactory.setupPriceParameters();
        LumonTestDataFactory.setupPricingSummaryB2C();
        LumonTestDataFactory.setupSyncedQuoteB2C();        
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupSyncedQuoteLineItemsB2C();
        Test.stopTest();
    }     
    @IsTest
    static void getQuoteLineItemsTest(){
        Test.startTest();
        List<QuoteLineItem> qlis = QuoteLineItemController.getQuoteLineItems(b2cSyncedQuoteId);
        System.Debug ('--- '+ qlis.size() +' QuoteLineItems Returned');
		System.assertNotEquals(0,qlis.size(), 'Expected Quote Lines Items to be returned');
        System.debug('--- getQuoteLineItemsTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getQuoteLineItemsTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }   
    @IsTest
    static void getQuoteLineItemsByIdTest(){
        Test.startTest();
        List<Id> quoteIds = new List<Id>{b2cSyncedQuoteId};
        List<QuoteLineItem> qlis = QuoteLineItemController.getQuoteLineItemsById(quoteIds);
        System.Debug ('--- '+ qlis.size() +' QuoteLineItems Returned');
		System.assertNotEquals(0,qlis.size(), 'Expected Quote Lines Items to be returned');
        System.debug('--- getQuoteLineItemsByIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getQuoteLineItemsByIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getQuoteLineItemsToProductMapTest(){
        List<QuoteLineItem> qlis = QuoteLineItemController.getQuoteLineItems(b2cSyncedQuoteId);
        Test.startTest();
        Map<String,QuoteLineItem>  qliMap = QuoteLineItemController.getQuoteLineItemsToProductMap(qlis);
        System.Debug ('--- '+ qliMap.size() +' QuoteLineItems Returned in a Map');
		System.assertNotEquals(0,qliMap.size(), 'Expected Quote Lines Items to be returned');
        System.debug('--- getQuoteLineItemsByProductTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getQuoteLineItemsByProductTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getQuoteLineItemsToGroupMapTest(){
        List<QuoteLineItem> qlis = QuoteLineItemController.getQuoteLineItems(b2cSyncedQuoteId);
        Test.startTest();
        Map<String,QuoteLineItem>  qliMap = QuoteLineItemController.getQuoteLineItemsToGroupMap(qlis);
        System.Debug ('--- '+ qliMap.size() +' QuoteLineItems Returned in a Map');
		System.assertNotEquals(0,qliMap.size(), 'Expected Quote Lines Items to be returned');
        System.debug('--- getQuoteLineItemsToGroupMapTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getQuoteLineItemsToGroupMapTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
}