force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Apartment OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <label>Floor OLD</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>Plan_Type__c</fullName>
    <description>Type of Plan ,eg Visual, Blinds, Services</description>
    <label>Plan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Plan_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Count_Items__c.field-meta.xml
<CustomField>
    <fullName>Count_Items__c</fullName>
    <label>Count Items OLD</label>
    <summaryForeignKey>Configuration_Option__c.Configuration_Product__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Inspection_Code__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Code__c</fullName>
    <description>Salesforce equivalent of productInspectCode</description>
    <label>Inspection Code OLD</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Apartment__c.field-meta.xml
<CustomField>
    <fullName>Plan_Apartment__c</fullName>
    <description>Plan Apartment used in the configuration</description>
    <label>Plan Apartment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Floor__c.field-meta.xml
<CustomField>
    <fullName>Plan_Floor__c</fullName>
    <description>Plan Floor used in the configuration</description>
    <label>Plan Floor OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Line__c.field-meta.xml
<CustomField>
    <fullName>Plan_Line__c</fullName>
    <description>Plan Line used in the configuration</description>
    <label>Plan Line OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Plan_Name__c.field-meta.xml
<CustomField>
    <fullName>Plan_Name__c</fullName>
    <description>Lumon Plan Name as part of configuration</description>
    <inlineHelpText>Lumon Plan Name as part of configuration</inlineHelpText>
    <label>Plan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Item__c.field-meta.xml
<CustomField>
    <fullName>Product_Item__c</fullName>
    <inlineHelpText>Third Level Grouping of Products and Services</inlineHelpText>
    <label>Product Item OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Reference to the Product Model for this Item</description>
    <label>Product Model OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/ProductIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ProductIdentifier__c</fullName>
    <description>8 Digit Identifier for Configuration Products
Used in the RVN Identifier &lt;OpportunityNumber&gt;&lt;ProductIdentifier)</description>
    <displayFormat>6{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Unique Identifier for Configuration Products</inlineHelpText>
    <label>Product Identifier</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Code of the Product as using in External Systems</description>
    <formula>Product__r.Sales_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Code of the Product as using in External Systems</inlineHelpText>
    <label>Sales Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <description>The Unique Identifier of a Configuration Product (RVN)</description>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Product Sales Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ProductIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>Product Identifier</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Plan_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visual</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Sovelia</fullName>
    </customValue>
    <masterLabel>Lumon Plan Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>F-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing Beads</fullName>
    </customValue>
    <customValue>
        <fullName>h-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>L-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Rectangular Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Telescopic Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>U-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Upper Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Wall Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Screws</fullName>
    </customValue>
    <customValue>
        <fullName>Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 1</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 2</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 3</fullName>
    </customValue>
    <customValue>
        <fullName>Special Colors</fullName>
    </customValue>
    <customValue>
        <fullName>Sand Blasting</fullName>
    </customValue>
    <customValue>
        <fullName>Special Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Edge Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Items</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfigurationProductController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-09-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ConfigurationProductController {
    @AuraEnabled(cacheable=true)
    public static Configuration_Product__c getConfigurationProduct(Id recordId) { 
        // Find Configuration Product based on recordId
        List<Id> recordIds = new List<Id>{recordId};
        List<Configuration_Product__c> configProducts = getConfigurationProducts(recordIds);
        Configuration_Product__c configProduct = configProducts[0];
        return configProduct;
    }   
    @AuraEnabled(cacheable=false)
    public static Configuration_Product__c getConfigurationProductByNumber(String rvnNumber) {
        // Populate List from SOQL query on Product
        Id configProductId = [SELECT Id, SerialNumber__c FROM Configuration_Product__c WHERE ProductIdentifier__c =: rvnNumber LIMIT 1]?.Id; 
        List<Id> configProductIds = new List<Id>();
        configProductIds.add(configProductId);
        Configuration_Product__c configProduct = new Configuration_Product__c();
        System.debug('--- ConfigurationProductController - Get Configuration Product with Id '+configProductId); 
        List<Configuration_Product__c> configProducts =  getConfigurationProducts(configProductIds); 
        if  (configProducts?.size()>0) {
            configProduct = configProducts[0];
            System.debug('--- ConfigurationProductController - Configuration Product: '+configProduct.Name); 
        }        
        return configProduct;
    }
    @AuraEnabled(cacheable=true)
    public static List<Configuration_Product__c> getConfigurationProducts(List<Id> recordIds){
        List<Configuration_Product__c> configProducts = new List<Configuration_Product__c>();
        configProducts = [  SELECT  Id,
                                    Name,
                                    Configuration__c, // Keep
                                    ProductCode__c, //New
                                    SerialNumber__c, //New
                                    Configuration__r.Opportunity__c,
                                    Configuration__r.Plan_Type__c,
                                    Product_Group__c,
                                    Product_Model__c,
                                    Sales_Code__c,
                                    Quantity__c,
                                    Product__c,
                                    Product__r.Name,
                                    Product__r.Product_Group__c,
                                    Product__r.Cost_Category__c,
                                    Product__r.Cost_Type__c,
                                    Product__r.Product_Category__c, 
                                    Product__r.Product_Type__c, 
                                    Product__r.Product_Item__c, 
                                    Product__r.ProductCode, 
                                    Product__r.Sales_Code__c,
                                    Product__r.QuantityUnitOfMeasure,
                                    Product__r.Reclamation__c,
                                    Product__r.Installation__c,
                                    Product__r.IsActive,
                                    RVN_Number__c,
                                    RVN__c,
                                    Inspection_Code__c,
                                    Configuration__r.Plan_Apartment__c,
                                    Configuration__r.Plan_Line__c,
                                    Configuration__r.Plan_Floor__c,
                                    Configuration__r.Plan_Name__c,
                                    Count_Items__c
                            FROM Configuration_Product__c 
                            WHERE Id IN: recordIds
                            OR Configuration__c IN: recordIds
                            OR Configuration__r.Opportunity__c IN: recordIds 
                            OR Product__c IN: recordIds];
        return configProducts;
    }
}