force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>RVN Number unique value related to each Visual configuration</description>
    <formula>Opportunity__r.Opportunity_Number__c +  Visual_Structure_Number__c</formula>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <formula>Configuration_Product__r.Configuration__r.RVN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN Number OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <formula>Configuration_Product__r.RVN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Signing_status__c.field-meta.xml
<CustomField>
    <fullName>Signing_status__c</fullName>
    <label>Signing status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderGeneratorTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
 private class OrderGeneratorTest {
     @testSetup static void prepareData() {
         Test.startTest();
         LumonTestDataFactory.setupProducts();
         LumonTestDataFactory.setupPriceBookEntries();
         // B2C Setup
         LumonTestDataFactory.setupAccountB2C();
         LumonTestDataFactory.setupOpportunityB2C();
         LumonTestDataFactory.setupPriceParameters();
         LumonTestDataFactory.setupPricingSummaryB2C();
         LumonTestDataFactory.setupConfigurationB2C();
         LumonTestDataFactory.setupConfigurationProductsB2C();
         LumonTestDataFactory.setupConfigurationOptionsB2C();       
         LumonTestDataFactory.setupConfigurationMessagesB2C(); 
         LumonTestDataFactory.setupSyncedQuoteB2C();
         LumonTestDataFactory.setupSyncedQuoteLineItemsB2C();
         LumonTestDataFactory.setupContractB2C();
         LumonTestDataFactory.setupOrderB2C();
         LumonTestDataFactory.setupContentFiles();
         
         String body = '{"status": "OK","statusCode":"200"}';
         MockResponseGenerator mockResp = new MockResponseGenerator(body, 200);
         Test.setMock(HttpCalloutMock.class, mockResp);
         Test.stopTest();
         System.debug('---  OrderGeneratorTest - setupOpptTestData CPU TIME: '+LIMITS.getCpuTime());      
     }  
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static Id b2cSyncedQuoteId = LumonTestDataFactory.b2cSyncedQuoteId;
    private static Id b2cContractId = LumonTestDataFactory.b2cContractId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
    private static String visualPricingJSON = LumonTestConfigurations.visualPricingJSON;
    private static String soveliaPricingJSON = LumonTestConfigurations.soveliaPricingJSON;
    private static String testPricingJSON = LumonTestConfigurations.testPricingJSON;
     @IsTest
     public static void populateOrderJSONTest() {
         //opp.Terrain_Type__c = 'Terrain Class 0';
         //update opp;
         OpportunityTeamMember oppTeamMember = new OpportunityTeamMember (
         										OpportunityId = b2cOpportunityId,
         										UserId = UserInfo.getUserId(),
         										TeamMemberRole = 'Installation Manager');
         insert oppTeamMember;
         /*Configuration__c config = [SELECT Id FROM Configuration__c WHERE Name ='Test Order Config 2' OR opportunity__c =:b2cOpportunityId LIMIT 1];
         Configuration_Product__c configProduct = [SELECT Id,RVN_Number__c FROM Configuration_Product__c WHERE RVN_Number__c ='22222-2' OR Configuration__c =:config.Id limit 1];*/
         
         
         Test.startTest();
         
         String body = '{"status": "OK","statusCode":"200"}';
         MockResponseGenerator mockResp = new MockResponseGenerator(body, 200);
         Test.setMock(HttpCalloutMock.class, mockResp); 
         /*Quote q = [SELECT id, GrandTotal, LineItemCount FROM Quote WHERE OpportunityId =:b2cOpportunityId]; 
         System.debug('--- Quote '+q);*/
         Contract c = [SELECT Id,Status,StartDate, CustomerSignedDate from Contract where ID = :b2cContractId];
         System.debug('--- Contract Before Signing '+c);
         //Activate Contract
         c.CustomerSignedDate = Date.today();
         c.Status = 'Activated'; 
         c.Signing_status__c  = 'Signed';
         update c;
         System.debug('--- Contract After Signing '+c);    
         Order o = [SELECT Id,Status FROM Order WHERE OpportunityId = : b2cOpportunityId LIMIT 1];
         System.debug('--- Order Before Activation '+o);
         System.debug('--- Order Status '+o.Status);
         o.Status = 'Activated';
         update o;
         System.debug('--- Order After Activation '+o);
         OrderGenerator.populateOrderJSONFromComponent(o.Id);
         Test.stopTest();
         
         
     }
 }