force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product Entry in product2 Table</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code OLD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Quantity of an Item per Unit of Measure</description>
    <inlineHelpText>The Quantity of an Item per Unit of Measure</inlineHelpText>
    <label>Quantity</label>
    <precision>14</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Autogenerated RVN for all Plan Types</description>
    <formula>Configuration_Product__r.RVN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <label>Sales Code OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <description>Product Item Cost Type</description>
    <inlineHelpText>Product Item Cost Type</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Item__c.field-meta.xml
<CustomField>
    <fullName>Product_Item__c</fullName>
    <inlineHelpText>Third Level Grouping of Products and Services</inlineHelpText>
    <label>Product Item OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Reference to the Product Model for this Item</description>
    <label>Product Model OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN__c.field-meta.xml
<CustomField>
    <fullName>RVN__c</fullName>
    <description>Formula Field to generate the RVN Number</description>
    <formula>Opportunity_Number__c + IF (Visual_Structure_Number__c != null, Visual_Structure_Number__c, ProductIdentifier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Generated RVN</inlineHelpText>
    <label>RVN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Code of the Product as using in External Systems</description>
    <formula>Product__r.Sales_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Code of the Product as using in External Systems</inlineHelpText>
    <label>Sales Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>F-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Flat Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing Beads</fullName>
    </customValue>
    <customValue>
        <fullName>h-Beads</fullName>
    </customValue>
    <customValue>
        <fullName>L-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Rectangular Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Telescopic Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>U-Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Upper Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Wall Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Screws</fullName>
    </customValue>
    <customValue>
        <fullName>Nuts</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 1</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 2</fullName>
    </customValue>
    <customValue>
        <fullName>Other Sales 3</fullName>
    </customValue>
    <customValue>
        <fullName>Special Colors</fullName>
    </customValue>
    <customValue>
        <fullName>Sand Blasting</fullName>
    </customValue>
    <customValue>
        <fullName>Special Orders</fullName>
    </customValue>
    <customValue>
        <fullName>Edge Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Items</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConfigurationOptionController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-01-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class ConfigurationOptionController {
    @AuraEnabled(cacheable=true)
    public static Configuration_Option__c getConfigurationOption(Id recordId){
    List<Id> recordIds = new List<Id>{recordId};
	List<Configuration_Option__c> configOptions = getConfigurationOptions(recordIds);
    Configuration_Option__c configOption =configOptions[0];
		return configOption;
    }
    @AuraEnabled(cacheable=true)
    public static List<Configuration_Option__c> getConfigurationOptions(List<Id> recordIds){
        List<Configuration_Option__c> configOptions = new List<Configuration_Option__c>();
        configOptions = [   SELECT Id,
                                    Name,
                                    Product_Group__c,
                                    Product_Model__c,
                                    Product_Code__c,
                                    Sales_Code__c,
                                    Quantity__c,
                                    Product__c,
                                    Product__r.Name,
                                    Product__r.Product_Group__c,
                                    Product__r.Cost_Category__c,
                                    Product__r.Cost_Type__c,
                                    Product__r.Product_Category__c, 
                                    Product__r.Product_Type__c, 
                                    Product__r.Product_Item__c, 
                                    Product__r.ProductCode, 
                                    Product__r.Sales_Code__c,
                                    Product__r.QuantityUnitOfMeasure,
                                    Product__r.Reclamation__c,
                                    Product__r.Installation__c,
                                    Product__r.IsActive,
                                    Configuration_Product__c,
                                    Configuration_Product__r.RVN__c,
                         			Configuration_Product__r.Configuration__c,
                                    Configuration_Product__r.Configuration__r.Opportunity__c                                          
                            FROM Configuration_Option__c 
                            WHERE Id IN: recordIds
                            OR Configuration_Product__c IN: recordIds
                            OR Configuration_Product__r.Configuration__c IN: recordIds
                            OR Configuration_Product__r.Configuration__r.Opportunity__c IN: recordIds];
        return configOptions;
    }  
}