force-app/main/default/objects/Opportunity/fields/Business_Type_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_Attribute__c</fullName>
    <description>Attribute to Identify the Type of Business</description>
    <formula>Text(Business_Type__c)</formula>
    <inlineHelpText>Attribute to Identify the Type of Business e.g. Consumer, Reseller, Project</inlineHelpText>
    <label>Business Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Account Billing Country)</description>
    <formula>TEXT( Account.BillingCountryCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Customer_Attribute__c</fullName>
    <formula>IF( NOT(ISNULL(Account.AccountNumber)), Account.AccountNumber,&quot;&quot;)</formula>
    <label>Customer Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Organization_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Organization_Attribute__c</fullName>
    <description>Level 1 Classification based on Organization</description>
    <formula>Owner.Organization_Attribute__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Level 1 Classification based on Organization</inlineHelpText>
    <label>Organization Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Territory_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Territory_Attribute__c</fullName>
    <description>Attribute to Identify the Sales Area (based on Account Territory)</description>
    <formula>Territory2.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Sales Area</inlineHelpText>
    <label>Territory Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Business_Type_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Business_Type_Attribute__c</fullName>
    <formula>TEXT(Business_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Type Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <formula>Text( Country_Code__c  )</formula>
    <label>Country Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Customer_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Customer_Attribute__c</fullName>
    <formula>IF( NOT(ISNULL(Customer__r.AccountNumber)), Customer__r.AccountNumber,&quot;&quot;)</formula>
    <label>Customer Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Prices Expire</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/IsPriceList__c.field-meta.xml
<CustomField>
    <fullName>IsPriceList__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPriceList</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Organization_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Organization_Attribute__c</fullName>
    <formula>TEXT(Organization__c )</formula>
    <label>Organization Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Prices are Valid</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Territory_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Territory_Attribute__c</fullName>
    <formula>TEXT(Territory__c )</formula>
    <label>Territory Attribute</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Minimum_Price__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Minimum Price of an Item, used for Special Prices for example Color
If Total Sales Price is less than minimum Price then use Minimum Price</description>
    <inlineHelpText>Minimum Price of an Item, used for Special Prices for example Color</inlineHelpText>
    <label>Minimum Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Quantity_per_Order__c.field-meta.xml
<CustomField>
    <fullName>Quantity_per_Order__c</fullName>
    <description>The Maximum Quantity of an Item on an Order</description>
    <inlineHelpText>The Maximum Quantity of an Item on an Order</inlineHelpText>
    <label>Quantity per Order OLD</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Transmission</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Costs</inlineHelpText>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Costs</inlineHelpText>
    <label>Cost Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Cost_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lumon_Cost_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to indicate if the Product  requires Installation Services</description>
    <inlineHelpText>indicates if the Product requires Installation Services</inlineHelpText>
    <label>Installation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Cost_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Costs</fullName>
        <label>Additional Costs</label>
    </customValue>
    <customValue>
        <fullName>AdditionalSales</fullName>
        <label>Additional Sales</label>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
        <label>Extra Sales</label>
    </customValue>
    <customValue>
        <fullName>BuildingPermits</fullName>
        <label>Building Permits</label>
    </customValue>
    <customValue>
        <fullName>Permits</fullName>
    </customValue>
    <customValue>
        <fullName>CostReserv</fullName>
        <label>Cost Reservations</label>
    </customValue>
    <customValue>
        <fullName>ExternalService</fullName>
        <label>External Services</label>
    </customValue>
    <customValue>
        <fullName>External</fullName>
    </customValue>
    <customValue>
        <fullName>Factory</fullName>
    </customValue>
    <customValue>
        <fullName>FactoryPurchase</fullName>
        <label>Factory Purchase</label>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Manhours</fullName>
        <label>Installation Manhours</label>
    </customValue>
    <customValue>
        <fullName>InstallSupplies</fullName>
        <label>Installation Supplies</label>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Quarantee</fullName>
        <label>Quarantee Cost Reservation</label>
    </customValue>
    <customValue>
        <fullName>RentedMachinery</fullName>
        <label>Rental Machinery</label>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>SalesFreight</fullName>
        <label>Sales Freight</label>
    </customValue>
    <customValue>
        <fullName>SalesService</fullName>
        <label>Sales Services</label>
    </customValue>
    <customValue>
        <fullName>TravelExpenses</fullName>
        <label>Travel Expenses</label>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Wages</fullName>
    </customValue>
    <customValue>
        <fullName>Freight</fullName>
    </customValue>
    <customValue>
        <fullName>Installation Time</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <masterLabel>Lumon Cost Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Reclamation</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PriceBookEntryController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-10-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class PriceBookEntryController {
    @AuraEnabled(cacheable=false)
    public static Pricebook2 getPricebookRecord(Id pricebookId) {
        // Populate map from SOQL query on Pricebook
        if(Test.isRunningTest()){
            //Invoke mock web service response
            pricebookId = Test.getStandardPricebookId();
        }
        System.debug('--- Get Data for Pricebook: '+pricebookId);
        Pricebook2 pricebookRecord = ([SELECT Id, Name,CurrencyIsoCode,
                                                Organization_Attribute__c,Country_Attribute__c,//Tier 1 Factory Prices
                                                Territory_Attribute__c,Business_Type_Attribute__c,//Tier 2 Product Costs
                                                Profit_Center__c, Customer_Attribute__c //Tier 3 Sales Prices  
                                    FROM Pricebook2 
                                    WHERE Id = :pricebookId]);
        System.debug('--- Pricebook Record: '+pricebookRecord);
        return pricebookRecord;
    } 
    @AuraEnabled(cacheable=false)
    public static Pricebook2 getPriceList(Date closureDate) {
        // Populate map from SOQL query on Pricebook
        System.debug('--- Get PriceList valid on Date : '+closureDate);
        Pricebook2 pricelistRecord = new Pricebook2();
        if(Test.isRunningTest()){
            //Invoke mock web service response
            Id pbid = Test.getStandardPricebookId();
            pricelistRecord.Id = pbId;
         } else{
            pricelistRecord = ([SELECT Id, Name,CurrencyIsoCode,
                                                    Organization_Attribute__c,Country_Attribute__c,//Tier 1 Factory Prices
                                                    Territory_Attribute__c,Business_Type_Attribute__c,//Tier 2 Product Costs
                                                    Profit_Center__c, Customer_Attribute__c //Tier 3 Sales Prices                                              
                                    FROM Pricebook2 
                                    WHERE Start_Date__c <:closureDate
                                    AND (End_Date__c >:closureDate
                                    OR End_Date__c = null)
                                    AND IsPriceList__c = true]);
            System.debug('--- PriceList Record: '+pricelistRecord);
         }
        return pricelistRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> getPricebookEntries(String pricebookId) {
        // Populate map from SOQL query on PricebookEntry
        List<PricebookEntry> pricebookEntries = ([SELECT  Id,
                                                            Name,
                                                            Pricebook2Id, 
                                                            Pricebook2.Name,
                                                            Product2Id,
                                                            Product2.Name,
                                                            Product2.QuantityUnitOfMeasure,
                                                            Product2.ProductCode,
                                                            Product2.Reclamation__c,
                                                            Product2.Installation__c,
                                                            Product2.Cost_Category__c,
                                                            Product2.Cost_Type__c,
                                                            Product2.Product_Category__c,
                                                            Product2.Product_Type__c,
                                                            Product2.Product_Item__c,
                                                            Product2.Product_Group__c,
                                                            Product2.Sales_Code__c,
                                                            Product2.IsActive,
                                                            UnitPrice, 
                                                            Minimum_Price__c,
                                                            Quantity_Per_Order__c, 
                                                            Transmission__c,
                                                            //StandardPrice,
                                                            UseStandardPrice,
                                                            IsActive,
                                                            CurrencyIsoCode  
                                                    FROM PricebookEntry 
                                                    WHERE Pricebook2Id = :pricebookId]);
        System.debug('--- Pricebook Entries: '+pricebookEntries);                                         
        return pricebookEntries;
    } 

    public static Map<String,PricebookEntry> getPricebookEntryMap(String pricebookId, String currencyCode) {
        return getPricebookEntryMap(pricebookId, currencyCode, null);
    }

    public static Map<String,PricebookEntry> getPricebookEntryMap(
        String pricebookId,
        String currencyCode,
        Opportunity opportunityRecord
    ) {
        // Populate List from SOQL query on PriceBookEntry
        Boolean reclamation = opportunityRecord?.Order_type__c == 'Reclamation';
        Boolean isActive = true;
        System.debug('--- Get Pricebook Entries in '+currencyCode+' for Pricebook '+pricebookId); 
        List<PricebookEntry> pricebookEntries = ([  SELECT  Id,
                                                            Name,
                                                            Pricebook2Id, 
                                                            Pricebook2.Name,
                                                            Product2Id,
                                                            Product2.Name,
                                                            Product2.QuantityUnitOfMeasure,
                                                            Product2.ProductCode,
                                                            Product2.Reclamation__c,
                                                            Product2.Installation__c,
                                                            Product2.Cost_Category__c,
                                                            Product2.Cost_Type__c,
                                                            Product2.Product_Category__c,
                                                            Product2.Product_Type__c,
                                                            Product2.Product_Item__c,
                                                            Product2.Product_Group__c,
                                                            Product2.Sales_Code__c,
                                                            Product2.IsActive,
                                                            UnitPrice, 
                                                            Minimum_Price__c,
                                                            Quantity_Per_Order__c, 
                                                            Transmission__c,
                                                            //StandardPrice,
                                                            UseStandardPrice,
                                                            IsActive,
                                                            CurrencyIsoCode                                    
                                                    FROM PricebookEntry 
                                                    WHERE Pricebook2Id = :pricebookId
                                                    AND IsActive =: isActive
                                                    AND CurrencyIsoCode =: currencyCode
                                                    AND Product2.Reclamation__c =: reclamation
                                                    ]);  
            System.debug('--- Active Pricebook Entries: '+pricebookEntries.size()); 
        
        Map<String,PricebookEntry> pbeMap  = New Map<String,PricebookEntry>();  
        if (pricebookEntries.size()>0)  {                                
            for (PricebookEntry pricebookProduct :pricebookEntries) {
                String productCode = pricebookProduct.Product2.ProductCode;
                String product2Id = pricebookProduct.Product2Id;
                pbeMap.put(productCode,pricebookProduct);
            }
        }  
        return pbeMap;  
    }  
    
    public static Map<String, PricebookEntry> getPricebookEntriesByProductCodes(
        String pricebookId,
        String currencyCode,
        Opportunity opportunityRecord,
        List<String> productCodes
    ) {
        Boolean reclamation = opportunityRecord?.Order_type__c == 'Reclamation';
        List<PricebookEntry> pricebookEntries = [
            SELECT
                Id,
                Name,
                Pricebook2Id,
                Pricebook2.Name,
                Product2Id,
                Product2.Name,
                Product2.QuantityUnitOfMeasure,
                Product2.ProductCode,
                Product2.Reclamation__c,
                Product2.Installation__c,
                Product2.Cost_Category__c,
                Product2.Cost_Type__c,
                Product2.Product_Category__c,
                Product2.Product_Type__c,
                Product2.Product_Item__c,
                Product2.Product_Group__c,
                Product2.Sales_Code__c,
                Product2.IsActive,
                UnitPrice,
                Minimum_Price__c,
                Quantity_Per_Order__c,
                Transmission__c,
                UseStandardPrice,
                IsActive,
                CurrencyIsoCode
            FROM PricebookEntry
            WHERE
                Pricebook2Id = :pricebookId
                AND IsActive = TRUE
                AND CurrencyIsoCode = :currencyCode
                AND Product2.Reclamation__c = :reclamation
                AND Product2.ProductCode IN :productCodes
        ];
        Map<String, PricebookEntry> pricebookEntriesByProductCode = new Map<String, PricebookEntry>();
        for (PricebookEntry pricebookProduct : pricebookEntries) {
            pricebookEntriesByProductCode.put(pricebookProduct.Product2.ProductCode, pricebookProduct);
        }
        return pricebookEntriesByProductCode;
    }

}