force-app/main/default/objects/Opportunity/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>25% Advance + 75% Financing</fullName>
            </value>
            <value>
                <fullName>50% Advance + 50% Financing</fullName>
            </value>
            <value>
                <fullName>Aftersales 100% Final invoice</fullName>
            </value>
            <value>
                <fullName>Consumer 50/50</fullName>
            </value>
            <value>
                <fullName>Consumer Financing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Batch__c/Payment_Batch__c.object-meta.xml
<CustomObject>
    <description>This is child object to payment plan</description>
    <label>Payment Batch</label>
    <nameField>
        <label>Payment Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Batch__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Payment_Plan__r.Opportunity__r.Amount  *  Amount_percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Batch__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Payment Batches</relationshipLabel>
    <relationshipName>Payment_Batches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Batch__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Final Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <description>Payment Plan object determine payment details of opportunity</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PricingPaymentInstallmentsController.cls
/**
 * @description       : NOT IN USE
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-09-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class PricingPaymentInstallmentsController {
    /*public with sharing class ComponentData {
        @AuraEnabled
        public Quote quote { get; private set; }
        @AuraEnabled
        public Opportunity opportunity { get; private set; }
        @AuraEnabled
        public List<Payment_Batch__c> items { get; private set; }
        public ComponentData(Id recordId) {
            opportunity = OpportunityController.getOpportunity(recordId);
            try {
                quote = QuoteController.getQuote(opportunity.SyncedQuoteId);
            } catch (Exception e) {
                throw new PricingSummaryService.PricingDataException('The synced quote can\'t be found');
            }
            items = [
                SELECT Amount__c, Description__c, Number__c, Type__c
                FROM Payment_Batch__c
                WHERE Payment_Plan__r.Opportunity__c = :opportunity.Id
            ];
        }
    }

    @AuraEnabled(cacheable=false)
    public static ComponentData getComponentData(Id recordId) {
        return new ComponentData(recordId);
    }*/
}