force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Project_Number__r.Project_Number__c</formula>
    <label>Project Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Project number for the order</description>
    <label>Project OLD</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Umbrella Object that existing for the complete &quot;life&quot; of an Installation
For New Installations as new Project is created
For Claims or AfterSales on Existing Installations an Existing Project is linked to Opportunity

The Project Number (8 digits) is used to uniquely Identify all Related Opportunities, Quotes and Orders</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <description>Project Number for the order</description>
    <displayFormat>{0000000}</displayFormat>
    <label>Project Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/ProjectControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-05-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
public with sharing class ProjectControllerTest {
    @TestSetup
    public static void prepareData(){
        Test.startTest();
        LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPrices();
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();
        Test.stopTest();
    }   
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    @IsTest
    static void getProjectByIdTest(){
        Id  projectId = [SELECT Id, Project_Number__c FROM Opportunity WHERE Id =: b2cOpportunityId LIMIT 1]?.Project_Number__c;
        Test.startTest();
        Project__c prj = ProjectController.getProjectById(projectId);
        System.Debug ('----'+ prj.Name +' Projects Returned');
        System.assertNotEquals(null,prj.name, 'Expected One or More Projects to be returned');
        System.debug('--- getProjectByIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getProjectByIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
    @IsTest
    static void getProjectsbyRelatedIdTest(){
        Id  projectId = [SELECT Id, Project_Number__c FROM Opportunity WHERE Id =: b2cOpportunityId LIMIT 1]?.Project_Number__c;
        List<Id> projectIds = New List<Id>();
        projectIds.add(projectId);
        Test.startTest();
        List<Project__c> prjs = ProjectController.getProjectsbyIds(projectIds);
        System.Debug ('----'+ prjs.size() +' Projects Returned');
        if (prjs.size()>0){
            System.Debug (prjs);
        }
        System.assertNotEquals(0,prjs.size(), 'Expected One or More Projects to be returned');
        System.debug('--- getProjectsbyRelatedIdTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- getProjectsbyRelatedIdTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();
    }
}