force-app/main/default/objects/Factory__c/Factory__c.object-meta.xml
<CustomObject>
    <label>Factory</label>
    <nameField>
        <label>Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory__c/fields/Default_Factory__c.field-meta.xml
<CustomField>
    <fullName>Default_Factory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Factory OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory_Address__c.field-meta.xml
<CustomField>
    <fullName>Factory_Address__c</fullName>
    <label>Factory Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory_code__c.field-meta.xml
<CustomField>
    <fullName>Factory_code__c</fullName>
    <description>Factory code required for integration</description>
    <label>Factory code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory_Location__c.field-meta.xml
<CustomField>
    <fullName>Factory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Factory</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Factories</relationshipLabel>
    <relationshipName>Factories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Hours OLD</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Factories</relationshipLabel>
    <relationshipName>Factories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FactoryController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-12-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class FactoryController {
    @AuraEnabled(cacheable=true)
    public static Factory__c getFactoryRecord(Id recordId) {
        // Populate map from SOQL query on Factory
        List<Id> recordIds = new List<Id>{recordId};
        List<Factory__c> factoryRecords = getFactories(recordIds);        
        Factory__c factoryRecord = factoryRecords[0];
        System.debug('--- Factory Record: '+factoryRecord);
        return factoryRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<Factory__c> getFactories(List<Id> recordIds) {
        List<Factory__c> factories = ([SELECT Id,
                                                Name, 
                                                Default_Factory__c,    
                                                Factory_code__c, 
                                                Operating_Hours__c,
                                                Factory_Address__Street__s, 
                                                Factory_Address__City__s, 
                                                Factory_Address__PostalCode__s, 
                                                Factory_Address__StateCode__s, 
                                                Factory_Address__CountryCode__s, 
                                                Factory_Address__Latitude__s, 
                                                Factory_Address__Longitude__s, 
                                                Factory_Address__GeocodeAccuracy__s, 
                                                Factory_Address__c, 
                                                Factory_Location__c                              
                                    FROM Factory__c 
                                    WHERE Id IN :recordIds
                                    ]);
        System.debug('--- Factory Record Count : '+factories.size());
        return factories;
    } 
}