force-app/main/default/objects/Factory__c/Factory__c.object-meta.xml
<CustomObject>
    <label>Factory</label>
    <nameField>
        <label>Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Production_Time__c/Production_Time__c.object-meta.xml
<CustomObject>
    <description>Holds a reference to the estimated/expected Times to produce a Finished Good</description>
    <label>Production Time</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Production Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Time__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <inlineHelpText>Estimated/Expected Time to Finish Production in calendar Days</inlineHelpText>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Extra_Days__c.field-meta.xml
<CustomField>
    <fullName>Extra_Days__c</fullName>
    <label>Extra Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>Factory</label>
    <referenceTo>Factory__c</referenceTo>
    <relationshipLabel>Production Times</relationshipLabel>
    <relationshipName>Production_Times</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Production Times</relationshipLabel>
    <relationshipName>Production_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT(Product__r.Product_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LumonTestProductionTimes.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-10-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class LumonTestProductionTimes {
    public static void setupProductionTimes(){
        List<Id> productIds = LumonTestVariables.productIds;
        setupProductionTimes(productIds);
    }
    public static void setupProductionTimes(list<Id> productIds) {
        List<Production_Time__c> pts = new List<Production_Time__c>();
        Factory__c factory = new Factory__c(Name = 'Test Factory');
        insert factory;     
        List<Product2> products = LumonTestVariables.products;  
        for (Product2 p : products) {
            if (p.QuantityUnitOfMeasure != 'h'){
                Production_Time__c pt = new Production_Time__c();
                if (p.ProductCode == p.Product_Group__c) {
                    pt.Days__c=22;
                    pt.Extra_Days__c=0;
                    System.debug('--- LumonTestProductionTimes - Production Days for '+p.Name);
                } else if (p.productCode == p.Product_Group__c+'-SPECIAL') {
                    pt.Days__c=0;
                    pt.Extra_Days__c=3;
                    System.debug('--- LumonTestProductionTimes - Extra Production Days for '+p.Name);
                } else {
                    //System.debug('--- No Production Days for '+p.Name);
                    continue;
                }
                pt.Factory__c =factory.Id;
                pt.Product__c=p.Id;
                pt.IsActive__c=true;
                pts.add(pt);
            }
        }
        insert pts;
    }
    public static void setupProductionTimeData(){
        List<Product2> products = LumonTestVariables.products;  
        if(products?.size()>0){
            System.debug('--- LumonTestProductionTime - Using existing Products');
        } else {
            LumonTestProducts.setupProductData();
        }
        setupProductionTimes();
        List<Production_Time__c> productionTimes = LumonTestVariables.productionTimes;
        System.debug('--- LumonTestProductionTimes - productionTimes '+products.size()+' Production Times'); 
    }  
    @TestSetup
    static void prepareData() {
        List<Product2> products = LumonTestVariables.products;
        List<PricebookEntry> pricebookEntries = LumonTestVariables.pricebookEntries;
        Test.startTest();
        if(products?.size()>0){
            System.debug('--- LumonTestProductionTime - Using existing Products');
        } else {
            LumonTestProducts.setupProductData();
        }
        if(pricebookEntries?.size()>0){
            System.debug('--- LumonTestProductionTime - Using existing pricebookEntries');
        } else {
            LumonTestPricebooks.setupPricebookData();
        }
        Test.stopTest();
    }
    @Istest
    public static void setupProductionTimeDataTest(){
        String testResult;
        Test.startTest();
        try {
            setupProductionTimeData();
            List<Production_Time__c> productionTimes = LumonTestVariables.productionTimes;
            testResult = ('Inserted '+productionTimes.size()+' Test Production Times');
            System.assertNotEquals(0,productionTimes.size(), 'Expected Production Times to be Created');
        } catch (exception e){
            testResult = ('Error when inserting Production Times: '+e.getMessage());
        }
        Test.stopTest();
        System.debug('LumonTestProductionTime - result: '+testResult);
        System.AssertNotEquals(true, testResult.contains('error'));
    }
}