force-app/main/default/objects/Factory__c/Factory__c.object-meta.xml
<CustomObject>
    <label>Factory</label>
    <nameField>
        <label>Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <inlineHelpText>First Level Grouping of Products and Services</inlineHelpText>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Grouping of Items into Main Products
=&gt; API names required by Integrations</description>
    <inlineHelpText>Grouping of Items into Main Products</inlineHelpText>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <description>Field to Indicate the (sub)group of Product the Item belongs to
For example PELTI used for LGR =&gt; Product Group = LGR and Product Model = PELTI</description>
    <inlineHelpText>Field to Indicate the (sub)group of Product the Item belongs to</inlineHelpText>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <inlineHelpText>Second Level Grouping of Products and Services</inlineHelpText>
    <label>Product Type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Indicate if the Product is applicable for Reclamation
Used to find the reclamation code for Main Products</description>
    <inlineHelpText>Indicates if the Product is applicable for Reclamation</inlineHelpText>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Code__c</fullName>
    <description>Product Id as used by External Systems</description>
    <externalId>true</externalId>
    <label>Sales Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/Production_Time__c.object-meta.xml
<CustomObject>
    <description>Holds a reference to the estimated/expected Times to produce a Finished Good</description>
    <label>Production Time</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Production Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Time__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Business_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <inlineHelpText>Estimated/Expected Time to Finish Production in calendar Days</inlineHelpText>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Extra_Days__c.field-meta.xml
<CustomField>
    <fullName>Extra_Days__c</fullName>
    <label>Extra Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>Factory</label>
    <referenceTo>Factory__c</referenceTo>
    <relationshipLabel>Production Times</relationshipLabel>
    <relationshipName>Production_Times</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Production Times</relationshipLabel>
    <relationshipName>Production_Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <formula>TEXT(Product__r.Product_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Product_Model__c.field-meta.xml
<CustomField>
    <fullName>Product_Model__c</fullName>
    <label>Product Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Product_Models</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Production_Time__c/fields/Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Business_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>Project</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <masterLabel>Lumon Business Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Extra Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Items</fullName>
    </customValue>
    <customValue>
        <fullName>Product Models</fullName>
    </customValue>
    <customValue>
        <fullName>Product Options</fullName>
    </customValue>
    <customValue>
        <fullName>Products</fullName>
    </customValue>
    <customValue>
        <fullName>Product Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Samples</fullName>
    </customValue>
    <customValue>
        <fullName>Scale Models</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Costs</fullName>
    </customValue>
    <customValue>
        <fullName>Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Test Products</fullName>
    </customValue>
    <customValue>
        <fullName>Unclassified</fullName>
    </customValue>
    <customValue>
        <fullName>Product Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Service Costs</fullName>
        <isActive>false</isActive>
        <label>Service Costs</label>
    </customValue>
    <customValue>
        <fullName>Product Features</fullName>
        <isActive>false</isActive>
        <label>Product Features</label>
    </customValue>
    <customValue>
        <fullName>Product Components</fullName>
        <isActive>false</isActive>
        <label>Product Components</label>
    </customValue>
    <masterLabel>Lumon Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lumon_Product_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Posts</fullName>
    </customValue>
    <customValue>
        <fullName>Anchors</fullName>
    </customValue>
    <customValue>
        <fullName>Balcony Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Balustrades</fullName>
    </customValue>
    <customValue>
        <fullName>Bars</fullName>
    </customValue>
    <customValue>
        <fullName>Beads</fullName>
    </customValue>
    <customValue>
        <fullName>Beams</fullName>
    </customValue>
    <customValue>
        <fullName>Blind Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Blinds</fullName>
    </customValue>
    <customValue>
        <fullName>Bottom Seals</fullName>
    </customValue>
    <customValue>
        <fullName>Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Clips</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 2</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 3</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 4</fullName>
    </customValue>
    <customValue>
        <fullName>Color Group 5</fullName>
    </customValue>
    <customValue>
        <fullName>Continuous Brackets</fullName>
    </customValue>
    <customValue>
        <fullName>Corner Frames</fullName>
    </customValue>
    <customValue>
        <fullName>Cost Reservations</fullName>
    </customValue>
    <customValue>
        <fullName>Cover Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Covers</fullName>
    </customValue>
    <customValue>
        <fullName>Decor Profiles</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Dividing Screens</fullName>
    </customValue>
    <customValue>
        <fullName>Doors</fullName>
    </customValue>
    <customValue>
        <fullName>Drain Pipes</fullName>
    </customValue>
    <customValue>
        <fullName>End Gap Profiles</fullName>
    </customValue>
    <masterLabel>Lumon Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductionTimeController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-03-2023
 * @last modified by  : Henk Reynders
**/
public with sharing class ProductionTimeController {
    @AuraEnabled(cacheable=true)
    public static List<Production_Time__c> getProductionTimes(Boolean isActive) {
        // Populate map from SOQL query on Production Time
        List<Production_Time__c> productionTimes = ([SELECT Id,
                                                            Name,
                                                            Factory__c,
                                                            Product__c,
                                                            Product__r.Name,
                                                            Product__r.ProductCode,
                                                            Product__r.Sales_Code__c,
                                                            Product__r.Product_Group__c,
                                                            Product__r.Product_Model__c,
                                                            Product__r.Product_Category__c,
                                                            Product__r.Product_Type__c,
                                                            Product__r.Product_Item__c,
                                                            Product__r.IsActive,
                                                            Days__c, 
                                                            Extra_Days__c,
                                                            Business_Type__c, 
                                                            Reference__c, 
                                                            Reclamation__c, 
                                                            Order_Type__c, 
                                                            IsActive__c
                                                    FROM Production_Time__c
                                                    WHERE IsActive__c =: isActive]);
        System.debug('--- Production Times: '+productionTimes);                                         
        return productionTimes;
    } 
    @AuraEnabled(cacheable=false)
    public static Map<String,Production_Time__c> getProductionTimeMap(Boolean isActive) {
        // Populate List from SOQL query on Production Time
        System.debug('--- Get Production Times'); 
        List<Production_Time__c> productionTimes = getProductionTimes(isActive);
        System.debug('--- Returned Production Times: '+productionTimes.size()); 
        Map<String,Production_Time__c> productionTimeMap  = New Map<String,Production_Time__c>();  
        if (productionTimes.size()>0)  {                                
            for (Production_Time__c productionTime :productionTimes) {
                String productCode = productionTime.Product__r.ProductCode;
                String product2Id = productionTime.Product__c;
                productionTimeMap.put(productCode,productionTime);
            }
        }  
        return productionTimeMap;  
    }  
}