force-app/main/default/objects/ProcessStepEvent__e/ProcessStepEvent__e.object-meta.xml
<CustomObject>
    <label>Process Step</label>
    <pluralLabel>Process Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProcessStepEvent__e/fields/documentId__c.field-meta.xml
<CustomField>
    <fullName>documentId__c</fullName>
    <description>The Id of the file that contains the XML or JSON to Process</description>
    <label>Document Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/JsonString__c.field-meta.xml
<CustomField>
    <fullName>JsonString__c</fullName>
    <description>The JSON relevant to the Process Step</description>
    <label>JSON String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <description>The Type of Object of the Record from where the Event is Triggered</description>
    <label>Object Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/ProcessActivity__c.field-meta.xml
<CustomField>
    <fullName>ProcessActivity__c</fullName>
    <description>The Process related Activity to Initiate</description>
    <label>Process Activity</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/ProcessStage__c.field-meta.xml
<CustomField>
    <fullName>ProcessStage__c</fullName>
    <description>The Stage of the Process</description>
    <label>Process Stage</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>The Id of the Record from where the Event is Triggered</description>
    <label>recordId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessEvent.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-26-2024
 * @last modified by  : Henk Reynders
**/
public class ProcessEvent {
    @AuraEnabled
    public static void publishProcessEvent(String stage, String activity,
                                            String recordId, String objectType,
                                            String jsonString, String documentId){
        List<ProcessStepEvent__e> processEvents = new List<ProcessStepEvent__e>();    
        ProcessStepEvent__e  stepEvt  = new ProcessStepEvent__e ( 
                                                        ProcessStage__c = stage, 
                                                        ProcessActivity__c = activity, 
                                                        recordId__c = recordId,//Parent Record Id 
                                                        objectType__c = objectType,
                                                        JsonString__c = jsonString,
                                                        documentId__c = documentId);
        System.Debug('--- ProcessEvent - Stage '+stage);
        System.Debug('--- ProcessEvent - Activity '+activity);                                  
        System.Debug('--- ProcessEvent - Record: '+recordId);     
        System.Debug('--- ProcessEvent - Object: '+objectType);                                              
        processEvents.add(stepEvt);
        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(processEvents);
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('--- ProcessStep - Successfully published Process Event');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('--- ProcessStep - Failed to publish Process Event with Error: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }       
        }
    }
}