force-app/main/default/objects/ProcessStepEvent__e/ProcessStepEvent__e.object-meta.xml
<CustomObject>
    <label>Process Step</label>
    <pluralLabel>Process Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProcessStepEvent__e/fields/documentId__c.field-meta.xml
<CustomField>
    <fullName>documentId__c</fullName>
    <description>The Id of the file that contains the XML or JSON to Process</description>
    <label>Document Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/JsonString__c.field-meta.xml
<CustomField>
    <fullName>JsonString__c</fullName>
    <description>The JSON relevant to the Process Step</description>
    <label>JSON String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <description>The Type of Object of the Record from where the Event is Triggered</description>
    <label>Object Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/ProcessActivity__c.field-meta.xml
<CustomField>
    <fullName>ProcessActivity__c</fullName>
    <description>The Process related Activity to Initiate</description>
    <label>Process Activity</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/ProcessStage__c.field-meta.xml
<CustomField>
    <fullName>ProcessStage__c</fullName>
    <description>The Stage of the Process</description>
    <label>Process Stage</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessStepEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>The Id of the Record from where the Event is Triggered</description>
    <label>recordId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessStepTriggerHandler.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 07-06-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class ProcessStepTriggerHandler {
    public static void initiateProcessStep(List<ProcessStepEvent__e> processSteps) {
        for (ProcessStepEvent__e step : processSteps) {      
            System.debug('--- ProcessController - executeProcessStep: ' + step);
            String processStage = step.ProcessStage__c;
            String processActivity = step.ProcessActivity__c;
            String recordId = step.recordId__c;
            String objectType = step.ObjectType__c;
            String jsonString = step.JsonString__c;
            String documentId = step.documentId__c;
            /*ProcessController.executeProcessStep( configType, configAction,
                                               recordId,objectType,
                                               jsonString, JsonData);*/
        }
    }
}