force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Building_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Address__c</fullName>
    <label>Building Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Building_Height__c.field-meta.xml
<CustomField>
    <fullName>Building_Height__c</fullName>
    <inlineHelpText>Indication of the Building Highest Level (mm)</inlineHelpText>
    <label>Building Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Building_Location__c.field-meta.xml
<CustomField>
    <fullName>Building_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Building</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Number_of_Floors__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Floors__c</fullName>
    <label>Number of Floors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/On_Hill_or_Slope__c.field-meta.xml
<CustomField>
    <fullName>On_Hill_or_Slope__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indication whether Building is on a Hill or Slope</inlineHelpText>
    <label>On Hill or Slope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Owned_By__c.field-meta.xml
<CustomField>
    <fullName>Owned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Structural_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Structural_Analysis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Structural Analysis</label>
    <referenceTo>Structural_Analysis__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/Structural_Analysis__c.object-meta.xml
<CustomObject>
    <label>Structural Analysis</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Structural Analysis Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Structural Analyses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Structural_Analysis__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <description>Building where these Structural Analysis is applicable</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Structural Analyses</relationshipLabel>
    <relationshipName>Structural_Analyses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Building_Height__c.field-meta.xml
<CustomField>
    <fullName>Building_Height__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Building height in respective unit of measure</description>
    <label>Building Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BuildingController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class BuildingController {
    @AuraEnabled(cacheable=true)
    public static Building__c getBuildingRecord(Id recordId) {
        // Populate map from SOQL query on Building
        List<Id> recordIds = new List<Id>{recordId};
        List<Building__c> buildingRecords = getBuildings(recordIds);        
        Building__c buildingRecord = buildingRecords[0];
        System.debug('--- BuildingController - Building Record: '+buildingRecord);
        return buildingRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<Building__c> getBuildings(List<Id> recordIds) {
        List<Building__c> buildings = ([SELECT Id,
                                                Name, 
                                                Building_Address__Street__s, 
                                                Building_Address__City__s, 
                                                Building_Address__PostalCode__s, 
                                                Building_Address__StateCode__s, 
                                                Building_Address__CountryCode__s, 
                                                Building_Address__Latitude__s, 
                                                Building_Address__Longitude__s, 
                                                Building_Address__GeocodeAccuracy__s, 
                                                Building_Address__c, 
                                                Building_Height__c,
                                                Building_Location__c, 
                                                Number_of_Floors__c, 
                                                On_Hill_or_Slope__c, 
                                                Owned_By__c, 
                                                Property_Type__c, 
                                                Structural_Analysis__c                              
                                    FROM Building__c 
                                    WHERE Id IN :recordIds
                                    OR Owned_By__c IN: recordIds
                                    OR Structural_Analysis__c IN: recordIds
                                    ]);
        System.debug('--- BuildingController - '+buildings.size()+' Buildings Created.');
        return buildings;
    } 
}