force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Building_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Address__c</fullName>
    <label>Building Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/BuildingHeight__c.field-meta.xml
<CustomField>
    <fullName>BuildingHeight__c</fullName>
    <inlineHelpText>Indication of the Building Highest Level (mm)</inlineHelpText>
    <label>Building Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/BuildingLocation__c.field-meta.xml
<CustomField>
    <fullName>BuildingLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Building</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/NumberOfFloors__c.field-meta.xml
<CustomField>
    <fullName>NumberOfFloors__c</fullName>
    <label>Number of Floors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/OwnedBy__c.field-meta.xml
<CustomField>
    <fullName>OwnedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account that Owns the Building</description>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/PropertyType__c.field-meta.xml
<CustomField>
    <fullName>PropertyType__c</fullName>
    <description>The Type of Property</description>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/StructuralAnalysis__c.field-meta.xml
<CustomField>
    <fullName>StructuralAnalysis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Structural Analysis</label>
    <referenceTo>Structural_Analysis__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factory__c/Factory__c.object-meta.xml
<CustomObject>
    <label>Factory</label>
    <nameField>
        <label>Factory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory__c/fields/Default_Factory__c.field-meta.xml
<CustomField>
    <fullName>Default_Factory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Factory OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory_Address__c.field-meta.xml
<CustomField>
    <fullName>Factory_Address__c</fullName>
    <label>Factory Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory_code__c.field-meta.xml
<CustomField>
    <fullName>Factory_code__c</fullName>
    <description>Factory code required for integration</description>
    <label>Factory code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory_Location__c.field-meta.xml
<CustomField>
    <fullName>Factory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Factory</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Factories</relationshipLabel>
    <relationshipName>Factories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Operating_Hours__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operating Hours OLD</label>
    <referenceTo>OperatingHours</referenceTo>
    <relationshipLabel>Factories</relationshipLabel>
    <relationshipName>Factories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/OwnedBy__c.field-meta.xml
<CustomField>
    <fullName>OwnedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which Company Owns the Warehouse</description>
    <inlineHelpText>Indicates which Company Owns the Warehouse</inlineHelpText>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>LumonWarehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/WarehouseCode__c.field-meta.xml
<CustomField>
    <fullName>WarehouseCode__c</fullName>
    <description>Location Code (Unique Id for ERP)</description>
    <externalId>true</externalId>
    <inlineHelpText>Location Code (Unique Id for ERP)</inlineHelpText>
    <label>Warehouse Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/WarehouseId__c.field-meta.xml
<CustomField>
    <fullName>WarehouseId__c</fullName>
    <description>Short Name (Unique Id)</description>
    <externalId>true</externalId>
    <inlineHelpText>Short Name (Unique Id)</inlineHelpText>
    <label>Warehouse Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LumonTestLocations.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-14-2024
 * @last modified by  : Henk Reynders
**/
@isTest
public class LumonTestLocations{
    public static void setupFactories(){
        List<Factory__c> factories = new List<Factory__c>();
        Factory__c factory = new Factory__c();
        factory.Name = 'Finland Factory';
        factory.Default_Factory__c = true;       		  
        factory.Factory_code__c = 'LU';       
        factory.Factory_Address__Street__s ='Korjalankatu 28'; 
        factory.Factory_Address__City__s = 'Kouvola'; 
        factory.Factory_Address__PostalCode__s = '45130';
        //factory.Factory_Address__StateCode__s; 
        factory.Factory_Address__CountryCode__s = 'FI'; 
        //factory.Factory_Address__Latitude__s; 
        //factory.Factory_Address__Longitude__s;
        //factory.Factory_Address__GeocodeAccuracy__s; 
        //factory.Factory_Address__c, 
        //factory.Operating_Hours__c
        //factory.Factory_Location__c  
        factories.add(factory);
        insert factories;
    }
    public static void setupWarehouses(){
        List<Warehouse__c> warehouses = new List<Warehouse__c>();
        Warehouse__c warehouse = new Warehouse__c();
        warehouse.Name = 'Finland Warehouse';
        warehouse.Organization__c = 'LSU';   
        warehouse.warehouseId__c = '2195';    		  
        warehouse.WarehouseCode__c = 'MC';      
        warehouse.Warehouse_Address__Street__s ='Kaitilankatu 11'; 
        warehouse.Warehouse_Address__City__s = 'Kouvola'; 
        warehouse.Warehouse_Address__PostalCode__s = '45130';
        //warehouse.Warehouse_Address__StateCode__s; 
        warehouse.Warehouse_Address__CountryCode__s = 'FI'; 
        warehouses.add(warehouse);
        insert warehouses;
    }
    public static void setupBuildings(){
        List<Building__c> buildings = new List<Building__c>();
        Building__c building = new Building__c(); 
        building.Name = 'Apartment Building';
        /*building.BuildingAddress__Street__s = 'Asematie 1'; 
        building.BuildingAddress__City__s = 'Vantaa';
        building.BuildingAddress__PostalCode__s = '01300'; 
        //building.BuildingAddress__StateCode__s;
        building.BuildingAddress__CountryCode__s = 'FI';
        //building.BuildingAddress__Latitude__s, 
        //building.BuildingAddress__Longitude__s, 
        //building.BuildingAddress__GeocodeAccuracy__s, 
        //Building_Address__c, 
        building.BuildingHeight__c = 10000;
        //building.BuildingLocation__c;
        building.NumberOfFloors__c = 3;
        //building.OwnedBy__c = b2cAccountId;
        building.PropertyType__c = 'APA';
        //building.StructuralAnalysis__c;*/
        buildings.add(building);
        insert buildings;
    }
    public static void setupLocationData(){ 
        setupFactories();
        setupWarehouses();
        setupBuildings();
    }  
    @IsTest
    static void setupLocationDataTest(){
        String testResult;
        Test.startTest();
        try {
            setupLocationData();
            testResult = 'successfully inserted Locations';
        } catch (exception e){
            testResult = 'Error when inserting Locations: '+e.getMessage();
        }
        System.debug('--- LumonTestLocations - CPU TIME: '+LIMITS.getCpuTime());
        System.debug('--- LumonTestLocations - Queries used: '+LIMITS.getQueries());
        Test.stopTest();       
        System.AssertNotEquals(true, testResult.contains('Error'));
        List<Id> warehouseIds = LumonTestVariables.warehouseIds;
        System.AssertNotEquals(null, warehouseIds, ' Expected Warehouse(s) to be Inserted');
        List<Id> factoryIds = LumonTestVariables.factoryIds;
        System.AssertNotEquals(null, factoryIds, ' Expected Factories to be Inserted');
        List<Id> buildingIds = LumonTestVariables.buildingIds;
        System.AssertNotEquals(null, buildingIds, ' Expected Buildings to be Inserted');
    }

}