force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Building_Height__c.field-meta.xml
<CustomField>
    <fullName>Building_Height__c</fullName>
    <inlineHelpText>Indication of the Building Highest Level (mm)</inlineHelpText>
    <label>Building Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Structural_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Structural_Analysis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Structural Analysis</label>
    <referenceTo>Structural_Analysis__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Terrain_Type__c.field-meta.xml
<CustomField>
    <fullName>Terrain_Type__c</fullName>
    <label>Terrain Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Terrain_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Wind_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Wind_Pressure__c</fullName>
    <inlineHelpText>Wind pressure (kN/m2)</inlineHelpText>
    <label>Wind Pressure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <inlineHelpText>Reference Wind speed (m/s)</inlineHelpText>
    <label>Wind Speed DEL</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows related opportunity</description>
    <inlineHelpText>Please associate case to an opportunity if known</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Shows the Oportunity Number related to the Configuration Plan</description>
    <formula>Opportunity__r.Opportunity_Number__c</formula>
    <inlineHelpText>The Oportunity Number related to the Configuration Plan</inlineHelpText>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Order number for integration from Opportunity</description>
    <formula>Opportunity__r.Opportunity_Number__c</formula>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <formula>TEXT(Opportunity__r.Order_type__c)</formula>
    <label>Order type OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Building_Height__c.field-meta.xml
<CustomField>
    <fullName>Building_Height__c</fullName>
    <description>Later: possibly later consider moving to building</description>
    <inlineHelpText>Indication of the Building Highest Level (mm)</inlineHelpText>
    <label>Building Height DEL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed__c</fullName>
    <description>This field is checked when associated final contract is signed</description>
    <formula>ISPICKVAL(Contract.Status, &quot;Signed&quot;) || ISPICKVAL(Contract.Status,&quot;Activated&quot;) &amp;&amp;  ISPICKVAL(Contract.Contract_type__c, &quot;Final Contract&quot;)</formula>
    <label>Contract Signed OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <description>Attribute to Identify the Country Specific Defaults and Sales Area (based on Account Billing Country)</description>
    <formula>TEXT( Account.BillingCountryCode )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Attribute to Identify the Country Specific Defaults and Sales Area</inlineHelpText>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/On_a_Hill_or_Slope__c.field-meta.xml
<CustomField>
    <fullName>On_a_Hill_or_Slope__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indication whether the Building is Located on a Hill or Slope</inlineHelpText>
    <label>On a Hill or Slope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Auto number to have a unique 8 digit number that links Sales Objects. Used as sales reference</description>
    <displayFormat>{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number OLD</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_type__c.field-meta.xml
<CustomField>
    <fullName>Order_type__c</fullName>
    <description>Claim or normal order</description>
    <inlineHelpText>Select if the order is a reclamation or a normal order</inlineHelpText>
    <label>Order type OLD</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Claim</fullName>
            </value>
            <value>
                <fullName>Reclamation</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Snowload__c.field-meta.xml
<CustomField>
    <fullName>Snowload__c</fullName>
    <inlineHelpText>Indication of the Snowload at the Building Location</inlineHelpText>
    <label>Snowload</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Structural_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Structural_Analysis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Structural Analysis OLD</label>
    <referenceTo>Structural_Analysis__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terrain_Type__c.field-meta.xml
<CustomField>
    <fullName>Terrain_Type__c</fullName>
    <inlineHelpText>Classification of the Terrain Type
0 - Sea, coastal exposed to the open sea
I - Lakes or area with negligible vegetation
II - Area with low vegetation such as grass and isolated obstacles (trees, buildings) with separations of at least 20 obstacle heights
III - Area with regular cover of vegetation or buildings or with isolated obstacles with separations of maximum 20 obstacle heights (such as villages, suburban terrain, forest)
IV - Area in which at least 15 % of surface is cove</inlineHelpText>
    <label>Terrain Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Terrain_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wind_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Wind_Pressure__c</fullName>
    <description>Wind pressure value set as default country parameter</description>
    <label>Wind Pressure DEL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <inlineHelpText>Indication of the Windspeed at the Building Location</inlineHelpText>
    <label>Wind Speed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/Structural_Analysis__c.object-meta.xml
<CustomObject>
    <label>Structural Analysis</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Structural Analysis Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Structural Analyses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Structural_Analysis__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <description>Building where these Structural Analysis is applicable</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Structural Analyses</relationshipLabel>
    <relationshipName>Structural_Analyses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Building_Height__c.field-meta.xml
<CustomField>
    <fullName>Building_Height__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Building height in respective unit of measure</description>
    <label>Building Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/On_a_Hill_or_Slope__c.field-meta.xml
<CustomField>
    <fullName>On_a_Hill_or_Slope__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate whether the default location is a hill or slope</description>
    <label>On a Hill or Slope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Snowload__c.field-meta.xml
<CustomField>
    <fullName>Snowload__c</fullName>
    <description>Snowload Structural Analysis Default</description>
    <label>Snowload</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Terrain_Type__c.field-meta.xml
<CustomField>
    <fullName>Terrain_Type__c</fullName>
    <inlineHelpText>Classification of the Terrain Type
0 - Sea, coastal exposed to the open sea
I - Lakes or area with negligible vegetation
II - Area with low vegetation such as grass and isolated obstacles (trees, buildings) with separations of at least 20 obstacle heights
III - Area with regular cover of vegetation or buildings or with isolated obstacles with separations of maximum 20 obstacle heights (such as villages, suburban terrain, forest)
IV - Area in which at least 15 % of surface is cove</inlineHelpText>
    <label>Terrain Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Terrain_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Wind_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Wind_Pressure__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Wind pressure value set as default country parameter</description>
    <label>Wind Pressure</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Country_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Attribute__c</fullName>
    <formula>Country</formula>
    <label>Country Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Country_Code_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_Attribute__c</fullName>
    <formula>TEXT(CountryCode)</formula>
    <label>Country Code Attribute OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Terrain_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Terrain Class 0</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class I</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class II</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class III</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class IV</fullName>
    </customValue>
    <customValue>
        <fullName>Terrain Class V</fullName>
        <isActive>false</isActive>
        <label>Terrain Class V</label>
    </customValue>
    <masterLabel>Lumon Terrain Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VisualContainerController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 03-22-2024
 * @last modified by  : Henk Reynders
**/
public class VisualContainerController {
	@AuraEnabled
	public static Boolean checkContractStatus(String recordId) {
		return [SELECT Contract_Signed__c FROM Opportunity WHERE Id =: recordId]?.Contract_Signed__c;
	}

	@AuraEnabled
	public static Boolean checkContractStatusFromConfiguration(String recordId) {
		Id oppId = [SELECT Opportunity__c FROM Configuration__c WHERE Id =: recordId]?.Opportunity__c;
		if (oppId != null) {
			return false;//[SELECT Contract_Signed__c FROM Opportunity WHERE Id =: oppId].Contract_Signed__c;
		} else {
			return false;
		}
	}

	@AuraEnabled
	public static String getStartupParams(String recordId) {
		return getStartupParamsFromOpportunity(recordId, '');
	}

	public static String getStartupParamsFromOpportunity(String recordId, String orderType) {
		User user = [SELECT Name,Profile.Name, Country_Attribute__c,Country_Code_Attribute__c,LanguageLocaleKey FROM User WHERE Id =: UserInfo.getUserId()];
		System.debug('--- user: '+user);
		Opportunity opp = [SELECT  	Opportunity_Number__c,
							Owner.LanguageLocaleKey,
							StageName, 
							Country_Attribute__c,
							Order_type__c, 
							Building__r.Structural_Analysis__r.Wind_Pressure__c, 
							Building__r.Structural_Analysis__r.Wind_Speed__c, 
							Building__r.Structural_Analysis__r.Terrain_Type__c, 
							Building__r.Structural_Analysis__r.On_a_Hill_or_Slope__c, 								
							Building__r.Structural_Analysis__r.Snowload__c,
							Building__r.Structural_Analysis__r.Building_Height__c, 
							Building__r.Structural_Analysis__r.Seals_between_panes__c, 
							Building__r.Structural_Analysis__r.Drainage_holes__c, 
							Building__r.Structural_Analysis__r.Combined_load__c
					FROM Opportunity WHERE Id =: recordId];
		VisualWrapper wrapper = new VisualWrapper();
		VisualDef visual = new VisualDef();
		BaseInfo baseInfo = new BaseInfo();
		baseInfo.configId = '';
		baseInfo.baseConfigId = '';
        //System.Debug('--- VisualContainerController - User language key: '+user.LanguageLocaleKey);
        String userLocale = user.LanguageLocaleKey;
		baseInfo.lan = userLocale.length()> 2? userLocale : userLocale.toLowerCase()+'-'+userLocale.toUpperCase();
		baseInfo.lumonPlanName = '';
		baseInfo.lumonPlanLine = '';
		baseInfo.lumonPlanFloor = '';
		baseInfo.lumonPlanApartment = '';

		if(String.isBlank(orderType)) {
			if (opp.Order_type__c == 'Normal') {
				orderType = 'default';
			} else if (opp.Order_type__c == 'Reclamation') {
				orderType = 'reclamation';
			}
		}
		String terrainClass = opp.Building__r.Structural_Analysis__r.Terrain_Type__c;
		Integer terrainValue = new Map<String, Integer> {
            'Terrain Class 0' => 0,
            'Terrain Class I' => 1,
            'Terrain Class II' => 2,
            'Terrain Class III' => 3,
            'Terrain Class IV' => 4,
            'Terrain Class V' => 5
		}.get(terrainClass);
		baseInfo.initMode = orderType;
		List<String> statusesToLockPlan = new List<String>{'Contract Signed', 'Closed Won', 'Closed Lost'};
		System.debug('statusesToLockPlan'+statusesToLockPlan);
		baseInfo.lockedPlan = statusesToLockPlan.contains(opp.StageName);
		System.debug('baseInfo.lockedPlan'+baseInfo.lockedPlan);
		baseInfo.offerId = opp.Id;

		StartupParam stParam = new StartupParam();
		stParam.sfdcConfigId = '';
        //stParam.WindSpeed = Integer.valueOf(opp.Wind_Speed__c);
		stParam.WindSpeed = opp.Building__r.Structural_Analysis__r.Wind_Speed__c != null ? opp.Building__r.Structural_Analysis__r.Wind_Speed__c.setScale(2) : 10;
		stParam.WindPressure = opp.Building__r.Structural_Analysis__r.Wind_Pressure__c != null ? opp.Building__r.Structural_Analysis__r.Wind_Pressure__c: 0;
        //System.debug('*** stParam.WindSpeed ***'+stParam.WindSpeed);
		stParam.TerrainType = terrainValue;
		stParam.IsHill = opp.Building__r.Structural_Analysis__r.On_a_Hill_or_Slope__c;
		stParam.SnowLoading = opp.Building__r.Structural_Analysis__r.Snowload__c;
		stParam.RoofHeight = opp.Building__r.Structural_Analysis__r.Building_Height__c;
		stParam.Seal = opp.Building__r.Structural_Analysis__r.Seals_between_panes__c;
		stParam.WaterHoles = opp.Building__r.Structural_Analysis__r.Drainage_holes__c;
		stParam.CountryCode = opp.Country_Attribute__c;
//		stParam.IncludeBlinds
//		stParam.offerBlindsIncluded
		stParam.CombinedLoad = opp.Building__r.Structural_Analysis__r.Combined_load__c;
		stParam.OrderNumber = opp.Opportunity_Number__c;
		stParam.LockRVN = false;
//		stParam.SplitPlan
		System.debug('*** stParam ***'+stParam);
		baseInfo.startupParameters = stParam;
		visual.baseInfo = baseInfo;
		wrapper.visual = visual;
		System.Debug('--- VisualContainerController - Wrapper: '+JSON.serializePretty(wrapper));
		return JSON.serialize(wrapper);
	}

	@AuraEnabled
	public static String getStartupParamsFromCase(String recordId) {
		return getStartupParamsFromOpportunity(
			[SELECT Opportunity__c FROM Case WHERE Id = :recordId]?.Opportunity__c,
			'reclamation'
		);
	}

	@AuraEnabled
	public static String getStartupParamsFromConfiguration(String recordId) {
		User user = [SELECT Name,Profile.Name,Country_Attribute__c,Country_Code_Attribute__c,LanguageLocaleKey FROM User WHERE Id =: UserInfo.getUserId()];
		Configuration__c config = [SELECT Opportunity__c, Plan_Name__c, Plan_Line__c, Visual_Id__c, 
										//Plan_Floor__c, 
										Plan_Apartment__c, LockPlan__c, Lock_RVN__c
		FROM Configuration__c WHERE Id =: recordId];
		System.debug('--- user: '+user);
		Opportunity opp = [SELECT  	Opportunity_Number__c,
									Owner.LanguageLocaleKey,
									StageName, 
									Country_Attribute__c,
									Order_type__c, 
									Building__r.Structural_Analysis__r.Wind_Pressure__c, 
									Building__r.Structural_Analysis__r.Wind_Speed__c, 
									Building__r.Structural_Analysis__r.Terrain_Type__c, 
									Building__r.Structural_Analysis__r.On_a_Hill_or_Slope__c, 								
									Building__r.Structural_Analysis__r.Snowload__c,
									Building__r.Structural_Analysis__r.Building_Height__c, 
									Building__r.Structural_Analysis__r.Seals_between_panes__c, 
									Building__r.Structural_Analysis__r.Drainage_holes__c, 
									Building__r.Structural_Analysis__r.Combined_load__c
							FROM Opportunity WHERE Id =: config.Opportunity__c];
		String terrainClass = opp.Building__r.Structural_Analysis__r.Terrain_Type__c;
		Integer terrainValue = new Map<String, Integer> {
								'Terrain Class 0' => 0,
								'Terrain Class I' => 1,
								'Terrain Class II' => 2,
								'Terrain Class III' => 3,
								'Terrain Class IV' => 4,
								'Terrain Class V' => 5
					}.get(terrainClass);
		VisualWrapper wrapper = new VisualWrapper();
		VisualDef visual = new VisualDef();
		BaseInfo baseInfo = new BaseInfo();
		baseInfo.configId = config.Visual_Id__c;
		baseInfo.baseConfigId = ''; // needed when creating a new plan from template
        //System.Debug('--- VisualContainerController - User language key: '+user.LanguageLocaleKey);
        String userLocale = user.LanguageLocaleKey;
		baseInfo.lan = userLocale.length()> 2? userLocale : userLocale.toLowerCase()+'-'+userLocale.toUpperCase();
		baseInfo.lumonPlanName = config.Plan_Name__c;
		baseInfo.lumonPlanLine = config.Plan_Line__c;
		//baseInfo.lumonPlanFloor = config.Plan_Floor__c;
		baseInfo.lumonPlanApartment = config.Plan_Apartment__c;
		String orderType = '';
		if (opp.Order_type__c == 'Normal') {
			orderType = 'default';
		} else if (opp.Order_type__c == 'Reclamation') {
			orderType = 'reclamation';
		}
		baseInfo.initMode = orderType;
		baseInfo.lockedPlan = config.LockPlan__c;
		baseInfo.offerId = opp.Id;

		StartupParam stParam = new StartupParam();
		stParam.sfdcConfigId = config.Id;
        //stParam.WindSpeed = String.valueOf(opp.Wind_Speed__c);
		stParam.WindSpeed = opp.Building__r.Structural_Analysis__r.Wind_Speed__c != null ? opp.Building__r.Structural_Analysis__r.Wind_Speed__c.setScale(2) : 10;
		stParam.WindPressure = opp.Building__r.Structural_Analysis__r.Wind_Pressure__c != null ? opp.Building__r.Structural_Analysis__r.Wind_Pressure__c: 0;
        //System.debug('*** stParam.WindSpeed ***'+stParam.WindSpeed);
		stParam.TerrainType = terrainValue;
		stParam.IsHill = opp.Building__r.Structural_Analysis__r.On_a_Hill_or_Slope__c;
		stParam.SnowLoading = opp.Building__r.Structural_Analysis__r.Snowload__c;
		stParam.RoofHeight = opp.Building__r.Structural_Analysis__r.Building_Height__c;
		stParam.Seal = opp.Building__r.Structural_Analysis__r.Seals_between_panes__c;
		stParam.WaterHoles = opp.Building__r.Structural_Analysis__r.Drainage_holes__c;
		stParam.CountryCode = opp.Country_Attribute__c;
//		stParam.IncludeBlinds
//		stParam.offerBlindsIncluded
		stParam.CombinedLoad = opp.Building__r.Structural_Analysis__r.Combined_load__c;
		stParam.OrderNumber = opp.Opportunity_Number__c;
		stParam.LockRVN = config.Lock_RVN__c;
//		stParam.SplitPlan
		System.debug('*** stParam 2 ***'+stParam);
		baseInfo.startupParameters = stParam;
		visual.baseInfo = baseInfo;
		wrapper.visual = visual;

		return JSON.serialize(wrapper);
	}

	public class VisualWrapper {
		public VisualDef visual {public get; public set;}
	}

	public class VisualDef {
		public BaseInfo baseInfo {public get; public set;}
	}

	public class BaseInfo {
		public String configId {public get; public set;}
		public String baseConfigId {public get; public set;}
		public String lan {public get; public set;}
		public String lumonPlanName {public get; public set;}
		public String lumonPlanLine {public get; public set;}
		public String lumonPlanFloor {public get; public set;}
		public String lumonPlanApartment {public get; public set;}
		public String initMode {public get; public set;}
		public Boolean lockedPlan {public get; public set;}
		public String offerId {public get; public set;}
		public StartupParam startupParameters {public get; public set;}
	}

	public class StartupParam {
		public List<Product> Products {public get; public set;}
		public String sfdcConfigId {public get; public set;}
		public Double WindSpeed {public get; public set;}
		public Double WindPressure {public get; public set;}
		public Integer TerrainType {public get; public set;}
		public Boolean IsHill {public get; public set;}
		public Double SnowLoading {public get; public set;}
		public Double RoofHeight {public get; public set;}
		public Boolean Seal {public get; public set;}
		public Boolean WaterHoles {public get; public set;}
		public String CountryCode {public get; public set;}
	//	public Boolean IncludeBlinds {public get; public set;}
	//	public Boolean offerBlindsIncluded {public get; public set;}
		public Double CombinedLoad {public get; public set;}
		public String OrderNumber {public get; public set;}
		public Boolean LockRVN {public get; public set;}
		public Boolean SplitPlan {public get; public set;}
	}

	public class Product {
		public String ProductCode {public get; public set;}
		public String CostType {public get; public set;}
	}
}