force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Building_Address__c.field-meta.xml
<CustomField>
    <fullName>Building_Address__c</fullName>
    <label>Building Address OLD</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Combined_load__c.field-meta.xml
<CustomField>
    <fullName>Combined_load__c</fullName>
    <inlineHelpText>Indication of the Combined Load</inlineHelpText>
    <label>Combined load</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Drainage_holes__c.field-meta.xml
<CustomField>
    <fullName>Drainage_holes__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indication whether Drainage holes are required</inlineHelpText>
    <label>Drainage holes DEL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Heatsoak__c.field-meta.xml
<CustomField>
    <fullName>Heatsoak__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indication whether heat soak is required</inlineHelpText>
    <label>Heatsoak DEL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/On_Hill_or_Slope__c.field-meta.xml
<CustomField>
    <fullName>On_Hill_or_Slope__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indication whether Building is on a Hill or Slope</inlineHelpText>
    <label>On Hill or Slope</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Owned_By__c.field-meta.xml
<CustomField>
    <fullName>Owned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Property_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Snow_Load__c.field-meta.xml
<CustomField>
    <fullName>Snow_Load__c</fullName>
    <label>Snow Load</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Structural_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Structural_Analysis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Structural Analysis</label>
    <referenceTo>Structural_Analysis__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <description>The Salesforce equivalent of the Visual Configuration Plan</description>
    <label>Configuration Plan</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Configuration Plans</relationshipLabel>
    <relationshipName>ConfigurationPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Message__c/Configuration_Message__c.object-meta.xml
<CustomObject>
    <label>Configuration Message</label>
    <nameField>
        <label>Configuration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Message__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Configuration Messages</relationshipLabel>
    <relationshipName>ConfigurationMessages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Option__c/Configuration_Option__c.object-meta.xml
<CustomObject>
    <label>Configuration Option</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Option__c/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipName>Configuration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration Plan</label>
    <referenceTo>Configuration__c</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>Configuration_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to populate Opportunity data to contract - Integration purpose</description>
    <inlineHelpText>This is the related opportunity</inlineHelpText>
    <label>Opportunity OLD</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>ContractsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/Structural_Analysis__c.object-meta.xml
<CustomObject>
    <label>Structural Analysis</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Structural Analysis Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Structural Analyses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Structural_Analysis__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <description>Building where these Structural Analysis is applicable</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Structural Analyses</relationshipLabel>
    <relationshipName>Structural_Analyses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Combined_Load__c.field-meta.xml
<CustomField>
    <fullName>Combined_Load__c</fullName>
    <label>Combined Load</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Structural_Analysis__c/fields/Drainage_Holes__c.field-meta.xml
<CustomField>
    <fullName>Drainage_Holes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Drainage Holes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Property_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APA</fullName>
        <label>Apartment Building</label>
    </customValue>
    <customValue>
        <fullName>COT</fullName>
        <label>Cottage</label>
    </customValue>
    <customValue>
        <fullName>HRC</fullName>
        <label>HoReCa</label>
    </customValue>
    <customValue>
        <fullName>PRJA</fullName>
        <label>Project-A</label>
    </customValue>
    <customValue>
        <fullName>PRJB</fullName>
        <label>Project-B</label>
    </customValue>
    <customValue>
        <fullName>ROW</fullName>
        <label>Row House</label>
    </customValue>
    <customValue>
        <fullName>HOU</fullName>
        <label>Single Family House</label>
    </customValue>
    <masterLabel>Lumon Property Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContractTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
@IsTest
private class ContractTriggerHandlerTest {
    @TestSetup
    static void PrepareData(){
        Test.startTest();
		LumonTestDataFactory.setupProducts();
        LumonTestDataFactory.setupPriceBookEntries();
        // B2C Setup
        LumonTestDataFactory.setupAccountB2C();
        LumonTestDataFactory.setupOpportunityB2C();  
        LumonTestDataFactory.setupConfigurationB2C();
        LumonTestDataFactory.setupConfigurationProductsB2C();
        LumonTestDataFactory.setupConfigurationOptionsB2C();       
        LumonTestDataFactory.setupConfigurationMessagesB2C();
        LumonTestDataFactory.setupSyncedQuoteB2C();
        LumonTestDataFactory.setupSyncedQuoteLineItemsB2C();
        LumonTestDataFactory.setupContractB2C();
        Test.stopTest();
    }
    private static Id b2cAccountId = LumonTestDataFactory.b2cAccountId;
    private static Id b2cOpportunityId = LumonTestDataFactory.b2cOpportunityId;
    private static Id b2cSyncedQuoteId = LumonTestDataFactory.b2cSyncedQuoteId;
    private static Id b2cContractId = LumonTestDataFactory.b2cContractId;
    private static List<Configuration__c> b2cConfigurations = LumonTestDataFactory.b2cConfigurations;
    private static List<Configuration_Product__c> b2cConfigProducts = LumonTestDataFactory.b2cConfigProducts;
    private static List<Configuration_Option__c> b2cConfigOptions = LumonTestDataFactory.b2cConfigOptions;
    private static List<Configuration_Message__c> b2cConfigMessages = LumonTestDataFactory.b2cConfigMessages;
    private static String visualPricingJSON = LumonTestConfigurations.visualPricingJSON;
    private static String soveliaPricingJSON = LumonTestConfigurations.soveliaPricingJSON;
    private static String testPricingJSON = LumonTestConfigurations.testPricingJSON;

    @IsTest
    public static void updateContractToSignedTest() {
        //Building__c  b = [select Id,Building_Address__c, Combined_load__c, Drainage_holes__c, Heatsoak__c, Name, On_Hill_or_Slope__c, Owned_By__c, Property_Type__c, Snow_Load__c, Structural_Analysis__c from Building__c limit 1];
        //System.debug('--- b val ---'+b);
        contract con = [SELECT Id, AccountId, Opportunity__c FROM Contract WHERE Id =: b2cContractId  LIMIT 1];
        Test.startTest();
        System.debug('--- updateContractToSignedTest - Contract Before: '+con); 
        String body = '{"response": "success"}';
        MockResponseGenerator mockResp = new MockResponseGenerator(body, 200);
        Test.setMock(HttpCalloutMock.class, mockResp);
        // Activate Contract
        con.Status = 'Signed';
        update con;
        System.debug('--- updateContractToSignedTest - Contract After: '+con); 
        System.debug('--- updateContractToSignedTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- updateContractToSignedTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();  
        ContentDocumentLink contractMessage = [SELECT Id, ContentDocument.Title, ContentDocumentId, ContentDocument.FileType FROM ContentDocumentLink WHERE LinkedEntityId =: con.Id];
        System.assertNotEquals(null,contractMessage.Id,'Expected Contract Message File');
        System.debug('--- updateContractToSignedTest - Contract Message File: '+contractMessage.ContentDocument.title);
    }

    @IsTest
    public static void updateContractToActivatedTest() {
        contract con = [SELECT Id, AccountId, Opportunity__c FROM Contract WHERE Id =: b2cContractId  LIMIT 1];
        System.Debug('--- Contract: '+con);
        
        String body = '{"response": "success"}';
        MockResponseGenerator mockResp = new MockResponseGenerator(body, 200);
        // Change Contract status from Draft to Signed
        con.Status = 'Activated';
        update con;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mockResp);
        
        ContractTriggerHandler.submitContract(con.Id);
        System.debug('--- updateContractToActivatedTest - CPU TIME: '+LIMITS.getCpuTime()); 
        System.debug('--- updateContractToActivatedTest - SOQL USED: ' + LIMITS.getQueries());
        Test.stopTest();  

        System.assert([SELECT count() FROM ContentDocumentLink WHERE LinkedEntityId =: con.Id] > 0);
    }
}