force-app/main/default/objects/ConfigurationEvent__e/ConfigurationEvent__e.object-meta.xml
<CustomObject>
    <description>Event to initiate and control processing of Configurations and Prices</description>
    <label>Configuration Event</label>
    <pluralLabel>Configuration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfigurationEvent__e/fields/blindsJSON__c.field-meta.xml
<CustomField>
    <fullName>blindsJSON__c</fullName>
    <label>blindsJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configAction__c.field-meta.xml
<CustomField>
    <fullName>configAction__c</fullName>
    <label>configAction</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configId__c.field-meta.xml
<CustomField>
    <fullName>configId__c</fullName>
    <description>Reference to the Salesforce Configuration (Plan) Record</description>
    <label>configId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configJSON__c.field-meta.xml
<CustomField>
    <fullName>configJSON__c</fullName>
    <description>JSON Representation of the Configuration Objects</description>
    <label>configJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configType__c.field-meta.xml
<CustomField>
    <fullName>configType__c</fullName>
    <description>Indicates the Type of Configuration this Event Relates to
-&gt; Any,Visual, Blinds, Pricing, Items</description>
    <label>configType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/itemJSON__c.field-meta.xml
<CustomField>
    <fullName>itemJSON__c</fullName>
    <description>JSON Representation of the Line Items</description>
    <label>itemJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <description>The Type of Record</description>
    <label>objectType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/pricingJSON__c.field-meta.xml
<CustomField>
    <fullName>pricingJSON__c</fullName>
    <description>String that contains the JSON representation of the Pricing Items as received from Visual</description>
    <label>pricingJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the Current Record</description>
    <label>recordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/structureJSON__c.field-meta.xml
<CustomField>
    <fullName>structureJSON__c</fullName>
    <description>The String to hold the JSON of the Structure</description>
    <label>structureJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/visualPlanId__c.field-meta.xml
<CustomField>
    <fullName>visualPlanId__c</fullName>
    <label>visualPlanId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationEvent.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
public class ConfigurationEvent {
    @AuraEnabled
    public static void publishConfigurationEvent(   String configType, //Blinds,Structure,Pricing,Other
                                                    String configAction, //ConfigAction
                                                    String configId, //Configuration.Id
                                                    String recordId, //Parent Record Id 
                                                    String objectType, //Parent Object Type
                                                    String externalId, //Opportunity.Id
                                                    String documentId, //Link to the File uploaded 
                                                    String contentJSON //Visual Request BODY (Pricing File Content)
                                                    ){
        List<ConfigurationEvent__e> configEvents = new List<ConfigurationEvent__e>();    
        ConfigurationEvent__e  cfgEvt  = new ConfigurationEvent__e ( 
                                                        configType__c = configType, //Blinds,Structure,Pricing,Other
                                                        configAction__c = configAction, //ConfigAction
                                                        configId__c = configId, //Configuration.Id
                                                        recordId__c = recordId,//Parent Record Id 
                                                        objectType__c = objectType,
                                                        pricingJSON__c = contentJSON,
                                                        configJSON__c = contentJSON,
                                                        blindsJSON__c = contentJSON,
                                                        itemJSON__c = contentJSON,
                                                        structureJSON__c = contentJSON,
                                                        visualPlanId__c =externalId
                                                        ); //Parent Object Type
        System.Debug('--- ConfigurationEvent - '+configType+' Configuration Event -  '+configAction+' Action for '+objectType+' with Id '+recordId);       
        System.Debug('--- ConfigurationEvent - '+configType+' Configuration Event - Configuration Plan '+configId+' with Visual Id '+externalId);                                  
        System.Debug('--- ConfigurationEvent - '+configType+' Configuration Event - Content: '+contentJSON);       
        configEvents.add(cfgEvt);
        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(configEvents);
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }       
        }
    }
}