force-app/main/default/objects/ConfigurationEvent__e/ConfigurationEvent__e.object-meta.xml
<CustomObject>
    <description>Event to initiate and control processing of Configurations and Prices</description>
    <label>Configuration Event</label>
    <pluralLabel>Configuration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfigurationEvent__e/fields/configAction__c.field-meta.xml
<CustomField>
    <fullName>configAction__c</fullName>
    <label>configAction</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configId__c.field-meta.xml
<CustomField>
    <fullName>configId__c</fullName>
    <description>Reference to the Salesforce Configuration (Plan) Record</description>
    <label>configId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/configType__c.field-meta.xml
<CustomField>
    <fullName>configType__c</fullName>
    <description>Indicates the Type of Configuration this Event Relates to
-&gt; Any,Visual, Blinds, Pricing, Items</description>
    <label>configType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/documentId__c.field-meta.xml
<CustomField>
    <fullName>documentId__c</fullName>
    <label>documentId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/objectType__c.field-meta.xml
<CustomField>
    <fullName>objectType__c</fullName>
    <description>The Type of Record</description>
    <label>objectType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/pricingJSON__c.field-meta.xml
<CustomField>
    <fullName>pricingJSON__c</fullName>
    <description>String that contains the JSON representation of the Pricing Items as received from Visual</description>
    <label>pricingJSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the Current Record</description>
    <label>recordId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationEvent__e/fields/visualPlanId__c.field-meta.xml
<CustomField>
    <fullName>visualPlanId__c</fullName>
    <label>visualPlanId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigurationEventTriggerHandler.cls
/**
 * @description       : NOT IN USE Handles Configuration Events for CPQ
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-08-2024
 * @last modified by  : Henk Reynders
**/
public without sharing class ConfigurationEventTriggerHandler {
    /*Disabled 01.10.2024
    public static void processConfiguration(List<ConfigurationEvent__e> configChangeEvents){
        // Iterate through each notification.
        for (ConfigurationEvent__e event : configChangeEvents) {      
            System.debug('--- Event: ' + event);
            String configType = event.configType__c;
            System.debug('--- Configuration Type: ' + configType);
            String configAction = event.configAction__c;
            System.debug('--- Configuration Action: ' + configAction);
            String configId = event.configId__c;
            //System.debug('--- Configuration: ' + configId);
            String recordId = event.recordId__c;
            //System.debug('--- record: ' + recordId);
            String objectType = event.objectType__c;
            //System.debug('--- objectType: ' + objectType);
            String visualPlanId = event.visualPlanId__c;
            //System.debug('--- visualPlanId: ' + visualPlanId);
            String documentId = event.documentId__c;
            //System.debug('--- documentId: ' + documentId);
            String contentJSON = event.pricingJSON__c;
            //System.debug('--- contentJSON: ' + contentJSON);
            // Executed Quoting Process for Enhanced Pricing
            //System.debug('--- Start Processing '+contentJSON);
            QuotingManager.executeQuotingProcess( configType, configAction,
                                            configId,recordId,objectType,
                                            visualPlanId, documentId,contentJSON);
        }
    }*/
}