force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <label>Data Source</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Warehouse description - Can be used in the Delivery address description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Organizations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Owned_By__c.field-meta.xml
<CustomField>
    <fullName>Owned_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which Company Owns the Warehouse</description>
    <inlineHelpText>Indicates which Company Owns the Warehouse</inlineHelpText>
    <label>Owned By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Warehouse_Address__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Address__c</fullName>
    <label>Warehouse Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.LocationType</field>
            <operation>equals</operation>
            <value>Warehouse</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/WarehouseCode__c.field-meta.xml
<CustomField>
    <fullName>WarehouseCode__c</fullName>
    <description>Location Code (Unique Id for ERP)</description>
    <externalId>true</externalId>
    <inlineHelpText>Location Code (Unique Id for ERP)</inlineHelpText>
    <label>Warehouse Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/fields/WarehouseId__c.field-meta.xml
<CustomField>
    <fullName>WarehouseId__c</fullName>
    <description>Short Name (Unique Id)</description>
    <externalId>true</externalId>
    <inlineHelpText>Short Name (Unique Id)</inlineHelpText>
    <label>Warehouse Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WarehouseController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 05-12-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class WarehouseController {
    @AuraEnabled(cacheable=true)
    public static Warehouse__c getWarehouseRecord(Id recordId) {
        // Populate map from SOQL query on Warehouse
        List<Id> recordIds = new List<Id>{recordId};
        List<Warehouse__c> warehouseRecords = getWarehouses(recordIds);        
        Warehouse__c warehouseRecord = warehouseRecords[0];
        System.debug('--- Warehouse Record: '+warehouseRecord);
        return warehouseRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<Warehouse__c> getWarehouses(List<Id> recordIds) {
        List<Warehouse__c> warehouses = ([SELECT Id,
                                                Name, 
                                                Data_Source__c, 
                                                Description__c, 
                                                Organization__c, 
                                                Owned_By__c, 
                                                WarehouseCode__c, 
                                                WarehouseId__c,  
                                                Warehouse_Address__Street__s, 
                                                Warehouse_Address__City__s, 
                                                Warehouse_Address__PostalCode__s, 
                                                Warehouse_Address__StateCode__s, 
                                                Warehouse_Address__CountryCode__s, 
                                                Warehouse_Address__Latitude__s, 
                                                Warehouse_Address__Longitude__s, 
                                                Warehouse_Address__GeocodeAccuracy__s, 
                                                Warehouse_Address__c, 
                                                Warehouse_Location__c    
                                        FROM Warehouse__c 
                                    WHERE Id IN :recordIds
                                    OR Owned_By__c IN:recordIds
                                    ]);
        System.debug('--- Warehouse Record Count : '+warehouses.size());
        return warehouses;
    } 
}