force-app/main/default/objects/Install_Expense__c/Install_Expense__c.object-meta.xml
<CustomObject>
    <description>Install Expense object to define BU respective Installation expenses. (LUM-1483)</description>
    <label>Install Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Expenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Install_Expense__c/fields/Hourly_Expense__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Expense__c</fullName>
    <description>Average Hourly Expense respect to BU</description>
    <label>Hourly Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/Integration_Credentials__mdt.object-meta.xml
<CustomObject>
    <label>Integration Credentials</label>
    <pluralLabel>Integration Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Credentials__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Environment_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Name__c</fullName>
    <label>Environment Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__mdt/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <label>Integration Name OLD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Install_Expense__c.field-meta.xml
<CustomField>
    <fullName>Install_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation expense specific to the region where the work is done.</description>
    <label>Install Expense</label>
    <referenceTo>Install_Expense__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Unique number (Sales Order Number + Visual given number) coming from Opportunity Product.</description>
    <label>RVN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderLineItemTriggerHandler.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-02-2023
 * @last modified by  : Henk Reynders
**/
public without sharing class WorkOrderLineItemTriggerHandler {
	public static void populateJSON(List<WorkOrderLineItem> newWorkOrderLineItems, Map<Id, WorkOrderLineItem> oldWorkOrderLineItems, Boolean resubmitOrder) { //Added resubmitOrder as part of LUM-1282
		List<WorkOrderLineItem> itemsToProcess = new List<WorkOrderLineItem>();
		Set<Id> installExpenseIds = new Set<Id>();
		Set<Id> installerIds = new Set<Id>();
        
        Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
		System.debug('--- isSandbox ---'+isSandbox);
		String envName = 'production';
		if ([SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox) {
			envName = String.valueOf(URL.getOrgDomainUrl()).substringBetween('--', '.sandbox');
			envName = envName.remove('--c');
			if (envName != 'lumonTest' && envName != 'develop1' ) {
				envName = 'sandbox';
			}
		}
		Integration_Credentials__mdt credentials;
		credentials = [SELECT API_Key__c, Endpoint__c FROM Integration_Credentials__mdt WHERE Integration_Name__c = 'FrendsInstallation' AND Environment_Name__c =: envName];
        
		//Added resubmitOrder as part of LUM-1282
        for (WorkOrderLineItem worOrdLinItem : newWorkOrderLineItems) {
			WorkOrderLineItem oldItem = oldWorkOrderLineItems.containsKey(worOrdLinItem.Id) ? oldWorkOrderLineItems.get(worOrdLinItem.Id): new WorkOrderLineItem();
			
            if ((worOrdLinItem.Status == 'Completed'&& oldItem.Status != 'Completed' && 
                 worOrdLinItem.RVN_Number__c != null ) || resubmitOrder) 
            {
                 itemsToProcess.add(worOrdLinItem);
				 installExpenseIds.add(worOrdLinItem.Install_Expense__c);
                 if (worOrdLinItem.LastModifiedById != null) 
                 {
                    installerIds.add(worOrdLinItem.LastModifiedById);
                 }
			}
		}
        
		Map<Id,Install_Expense__c> installExpenseMap = new  Map<Id,Install_Expense__c>( [SELECT Id,Hourly_Expense__c from Install_Expense__c where Id IN : installExpenseIds]);
		Map<Id, User> userIdToUser = new Map<Id, User>([SELECT Username FROM User WHERE Id IN :installerIds]);
        Decimal installExpense = 0.00;
		
        for (WorkOrderLineItem item : itemsToProcess) {
			SalesLineWrapper wrapper = new SalesLineWrapper();
			SalesLineDef sLineDef = new SalesLineDef();
			sLineDef.Installed = 'Yes';
            sLineDef.company = 'LSU'; // This is hardcoded but this should be taken from Installer Organization Attribute
			sLineDef.TVN = item.RVN_Number__c;

			UpdateDef upd = new UpdateDef();
			upd.InstallerName = item.LastModifiedById != null ? userIdToUser.get(item.LastModifiedById).Username : '';
			upd.InstallDate = item.StartDate != null ? String.valueOf(item.StartDate).substring(0,10) : '';
            //LUM-1483 Install Expense calculation
            if(installExpenseMap.get(item.Install_Expense__c).Hourly_Expense__c != NULL && item.Duration != NULL){
                installExpense = installExpenseMap.get(item.Install_Expense__c).Hourly_Expense__c * item.Duration;
                installExpense = installExpense.setScale(2);
            }
            upd.InstallExpense = installExpense != null ?  String.valueOf(installExpense) : '';
			upd.DeliveryDateRealised = item.EndDate != null ? String.valueOf(item.EndDate).substring(0,10) : '';

			sLineDef.Update1 = upd;
			wrapper.SalesLine = sLineDef;
			String jsonBody = JSON.serialize(wrapper);
			jsonBody = jsonBody.replace('Update1', 'Update');
			System.debug('!! json: ' + jsonBody);
			notifyFrends(jsonBody, credentials.Endpoint__c, credentials.API_Key__c);
		}
	}

	@future (callout=true)
	public static void notifyFrends (String jsonBody, String endpoint, String apiKey) {
		Http http = new Http();
		HttpRequest request = new HttpRequest();
		request.setEndpoint(endpoint);
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json;charset=UTF-8');
		request.setHeader('Authorization', apiKey);
		request.setBody(jsonBody);
		HttpResponse response = http.send(request);

		System.debug('STATUS: ' + response.getStatus());

		if (response.getStatusCode() != 200) {
			System.debug('ERROR: ' + response.getBody());
		} else {
			System.debug('SUCCESS: ' + response.getBody());
		}
	}

	public class SalesLineWrapper {
		public SalesLineDef SalesLine {public get; public set;}
	}

	public class SalesLineDef {
		public String Installed {public get; public set;}
		public String TVN {public get; public set;}
        public String company {public get; public set;}
		public UpdateDef Update1 {public get; public set;}
	}

	public class UpdateDef {
		public String InstallerName {public get; public set;}
		public String InstallExpense {public get; public set;}
		public String DeliveryDateRealised {public get; public set;}
		public String InstallDate {public get; public set;}
	}
}