force-app/main/default/objects/Install_Expense__c/Install_Expense__c.object-meta.xml
<CustomObject>
    <description>Install Expense object to define BU respective Installation expenses. (LUM-1483)</description>
    <label>Install Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Expenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Install_Expense__c/fields/Hourly_Expense__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Expense__c</fullName>
    <description>Average Hourly Expense respect to BU</description>
    <label>Hourly Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Install_Expense__c/fields/Profit_Center__c.field-meta.xml
<CustomField>
    <fullName>Profit_Center__c</fullName>
    <description>Profit Center value updated from Globsl picklist</description>
    <label>Profit Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lumon_Profit_Centers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Install_Expense__c.field-meta.xml
<CustomField>
    <fullName>Install_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation expense specific to the region where the work is done.</description>
    <label>Install Expense</label>
    <referenceTo>Install_Expense__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Installed_By__c.field-meta.xml
<CustomField>
    <fullName>Installed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contains the installer&apos;s (user) reference after the WOLi has been set to Completed status.</description>
    <label>Installed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Unique number (Sales Order Number + Visual given number) coming from Opportunity Product.</description>
    <label>RVN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Lumon_Profit_Centers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>100 LUI Administration</fullName>
    </customValue>
    <customValue>
        <fullName>10 SVI Production</fullName>
    </customValue>
    <customValue>
        <fullName>110 LNA Administration</fullName>
    </customValue>
    <customValue>
        <fullName>15 SVI Production Aftersales</fullName>
    </customValue>
    <customValue>
        <fullName>160 LNP Production</fullName>
    </customValue>
    <customValue>
        <fullName>161 LNP Administration</fullName>
    </customValue>
    <customValue>
        <fullName>172 LNC Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>173 LNC West dealers</fullName>
    </customValue>
    <customValue>
        <fullName>174 LNC Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>175 LNC Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>176 LNC Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>177 LNC US</fullName>
    </customValue>
    <customValue>
        <fullName>178 LNC Customer service</fullName>
    </customValue>
    <customValue>
        <fullName>181 LNU US Dealers</fullName>
    </customValue>
    <customValue>
        <fullName>182 LNU Buffalo</fullName>
    </customValue>
    <customValue>
        <fullName>200 LUI International</fullName>
    </customValue>
    <customValue>
        <fullName>20 SVI Consumer</fullName>
    </customValue>
    <customValue>
        <fullName>210 LUI Kouvola</fullName>
    </customValue>
    <customValue>
        <fullName>220 LUI Jyväskylä</fullName>
    </customValue>
    <customValue>
        <fullName>230 LUI Oulu</fullName>
    </customValue>
    <customValue>
        <fullName>240 LUI Vantaa</fullName>
    </customValue>
    <customValue>
        <fullName>250 LUI Kuopio</fullName>
    </customValue>
    <customValue>
        <fullName>25 SVI Consumer West</fullName>
    </customValue>
    <customValue>
        <fullName>271 LUI R&amp;D</fullName>
    </customValue>
    <customValue>
        <fullName>272 LUI HR</fullName>
    </customValue>
    <customValue>
        <fullName>273 LUI Technical Support</fullName>
    </customValue>
    <customValue>
        <fullName>274 LUI ICT</fullName>
    </customValue>
    <customValue>
        <fullName>275 LUI Finance</fullName>
    </customValue>
    <customValue>
        <fullName>280 LFE Production</fullName>
    </customValue>
    <customValue>
        <fullName>290 LFE Administration</fullName>
    </customValue>
    <customValue>
        <fullName>4010 LSU Vantaa West</fullName>
    </customValue>
    <masterLabel>Lumon Profit Centers</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/WorkOrderLineItemTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-01-2023
 * @last modified by  : Henk Reynders
**/

@IsTest
private class WorkOrderLineItemTriggerHandlerTest {
	@TestSetup
    public static void prepareData(){
        Test.startTest();
        //SalesTestDataFactory.setupAccountRecords();
        LumonTestDataFactory.setupAccountB2C();
        Test.stopTest();
    }   
	@IsTest
	static void updateToCompletedTest () {
		Account acc = [SELECT Id FROM Account WHERE Name =: 'My Person Account' LIMIT 1];
		Install_Expense__c insExpense = new Install_Expense__c(Profit_Center__c = '4010 LSU Vantaa West', Hourly_Expense__c = 52, Name ='Vantaa West');
        insert insExpense;
		WorkOrder wo = new WorkOrder(AccountId = acc.Id);
		insert wo;
		WorkOrderLineItem woli = new WorkOrderLineItem(WorkOrderId = wo.Id, Install_Expense__c = insExpense.Id, RVN_Number__c = '123456', Installed_By__c = UserInfo.getUserId());
		insert woli;

		Test.startTest();

		String body = '{"response": "success"}';
		MockResponseGenerator mockResp = new MockResponseGenerator(body, 200);
		Test.setMock(HttpCalloutMock.class, mockResp);

		update new WorkOrderLineItem(Id = woli.Id, Status = 'Completed');

		Test.stopTest();
	}
}