force-app/main/default/objects/Install_Expense__c/Install_Expense__c.object-meta.xml
<CustomObject>
    <description>Install Expense object to define BU respective Installation expenses. (LUM-1483)</description>
    <label>Install Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Expenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderLineItem/fields/Install_Expense__c.field-meta.xml
<CustomField>
    <fullName>Install_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation expense specific to the region where the work is done.</description>
    <label>Install Expense</label>
    <referenceTo>Install_Expense__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Unique number (Sales Order Number + Visual given number) coming from Opportunity Product.</description>
    <label>RVN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReSubmitWorkOrderLIController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 12-03-2023
 * @last modified by  : Henk Reynders
**/

public class ReSubmitWorkOrderLIController {
    @AuraEnabled
    public static void reSubmitWOLI(String woliId){
        if(String.isNotBlank(woliId)){
            WorkOrderLineItem woliObj = new WorkOrderLineItem();
            woliObj = [Select id,RVN_Number__c,Status,LastModifiedById,StartDate,
                       EndDate,Install_Expense__c,Duration from WorkOrderLineItem where Id =: woliId];
            WorkOrderLineItemTriggerHandler.populateJSON(new List<WorkOrderLineItem>{woliObj},
                                                         new Map<Id,WorkOrderLineItem>(),true);
        }
    }
}