force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The Opportunity the (Parent) Configuration belongs to</description>
    <formula>Configuration__r.Opportunity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Opportunity the (Parent) Configuration belongs to</inlineHelpText>
    <label>Opportunity OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity related to the work. Used to access e.g. product detail.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InstallationPdfControllerTest.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 10-01-2024
 * @last modified by  : Henk Reynders
**/
@IsTest
private class InstallationPdfControllerTest {

    @TestSetup
    public static void setupData(){
        Test.startTest();
        LumonTestConfigurationFiles.setupConfigFiles();
        insert new WorkOrder(Subject = 'Work Order Test',
                Opportunity__c = [SELECT Id FROM Opportunity LIMIT 1].Id,
                AccountId = [SELECT Id FROM Account WHERE (IsPersonAccount = true) LIMIT 1].Id);
        Test.stopTest();

    }
    @IsTest
    static void getConfigurationProductsTest() {
        Test.startTest();
        List<Configuration_Product__c> configurationProducts =
                GenerateInstallerPdfController.getConfigurationProducts([SELECT Id FROM WorkOrder LIMIT 1].Id);
        System.assert(configurationProducts.size() > 0, 'Configuration products should be populated');
        Test.stopTest();
    }
}