force-app/main/default/objects/Configuration_Product__c/Configuration_Product__c.object-meta.xml
<CustomObject>
    <label>Configuration Product</label>
    <nameField>
        <label>Configuration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuration_Product__c/fields/Installable_Product__c.field-meta.xml
<CustomField>
    <fullName>Installable_Product__c</fullName>
    <formula>Product__r.Installation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installable Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Configuration Products</relationshipLabel>
    <relationshipName>ConfigurationProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configuration_Product__c/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Install_Expense__c/Install_Expense__c.object-meta.xml
<CustomObject>
    <description>Install Expense object to define BU respective Installation expenses. (LUM-1483)</description>
    <label>Install Expense</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Expenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Salesforce equivalent of rvn of Product</description>
    <externalId>true</externalId>
    <label>RVN Number OLD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Apartment_number__c.field-meta.xml
<CustomField>
    <fullName>Apartment_number__c</fullName>
    <description>Line part of the Apartment address.</description>
    <formula>Configuration_Product__r.Configuration__r.Plan_Apartment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apartment number OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Combination_name__c.field-meta.xml
<CustomField>
    <fullName>Combination_name__c</fullName>
    <description>Used to provide more details to WO/WOLI based configuration product selection in Reclamation/Warranty Case creation from Account.</description>
    <formula>Street &amp; &quot;: &quot; &amp; Configuration_Product__r.Product__r.Name &amp; &quot; (Plan: &quot; &amp;  Configuration_Product__r.Configuration__r.Plan_Name__c &amp; &quot;, RVN: &quot; &amp; RVN_Number__c &amp; &quot;)&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Combination name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Combined_info__c.field-meta.xml
<CustomField>
    <fullName>Combined_info__c</fullName>
    <description>Used in WOLI list to provide more details in the Salestori integration work to the Installer.</description>
    <formula>IF
(
ISBLANK( Apartment_number__c ),
Configuration_Product__r.Product__r.Name,
(Configuration_Product__r.Product__r.Name &amp; &quot; F:&quot; &amp; Floor__c &amp; &quot; A:&quot; &amp; Apartment_number__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Combined info OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Config_Product_name__c.field-meta.xml
<CustomField>
    <fullName>Config_Product_name__c</fullName>
    <description>Allow to show the Configuration Product name for the Installer on the WO WOLIs list.</description>
    <formula>Configuration_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Config Product name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Configuration_Product__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuration Product</label>
    <referenceTo>Configuration_Product__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <description>Floor part of the Apartment address.</description>
    <formula>Configuration_Product__r.Configuration__r.Plan_Floor__c</formula>
    <label>Floor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Install_Expense__c.field-meta.xml
<CustomField>
    <fullName>Install_Expense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation expense specific to the region where the work is done.</description>
    <label>Install Expense</label>
    <referenceTo>Install_Expense__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Installable_Product__c.field-meta.xml
<CustomField>
    <fullName>Installable_Product__c</fullName>
    <description>Defines if this work will require an Asset to be created.</description>
    <formula>IF(
   ISPICKVAL(WorkType.Type__c, &quot;New Product installation&quot;), 
   TRUE, 
   FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installable Product OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Installed_By2__c.field-meta.xml
<CustomField>
    <fullName>Installed_By2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contains the installer&apos;s reference after the WOLI has been set to Completed status.</description>
    <label>Installed By2</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Installed_By__c.field-meta.xml
<CustomField>
    <fullName>Installed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contains the installer&apos;s (user) reference after the WOLi has been set to Completed status.</description>
    <label>Installed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Is_installable__c.field-meta.xml
<CustomField>
    <fullName>Is_installable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Defines if this work will require an Asset to be created. Set by automation (flow).</description>
    <label>Is installable OLD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Is_Reclamation__c.field-meta.xml
<CustomField>
    <fullName>Is_Reclamation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is set when the WOLI is of type Reclamation.</description>
    <label>Is Reclamation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>Line part of the Apartment address.</description>
    <formula>Configuration_Product__r.Configuration__r.Plan_Line__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Line Item that refers to the work needed i.e. the WOLI.</description>
    <label>Opportunity Product OLD</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Original_WOLI_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_WOLI_Id__c</fullName>
    <description>In Salestori integration, when splitting the work to different WOs and WOLIs, this id is used to reference the original WOLI under the original WO and help to find the related Content Document Links.</description>
    <label>Original WOLI Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product OLD</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <description>Shows the related Opportunity Product name on the related list, if needed.</description>
    <formula>Opportunity_Product__r.PricebookEntry.Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RemoteFile__c.field-meta.xml
<CustomField>
    <fullName>RemoteFile__c</fullName>
    <description>Reference to the Remote File Name</description>
    <label>Remote File</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RemoteFolder__c.field-meta.xml
<CustomField>
    <fullName>RemoteFolder__c</fullName>
    <description>Reference to the Remote Folder where Attachments are stored</description>
    <label>Remote Folder</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/RVN_Number__c.field-meta.xml
<CustomField>
    <fullName>RVN_Number__c</fullName>
    <description>Unique number (Sales Order Number + Visual given number) coming from Opportunity Product.</description>
    <label>RVN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Work_duration_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Work_duration_in_minutes__c</fullName>
    <description>Calculated duration in minutes. Is the difference between End and Startdate.</description>
    <formula>IF
(
  NOT ISBLANK(EndDate) &amp;&amp; NOT ISBLANK(StartDate),
  (EndDate -  StartDate)*24*60,
  0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work duration in minutes OLD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WorkOrderLineItemController.cls
/**
 * @description       : 
 * @author            : Henk Reynders
 * @group             : 
 * @last modified on  : 08-13-2024
 * @last modified by  : Henk Reynders
**/
public with sharing class WorkOrderLineItemController {
    @AuraEnabled(cacheable=true)
    public static WorkOrderLineItem getWorkOrderLineItem(Id recordId) {  
        System.debug('--- WorkOrderLineItemController - Get Work Order Line Item with Id: '+recordId);
        List<Id> recordIds = new List<Id>{recordId};
        List<WorkOrderLineItem> workOrderLineItems = getWorkOrderLineItems(recordIds);
        WorkOrderLineItem workOrderLineItemRecord = workOrderLineItems[0];
        System.debug('--- WorkOrderLineItemController - Work Order Line Item Record: '+workOrderLineItemRecord);
        return workOrderLineItemRecord;
    } 
    @AuraEnabled(cacheable=true)
    public static List<WorkOrderLineItem> getWorkOrderLineItems(List<Id> recordIds) {
        // Populate map from SOQL query on QuotelineItem
        List<WorkOrderLineItem> workOrderLineItems = ([ SELECT  Id,
                                                            LineItemNumber, 
                                                            CurrencyIsoCode, 
                                                            WorkOrderId, 
                                                            ParentWorkOrderLineItemId, 
                                                            Product2Id, 
                                                            AssetId, 
                                                            OrderId, 
                                                            RootWorkOrderLineItemId, 
                                                            Description, 
                                                            StartDate, 
                                                            EndDate, 
                                                            Status, 
                                                            PricebookEntryId, 
                                                            Quantity, 
                                                            UnitPrice, 
                                                            Discount, 
                                                            ListPrice, 
                                                            Subtotal, 
                                                            TotalPrice, 
                                                            Duration, DurationType, DurationInMinutes, 
                                                            WorkTypeId, 
                                                            Street, City, State, PostalCode, Country, StateCode, CountryCode, Latitude, Longitude, GeocodeAccuracy, Address, 
                                                            ServiceTerritoryId, 
                                                            Subject, 
                                                            StatusCategory, IsClosed, Priority, 
                                                            ServiceAppointmentCount, LocationId, 
                                                            MinimumCrewSize, RecommendedCrewSize, ServiceReportTemplateId, 
                                                            ReturnOrderLineItemId, ReturnOrderId, 
                                                            SuggestedMaintenanceDate, MaintenancePlanId, IsGeneratedFromMaintenancePlan, MaintenanceWorkRuleId, 
                                                            AssetWarrantyId, 
                                                            ProductServiceCampaignId, ProductServiceCampaignItemId, 
                                                            FSL__IsFillInCandidate__c, FSL__VisitingHours__c, 
                                                            Work_duration_in_minutes__c, 
                                                            Configuration_Product__c, Installed_By2__c, Installed_By__c, Is_installable__c, Opportunity_Product__c, RVN_Number__c, 
                                                            Installable_Product__c, 
                                                            Product_name__c, Product__c, Is_Reclamation__c, Combination_name__c, 
                                                            Install_Expense__c, Config_Product_name__c, 
                                                            Floor__c, Line__c, Apartment_number__c, 
                                                            Original_WOLI_Id__c, Combined_info__c,
                                                            RemoteFile__c, RemoteFolder__c
                                            FROM WorkOrderLineItem
                                            WHERE Id IN :recordIds
                                                OR WorkOrderId IN :recordIds
                                                OR OrderId IN :recordIds
                                                OR AssetId IN :recordIds
                                            ORDER BY WorkOrderId,LineItemNumber]);
        System.debug('--- WorkOrderLineItemController - Work Order Line Items: '+workOrderLineItems);                                         
        return workOrderLineItems;
    }                                         
}